### ISSUE TITLE
Frontend General - צבע תבנית שונה עבור אתר פסטיבל

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#1]
יש ליצור שדה הגדרת צבע עבור תבנית פסטיבל. 
כך שעורכי התוכן יוכלו לעדכן את ערך הצבע הזה. 
לדעתי יש רכיב שאמור לעשות משהו כזה. או שתעשי בלי רכיב...

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar מה עם כל האייקונים שכרגע הם תמונות?<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar טוב, הרעיוםש היה לי עם האייקונים לא שייך כיוון שבהרבה מקומות הם מונחים על מקום שהרקע שלהם צריך להיות שקוף אז צריך לךמצוא לזה פיתרון.<br />לא סיימתי עדיין ועברתי את ה-3 שעות כבר..<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar סיימתי מלבד האייקונים. אין ברירה חייבים שהם יהיו תווים ולא תמונות. פה: http://fontawesome.io/icons/ יש דברים מאו ד דומים לאיקונים שיש באתר. אין ברירה לדעתי.<br />

**Comment by JerusalemCinematheque** [comment]
איפה אנחנו עורכים את הצבע?

**Comment by reasonat** [comment]
We have issue with the top menu icons which need to be icons instead of images. We should find free icons to use. @bruria1 Please find some icons to use and send a link here.

**Comment by JerusalemCinematheque** [comment]
האם מצאתם פתרון לעניין?

**Comment by bruria1** [comment]
אז ככה:
זה אומר להחליף את כל האייקונים שכעת הם תמונה לפונט של אייקונים - fontawsome:
שעון - http://fontawesome.io/icon/clock-o/
חיפוש - http://fontawesome.io/icon/search/
לב - http://fontawesome.io/icon/heart-o/
עגלת קניות - http://fontawesome.io/icon/shopping-cart/
נגישות - http://fontawesome.io/icon/wheelchair/
לוח שנה - http://fontawesome.io/icon/calendar-plus-o/
לוח שנה מלא - אין.. נצטרך לעשות אותו בצבע אחר או לוותר על זה.
כפתור סגירה - http://fontawesome.io/icon/times/
פייסבוק - http://fontawesome.io/icon/facebook/
ווטאפ - http://fontawesome.io/icon/whatsapp/

עמוד איש:
מעטפה - http://fontawesome.io/icon/envelope-o/
מיקום - http://fontawesome.io/icon/map-marker/
בועה - http://fontawesome.io/icon/comment-o/

אם זה בעייתי מבחינתכם אפשר לחפש פונטים נוספים שיותר יתאימו..
כמו למשל הפונט הזה שהרבה יותר דומה למה שקיים באתר אבל הוא בתשלום:
https://icomoon.io/#icons-lindua

**Comment by JerusalemCinematheque** [comment]
מה זה לוח שנה מלא?

**Comment by bruria1** [comment]
זה כאשר לוחצים על לוח השנה הוא מציג אותו מלא.

**Comment by navotb** [comment]
סליחה על השאלה, אי אפשר להמיר את האייקונים שיש עכשיו לפונט? איך דרך לעשות את זה?

**Comment by reasonat** [comment]
יש דרך לעשות את זה כמובן אבל אין מי שיעשה את זה. בעיקרון אלקנה אמור אבל זה לא חלק מההסכם למיטב הבנתי
וכעת אנחנו צריכים להתקדם עם הנושא.

**Comment by JerusalemCinematheque** [comment]
האם כל מעצב גרפי יכול לעשות את זה?

**Comment by reasonat** [comment]
בהחלט. אבל אני מבין מברוריה שמה שהיא שלחה יכול בהחלט לענות על הציפיות לא?

**Comment by bruria1** [comment]
https://icomoon.io/app/#/select/library
יש פה הרבה אייקונים חינמיים, צריך פשוט למצוא את האייקונים המתאימים..

**Comment by JerusalemCinematheque** [comment]
אתם יכולים בבקשה להעביר אלינו את האייקונים ולהסביר מה בדיוק צריך?
אנחנו נעביר את זה לגרפיקה שאנחנו עובדים איתם לראות אם הם יכולים לעשות זאת

**Comment by bruria1** [comment]
שלחתי את הקובץ במייל, לא הייתה אפשרות לעלות פה.
יכול להיות שהוא חלקי ולא מכיל את כל מה שצריך

**Comment by navotb** [comment]
ברוריה
הייתי רוצה לנסות להמיר את קובץ האילוסטרטור ששלח אלקנה בזמנו לאייקונים
פונטיים - אני אטפל בחלק הזה.
האם זה פתרון טוב עבורך? ואם כן, האם תרצי להנחות איך תרצי לקבל אותם?
נבות

2017-05-10 9:48 GMT+03:00 Bruria <notifications@github.com>:

**Comment by bruria1** [comment]
אני צריכה לקבל את כקובץ מסוג פונט ttf

**Comment by navotb** [comment]
אוקיי
והקווים/משטחים - שחורים? בלי שני צבעים או משהו כזה, נכון?

**Comment by bruria1** [comment]
לא הבנתי אותך

**Comment by navotb** [comment]
בקובץ של אלקנה האייקונים מופיעים עם שני צבעים לפעמים, למשל: הלב מופיע עם קו
חיצוני שחור ומילוי אדום. ממה שקראתי, את צריכה לקבל את האייקונים בצבע אחד
שחור והשאר לבן/שקוף

**Comment by bruria1** [comment]
כן. בצבע אחד בלבד.
