### ISSUE TITLE
If event is marked as domain access > publish to festival do not display on cinematheque side

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#100]
ערכנו עכשיו כל מיני אירועים שהופיעו בקלנדר הסינמטק ונועדו לקלנדר פסטיבל. סימנו אותם כשייכים לדומיין פסטיבל. אבל הם עדיין מופיעים בצד סינמטק
לדוגמא
http://jer-cin.reasonat.com/he/event/6463

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar I made changes for calendars: full width and pane. May be are there some other page which need to fix?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko each node which doesnt set on the domain access to publish on Cinemateque shuoldnt get publish all over the Cinemateque site. Node can be however display on both Cinemateque site and Festival if both checked under the domain access. <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar Now at the dev site you should see only nodes published to current domain<br />

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque To review on dev site

**Comment by JerusalemCinematheque** [comment]
great
