### ISSUE TITLE
Low and wide image (for Home Page) if no main picture attached

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#103]
@bruria1 @reasonat 
אם לנוד אין תמונה מרכזית, אבל יש לו תמונה צרה ונמוכה להוםפייג', לא ניתן להעלות את הנוד להוםפייג'
לדוגמא,  
taxonomy/term/591

העליתי תמונה נמוכה וצרה ללובי, אבל לא העליתי תמונה ראשית
עברתי להומפייג' וביקשתי להעלות את הלובי 
ניסיתי להוסיף אותו בוון אייטם סטטי וגם בתמונות הגלריה
אבל אחרי השמירה האייטם לא הופיע בפרונטאנד של ההומפייג'
רק אחרי שהוספתי ללובי תמונה ראשית, הופיע האייטם עם התמונה הנמוכה והצרה בהומפייג'

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
יופי תודה
