### ISSUE TITLE
Lobby order

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#104]
כאנחנו באים לסדר את פריטי הלובי לפי מועד אירוע, האייטמים לא מסתדרים בצורה כרונולוגית
נראה שזה מסתדר לפי המספר הראשון בתאריך במקום לפי כל התאריך

![image](https://cloud.githubusercontent.com/assets/26960693/25807010/fe67dc56-340d-11e7-9f34-83d081e7fc7c.png)

**Comment by reasonat** [comment]
Again, syncing from you doesn't work. I cant know why... 
Here is the duplicated task I have created. Closing this one. 
https://github.com/Reasonat1/Cinema/issues/109
