### ISSUE TITLE
personal page title of film list

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#105]
משהו השתבש בשורה שנמצאת מעל רשימת הסרטים
במקום שיהיה כתוב 
saved films
כתוב
saved movie groups

ובעברית
במקום שיהיה כתוב 
סרטים שמורים 
כתוב
מקבץ סרטיםים שמורים

**Comment by reasonat** [comment]
I have update this related issue with this info. 
Closing this one
