### ISSUE TITLE
toptix top margin

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#106]
toptix frame opens by clicking event tickets button .

the frame top border is too close to page top, please add top margin because the top border has an "X" which allows closing it .

**Comment by bruria1** [comment]
לפי מה שאני רואה הבעייה קיימת רק לאדמין.
האם אני טועה?

**Comment by reasonat** [comment]
@yakoub ?

**Comment by reasonat** [comment]
I can approve this is only for admin user. Closing this issue.
