### ISSUE TITLE
Homepage - ordering by date isn't working well

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#109]
כאנחנו באים לסדר את פריטי הלובי לפי מועד אירוע, האייטמים לא מסתדרים בצורה כרונולוגית
נראה שזה מסתדר לפי המספר הראשון בתאריך במקום לפי כל התאריך

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;3f8dae3320f1452eac098d118c2b1b74:F37642833.A948692&#x2F;lobby+order.png">lobby order.png</a>

**Comment by JerusalemCinematheque** [comment]
![image](https://cloud.githubusercontent.com/assets/26960693/26144528/e2bf2082-3af1-11e7-8652-d04f34a5258d.png)

מתקבלת הודעת שגיאה

**Comment by bruria1** [comment]
אני לא רואה את הבעייה בעמוד הספציפי הזה. הסדר הנכון התקבל בלחיצה על תאריך ולא קיבלתי הודעת שגיאה. זה קרה בעוד מקומות שאתם יכולים להראות לי?

**Comment by JerusalemCinematheque** [comment]
נראה שזה עכשיו בסדר
