### ISSUE TITLE
Editor - adding media content into body text

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#112]
Add option to ckeditor to insert entity display mode / existing view into the content.

**Comment by reasonat** [comment]
Does the need is only for Logo's block? I guess not... 
Which node types this is relevant to [movies, events, etc]?

**Comment by JerusalemCinematheque** [comment]
all node types

not just the logos, as we wrote in a separate email - there is no embed option on the site. 
it would be great if we could add different features and contect type to other pages, similar to adding bio in film and article pages.

**Comment by JerusalemCinematheque** [comment]
יש איזו התקדמות עם עניין זה?

**Comment by JerusalemCinematheque** [comment]
@reasonat 
האם יש אפשרות לפחות להכניס את מנגנון הלוגואים לתוך סוגי התכנים השונים?

**Comment by reasonat** [comment]
אנחנו בודקים את הנושא.

**Comment by JerusalemCinematheque** [comment]
אמיר תוכל לעדכן אותנו בבקשה תוך כמה זמן אתם חושבים שזה יעמוד

**Comment by reasonat** [comment]
So this is the case: 
Embed entity inside the content using the editor - We can only embed nodes (Not terms or block or views) and in 1 display. 
Embed block - We can do this below the main content. This was we can embed logos gallery for example.

**Comment by JerusalemCinematheque** [comment]
below content meaning lets say in lobby - after lobby descirption or after content list?

embeded block - but it's a different logos gallery each time yes?

**Comment by reasonat** [comment]
We talk here only about content pages - Movie, article. No Lobby term page. 
What do you mean by "different logos" ?

**Comment by JerusalemCinematheque** [comment]
we have to have the logos gallery on lobby page as well
it's a different logo strip added to each page

**Comment by navotb** [comment]
we are asked to publish logos in each different page (film, lobby, articel
etc.) of the supporters of the film/event/program etc. so for each item it
is a different selection of logos.

**Comment by reasonat** [comment]
This are 2 separated  requests which will be in freeze. 
I combine them into one issue - https://github.com/Reasonat1/Cinema/issues/228

**Comment by reasonat** [comment]
@bruria1 Since on https://github.com/Reasonat1/Cinema/issues/228 we are dealing with embeding the logos block into nodes and lobby, here lets bring the focus back on the simple task which I guess already done:
- Adding image using wysiwyg

**Comment by bruria1** [comment]
@reasonat האם יש בעיה עם זה? עם העורך הקודם היתה בעיה אבל כעת נראה ליזה עובד מצויין.
http://dev.jff.reasonat.com/en/movie/8524

**Comment by bruria1** [comment]
מחכה לתגובתכם..

**Comment by reasonat** [comment]
Test and it looks good. Closing this issue. Reopen if needed.

**Comment by JerusalemCinematheque** [comment]
is there no way to have embedding on the site?

**Comment by bruria1** [comment]
לא הבנתי את שאלתכם?
להטמיע את מה? איפה?

**Comment by JerusalemCinematheque** [comment]
מלהטמיע סרטוני יוטיוב  להטמעה של מפות גוגל או דף חיצוני שמאפשר לעשות אייפריים

**Comment by reasonat** [comment]
Embedding Iframe is yet another request which is not in this request / scope. I open a new issue and freeze it. 
Closing this one, reopen if needed.
