### ISSUE TITLE
הגלרייה בעמוד הבית לא עובדת

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#114]
הגלרייה נקראית מהקובץ basic.js בשורה 1282.
כאשר האתר לא עובר אגרגציה עולה שגיאת js.

**Comment by yakoub** [comment]
@bruria1 the problem indeed that more-item class was not ready when needed to call the owlcarousel
now i moved the code here : 17a70b11ce1a13bb5904e8f39781b6baed1786f0
and verified owlcarousel is called .
but i don't know if now the page is good or still have other problems

**Comment by bruria1** [comment]
לבדיקה
