### ISSUE TITLE
header menu height

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#115]
@bruria1 
התפריט בהדר צריך לעלות כמה פיקסלים למעלה ולהיות מיושר עם האייקונים
![image](https://cloud.githubusercontent.com/assets/26960693/26032425/395ea5b4-389c-11e7-95ba-272054ff74c3.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
בצד עברית זה בסדר
בצד אנגלית התפריט התיישר למעלה במקום יישור אמצעי

**Comment by bruria1** [comment]
לבדיקה באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
עדיין נראה קצת גבו

**Comment by bruria1** [comment]
עכשיו?

**Comment by JerusalemCinematheque** [comment]
נראה מעולה
