### ISSUE TITLE
Saving film page error

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#116]
@reasonat  ניסינו לערוך את העמוד
http://jer-cin.org.il/he/node/5322/edit

לאחר לחיצה על שמירה קיבלנו את הודעת שגיאה
![image](https://cloud.githubusercontent.com/assets/26960693/26032444/a5cae6f4-389c-11e7-8ca8-69120d3bf430.png)

זה קרה מספר פעמים

**Comment by bruria1** [comment]
@yakoub הבעייה נגרמת מהסימון של הצ'קבוקס:
Create events
אתה הוספת את זה? אתה יכול לבדוק למה זה גורם לשגיאה?

**Comment by yakoub** [comment]
fixed .
