### ISSUE TITLE
facebook share - information shown

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#117]
@reasonat  שימו לב למידע שמגיע כשעושים שייר לאתר עצמו בפייסבוק
![image](https://cloud.githubusercontent.com/assets/26960693/25949830/8e4862d2-3661-11e7-93ce-f818c748db83.png)

בעיקר לא מובן לי ההופעה של המייל שלי פה

**Comment by bruria1** [comment]
האם עשיתם שייר לעמוד הבית? כי ממה שאני  רואה זה לא מה שקורה..

**Comment by JerusalemCinematheque** [comment]
גם אני לא, אבל זה בעמוד שלי משתמשת לא בעמוד של הסינמטק

**Comment by bruria1** [comment]
לא הבנתי.. מה שיתפת שזה מה שקיבלת?

**Comment by bruria1** [comment]
מחכה לתגובתכם..

**Comment by reasonat** [comment]
I have checked several pages and share open graph configured well. 
I am closing this issue, reopen if needed with examples.
