### ISSUE TITLE
calendar frontend on dev site does not update

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#118]
@reasonat @bruria1 @yakoub 
כתבתי על זה הערה באחד הנושאים הפתוחים, אבל נראה לי שכדאי לפתוח על זה שירשור
משום מה חלק מהאירועים שאנחנו מעדכנים היום באתר הdev לא מתעדכנים בפרונטאנד
או שלוקח להם הרבה זמן עד שרואים אותם בפרונט, גם אחרי שניקינו את הקאש
לדוגמא הוספנו אירועים לימים אחרי ה-31.5, אבל הם לא מופיעים
הערת ההקרנה שהוספנו ב-31.5 בpeople that are not me הופיעה רק אחרי שניקינו את הקאש ועשינו ריפרש כמה וכמה פעמים
או הוספנו קוד הקרנה בצד עברית והוא לא מופיע
ודוגמא נוספת, כשאני מחוברת כעורכת אני רואה את קוד ההקרנה ותקציר הסרט שהוספתי ל
there will be blood
ב-28.5. אבל כשאני לא מחוברת אני לא רואה מידע זה

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;546f86b65c2f4daea572a08135800518:F39123172.A948692&#x2F;Capture_cache.PNG">Capture_cache.PNG</a>

**Comment by yakoub** [comment]
אתם בטוחים שזה קורה רק ב DEV ?
כלומר זה קורה ב dev.jer-cin.reasonat.com 
אבל לא קורה ב jer-cin.org.il

**Comment by JerusalemCinematheque** [comment]
jer-cin מתעדכן מיידית
אנחנו נתקלים בזה רק באתרי ה-dev
אני לא יודעת אם זה בכל האתר, כי אני כרגע בודקת רק את עמודי הקלנדר
רק עכשיו אני רואה את קוד ההקרנה שהוספנו לאחת ההקרנות
ולדוגמא הנה אירוע שמתקיים ב-27.9
http://dev.jff.reasonat.com/en/event/6858
אבל היום הזה לא מופיע בקלנדר
אז יכול להיות שזה לא כל האתר, אלא רק עמוד הקלנדר

**Comment by JerusalemCinematheque** [comment]
יש חדש?

**Comment by reasonat** [comment]
@yakoub Please check this.

**Comment by JerusalemCinematheque** [comment]
קשה לנו להתקדם עם סגירת ענייני הקלנדר עד שהבאג הזה ייפתר

**Comment by yakoub** [comment]
@reasonat can someone please provide an updated example because much time has passed since this issue was opened .
i need detailed example so i understand the problem because i am not familiar with the calendar .

**Comment by JerusalemCinematheque** [comment]
a few examples 
1. there are dates that have events that do not show up on the calendar/ such as events on 27.6 frankenstein / 2.8 hangmen / 22.8 peter pan / 29.8 rosencrantz and guilderstern / 27.9 amadeus
so days that have events in them are not displayd
2. we created a day full of events in 7 or 8 halls on 27.5. Only one event is displayed
3. when we add events it takes the system some time to show them, if at all. the update is not immediate

**Comment by reasonat** [comment]
Moving this task to Alex

**Comment by sato2004** [comment]
What calendar are we talking about? This one http://dev.jer-cin.reasonat.com/en/article/4284 or http://dev.jff.reasonat.com/en/festival-calendar ?

**Comment by JerusalemCinematheque** [comment]
festival calendar

**Comment by sato2004** [comment]
This calendar shows only events published to Jerusalem Film Festival. After I've changed published options for each event, you can see these events on the calendar.  Moreover, this calendar shows only days from the range - Dates for navigation for current festival (This range you can change when editing the festival, for example here - http://dev.jer-cin.reasonat.com/en/taxonomy/term/12/edit )

**Comment by JerusalemCinematheque** [comment]
We were told that the festival calendar has no connection to the festival range. has this changed?
also i created many more events that have disappeared from the system
here are screen shots of the 27.5 of all the events that we created

![image](https://user-images.githubusercontent.com/26960693/26873234-c9ba7e2e-4b81-11e7-8c1e-61a325688ed6.png)
![image](https://user-images.githubusercontent.com/26960693/26873257-dd9d0772-4b81-11e7-92a5-8154750c76fe.png)

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

In the calendar there is a navigation for the days, these days are taken from the range - Dates for navigation. is it ok?
If I set here - http://dev.jer-cin.reasonat.com/en/admin/events-manager a filter by date 27.05 I dont see these events, It looks like these events have been deleted

**Comment by JerusalemCinematheque** [comment]
@reasonat we decided yesterday in our conversation that festival navigation range will no longer be a field in the term page. Or maybe i didn't understand. 
the events were published on the jff dev site. how can it be that all of them were deleted? perhaps it's a bug?

**Comment by JerusalemCinematheque** [comment]
i just created an event on 11.6
http://dev.jff.reasonat.com/en/event/7180
it does not showup on the calendar

**Comment by JerusalemCinematheque** [comment]
could this have anything to do with linking events/films to festival term?

**Comment by reasonat** [comment]
@JerusalemCinematheque It's what we have talked about :) 
Again - Festival term have public date range. 
Nodes that associate with the current festival get publish on the calendar

**Comment by JerusalemCinematheque** [comment]
okay i think then that we need full instructions about how to operate the calendar
we go to the festival term
we put in what dates? right now it's 8.4-30.9.17 in both festival publish date and navigation dates
then with every film and event we connect them to the festival term?

**Comment by JerusalemCinematheque** [comment]
but look the event i mentioned before
we didn't see it when we wrote the comment
but now an hour plus later it does show up in the calendar

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

This is a cache issue, if an event is not displayed on the calendar, you need to clear cache

**Comment by JerusalemCinematheque** [comment]
i had to clear cache a couple of times and reopen the browser to see the updates
is this going to be an issue on the live site as well?
we might have hourly updates, no one clears their cache that often
I also don't understand how all the events that i created for 27.5 were deleted and hope it's not a bug

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

Not browser cache, drupal cache

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

I think some time ago @yakoub abaya made update database of dev site from live site. After the update, the content of the site became the same as on a live site

**Comment by JerusalemCinematheque** [comment]
ok. so are we going to have to clear drupal cache after every update?

**Comment by JerusalemCinematheque** [comment]
just wanted to make sure that this wont be an issue on live site

**Comment by sato2004** [comment]
Yes, if there are some issues, it makes sense to clear drupal cache after update.
