### ISSUE TITLE
Calendar - toptix window 

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#119]
@reasonat  כשהפופ-אפ פתוח ולוחצים על כפתור הכרטיסים מתוך הפופ-אפ, חלונית טופטיקס צריכה להיפתח מעל הפופ-אפ ולא מתחתיה

**Comment by bruria1** [comment]
אני לא רואה את הבעייה.. או שלא הבנתי אותה?

**Comment by JerusalemCinematheque** [comment]
![image](https://cloud.githubusercontent.com/assets/26960693/26345874/f12fe240-3fac-11e7-9907-6d52a89066ab.png)

חלונית הרכישה נפתחת מתחת לפופ אפ במקום מעל הפופ אפ

**Comment by bruria1** [comment]
משום מה אני לא מצליחה לראות שום אירועים בלוח הפסטיבל.
@yakoub? @reasonat ?

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
אני רואה רק את ה-31.5
קשור אולי ל #118

**Comment by JerusalemCinematheque** [comment]
כפתור הכרטיסים לא עובד

**Comment by JerusalemCinematheque** [comment]
הכפתור לא עובד בצד אנגלית. בצד עברית עובד כמו שצריך והבעיה של החלונית נפתרה שם

**Comment by bruria1** [comment]
אני לא רואה בעיה. הכפתור עובד לי בעברית ובאנגלית.

**Comment by reasonat** [comment]
I can't see this issue on en / he site. 
Seems to me task https://github.com/Reasonat1/Cinema/issues/118  has nothing to do with it.

**Comment by reasonat** [comment]
Closing this issue. Please open if this happens again.
