### ISSUE TITLE
hall area display

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#120]
1. להחליף את החיווי לאולמות נוספים לשני חצים בבולד ושיהיו באותה שורה כמו האולמות
2. אולי כדאי להוסיף קו מתחת לשם כל אולם. השורה קצת מרחפת לה
3. כשעושים סקרול החלק של הקוביות מציץ מעל שורת האולמות
![image](https://cloud.githubusercontent.com/assets/26960693/26101380/a65e9f2c-3a39-11e7-978f-01ec1f2c54e4.png)

**Comment by reasonat** [comment]
I have update this task and close this one. Try to comment on exciting tasks instead of pening new one.. 
https://github.com/Reasonat1/Cinema/issues/46
