### ISSUE TITLE
share icons on http://jer-cin.org.il/he/movie/564

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#123]
@bruria1 @reasonat 
אייקוני השיתוף כאן (ונראה שרק כאן) השתבשו ומוצגים כטקסט במקום אייקון
http://jer-cin.org.il/he/movie/564

**Comment by bruria1** [comment]
טופל.
מישהו ערך את הדף הזה ושינה לו את התצוגה. יכול להיות שזה היה כבר ממש ממזמן.
