### ISSUE TITLE
Add FB and Google Pixels to the site

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#125]
This is an out of scope task which is on hold now.

**Comment by reasonat** [comment]
@JerusalemCinematheque Meanwhile you can provide us with the pixels and details.

**Comment by navotb** [comment]
We don't have pixels now, but from our experience pixels are add and
changed with every campaign, as you wish to collect users details in order
to retarget. There should be an option of adding and deleting pixels.

**Comment by reasonat** [comment]
option where? 
As far as I know, working with pixels with other client, we used to work with SEO person which provide with the info needed.

**Comment by navotb** [comment]
True, and we have marketing firm which provide us with the pixels. The
issue is that pixels come and go, and they are changed according to
campaign.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

This will be bases on bank hours / We can think about developing a way so you can change them - Which will also be on a bank hours.
