### ISSUE TITLE
person list when asking to add person to film page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#126]
@reasonat @yakoub 
משום מה כשאנחנו מבקשים לקשר איש בעמוד סרט (טבלת קרדיטים) לא נשלפות כל התוצאות האפשריות בחיפוש.
ראו חיפוש של שו פן
בשליפה של התוצאות לא מוצאים אותו
![image](https://cloud.githubusercontent.com/assets/26960693/26527370/47abcc0a-439b-11e7-85b3-49c528eae193.png)
רק אם כותבים את השם המלא התוצאה נשלפת

**Comment by reasonat** [comment]
אבל אפשר לראות בתמונה שצירפתם שכן רואים את שון פן בתחתית...

**Comment by JerusalemCinematheque** [comment]
שו
לא
שון

**Comment by reasonat** [comment]
For my best knowledge it's set up to first 3 letters include space. 
@yakoub ?

**Comment by JerusalemCinematheque** [comment]
החיפוש היה על השם פן, הפן השני שיש במערכת כן נשלף למרות שזה רק 2 אותיות

**Comment by reasonat** [comment]
כאשר אני מחפש ״שון״ זה מציג תוצאות. 
לא רוצה שניכנס לזה כעת, זה ברמת הרכיב הדרופלי ולא רואה כך בעיה קריטית כלל.

**Comment by JerusalemCinematheque** [comment]
יש כאן עוד דוגמא לבעיתיות של העניין
בהוספה של סרטים למקבץ יש לי סרט עם שלוש אותיות שאני לא יכולה למצוא כי לא מוצגות לי כל התוצאות
הסרט נקרא out
![image](https://user-images.githubusercontent.com/26960693/26878233-6c81e7a6-4b95-11e7-9bf5-2347a5a0e350.png)

**Comment by reasonat** [comment]
I think the best solution will be to change the widget to the one which open a dialog with advance search. @bruria1 ?

**Comment by bruria1** [comment]
@reasonat 
את כל שדות הרפרנס??? יש המון כאלה

**Comment by JerusalemCinematheque** [comment]
אין אפשרות פשוט להגדיל את כמות התוצאות שנשלפות?

**Comment by reasonat** [comment]
@bruria1 אני חושב שפשוט נתחיל בשדה הזה שמעורר בעיות, ככל הנראה בגלל כמות הערכים
@JerusalemCinematheque בטוח שאפשר אבל זה להתלכלך כעת כמה שעות.
