### ISSUE TITLE
Festival Archive - Update Festival taxonomy with related fields

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#127]
**Festival taxonomy should have this fields included:** 
There are currently many fields which need to stay, and here few more which need to get included if now already exist. 
 □ Image  - Main Archive image
 □ Paragraphs elements - The same like homepage functionality 

**Update:** 
We should have 2 seperate date fields - 1 is already exist. 
**Dates for navigation display (Exist - Just update the name of the field)** 
- Starting and Ending festival dates - This dates get display at the header of the festival site. 

**Dates for Festival content to get published - This is the new date field.** 
 □ Field name can be "Festival publish dates" 
 □ Start and end date

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

@Amir Taiar תמונה כבר הייתה. הוספתי את השדה של סקשיין. עכשיו נשאר לבדוק שכל העיצוב מתלבש טוב שם. לבדוק את זה?

**Comment by reasonat** [comment]
@bruria1 Sure

**Comment by bruria1** [comment]
@reasonat עובד..

**Comment by navotb** [comment]
I think we need more fields here

   1.  "festival name"  - is this field is the one that is sent to the
   navigation bar?
   2.  if yes- than all of the festivals under this domain will have the
   same name: Jerusalem Film Festival.
   3.  Since we do want the same name on the navigation bar

but

we don't want to have the same name for all the editions,

3.1 we need a second field for "Edition name" - this field is for

3.1.1 management purposes, i believe this is the right field for the
reference widget etc.

3.1.2 i think this is also the right field for the lobby title in the lobby
of lobbys etc.

**Comment by reasonat** [comment]
Edition has a title which is the term core title, and this will be the one to reference to.
We can add "Administration title" field, but I see no reason to. 

Current festival can always be "Jerusalem Film Festival" and then changed to something like "Jerusalem 2016 Film Festival"...

**Comment by navotb** [comment]
My worries is per the title in the navigation bar. Other than this i do not
really see a problem. I will prefer to define two different fields: one as
core for reference, and one for the navigation Bar.

**Comment by navotb** [comment]
My worries is per the title in the navigation bar. Other than this i do not
really see a problem. I will prefer to define two different fields: one as
core for reference, and one for the navigation Bar.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Bruria Helfer I added field - Festival publish dates

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@sato2004 We need to make sure that "Festival publish dates" reference field multilanguage behave is as like other reference fields on the site. Meanining when I translate movie node (example) to hebrew, the field will be coresponded with the hebrew term.
This is duplicate of Last comment is a duplicate of https://github.com/Reasonat1/Cinema/issues/155

**Comment by reasonat** [comment]
Seems like we can close this issue now
