### ISSUE TITLE
Home page item timing issues

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#128]
@reasonat @bruria1 
אייטמים בהום פייג' יורדים לפני הזמן שנקבע
לדוגמא
שטח הפקר תוכנן להופיע עד 25.5 בשעה 20:00
![image](https://cloud.githubusercontent.com/assets/26960693/26528250/e3b92e76-43af-11e7-8d76-17e1ab5e4d49.png)

אבל כבר בשעה 17:30 (אם לא לפני) הוא כבר לא הופיע
![image](https://cloud.githubusercontent.com/assets/26960693/26528251/f312a1b8-43af-11e7-968d-940a35dd0892.png)

**Comment by reasonat** [comment]
@sato2004 Please check this.

**Comment by sato2004** [comment]
fixed on the dev

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
is this fixed on live site as well?

**Comment by reasonat** [comment]
No, on dev. I close issues before deploy. They can always be open again.
