### ISSUE TITLE
screening details on film page is off

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#129]
@bruria1 @reasonat 
אני עכשיו מסתכלת במסך ברזולוציה 1920 ואני רואה שיש הבדל די משמעותי בתצוגה של שורת ההקרנה בין עמוד סרט לבין עמוד אירוע. כשבעמוד סרט השורה לא נכנסת לתוך קווי הגריד ונמתחת על פני כל המסך
לדוגמא
סרט
http://jer-cin.org.il/he/movie/7388
לעומת האירוע עם הסרט
http://jer-cin.org.il/he/event/7391

**Comment by bruria1** [comment]
לבדיקה באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok
