### ISSUE TITLE
front page - adding event/film 

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#130]
@bruria1 
אנחנו לא מצליחים בתצוגת רשימה רחבה בתוכן מסוג פרונט פייג' להוסיף נודים.
אחרי שאנחנו  פותחים את טבלת ההוספה, עושים חיפוש, לוחצים על האייטם המבוקש ועושים שמירה, החלונית לא נסגרת ולא ניתן לבחור את הנוד המבוקש

**Comment by JerusalemCinematheque** [comment]
זה גם בתצוגת ליסטה רגילה ותצוגת ספיישל גריד

**Comment by JerusalemCinematheque** [comment]
עכשיו לא מצליחה להוסיף לכל סוגי התוכן, למרות שלפני כמה דקות כן היה אפשר להוסיף בתצוגת גריד ובוואן אייטם

**Comment by bruria1** [comment]
ואם אתה סוגרים ידנית את החלונית, עם האיקס בצד ימין, התוכן הועלה למקום הנכון?

**Comment by JerusalemCinematheque** [comment]
לא

**Comment by bruria1** [comment]
פתחתי לזה טיקט #136
