### ISSUE TITLE
problem with transfering to English side

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#131]
@reasonat @bruria1 
כשלוחצים על מעבר לאנגלית של עמוד לובי זה
http://jer-cin.org.il/he/lobby/5-%D7%99%D7%9E%D7%99%D7%9D-%D7%91%D7%99%D7%95%D7%A0%D7%99
עוברים משום מה לעמוד לובי של תכנית אחרת ולא לעמוד הלובי המתורגם

לא יודעים אם זה קשור לכך שבתפריט האתר הלובי אליו עוברים באנגלית הופיע לפני כן גם בצד עברית והחלפנו אותו, אבל עוד לא עשינו זאת בתפריט בצד אנגלית

בכל אופן נוצר איזשהו לינקג' מוזר

**Comment by bruria1** [comment]
בדקו בבקשה

**Comment by bruria1** [comment]
מחכה לאישורכם..

**Comment by reasonat** [comment]
Test and it looks good. Closing this issue. Reopen if needed.
