### ISSUE TITLE
Clickable items

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#132]
@bruria1 
בכל התצוגות רצוי שכל האייטם יהיה קליקבילי לתוכן המקושר ולא רק התמונה או התמונה והכותרת
אלא גםהכותר,  התת כותרת או הטקסט להופ פייג'

**Comment by bruria1** [comment]
@reasonat 
אתה חושב שנכון שהטקסט גם יהווה קישור?

**Comment by reasonat** [comment]
From the title and description I can't even understand which display are we talking about here.

**Comment by JerusalemCinematheque** [comment]
בעמוד הבית
בכל סוגי התצוגות היינו רוצים שגם התמונה וגם הטקסט שמופיע על התמונה (כותרת, תת כותרת, טקסט להום פייג') יהיו קליקבילים

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
נראה שעובד בכל התצוגות
רק בוואן אייטם עובד קצת יותר מידי טוב וכפתור הכרטיסים גם מפנה לעמוד האייטם במקום לפתוח את כפתור הכרטיסים

**Comment by bruria1** [comment]
עודכן בסביבת הפיתוח

**Comment by JerusalemCinematheque** [comment]
ok
