### ISSUE TITLE
ipad compatibility

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#133]
@bruria1 תוכלי בבקשה לבדוק את האתר בתצוגת אייפד?
 יש שם כל מיני בעיות של מיקום השבירה - בעמוד הבית בתצוגת תמונות הגלריה שאין מרווח בין התמונות, בתצוגת גריד שתמונות נדבקות אחת לשנייה
בעמוד לובי שורת ההקרנה בורחת
וזה רק חלק מהדברים שראינו

**Comment by bruria1** [comment]
אנא בדקו

**Comment by bruria1** [comment]
מחכה לאישורכם..

**Comment by reasonat** [comment]
Test and it looks good. Closing this issue. Reopen if needed.
