### ISSUE TITLE
site name

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#134]
שם האתר גם בשמירה במועדפים וגם בתוצאות חיפוש מופיע באנגלית
אפשר לשנות את זה כך שאם מגיעים לתוצאות חיפוש או שומרים את צד עברית השם מופיע בעברית
ואם באנגלית אז השם מופיע באנגלית?

**Comment by reasonat** [comment]
@bruria1 Please translate open-graph and metatag settings to HP 
http://jer-cin.org.il/he/admin/config/search/metatags/config/global%3Afrontpage/translate 
Then check saving to browsers favorite. Search changes will be only after a while though.

**Comment by bruria1** [comment]
לבדיקה.

**Comment by JerusalemCinematheque** [comment]
אפשר שאם שומרים את צד אנגלית השם יופיע באנגלית?

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
מעולה
