### ISSUE TITLE
send to my calendar icon disappears from main calendar

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#135]
@bruria1 
בלוח השנה הגדול במעבר ליום אחר אייקון שלח לקלנדר שלי נעלם
כניסה לקלנדר האייקון מופיע
![image](https://cloud.githubusercontent.com/assets/26960693/26529940/7df0be32-43d3-11e7-8925-18d461202af7.png)
עוברים יום והאייקון לא מופיע
![image](https://cloud.githubusercontent.com/assets/26960693/26529941/8aefbd18-43d3-11e7-89e9-09b45275f933.png)

**Comment by bruria1** [comment]
@yakoub ?

**Comment by reasonat** [comment]
@sato2004 This seems like an API issue - Please check this

**Comment by sato2004** [comment]
@reasonat  fixed on the dev site

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
this hasn't been fixed on live site yet

**Comment by reasonat** [comment]
See other comment...
