### ISSUE TITLE
החלונית של הוספת תוכן לא נסגרת

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#136]
אם למשל מוסיפים תוכן מסוג calendar note ושם מוסיפים פרגרפ של קישור לנוד ושם בוחרים  תוכן, לאחר בחירת התוכן החלונית לא נסגרת.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

http://dev.jer-cin.reasonat.com/en/node/add/calendar-note
add node reference -> add item

**Comment by reasonat** [comment]
As far as I see this can be closed. @bruria1 @yakoub ?

**Comment by yakoub** [comment]
@reasonat no, problem not fixed yet

**Comment by yakoub** [comment]
@reasonat  @bruria1  i don't understand this setup and don't know about paragraphs .
is this standard paragraph widget which opens a view like that ?
how can i create similar setup on clean drupal installation ?

**Comment by yakoub** [comment]
fixed .

**Comment by JerusalemCinematheque** [comment]
ok
