### ISSUE TITLE
calendar - mobile view

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#137]
@reasonat @bruria1 
האם קיימת גרסה ריספונסיבית לקלנדר הפסטיבל?
ראינו שהיה משהו בעבר, אבל כרגע בקישור 
http://jff.reasonat.com/en/festival-calendar-mobile
לא רואים שום דבר

**Comment by bruria1** [comment]
http://dev.jff.reasonat.com/he/festival-calendar-mobile
