### ISSUE TITLE
Highlight cart icon for log in user

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#139]
Hightlight the icon at the top menu when: 
- There are items in the cart
AND
- When user is log-in

**Comment by navotb** [comment]
toptix user or drupal user?

**Comment by reasonat** [comment]
Lets wait for @yakoub to tell us which will be the best option

**Comment by navotb** [comment]
I think it is only toptix user, since i can have tix in basket without
being registered in drupal side.

**Comment by yakoub** [comment]
yes, this is about toptix user .

**Comment by reasonat** [comment]
@yakoub Can we a class fir this case? Or other solution?

**Comment by yakoub** [comment]
i don't understand

**Comment by reasonat** [comment]
We need to find a way to highlight the cart icon in case there are items in the cart. 
How can we do this? Please do it :)

**Comment by yakoub** [comment]
@reasonat i added class "active" to the basket <button> .

**Comment by reasonat** [comment]
@bruria1 Please frontend this.

**Comment by bruria1** [comment]
Done

**Comment by JerusalemCinematheque** [comment]
don't see a difference between when signed in or not signed in

**Comment by JerusalemCinematheque** [comment]
working now

**Comment by JerusalemCinematheque** [comment]
when user (anonymous or not) has items in basket, basket supposed to be highlighted

![image](https://user-images.githubusercontent.com/26960693/27932048-ecffbd56-62a4-11e7-9e39-c261dc7696a1.png)

**Comment by bruria1** [comment]
@yakoub I need a class for that case.

**Comment by yakoub** [comment]
fixed
