### ISSUE TITLE
personal page - title before save films and events

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#140]
@reasonat @bruria1 
הכותרת שמופיע לפני רשימת הסרטים השמורים השתבשה ומופיע כ
3 Saved סרטs
גם בעברית וגם באנגלית

בצד עברית בחלק של ההקרנות שלי מופיע ההסבר על העמוד באנגלית במקום בעברית
Use the  to create your films and events WISH LIST

**Comment by bruria1** [comment]
לבדיקה.

**Comment by JerusalemCinematheque** [comment]
בצד אנגלית עדיין מופיע משובש

וזה?
בצד עברית בחלק של ההקרנות שלי מופיע ההסבר על העמוד באנגלית במקום בעברית
Use the to create your films and events WISH LIST

אנחנו צריכים לערוך את העמוד מחדש? איפה אנחנו עושים זאת?

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
בצד אנגלית עדיין מופיע כ
Saved **סרטs**
במקום
saved films

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
