### ISSUE TITLE
home page - adding items

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#141]
@bruria1 @reasonat 
אי אפשר להוסיף פריטים ברצף בלי לעשות שמירה אחרי הוספה של כל פריט
לדוגמא - הוספנו חלק של גריד
עשינו שמירה
הוספנו אייטם
ביקשנו להוסיף עוד אייטם
השורה עבור האייטם החדש לא נפתחת. ומתקבל מסך כזה
![image](https://cloud.githubusercontent.com/assets/26960693/26668628/496dc4a6-46b3-11e7-9709-68655cc0a5a5.png)
וכשעושים שמירה מתקבלת הודעת השגיאה הבאה
Fatal error: Call to undefined function _radix_process_element() in /home/jercin/public_html/includes/form.inc on line 1870

רק אם מוסיפים אייטם ועושים שמירה ניתן להוסיף אייטם נוסף

**Comment by bruria1** [comment]
@yakoub Can you check this?

**Comment by yakoub** [comment]
לא הצלחתי לשחזר הבעיה
http://jer-cin.reasonat.com/en/node/7591/edit

**Comment by bruria1** [comment]
@yakoub זה קורה כשאתה מוסיף למשל לקבוצה של גריד תוכן, מסיים ואז מוסיף תוכן נוסף לאותה קבוצה.

**Comment by bruria1** [comment]
האם זה עדיין קורה? מבדיקה שלי זה עובד טוב כעת.

**Comment by JerusalemCinematheque** [comment]
עובד בסדר גמור עכשיו
