### ISSUE TITLE
Paragraph form - Add a title to each item in the edit form

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#142]
לא לעכשיו, אלא אם זה משהו פשוט
אבל זה מאוד יעזור אם בכל שדה יהיה כתוב איזה אייטם יש בו
יעזור לנו מאוד לנווט ולנהל את העמוד

**Comment by reasonat** [comment]
@bruria1 Yes! Actually we do need this also for other projects. This is a module issue, and I think we should look for an issue / report one.

**Comment by bruria1** [comment]
בבקשה הסתכלו כעת באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
אני לא רואה שמשהו השתנה.
זה אמור להיות תקף גם על פריטים שכבר נמצאים שם או רק על פריטים שנוסיף מעכשיו?

**Comment by bruria1** [comment]
כעת זה עובד.
אך אם משנים נוד בתוך אחד מהלמנטים זה לא מתעדכן אלא רק ברענון ל העמוד. האם זה קריטי?

**Comment by JerusalemCinematheque** [comment]
רענון העמוד כלומר בשמירה?

**Comment by bruria1** [comment]
כן. אם תשנו תוכן הכותרת לא תעודכן. רק על ידי שמירה הכותרות יתעדכנו.

**Comment by JerusalemCinematheque** [comment]
אז הכל בסדר
