### ISSUE TITLE
new person type

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#144]
@reasonat 
האם אפשר בבקשה להוסיף באיש פרסון טייפ - "פורמט"?

**Comment by navotb** [comment]
או לחילופין להפוך את person type לטבלת ערכים שאפשר לעדכן אותה?

**Comment by bruria1** [comment]
http://jer-cin.org.il/he/admin/structure/taxonomy/person_type
אתם יכולים להוסיף. תוסיפו באנגלית ואז תוסיפו תרגום לעברית
