### ISSUE TITLE
 management page - Operations options

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#145]
@reasonat 
אנא תוסיפו בעמודי הניהול השונים
operations options
כפי שיש בעמוד ניהול התוכן הכללי
ואם אפשר להוסיף לאפשרויות שם 
change domain access / publish to domain access
יהיה מעולה

**Comment by bruria1** [comment]
כוונתכם לאפשרות לשנות באופן גורף את הדומיין של התכנים?
איזה עוד דברים אתם צריכים שם?

**Comment by JerusalemCinematheque** [comment]
ניסיתי עכשיו לעשות את השינוי דומיין
בחרתי סרט
לחצתי על שינוי דומיין לדומיין סינמטק
לחצתי אישור
ואז קיבלתי את הודעת השגיאה הבאה
 
 
![image](https://cloud.githubusercontent.com/assets/26960693/26818649/2a5e617a-4aa4-11e7-8847-1d50cdd45ba3.png)
 
 
אבל כשחזרתי אחורה ראיתי שהשינוי כן נעשה

**Comment by bruria1** [comment]
כרגע עשיתי זאת ולא עלתה לי שגיאה.
איפה עשית? בלייב? בדב?
מה בדיוק עשית?

**Comment by JerusalemCinematheque** [comment]
בלייב
נכנסתי לעמוד ניהול סרטים
בחרתי נודס שנוצרו עד ה-20.6.2016
סימנתי את הסרט הצחוק האחרון
לחצתי על change domain
בחרתי בnew domain settings
jerusalem cinematheque
ובaction to perform
replace
ואז הבא
נפתח מסך שבו נראה שהמערכת מבצעת את הפעולה
ואז הופיעה השגיאה

**Comment by bruria1** [comment]
אכן מופיעה שגיאה כאשר מבצעים סינון.
@yakoub האם תוכל לבדוק את זה?

**Comment by JerusalemCinematheque** [comment]
יש חדש?

**Comment by sato2004** [comment]
fixed on dev

**Comment by bruria1** [comment]
מחכה לאישורכם..

**Comment by reasonat** [comment]
I test and it looks fine. Closing this issue, pleaser reopen if needed.
