### ISSUE TITLE
person with only first name

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#146]
@reasonat @bruria1 
כיש "איש" שיש לו רק שם פרטי כמו מדונה או סאנדנס 
בפרונטאנד מוצג שחסר שדה שם משפחה
לדוגמא
http://jff.reasonat.com/he/movie/597
מבינים שבגלל ששם נוצר משדה שם פרטי ושדה שם משפחה אז נוצרת כאן הבעיה, אבל יש לנו מקרים שאין שם משפחה

**Comment by bruria1** [comment]
הפיתרון הכי פשוט הוא שאם אין שם משפחה תרשמו בשדה רווח.

**Comment by navotb** [comment]
אבל אז זה ייצור טעויות במקרה של מספר פריטים בשדה למשל:
משחק: מדונה ,  וורן ביטי

הרווח אחרי מדונה ולפני הפסיק הוא רווח מיותר

**Comment by bruria1** [comment]
אם כך מלאו רק את שם המשפחה ואת השם הפרטי השאירו עם רווח. אני חושבת שכך הבעייה לא מתרחשת.

**Comment by navotb** [comment]
אני חושב שנקבל את אותה הבעיה מהצד השני של הפסיק: במקום רווח אחד, יהיו לנו
שני רווחים.
אי אפשר להגיד לשדה שאם הוא ריק שלא יציג כלום? למה בכלל הוא מציג את שם השדה?

2017-06-04 9:13 GMT+03:00 Bruria <notifications@github.com>:

**Comment by bruria1** [comment]
האם ניסית? כי לפי מה שאני ראיתי לא הייתה בעייה.

**Comment by navotb** [comment]
אחלה, הסתדר
אבל שימי לב לשגיאה אחרת בנוד
http://jff.reasonat.com/he/movie/597

בחלק שמתחת לתמונה
בו מופיעים פרטי הסרט בפונט בולד
מופיע minutes וצ"ל דקות

**Comment by navotb** [comment]
ועוד ענין לא קשור
אבל נתקלתי בו במהלך העבודה על הענין הזה
שימי לב שבעמוד רשימת האישים person manager
בפילטר המיון "type"
נכנס משום מה "מועדון טרום בכורה" כאפשרות בחירה
למרות שאין כזה "person type" בטקסונומיה

​

2017-06-04 9:31 GMT+03:00 Navot <navotb@gmail.com>:

> אחלה, הסתדר
> אבל שימי לב לשגיאה אחרת בנוד
> http://jff.reasonat.com/he/movie/597
>
> בחלק שמתחת לתמונה
> בו מופיעים פרטי הסרט בפונט בולד
> מופיע minutes וצ"ל דקות
>
>

**Comment by bruria1** [comment]
סידרתי את שני הדברים

**Comment by JerusalemCinematheque** [comment]
ok
