### ISSUE TITLE
Festival Archive - Create the main archive page

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#152]
We need to make the main archive page
**This page should display:** 
 □ Grid view of all festivals terms - There should be a link to the term page
 □ organise by date fro new to old.

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

http://dev.jer-cin.reasonat.com/en/festival-archive @Amir Taiar

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Should we even have this page? For now it's only for testing. 
@bruria1 Please add date range field [where ever you want on each term) just for testing.

**Comment by navotb** [comment]
Should not it be just like a lobby of lobbys page? with the same
capabilities?

**Comment by bruria1** [comment]
@reasonat Done

**Comment by reasonat** [comment]
@navotb It does build in a grid teasers like the lobby pages. 
Same functionality meaning the ability to change the display modes - Not in this scope - This page isn't even part of the plan, we just made it for a QA process.

**Comment by reasonat** [comment]
Closing this issue

**Comment by JerusalemCinematheque** [comment]
רגע יש לי שאלה
כל מהדורה זה term
איך אנחנו מייצרים את עמוד הלובי של הארכיון עם כל המהדורות?
האם אפשר לקשר את הterm לעמוד מסוג פרונט פייג'?

**Comment by reasonat** [comment]
Sure, here is the task 
https://github.com/Reasonat1/Cinema/issues/167
