### ISSUE TITLE
Festival Archive - Display logic of nodes on site

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#153]
**Now that we have a festival date range we will need to implement this logic on Festival site:** 
All over the site (Search, Calendar, Lobby, Person favorite page, etc) the nodes that will be display are those who taged with the current festival. 

**For this to happen we will need some:** 
 □ Dummy festival terms - Past festivals. 
 □ Set current festival date range.

**Comment by navotb** [comment]
What we would like to have is 
1. The Content of the current edition of the festival is available until editor decide to move the edition to archive
2. This move is not dependant upon festival dates range (!!!)
3. Archive include editions of each festival, under each edition we can keep the lobbys, film, events etc,

**Comment by reasonat** [comment]
1+2. Means festival edition (term) range and that what this task is about. So I can't understand why it has nothing to do with dates range. 
3. Edition (Term) edited manually so you can add Lobbys, films and so on as you wish.

**Comment by navotb** [comment]
(1) Date range of edition for the display of items in the website is
different from the (2) date range of the festival itself, which is 13 to 23
of july this year.
So in the top navigation bar we want these dates to appear (2), but when it
comes to the date range of the content (1) we want it for much longer
period: starting months earlier and ending months later.

**Comment by reasonat** [comment]
Sure, I have update another task with this details. 
@sato2004 @bruria1 Should know by now that when talking about nodes display is according to the new date field which we already created.
