### ISSUE TITLE
Festival Archive - Festival term management page

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#154]
Create a new (if now exist) festival term management page. 
Use regular best practices, plus: 
 □ Date range column - So editor will know active festival. 
 □ Default order by date range starting from current to past festivals.

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

http://dev.jer-cin.reasonat.com/he/admin/festival-terms-manage @Amir Taiar

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Bruria Helfer
1.I can see this view as anonimous user. 
2. Change Festival date to Publish dates and make sure this is the field which display

**Comment by bruria1** [comment]
Done

**Comment by JerusalemCinematheque** [comment]
@reasonat דיברנו על להוציא את 
navigation dates

Change Festival date to Publish dates and make sure this is the field which display
רק רוצים לוודא שאין קשר בין פאבליש דייטס והתאריך שמופיע בראש האתר

**Comment by JerusalemCinematheque** [comment]
@bruria1 בעיות התצוגה שיש כאן קשורות לכך שזה בdev?

**Comment by bruria1** [comment]
התאריך שמופיע בראש האתר הוא תאריך שמוזן ידנית בתיבה הזו:
http://dev.jer-cin.reasonat.com/en/block/festival-title---hebrew/edit

**Comment by JerusalemCinematheque** [comment]
זה מה שחשבתי. רק רציתי לוודא כי ההערה לא היתה לי ברורה

**Comment by JerusalemCinematheque** [comment]
הם אפשר לשנות את הווידג'ט כך שהבחירה המרובה תהיה בשדה נפרד כל פעם ולא על ידי פסיקים?

**Comment by bruria1** [comment]
לא הבנתי על איזה שדה מדובר..

**Comment by JerusalemCinematheque** [comment]
סליחה אולי ההערה לא מתאימה לשרשור הזה
השדה בחירת פסטיבל בכל העמודים
האם אפשרי להפוך את השדה שיהיה כמו של השפות /מדינות וכו'
כלומר בחירה מרובה נפרדת בכל שדה

**Comment by reasonat** [comment]
לא קשור לפה אבל ברוריה ביצעה עדכון על זהשדה ומחיקה של השדה הקיים.
