### ISSUE TITLE
Festival Archive - Make sure node forms has festival term field reference

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#155]
All content type should have an entity reference field to festival taxonomy. 
Probably we will make most usage with movies, still all content type should have this field.

example :
http://dev.jer-cin.reasonat.com/he/node/6868/edit
private field - festival

**Comment by bruria1** [comment]
הוספתי את השדה ל-
אירוע, איש, מאמר, סרט, מקבץ סרטים
באתר דב.

**Comment by reasonat** [comment]
@bruria1 please make sure that this field work in a corresponding multi-language way, like other references fields. So when I add a translation to a node the corresponding term will be auto populate in the field [If exist]

**Comment by bruria1** [comment]
@reasonat זה לא קורה, ממה שאני יודעת זה קוה רק כאשר המילון מוגדר: 
Localize. Terms are common for all languages, but their name and description may be localized.
אבל פה זה לא מתאים כי התוכן צריך להיות לגמרי שונה באנגלית ובעברית.
גם משום מה כאשר באים לבחור פסטיבל מוצגים רק אלה באנגלית. אולי כדאי ש @yakoub יסתכל פה כי הוא עבד על התרגומים.

**Comment by reasonat** [comment]
@bruria1 התוכן שונה אבל המהדורה עדיין מוצגת בשתי השפות ולכן זה כן צריך להיות כך. 
@yakoub Please take a look - 
1.  This field need to be multi-language as we did with other reference fields. 
2.  The term page can

 manually get updated with content - Has nothing to do with 1st request.

**Comment by bruria1** [comment]
@reasonat 
המילון מוגדר כך:
 Translate. Different terms will be allowed for each language and they can be translated.
ואני חושבת שזה צריך להישאר כך

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Bruria Helfer or @Amir Taiar please provide example where translation synchronization is not working :
1 - node id
2 - taxonomy reference field name

**Comment by bruria1** [comment]
למשל פה:
http://dev.jer-cin.reasonat.com/he/node/6868/edit
private field - festival
מופיעים גם הערכים בעברית וגם באנגלית 
וכאשר אני הולכת לעמוד באנגלית:
http://dev.jer-cin.reasonat.com/en/node/6867/edit
הערך המוזן זה הערך בעברית

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@yakoub abaya Please take care of this. Main task is corresponeding field data. Secondery is that the data populated in the field widget will be in the language I am in. We can skip this 2nd issue.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Amir Taiar
1 - i don't understand what is "corresponding field data"
2 - the taxonomy select shows only english terms on both translation versions which is not default drupal behavior that shows all terms in all languages .

i remeber the taxonomy issue was passed for @Alex Voloshchenko for handling, was there any custom work done on the widget ?

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Amir Taiar someone changed the widget to autocomplete and that solved the problem unless it is required that it will be select list .

i tested it and synchronization is working, only if no translation exists for some term that you 'll get same term in different languages .

**Comment by yakoub** [comment]
@reasonat this is working now with autocomplete widget .

**Comment by JerusalemCinematheque** [comment]
אם נוד לא משוייך לפסטיבל אז לא יראו אותו?

**Comment by reasonat** [comment]
לא יראו אותו בלוח שנה

**Comment by JerusalemCinematheque** [comment]
ואם מדובר על מאמר / איש לדוגמא?
או שמספיק שעשינו להם שיוך לדומיין פסטיבל?

**Comment by reasonat** [comment]
אני לא מבין את השאלה

**Comment by JerusalemCinematheque** [comment]
אם יש לנו נודס מסוג מאמר / איש שלא עשינו להם שיוך לפסטיבל, האם לא יראו אותם במהדורה?
אם לא חיברנו איש למהדורה אבל הוא מקושר לסרט במהדורה, אז לא יראו אותו בעמוד הסרט?
או לא יוכלו להיכנס אליו?

**Comment by reasonat** [comment]
מאמר / איש יופיעו במהדורה במידה ותוסיפו אותם - שוב, זה עריכה ידנית
אם איש קשור לסרט דרך עמוד סרט אז יראו אותו בעמוד הסרט ללא קשר למהדורה כלל

**Comment by JerusalemCinematheque** [comment]
למעשה אנחנו לא מבינים למה צריך לשייך את כל סוגי התוכן למהדורה
ברור שאירועים, סרטים, מקבצים, לובי צריכים להיות מקושרים למהדורה
זה ייצור את החיווי העתידי בתוך העמודים ויערוך את הפילטור בחיפוש
לא ברור לי לגבי שאר סוגי התוכן ומה זה אומר אם הם לא משוייכים למהדורה

**Comment by JerusalemCinematheque** [comment]
וגם שדה השיוך לא שולף תוצאות 
לדוגמא כאן
http://jff.reasonat.com/en/node/8524/edit
ניסינו לשייך את הסרט לטרם פסטיבל 
Jerusalem film festival 2017
אבל התוצאה הזו לא נשלפת

**Comment by reasonat** [comment]
הוספנו את השדה לכל סוגי התוכן והישויות, גם אם כעת זה לא בשימוש. 
בקשר לבעיה שהעלית
@bruria1 please have a look

**Comment by bruria1** [comment]
@sato2004 Can you look at this?
cautocompete custom is not working properly. it upload another taxonomy.

**Comment by sato2004** [comment]
I changed the fields with autocomplete widget

**Comment by JerusalemCinematheque** [comment]
ok
