### ISSUE TITLE
Lobby - Add festival terms to management page

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#156]
Add a column to the management page +filters, of the Festival terms associated with each Lobby.

**Comment by bruria1** [comment]
@reasonat אין שדה כזה בלובי. צריך להיות שדה כזה כמו בשאר סוגי התוכן?

**Comment by reasonat** [comment]
Yes, at the basic level which we are facing now, a lobby can be referenced to a festival term.

**Comment by bruria1** [comment]
Done

**Comment by JerusalemCinematheque** [comment]
האם לא צריך להוסיף ללובי גם domain access?

**Comment by bruria1** [comment]
הוספתי באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
לא רואה שדה דומיין

**Comment by JerusalemCinematheque** [comment]
אני מסתכלת בעמוד ניהול לוביים
http://jff.org.il/he/admin/taxonomy-manage?language=All&machine_name=lobby&name=&field_administrative_title_value=&field_festival_tid_selective=All

ורואה את כל הלובי שאני קישרתי לפסטיבל הקולנוע 2017

אבל כשאני נכנסת לעריכה של כל אחד מהם או עושה סינון בעמוד ניהול של פסטיבל 2017
לא נראה שיש קישור לפסטיבל

**Comment by bruria1** [comment]
לא ברורה לי ההערה.
נכנסתי למשל לעריכה של הסיווג א-ת והוא אכן מסווג ל "פסטיבל הקולנוע ירושלים 2017"
איפה עוד זה אמור להופיע?

**Comment by JerusalemCinematheque** [comment]
לדוגמא
http://jff.org.il/he/taxonomy/term/693/edit?destination=admin/taxonomy-manage%3Flanguage%3DAll%26machine_name%3Dlobby%26name%3D%26field_administrative_title_value%3D%26field_festival_tid_selective%3DAll**

**

**Comment by bruria1** [comment]
אמור להיות בסדר כעת. אבל מחקתי לכם ערכים של הפסטיבל.
הוספתי לכם אופציה מהטבלה לעדכן באופן גורף את שדה בפסטיבל.

**Comment by JerusalemCinematheque** [comment]
מה עם דומיין אקסס לעמודי לובי?

**Comment by bruria1** [comment]
הכוונה לאפשרות לשייך לובי לדומיין מסויים?

**Comment by JerusalemCinematheque** [comment]
כן. כך שאם הסרט מוצג לאחר מכן בדומיין אחר לא יעבור איתו הלובי

**Comment by reasonat** [comment]
לא מבין למה שיעבור איתו הלובי? 
אין לנו אפשרות להוסיך שיוך דומיין לסיווג, יש לזה בעיקרון רכיב המאפשר את זה אלא שהוא מלא בבאגים ותקלות. כתיבת קוד ייעודי תיקח המון שעות עבודה. 
כיוון שגם כך מגיעים ללובי דרך העמודים עצמם לא רואה סיבה להשקיע בזה

**Comment by navotb** [comment]
אז איך אתה רוצה לעשות "השתתף בפסטיבל. 2017, בלובי X"?

2017-06-26 9:49 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by navotb** [comment]
סליחה, בלבלתי בין טקסנומיה פסטיבל לשיוך דומיין.

2017-06-26 10:56 GMT+03:00 Navot <navotb@gmail.com>:

**Comment by navotb** [comment]
the problem with this issue it this
assume film x is screened in festival under lobby 1
assume the same film x is being screened later in cinema under lobby 2
now, when we have the film page in cinema site, it will show both lobby 1
and lobby 2 as the film's lobbies (since lobby 1 does not have end date)

so we need to find a way to prevent festival lobbies from crossing to
cinema site

2017-06-26 11:12 GMT+03:00 Navot <navotb@gmail.com>:

**Comment by bruria1** [comment]
זו הבעיה היחידה?
כי אם כך אפשר לעשות זאת עם שדה פשוט בעמודי לובי.
@reasonat ?

**Comment by JerusalemCinematheque** [comment]
מה זה אומר שדה פשוט?
כמו הצ'ק בוקס שיש בקרדיטים בעמוד סרט
הצג בצד סינמטק
הצג בצד פסטיבל

**Comment by bruria1** [comment]
כן

**Comment by bruria1** [comment]
מחכה לאישורכם..

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb We are waiting...

**Comment by navotb** [comment]
where is the checkbox? on the lobby edit page? i can not find it, sorry.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Bruria Helfer

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

fixing something

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Bruria Helfer please review 
http://dev.jer-cin.org.il/he/event/8830
http://dev.jer-cin.org.il/he/taxonomy/term/688/edit

**Comment by bruria1** [comment]
@yakoub זה טוב.
אמור לעבוד אותו הדבר בעמוד סרט:
http://dev.jer-cin.org.il/he/movie/7322
זה היבט אחר.

**Comment by yakoub** [comment]
@bruria1 הוספתי גם לעמוד סרט

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
can the setting be according to the domain the lobby was created in?
as in, if we created the lobby in jer-cin domian the lobby automatically gets jer-cin domain
but if we created the lobby on jff domain then the lobby gets jff domain automatically

**Comment by reasonat** [comment]
הבקשה הזו חורגת 
I am closing this issue. Please reopen if needed.

**Comment by JerusalemCinematheque** [comment]
issue was closed but this hasn't been updated on live site

**Comment by reasonat** [comment]
@bruria1 ?

**Comment by bruria1** [comment]
האם מדובר על כך שהסיווג לחיץ? זה מעודכן גם בלייב לפי מה שאני רואה.
אם לא תראו לי דוגמה.

**Comment by JerusalemCinematheque** [comment]
לא. מדובר על עניין בחירת הדומיין ללובי כמו שיש כאן
http://dev.jff.reasonat.com/he/taxonomy/term/631

**Comment by bruria1** [comment]
@yakoub אני לא יודעת מה עשית שם.. בעמודי סרט זה עובד ולוביים שמשויכים לדומיין מופיעים אך ורק בדומיין אך בעמודי אירוע זה לא עובד.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

this should be fixed by synchronizing features and delivering to live site

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

https://www.wrike.com/open.htm?id=171727128

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Bruria Helfer i synchronized features and hope this will fix it, please review .

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

what i did is call function cm_extra_event_view_lobby_list from views php field

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

but this happens only in view movie_top_pane_view

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

in display panel_pane_2 field lobby_list

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

seems to me when i worked on this i didn't get requirement for the list to appear on event page but only on movie page

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

let me know what else needs to be done here

**Comment by bruria1** [comment]
@yakoub זה לא עובד בעמודי אירוע. רק בעמודי סרט.

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

@yakoub abaya זה לא עובד בעמודי אירוע, רק בעמודי סרט

**Comment by yakoub** [comment]
seems to be working now : http://jer-cin.org.il/he/event/11593

**Comment by JerusalemCinematheque** [comment]
זה צריך לעבוד על הצד המתורגם אוטומטית
כלומר עם שייכתי לובי לדומיין פסטיבל בצד אנגלית, הוא צריך גם להיות מקושר לדומיין הזה בצד עברית
לדוגמא
http://jff.org.il/he/taxonomy/term/747
שייכתי אותו מצד אנגלית לדומיין פסטיבל. אבל בצד עברית הוא משוייך לדומיין סינמטק

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
Ok
