### ISSUE TITLE
Event page - subtitles

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#158]
בעמוד אירוע אם לסרט המקושר אין שפת תרגום מופיע עדיין תרגום ל... למרות שבעמוד הסרט זה מופיע בסדר
לדוגמא
http://www.jer-cin.org.il/he/movie/7186

http://www.jer-cin.org.il/he/%D7%90%D7%99%D7%A8%D7%95%D7%A2/7189

**Comment by sato2004** [comment]
fixed on a live

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by reasonat** [comment]
משהו השתבש עם התצוגה של שדה "תרגום" בעמוד הסרט ובעמוד האירוע
בצד אנגלית חזרה המילה
subtitles
ובצד עברית כתוב
תרגום ל|תרגום לעברית
במקום רק תרגום לעברית

**Comment by JerusalemCinematheque** [comment]
this is on the DEV site 
http://dev.jff.reasonat.com/he/movie/8523

http://dev.jff.reasonat.com/en/movie/8524

And it happened after we added the logos

We still see the issue here

**Comment by yakoub** [comment]
@JerusalemCinematheque problem fixed .

**Comment by JerusalemCinematheque** [comment]
great
