### ISSUE TITLE
film page - credits

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#159]
@reasonat @yakoub 
שימו לב לנוד סרט הבא
http://jff.reasonat.com/he/movie/7769

בקרדיט פסטיבלים אמורים להופיע רק סאנדנס וsxsw
נכנס לשם המון זבל, נודס שלא קשורים לא לאישים ולא לשדה הזה

**Comment by JerusalemCinematheque** [comment]
תעשו לו רגע publish כדי לראות את הבעיה
אבל בבקשה אחרי זה תעבירו אותו חזרה לunpublish

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
אוקיי
זו בעיה שחוזרת על עצמה כבר כמה פעמים, אז אנחנו רק רוצים לוודא שהבאג אכן נפתר

**Comment by bruria1** [comment]
מה שעשיתי אמור לפתור את הבאג הזה.

**Comment by reasonat** [comment]
סוגר את זה אבל באמת גם מקווה שזהלא יחזור...

**Comment by navotb** [comment]
אתם יודעים להגיד למה זה קורה?

**Comment by bruria1** [comment]
כן. היה שם קוד לא נכון

**Comment by JerusalemCinematheque** [comment]
תראו כאן
http://jer-cin.org.il/he/event/7286

זה אומנם לא עמוד הסרט אבל זה אותה בעיה

**Comment by bruria1** [comment]
האם כעת בסדר?

**Comment by JerusalemCinematheque** [comment]
ok
נקווה שלא יצוץ שוב

**Comment by reasonat** [comment]
@bruria1 Please have a look - http://jff.org.il/en/movie/8771 
and here http://jff.org.il/en/movie/9397

**Comment by navotb** [comment]
In early stages it was a matter of bilingual issue. Is it still this
problem? If it is a frontend issue - do you know why it affects the backend?
