### ISSUE TITLE
film page - when language field is empty

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#160]
@bruria1 
ראו דוגמא
http://jff.reasonat.com/he/movie/7784

אם שדות השפה לא מולאו אין צורך שיופיעו הקווים המפרידים בשורת המידע שמופיעה מעל התקציר
כמו כן לא צריך להופיע תרגום ל....

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
רק יש פייפ מיותר אחרי הדקות

**Comment by bruria1** [comment]
בדקו כעת

**Comment by JerusalemCinematheque** [comment]
הפייפ שלפני הדקות עכשיו נעלם

**Comment by bruria1** [comment]
צרפת 2016 | 28 דקות

מה הבעייה?

**Comment by JerusalemCinematheque** [comment]
http://jff.reasonat.com/en/movie/7876

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
Ok
