### ISSUE TITLE
movie collection title in the films of the collection

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#161]
@bruria1 @reasonat 
האם יש אפשרות להוסיף לסרטים שמקושרים למקבץ את שם המקבץ אליו הם מקושרים?
לא בהופעה שלהם במקבץ, אלא בכל עמוד סרט
לדוגמא זה המקבץ שנקרא "שניים תיעודיים של וורנר הרצוג"
http://jer-cin.org.il/he/movie-group/6780

זה אחד הסרטים שמקושרים למקבץ זה
http://jer-cin.org.il/he/movie/6652

האם אפשר שבעמוד זה יהיה כתוב איפשהו  - שניים תיעודיים של וורנר הרצוג

**Comment by reasonat** [comment]
מקפיא את זה כעת
