### ISSUE TITLE
home page one item responsive display

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#162]
@bruria1 
בתצוגה ריספונסיבית בעמוד הבית
בוואן אייטם עם אירוע
נעלמו כותרות האירוע והסרט
![image](https://user-images.githubusercontent.com/26960693/26886051-0f85c28a-4bad-11e7-8b4f-7ca6a5edcf3e.png)

**Comment by bruria1** [comment]
לבדיקה באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok
