### ISSUE TITLE
Body text area

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#164]
@reasonat 
משהו השתנה  בתיבות הטקסטים
אי אפשר לעשות בו סקרול כדי לראות את כל הטקסט
וצריך לגרור אותו מלמטה כדי להגדיל את האזור ולראות את כל הטקסט
תראו לדוגמא כאן
http://jer-cin.org.il/en/node/4236/edit

**Comment by bruria1** [comment]
סידרתי. באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
http://dev.jer-cin.reasonat.com/en/node/4752/edit
לא רואים

**Comment by bruria1** [comment]
ברגע שהתוכן יחרוג מהחלונית יהיה סקרול

**Comment by JerusalemCinematheque** [comment]
http://dev.jff.reasonat.com/he/node/6794/edit?destination=admin/content%3Ftitle%3D%26type%3Dcm_article%26author%3D%26status%3DAll%26vid%3DAll

**Comment by JerusalemCinematheque** [comment]
ועכשיו קיבלנו הודעת שגיאה כשהכנסנו טקסט לקוביית פרטי אירוע מקוצרים שהטקסט ארוך מידי למרות שהוא לא
Short event details cannot be longer than 255 characters but is currently 905 characters long.


**
![image](https://user-images.githubusercontent.com/26960693/27010373-84534424-4eab-11e7-8758-14461e20b55e.png)
**

נראה שנכנס מלא טקסט לpath ומחרבש את ספירת האותיות

**Comment by bruria1** [comment]
אני לא רואה איפה יש בעייה עם ספירת התווים

**Comment by JerusalemCinematheque** [comment]
מכניס איזשהו קוד לpath ולא נתן לשמור
אז עשיתי שוב קופי פייסט והיה בסדר

בכל אופן לא נפתח סקרול כשיש טקסט ארוך יותר

**Comment by JerusalemCinematheque** [comment]
וכשאני מגדילה את הקופסא כל פעם שאני עושה פעולה הקופסא חוזרת למצבה הראשוני

**Comment by JerusalemCinematheque** [comment]
מקווה שאפשר להבין מהוידאו מה הבעיה
https://www.youtube.com/watch?v=n5jfwV_k-C4

**Comment by bruria1** [comment]
האם עורך התוכן החדש פותר את הבעיה?
בכל מקום שכבר יש תוכן יהיה עליכם להעבירלעורך התוכן החדש אם תרצו לערוך את התוכן.
שדות חדשים יופיעו עם עורך תוכן זה.

**Comment by JerusalemCinematheque** [comment]
הבדל משמעותי. תודה.
האם אפשר להגדיר ששורה חדשה  תהיה בריווח של פסקה חדשה ולא כמו ריווח בין משפטים באותה פסקה?

**Comment by bruria1** [comment]
לא הבנתי..

**Comment by JerusalemCinematheque** [comment]
כרגע כשעושים אנטר ומתחילים שורה חדשה הריווח בין שתי השורות הוא כמו של שתי שורות בתוך פסקה
היינו רוצים שכשלוחצים על אנטר יהיה רווח יותר גדול בין שתי השורות
כמו ריווח כפול (שזה מה שאני עושה עכשיו כדי שלא כל הטקסט יראה כמו פסקה אחת)

**Comment by JerusalemCinematheque** [comment]
לא שמנה
אנחנו כבר נסדר את זה ידנית
תודה

**Comment by JerusalemCinematheque** [comment]
i think this can be closed
