### ISSUE TITLE
festival calendar responsive view

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#165]
@reasonat @bruria1 

רוחב פס אולם רחב מידי 

להתאים לתצוגה היומית של צד סינמטק:             
שעה וכפתור כרטיסים באותה שורה
כותרת אירוע בשורה חדשה בבולד

פתיחה/ סגירה של אולם צד אנגלית לא עובד (ראו 11.6)

שורת הימים
חסרים חצי דפדוף

**הקובייה הימינית ביותר (צד אנגלית) נחתכת ואם עוברים ימים אז הקוביה השמאלית נחתכת**

![image](https://user-images.githubusercontent.com/26960693/26928368-8f20c4f2-4c5e-11e7-9baa-b072c055fb7a.png)

![image](https://user-images.githubusercontent.com/26960693/26928349-820cdff8-4c5e-11e7-8257-ab527779fc6c.png)

**כשמדפדפים בין הימים כמה מהקוביות מסומנות בצבע האתר**
![image](https://user-images.githubusercontent.com/26960693/26928313-5bd130fa-4c5e-11e7-8c10-7a48904719b5.png)

**Comment by bruria1** [comment]
בדקו כעת

**Comment by JerusalemCinematheque** [comment]
אפשר להצר את פס האולם אפילו עוד קצת

הפונט של השעה וכותרות האירועים גדול מידי. כדי להתאים לגודל מיני קלנדר סינמטק
כנ"ל כפתור הכרטיסים

סדר האולמות לא נשמר

כשעוברים יום, לחזור לתחילת העמוד

**Comment by bruria1** [comment]
רוחב פס האולם הוא על כל רוחב המסך. מה זאת אומרת להצר אותו?
השאר בסדר כעת?
לגבי סדר האולמות. מה זאת אומרת לא נשמר? איך הוא אמרו להיות?

**Comment by JerusalemCinematheque** [comment]
להצר מבחינה של גובה סליחה. אפשר להוריד לו כמה פיקסלים למעלה ולמטה
cinmeatheque 1
cinmeatheque 2
cinmeatheque 3
cinmeatheque 4

אם תיכנסי ל11.6 תראי שהסדר שם הוא
cinmeatheque 2
cinmeatheque 3
cinmeatheque 1
lev smadar
egypt hall
cinmeatheque 1
cinmeatheque 4
וכו'

**Comment by bruria1** [comment]
הסדר הוא לפי האירוע הקרוב ביותר.
האם אתם רוצים את הסדר לפי שמות האולמות?
לגבי הכותרת הנמכתי אותה

**Comment by JerusalemCinematheque** [comment]
כן לפי סדר האולמות

**Comment by JerusalemCinematheque** [comment]
האם אפשר להתאים את גודל כפתור הכרטיסים לגודל שלו במיני קלנדר סינמטק?

**Comment by bruria1** [comment]
האם כעת זה בסדר?

**Comment by JerusalemCinematheque** [comment]
אני לא מצליחה לגלול בתוך היום

**Comment by JerusalemCinematheque** [comment]
לגבי גודל כפתור הכרטיסים לצורך השוואה
![image](https://user-images.githubusercontent.com/26960693/27031770-4dfbb51c-4f7a-11e7-9f1f-dea565ae44b5.png)

![image](https://user-images.githubusercontent.com/26960693/27031816-7e5311b0-4f7a-11e7-8def-be4dfba82bb7.png)

**Comment by bruria1** [comment]
וכעת?

**Comment by JerusalemCinematheque** [comment]
אני רואה את זה אותו הדבר
ועדיין לא מצליחה לגלוש ביום עם הרבה אירועים כמו ה-11.6 (צד אנגלית)
ניקיתי קאש של האתר ושל הבראוזר

**Comment by bruria1** [comment]
לא רואה בעיה.. @reasonat

**Comment by JerusalemCinematheque** [comment]
אם סוגרים אולם אז אפשר לראות את האולם אחרי

**Comment by bruria1** [comment]
אין כרגע אירועים?
לא ניתן לראות את העמוד..

**Comment by JerusalemCinematheque** [comment]
יש ב-31.5 אירועים

**Comment by bruria1** [comment]
לא רואה כלל אירועים..
בלייב?

**Comment by JerusalemCinematheque** [comment]
לא. באתר פיתוח

**Comment by bruria1** [comment]
פה?
http://dev.jff.reasonat.com/he/festival-calendar
ריק...

**Comment by JerusalemCinematheque** [comment]
הוספנו אירועים גם לקלנדר וגם להערות קלנדר ב-15.6 בצד אנגלית בסביבת פיתוח

**Comment by bruria1** [comment]
עדיין לא הבנתי  מה הבעיה...

**Comment by JerusalemCinematheque** [comment]
יש ב-15.6 צד אנגלית אירועים בחמש אולמות
בתצוגה במובייל כשמנסים לגלול בתוך הקלנדר כל העמוד נגלל ולא רק הקלנדר, כל שלמעשב אי אפשר להגיע לכל האירועים שנמצאים ביום הזה
בנוסף לא רואים את הקלנדר נוטס

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
עובד
בקלנדר נוטס הכותרת ממורכזת במקום להיות מיושרת שמאלה / ימינה (בהתאם לשפה)

כשעוברים בין הימים אומנם העמוד חוזר להתחלה, אבל לא לגמרי להתחלה שלו אלא לכותרת של האירוע הראשון ביום

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
רק המעבר בין הימים
זה נפתח ככה
![image](https://user-images.githubusercontent.com/26960693/27260226-9a16d76a-542f-11e7-8d86-df5c5f8ed247.png)

במקום
![image](https://user-images.githubusercontent.com/26960693/27260229-a3a3cb26-542f-11e7-948c-acf706adca2f.png)

**Comment by bruria1** [comment]
בטוח? זה סודר.. נסו לרענן ולנקות את הקאש.

**Comment by JerusalemCinematheque** [comment]
עשינו ולא רואה שינוי
תגללי למטה באחד הימים ואז תעברי יום

בנוסף בצד עברית סדר האולמות לא נשמר. לב סמדר לדוגמא מופיע לפני סינמטק 4 למרות שבעמוד ניהול אולמות הוא מופיע אחריו (15.6)

**Comment by bruria1** [comment]
אמור להופיע כפי שהסדר בעמוד הסיווגים.

לגבי האג'קס האם ניקיתם את הקאש של הדפדפן במובייל?

**Comment by JerusalemCinematheque** [comment]
עכשיו הסדר בסדר

וכן ניקיתי את הקאש של הדפדפן ושל האתר

**Comment by bruria1** [comment]
ועדיין לחיצה לא מפנה לראש העמוד?
באתר פיתוח?

**Comment by JerusalemCinematheque** [comment]
לא

**Comment by bruria1** [comment]
אצלי עובד :(
נסו שוב..

**Comment by reasonat** [comment]
Closing this one and focusing on this one
https://github.com/Reasonat1/Cinema/issues/225
