### ISSUE TITLE
event translation

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#166]
@reasonat @yakoub 
הקמנו אירוע בצד אנגלית
http://dev.jff.reasonat.com/en/event/7183
ביקשנו לתרגם אותו
עברנו לצד עברית
עשינו שמור
מקבלים הודעת שגיאה שהדף לא נמצא
אבל בעמוד ניהול אירועים נראה שהאירוע קיים
בקלנדר נוסף יום האירוע (11.6) אבל לא מופיע שום בו שום אירוע
http://dev.jff.reasonat.com/he/event/7219

**Comment by reasonat** [comment]
@bruria1 Please review this

**Comment by bruria1** [comment]
@yakoub ??

**Comment by yakoub** [comment]
this is probably same issue as #169

**Comment by yakoub** [comment]
fixed by @sato2004 
problem was caused by view pane included in that page which was altered in custom hook views_query_alter in my_utilities.module .

**Comment by yakoub** [comment]
@reasonat please review
should i move this fix to live now or wait until all branch master is ready ?

**Comment by reasonat** [comment]
@yakoub  You can make a delivery at the end of this day

**Comment by JerusalemCinematheque** [comment]
we are still receiving messages that the page is not found after editing a saved item

**Comment by yakoub** [comment]
this problem is not related to translation .
please follow here instead : https://github.com/Reasonat1/Cinema/issues/186
