### ISSUE TITLE
Homepage - Add option to add Festival term

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#167]
When creating/editing HP, PG's should have the option to add Festival terms nodes in all display styles. 

**At the basic level add this fields:** 
- Image
- Title
Both linked to the term page.

**Comment by bruria1** [comment]
הוספתי את האופציה הזו בכל אפשרויות התצוגה בעמוד הבית

**Comment by bruria1** [comment]
מחכה לאישורכם..

**Comment by reasonat** [comment]
Closing this issue. Reopen if needed.
