### ISSUE TITLE
Festival Archive - Make sure current festival linked to Homepage

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#168]
Current Festival term (both language) should redirect to the Festival homepage.

**Comment by sato2004** [comment]
It is ready on dev site

**Comment by JerusalemCinematheque** [comment]
איך אנחנו בודקים את זה?

**Comment by reasonat** [comment]
@sato2004 Seems like all terms lead to HP. 
Also I have freeze this task but have a look, seems this issue link to this one. 
https://github.com/Reasonat1/Cinema/issues/208

**Comment by sato2004** [comment]
I can't see the bug, this link http://dev.jff.reasonat.com/en/festivals/jerusalem-film-festival-2017 have redirect to hp, this one http://dev.jff.reasonat.com/en/festivals/2017 does not have. 
About link http://jff.org.il/he/taxonomy/term/12 this is language issue, link should be http://jff.org.il/en/taxonomy/term/12

**Comment by reasonat** [comment]
@sato2004 Thanks. @JerusalemCinematheque I approve this after QA, Please review

**Comment by reasonat** [comment]
Tested: 
http://www.jff.org.il/en/festivals/jerusalem-film-festival-2017 - Lead to HP
http://www.jff.org.il/en/taxonomy/term/12 - Lead to HP
http://www.jff.org.il/he/festivals/%D7%A4%D7%A1%D7%98%D7%99%D7%91%D7%9C-%D7%94%D7%A7%D7%95%D7%9C%D7%A0%D7%95%D7%A2-%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D-2017 - Lead to HP

**Comment by JerusalemCinematheque** [comment]
so if i want to add the 2017 festival term to a front page i created for festival archive
it will lead back to the home page instead of the term page?
and it continues to be the current festival term untill its date range passes?
what happens if the next festival term and the current festival term have corresponding dates?
and does it matter if there is no current festival term?

**Comment by reasonat** [comment]
As we discussed, dates scheduling are on your responsible. 
But to unswer this, @sato2004 please answer: 
1. If 2 festival terms set to current date, what will happen to the homepage? 
2. If there is not term set for current dates, what happen to homepage?
