### ISSUE TITLE
event page - event detials spacing issue on dev site

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#170]
@bruria1 
באתר dev יש בעיה בריווח של תקציר האירוע
http://dev.jff.reasonat.com/en/event/7223
יכול להיות שזה קשור לdev?

**Comment by JerusalemCinematheque** [comment]
הפונט באופן כללי נראה לי לא בסדר

**Comment by bruria1** [comment]
done

**Comment by JerusalemCinematheque** [comment]
ok
