### ISSUE TITLE
main menu - english/hebrew

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#171]
@reasonat @bruria1 
באתר פסטיבל אין תפריט ראשי נפרד לעברית ולאנגלית
הוספתי עכשיו קישור במה שחשבתי שהוא התפריט לצד אנגלית והוא מופיע לי גם בצד עברית

**Comment by bruria1** [comment]
כעת כשתוסיפי קישורים תוכלי לבחור את השפה

**Comment by JerusalemCinematheque** [comment]
אני לא רואה איפה בוחרים את השפה

**Comment by bruria1** [comment]
![screen](https://user-images.githubusercontent.com/5786526/27072602-8d9747a4-5029-11e7-8c7f-b0a05dd040bd.png)

**Comment by JerusalemCinematheque** [comment]
באתר לייב אין בחירה

![image](https://user-images.githubusercontent.com/26960693/27073067-3fc7d2c6-502b-11e7-904c-f651a44a1a32.png)

**Comment by bruria1** [comment]
כשאת יוצרת לינק חדש את יכולה להגדיר שפה.
ברגקע שהלינק נוצר לא ניתן לשנות את השפה שלו

**Comment by JerusalemCinematheque** [comment]
ok
