### ISSUE TITLE
tickets button does not work

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#173]
@reasonat 
כפתור הכרטיסים לא עובד
לא בקוביות ולא בפופ אפ

**Comment by bruria1** [comment]
איפה? אני לא רואה בעיה..

**Comment by JerusalemCinematheque** [comment]
בקלנדר תראי לדוגמא 27.9

**Comment by bruria1** [comment]
@yakoub

**Comment by yakoub** [comment]
@bruria1 how do i reach 27.9 in the calendar ?

**Comment by JerusalemCinematheque** [comment]
it's the last day in the calendar on the english side

**Comment by yakoub** [comment]
currently http://dev.jff.org.il/he/festival-calendar is empty page .

**Comment by JerusalemCinematheque** [comment]
what happened to all the dummy events we created on dev side?

**Comment by yakoub** [comment]
i copied live database over dev one by request from @reasonat

**Comment by yakoub** [comment]
in future if you find it required we can put dummy content in csv file and import it after each database copy from live .

**Comment by yakoub** [comment]
@JerusalemCinematheque can you please add some new content so i can work on this ?

**Comment by JerusalemCinematheque** [comment]
see 27.9

**Comment by yakoub** [comment]
@JerusalemCinematheque i only see 13.7 and 19.7

**Comment by JerusalemCinematheque** [comment]
it's on dev site

**Comment by yakoub** [comment]
here http://dev.jff.org.il/he/festival-calendar
i see 17.6 and it has tickets button and it opens without problem

seems like you have read previous comment that i copied live site into dev site and all dummy content was lost

**Comment by JerusalemCinematheque** [comment]
button working on hebrew side
please check english side 27.9

yes we are creating new dummy events

**Comment by yakoub** [comment]
the tickets button in 27.9 working for me .

**Comment by JerusalemCinematheque** [comment]
ok thank you
maybe it was a cache issue
