### ISSUE TITLE
send to my films loading time

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#175]
@reasonat 
הלחיצה על הלב לוקחת זמן רב מידי

**Comment by reasonat** [comment]
באיזה אתר? באיזו סביבה?

**Comment by JerusalemCinematheque** [comment]
עמוד קלנדר בdev festival

**Comment by reasonat** [comment]
נבדוק באתר לייב ונשפר ביצועים במידת הצורך לאחר מכן

**Comment by JerusalemCinematheque** [comment]
בדקתי עכשיו בלייב בעמוד הקלנדר
לוקח לו איזה שלוש שניות לעבוד
הבעיה המרכזית היא ה"גרפיקה" של הפעולה. כלומר כשלוחצים על הלב המסך חמשיר ויש סימן של לודינג
מה שלא קיים בעמודים אחרים בפונקציה של הלב

**Comment by reasonat** [comment]
שלוש שניות זה הגיוני כל לא עושים שיפור ביצועים רציני יותר. 
@bruria1 למה במסך הלוח שנה יש החשכה להבדיל מעמודים אחרים?

**Comment by bruria1** [comment]
@reasonat על מה מדובר אמיר? אני לא רואה..

**Comment by reasonat** [comment]
I opened this issue and closing this one
https://github.com/Reasonat1/Cinema/issues/219
