### ISSUE TITLE
calendar hebrew side - discrepancy in view between user that is logged in and user that is not logged in

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#176]
@reasonat 
בצד עברית של הקלנדר יש הבדל בוויו בין משתמש מחובר ומשתמש לא מחובר
כשמשתמש לא מחובר חלק מהקוביות "יוצאות מהמקום שלהן"
תסתכלו על ה-11.6 בעברית
מפלצת עם אלף ראשים משובצת באולם לב סמדר
האולם לא מופיע כשלא מחוברים
וההקרנה קופצת לטור של סינמטק 1
ופעם נוספת לטור של אולם מצרים
יש שם עוד מספר דוגמאות כאלו
אלו אירועים שסומנו כמפורסמים אז לא אמורה להיות להם תצוגה שונה

משתמש מחובר
![image](https://user-images.githubusercontent.com/26960693/27037916-1279545a-4f92-11e7-9b18-2aeafbcbcace.png)

משתמש לא מחובר
![image](https://user-images.githubusercontent.com/26960693/27037889-05bc36ce-4f92-11e7-994e-32180cabe638.png)

**Comment by bruria1** [comment]
@sato2004 
משום מ ה למשתמש לא מחובר האולם "לב סמדר" בדוגמה פה לא מופיע.
תוכל לבדוק?

**Comment by JerusalemCinematheque** [comment]
יכול להיות שקשור ל
#188

**Comment by reasonat** [comment]
I cant see this issue again, and 188 waiting for review. 
CLosing this one
