### ISSUE TITLE
inserting link in body text

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#177]
ניסיתי להכניס בתוך עמוד קישור לעמוד חיצוני וקיבלתי הודעת שגיאה

[{"command":"settings","settings":{"basePath":"\/","pathPrefix":"en\/","ajaxPageState":{"theme":"cinemateque","theme_token":"MJ0EZpE30Wjef5VDg5G3VINCjpynBX5YFRT45AsV2gY","jquery_version":"1.10"},"colorbox":{"opacity":"0.85","current":"{current} of {total}","previous":"\u00ab Prev","next":"Next \u00bb","close":"Close","maxWidth":"98%","maxHeight":"98%","fixed":true,"mobiledetect":true,"mobiledevicewidth":"400px"},"da11y_setting":{"da11y_resize_font_plus":"Increase font size","da11y_resize_font_minus":"Decrease font size","da11y_bg_grayscale":"Grayscale","da11y_bg_high_contrast":"High Contrast","da11y_bg_negative_contrast":"Negative Contrast","da11y_bg_light":"Light Background","da11y_links_underline":"Links Underline","da11y_readable_font":"Readable Font","da11y_reset":"Reset","da11yLink_sitemap_title":"","da11yLink_sitemap_url":"","da11yLink_help_title":"","da11yLink_help_url":"","submit":"Save configuration","form_build_id":"form-uGDGS_YO-mIHRcVtcswGL7iYxJhqyz5HM2Prdj32iXA","form_token":"69qIjR7V4W9AQyGxox7t4yLLJ8QyW-hnW65DThKhl3A","form_id":"da11y_admin_settings","op":"Save configuration"},"jquery_ajax_load":{"trigger":".jquery_ajax_load","target":"#jquery_ajax_load_target","toggle":true,"animation":true,"base_path":"\/","module_path":"sites\/all\/modules\/jquery_ajax_load","site_name":"Jerusalem Cinematheque \u2013 Israel Film Archive","TBtrigger":".twitter_bootstrap_modal","TBmodaltrigger":".bs_modal","TBmodule":"sites\/all\/modules\/twitter_bootstrap_modal","TBpath":"\/","TBname":"Jerusalem Cinematheque \u2013 Israel Film Archive"},"CToolsModal":{"modalSize":{"type":"scale","width":".9","height":".9","addWidth":0,"addHeight":0,"contentRight":25,"contentBottom":75},"modalOptions":{"opacity":".55","background-color":"#FFF"},"animationSpeed":"fast","modalTheme":"CToolsModalDialog","throbberTheme":"CToolsModalThrobber"},"panopoly_magic":{"pane_add_preview_mode":"disabled"},"popup":{"effects":{"show":{"default":"this.body.show();","fade":"\n        if (this.opacity){\n          this.body.fadeTo(\u0027medium\u0027,this.opacity);\n        }else{\n          this.body.fadeIn(\u0027medium\u0027);\n        }","slide-down":"this.body.slideDown(\u0027medium\u0027)","slide-down-fade":"\n        this.body.animate(\n          {\n            height:\u0027show\u0027,\n            opacity:(this.opacity ? this.opacity : \u0027show\u0027)\n          }, \u0027medium\u0027\n        );"},"hide":{"default":"this.body.hide();","fade":"this.body.fadeOut(\u0027medium\u0027);","slide-down":"this.body.slideUp(\u0027medium\u0027);","slide-down-fade":"\n        this.body.animate(\n          {\n            height:\u0027hide\u0027,\n            opacity:\u0027hide\u0027\n          }, \u0027medium\u0027\n        );"}},"linger":"250","delay":"0"},"custom_search":{"form_target":"_self","solr":1},"ajax":{"edit-profile-content-editors":{"callback":"linkit_change_profile","wrapper":"linkit-dashbaord-ajax-wrapper","method":"replaceWith","effect":"fade","event":"click","url":"\/en\/system\/ajax","submit":{"_triggering_element_name":"profile"}}},"urlIsAjaxTrusted":{"\/en\/system\/ajax":true,"\/en\/linkit\/dashboard\/content_editors":true},"linkit":{"currentInstance":{"profile":"content_editors","autocomplete":{"charLimit":"3","wait":"350","remoteTimeout":"10000"}}}},"merge":true},{"command":"insert","method":"html","selector":"#linkit-modal","data":"\u003Cform action=\u0022\/en\/linkit\/dashboard\/content_editors\u0022 method=\u0022post\u0022 id=\u0022linkit-dashboard-form\u0022 accept-charset=\u0022UTF-8\u0022 role=\u0022form\u0022\u003E\u003Cdiv\u003E\u003Cdiv id=\u0022linkit-profile-changer\u0022\u003E\u003Cdiv class=\u0022form-item form-type-radios form-item-profile form-group\u0022\u003E\n  \u003Clabel for=\u0022edit-profile\u0022\u003ESelect profile to use \u003C\/label\u003E\n \u003Cdiv id=\u0022edit-profile\u0022 class=\u0022form-radios\u0022\u003E\u003Cdiv class=\u0022form-item form-type-radio form-item-profile radio\u0022\u003E\n  \u003Clabel for=\u0022edit-profile-content-editors\u0022\u003E\u003Cinput type=\u0022radio\u0022 id=\u0022edit-profile-content-editors\u0022 name=\u0022profile\u0022 value=\u0022content_editors\u0022 checked=\u0022checked\u0022 class=\u0022form-radio\u0022 \/\u003EContent Editors \u003C\/label\u003E\n\n\u003C\/div\u003E\n\u003C\/div\u003E\n\u003C\/div\u003E\n\u003C\/div\u003E\u003Cinput type=\u0022hidden\u0022 name=\u0022form_build_id\u0022 value=\u0022form-hQjlbyAGUtZZXGHIOtdKHlBPlrnDMvWEJQWIY4y7fz8\u0022 \/\u003E\n\u003Cinput type=\u0022hidden\u0022 name=\u0022form_token\u0022 value=\u0022i4Vw0Je_NcbRbXAXLknOgWk5ES4RMrmHckhol45ebjc\u0022 \/\u003E\n\u003Cinput type=\u0022hidden\u0022 name=\u0022form_id\u0022 value=\u0022linkit_dashboard_form\u0022 \/\u003E\n\u003Cdiv id=\u0022linkit-dashbaord-ajax-wrapper\u0022\u003E\u003Cdiv id=\u0022edit-linkit-container\u0022 class=\u0022form-wrapper\u0022\u003E\u003Cdiv class=\u0022form-item form-type-textfield form-item-linkit-search form-group\u0022\u003E\n  \u003Clabel for=\u0022edit-linkit-search\u0022\u003ESearch for content. \u003C\/label\u003E\n \u003Cinput class=\u0022linkit-search-element form-control form-text\u0022 type=\u0022text\u0022 id=\u0022edit-linkit-search\u0022 name=\u0022linkit_search\u0022 value=\u0022\u0022 size=\u002260\u0022 maxlength=\u0022255\u0022 \/\u003E\n\u003Cspan class=\u0022help-block\u0022\u003EStart typing to find content or paste a URL.\u003C\/span\u003E\n\u003C\/div\u003E\n\u003Cdiv class=\u0022form-item form-type-textfield form-item-linkit-path form-group\u0022\u003E\n  \u003Clabel for=\u0022edit-linkit-path\u0022\u003ELink URL \u003Cspan class=\u0022form-required\u0022 title=\u0022This field is required.\u0022\u003E*\u003C\/span\u003E\u003C\/label\u003E\n \u003Cinput class=\u0022linkit-path-element form-control form-text required\u0022 type=\u0022text\u0022 id=\u0022edit-linkit-path\u0022 name=\u0022linkit_path\u0022 value=\u0022http:\/\/israelfilm.blogspot.co.il\/2017\/06\/state-less-comes-to-local-cinematheques.html\u0022 size=\u002260\u0022 \/\u003E\n\u003Cspan class=\u0022help-block\u0022\u003EThis will be populated by the search, or you can fill it in yourself.\u003C\/span\u003E\n\u003C\/div\u003E\n\u003Cfieldset class=\u0022linkit-attributes collapsible collapsed form-wrapper panel panel-default\u0022 id=\u0022edit-linkit-attributes\u0022\u003E\u003Clegend class=\u0022panel-heading\u0022\u003E\u003Cdiv class=\u0022panel-title fieldset-legend\u0022\u003EOptions\u003C\/div\u003E\u003C\/legend\u003E\u003Cdiv class=\u0022panel-body fieldset-wrapper\u0022\u003E\u003Cdiv class=\u0022form-item form-type-textfield form-item-linkit-title form-group\u0022\u003E\n  \u003Clabel for=\u0022edit-linkit-title\u0022\u003ETitle \u003C\/label\u003E\n \u003Cinput class=\u0022linkit-attribute linkit-attribute-title form-control form-text\u0022 type=\u0022text\u0022 id=\u0022edit-linkit-title\u0022 name=\u0022linkit_title\u0022 value=\u0022\u0022 size=\u002240\u0022 maxlength=\u0022255\u0022 \/\u003E\n\u003C\/div\u003E\n\u003Cdiv class=\u0022form-item form-type-textfield form-item-linkit-class form-group\u0022\u003E\n  \u003Clabel for=\u0022edit-linkit-class\u0022\u003EClasses \u003C\/label\u003E\n \u003Cinput class=\u0022linkit-attribute linkit-attribute-class form-control form-text\u0022 type=\u0022text\u0022 id=\u0022edit-linkit-class\u0022 name=\u0022linkit_class\u0022 value=\u0022\u0022 size=\u002240\u0022 maxlength=\u0022255\u0022 \/\u003E\n\u003C\/div\u003E\n\u003C\/div\u003E\u003C\/fieldset\u003E\n\u003Cinput class=\u0022linkit-insert form-submit btn btn-default\u0022 type=\u0022submit\u0022 id=\u0022edit-linkit-insert\u0022 name=\u0022op\u0022 value=\u0022Insert link\u0022 \/\u003E\u003Ca id=\u0022linkit-cancel\u0022 href=\u0022#\u0022\u003ECancel\u003C\/a\u003E\u003C\/div\u003E\u003C\/div\u003E\u003C\/div\u003E\u003C\/form\u003E","settings":null},{"command":"insert","method":"prepend","selector":"#linkit-modal","data":"","settings":null}]

**Comment by reasonat** [comment]
איזה עמוד ?
מהם הצעדים שנעשו בכדי להוסיף את הלינק?

**Comment by JerusalemCinematheque** [comment]
http://jer-cin.org.il/en/node/7299/edit
בשדה תקציר ניסינו להכניס קישור חיצוני
כתבנו  טקסט. סימנו אותו. לחצנו על הכנסת קישור. הדבקנו את הקישור 
לחצנו אישור
ואז קיבלנו את הודעת השגיאה

**Comment by bruria1** [comment]
נסו עם עורך התוכן החדש

**Comment by JerusalemCinematheque** [comment]
ok
