### ISSUE TITLE
film page subtitles in english

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#179]
@bruria1 
בעמוד סרט במקום שיהיה כתוב תרגום ל
כתוב
subtitles
http://jer-cin.org.il/he/movie/3046

**Comment by bruria1** [comment]
סודר. מקווים שלא יקרה שוב.

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by navotb** [comment]
יש סיבה שזה חוזר?

**Comment by reasonat** [comment]
יש איזשהו עניין במעבר קונפיגורציות בין הסביבת פיתוח ללייב ואנחנו מנסים למצוא למה התרגומים נכנסים למסד נתונים במקום להגדרות.
