### ISSUE TITLE
event page subtitles

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#180]
@bruria1 
בעמוד אירוע במקום שיהי כתוב תרגום ל[שפת התרגום]
כתוב [שפת התרגום] תרגום ל
http://jer-cin.org.il/he/event/7304

**Comment by bruria1** [comment]
סודר. מקווים שלא יקרה שוב

**Comment by JerusalemCinematheque** [comment]
ok
