### ISSUE TITLE
JFF live site - heart icon color on event page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#181]
@bruria1 
בעמודי אירועים באתר הפסטיבל הלייב
ללב אין את צבע האתר וכשלוחצים עליו הוא מתמלא בצבע שחור
http://jff.reasonat.com/en/event/8527

**Comment by reasonat** [comment]
I guess this related to all heart over the site and not only to events?

**Comment by JerusalemCinematheque** [comment]
seems fine on film pages for add to my films function
not sure about the event line. I don;t have a working example

**Comment by bruria1** [comment]
סודר
זו היתה תקלה רק בפסטבל

**Comment by JerusalemCinematheque** [comment]
ok
