### ISSUE TITLE
Event page - event details - spacing

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#182]
@bruria1 
בעמוד אירוע הריווח שקבענו בעריכה לא נשמר בפרונטאנד

http://jff.reasonat.com/en/event/8527

**Comment by bruria1** [comment]
עכשיו זה בסדר?
הוספתי עורך תוכן חדש. ניתן להעביר אליו מהסלקט מתחת לעורך התוכן ולבחור:
ckeditor
הוא טוב יותר ואמור לא לעשות את הבעיות שניתקלתם בהם עד עכשיו.

**Comment by reasonat** [comment]
This is a duplication of https://github.com/Reasonat1/Cinema/issues/164#issuecomment-308078138
