### ISSUE TITLE
send to my list on live site reloads page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#183]
@reasonat 
לחיצה על הלב לשליחה לסרטים שלי / אירועים שלי גורם לכל העמוד לעשות reload
זה בכל העמודים
זה לא היה ככה לפני

**Comment by reasonat** [comment]
לא ברור
אם אתם משלבים מילה באנגלית עם העברית זה מבלבל...

**Comment by JerusalemCinematheque** [comment]
כשלוחצים על הלב העמוד נטען מחדש

**Comment by JerusalemCinematheque** [comment]
Heart icon on live site has a few issues

on home page in grid display - links to the item instead off adding to "my list"
on home page (other displays), film page, event page, lobby view - reloads the page insted of just adding to "my list"
i might have written about this in other tickets, but couldn't find them

**Comment by sato2004** [comment]
fixed on dev

**Comment by JerusalemCinematheque** [comment]
on home page ok
on film / event page pressing the heart makes the credits jump a few notes right / left
everytime you press on the heart they jump a bit further

**Comment by reasonat** [comment]
Re-assign to @bruria1

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
רק בפיתוח נכון?

**Comment by bruria1** [comment]
בינתיים כן.

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
בעמוד הבית לחיצה על הלב כשהמיני קלנדר סגור
פוצח את המיני קלנדר

**Comment by bruria1** [comment]
לבדיקה בפיתוח

**Comment by JerusalemCinematheque** [comment]
ok
