### ISSUE TITLE
finding events on JFF live site

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#184]
@reasonat 
אני לא מצליחה למצוא אירועים שהקמנו באתר לייב של הפסטיבל
לדוגמא
http://jff.reasonat.com/en/event/8531

אי אפשר למצוא אותו במערכת ניהול אירועים ותוכן

**Comment by bruria1** [comment]
http://jer-cin.org.il/en/admin/events-manager
הוא נמצא פה.
אם את מחפשת את הכותרת:
JFW - Jerusalem Film Workshop 2017
הוא מופיע.

**Comment by JerusalemCinematheque** [comment]
אני לא מוצאת אותו גם לא בצד סינמטק

**Comment by JerusalemCinematheque** [comment]
ברוריה זה דומה למה שהיה בעמוד הניהול של אישים שלא היה אפשר למצוא אישים שהם בסטטוס "לא מפורסם"
גם פה אי אפשר למצוא אירועים לא מפורסמים
לפחות ככה נראה לי

**Comment by bruria1** [comment]
זה בטיפול. בטיקט אחר.
