### ISSUE TITLE
views text translate problem

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#185]
event_ct_view/edit/panel_pane_6
has global text field which needs translation fix .
seem to break whenever features are reverted

movie view also need same fix : movie_top_pane_view/edit/panel_pane_8

another view : movie_group_ct:panel_pane_1

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

case : http://dev.jff.reasonat.com/he/event/7254

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Bruria Helfer please review .
i changed global text to only include subtitle field, and then in pre_render hook cm_extra i put in the field t('@language subtitle')
now it is working like before but without the span wrappers that you put on the subtitle text .
i didn't see any css applied on that span struture .

he : http://dev.jff.reasonat.com/he/event/7254
en: http://dev.jff.reasonat.com/en/event/7204

translation :
http://dev.jff.reasonat.com/en/admin/config/regional/translate/edit/20069
http://dev.jff.reasonat.com/en/admin/config/regional/translate/edit/16442

view :
http://dev.jff.reasonat.com/en/admin/structure/views/view/event_ct_view/edit/panel_pane_6

**Comment by bruria1** [comment]
רק שהתרגום ל צריך להיות בלי רווח אחריו.
@yakoub

**Comment by yakoub** [comment]
translation string not working as expected

**Comment by yakoub** [comment]
got confused between two different strings "@language subtitles" and "@languages subtitles"

**Comment by yakoub** [comment]
movie view also need same fix : movie_top_pane_view/edit/panel_pane_8

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

example moviegroup : http://dev.jer-cin.reasonat.com/en/movie-group/4741

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

translation code didn't check whether value is empty

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

some views had misplaced pipe character
