### ISSUE TITLE
error message when updating event on jer-cin site

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#186]
@reasonat 
כשאנחנו מבקשים לעדכן אירוע אחרי השמירה מתקבלת ההודעה הבאה
דף לא נמצא
הודעת סטטוס
One node translation has been synchronized.
אירוע סיפורה של יהדות ארה”ב בראי הקולנוע עודכן.
English
סליחה,

הדף שחיפשת לא נמצא....

האירוע כן מעודכן אבל העורך נזרק לעמוד עם הודעת שגיאה

זה האירוע
http://jer-cin.org.il/he/event/7304

**Comment by JerusalemCinematheque** [comment]
נראה שזה גם בעמודים אחרים
עדכנתי עכשיו את האיש הזה
http://jff.reasonat.com/he/person/1006
וקיבלתי אחרי שמירה את ההודעה הזו
דף לא נמצא
הודעת סטטוס
One node translation has been synchronized.
איש קרן יהושע רבינוביץ' לאמנויות תל אביב – פרויקט קולנוע עודכן.
English
סליחה,

הדף שחיפשת לא נמצא....

**Comment by JerusalemCinematheque** [comment]
any updates?

**Comment by JerusalemCinematheque** [comment]
at least on film page this seems to happen after we import screenings from toptix

**Comment by reasonat** [comment]
לא הצלחתי לשכפל למעט איש. 
ולכן פתחתי על זה קריאה אחרת ואת זו סוגר. 
אם יש מקרים בהם זה קורה אנא הגיבו שם. 
https://github.com/Reasonat1/Cinema/issues/245

**Comment by JerusalemCinematheque** [comment]
מתוך עמוד ניהול אירועים לחצנו על עדכן אירוע
http://dev.jff.reasonat.com/he/event/8818
ייבאנו את ההקרנה מטופטיקס
לחצנו שמור
וקיבלנו את ההודעה 
![image](https://user-images.githubusercontent.com/26960693/27770567-87aa4cc2-5f49-11e7-8798-21c3077a89b5.png)
