### ISSUE TITLE
person page list of titles on live site

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#187]
בעמוד איש לא רואים את כל הסרטים שמקושרים אליו
http://jff.reasonat.com/he/%D7%90%D7%99%D7%A9/1006

זה תמונת מסך מתי שהעמוד מתחיל לעלות

![image](https://user-images.githubusercontent.com/26960693/27082438-61ccfd8e-504d-11e7-87dd-d58b52458f86.png)

וזה אחרי שהעמוד עולה
![image](https://user-images.githubusercontent.com/26960693/27082456-79bf63e6-504d-11e7-816e-be3495ffd9d6.png)

**Comment by reasonat** [comment]
It looks like frontend issue. @bruria1

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
עדיין רואים משובש

**Comment by bruria1** [comment]
זה לא עודכן בלייב. אבקש מיעקוב לעדכן.

**Comment by JerusalemCinematheque** [comment]
ok
