### ISSUE TITLE
Calendar - Event merge between hall columns

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#188]
When looking at http://dev.jff.reasonat.com/he/festival-calendar day 11.6 there is a merge between event boxes one over the other.

**Comment by sato2004** [comment]
Fixed on dev, but these events no longer exists on dev site (after dev database was updated from live site)

**Comment by JerusalemCinematheque** [comment]
we added some more events. this seems to happen once we add more than six halls.
look at dev site now

**Comment by sato2004** [comment]
This happens if the event does not have a hall. What to do with such events? Hide them? Or something else? Now I added halls to 2 events and everything looks ok.

**Comment by JerusalemCinematheque** [comment]
ok. there shouldn't be any event that doesn't have a hall.
but yes may on the safe side if event does not have a hall and is not marked as "hide from festival calendar" it should be hidden

**Comment by sato2004** [comment]
fixed on dev and live

**Comment by reasonat** [comment]
Closing this issue. Reopen if needed.
