### ISSUE TITLE
Search  - User will know about festival nodes

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#190]
We talked about a way so when user search item he will know from looking at the results which entity results is related to current festival. 
I think the best way is to display: 
- Festivals related on each movie & event results - Not the current one. 
- Current festival - In a more clear way. 

Thoughts?

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque How do we push this further?

**Comment by JerusalemCinematheque** [comment]
isn't this related to #192 ?

**Comment by reasonat** [comment]
No. This is a suggestion as for the display of the search results. 
So I suggested 2 way to let the user know, in the search results, which festival the node result is related to.

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque ?

**Comment by JerusalemCinematheque** [comment]
התוצאות שמוצגות יהיו של מהדורה נוכחית
כאשר הפילטר של מהדורה נוכחית מופעל אוטומטית (כלומר רואים ליד המסננים  [איקס]פסטיבל הקולנוע ירושלים 0000)
אם משתמש סוגר את המסנן, יופיעו התוצאות מכל המהדורות

כשבכל תוצאה יש תצוגה כלשהי של שיוך לפסטיבל  ולמהדורה, כמו שיש כמו שיש סימון של סוג התוכן (סרט, אירוע, איש)

**Comment by bruria1** [comment]
בינתיים הוספתי את שם הספטיבל ליד התוצאה.

**Comment by JerusalemCinematheque** [comment]
בדב?
כי אני לדוגמא מנסה לחפש את 
the army of shadows
והתוצאה שאני מקבלת היא
1 item matched the army of shadows
Your search did not return any results.
![image](https://user-images.githubusercontent.com/26960693/29525020-13c1f2f6-869a-11e7-9a2a-736180cae9db.png)

כלומר רואים שיש תוצאה אבל לא רואים אותה

**Comment by bruria1** [comment]
כן.. סידרתי את זה.

**Comment by JerusalemCinematheque** [comment]
השיוך צריך להיראות כמו השיוך סוג תוכן. כלומר באותו גודל פונט וצבע
![image](https://user-images.githubusercontent.com/26960693/29566535-dacf57c2-8752-11e7-9566-6d6d925689be.png)

**Comment by bruria1** [comment]
היה צריך לעדכן את הקבצים. אמור להיות וב כעת.

**Comment by JerusalemCinematheque** [comment]
ok
