### ISSUE TITLE
Search - Display festivals on festival filters

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#191]
On dev site there are few festival terms, yet only current one display as filter option in the search page. 
I thought it's about no nodes related to more fetival terms but I reference 
http://dev.jff.reasonat.com/en/node/7187/edit & http://dev.jff.reasonat.com/he/node/7230/edit to "festival 3" term and still this festival doesnt show as option in the search page
http://dev.jff.reasonat.com/he/search/results/%D7%97%D7%99%D7%94

**Comment by sato2004** [comment]
@reasonat This task is not clear for me. What this filter should to do? We should see only items related to current festival in search results. Is not?

**Comment by reasonat** [comment]
@sato2004 No, on search results as mention in other task, we can see all nodes, even once which isn't related to current festival. So this filter will allow me as a user to see nodes related to different festivals. Later on we will add some symbol to each result telling the related festival.

**Comment by reasonat** [comment]
@JerusalemCinematheque you mention here https://github.com/Reasonat1/Cinema/issues/192#issuecomment-312493594 search isn't working in Hebrew? I can't see this issue.

**Comment by JerusalemCinematheque** [comment]
for example
this film http://jff.org.il/he/movie/9396
can't be found when searching in hebrew
here are the search results
http://jff.org.il/he/search/results/%D7%94%D7%A4%D7%99%D7%AA%D7%95%D7%99

when searching on english side, item is found
http://jff.org.il/en/search/results/The%20Beguiled

**Comment by sato2004** [comment]
fixed

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque to QA this I need movie which also (And for current one) refer to old festival term. Is there any?

**Comment by JerusalemCinematheque** [comment]
I'm sorry i don't understand the question
you need a movie that is in this festival and was also in a past festival?

**Comment by reasonat** [comment]
Yes

**Comment by reasonat** [comment]
I have test this and it looks fixed.  Closing this issue. Reopen if needed.
