### ISSUE TITLE
Domain Access - Management an nodes display logic

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#192]
**Management tables for editors (Event, movies, terms, etc)**
**Cinema** - All nodes are display whether the target Festival/Cinema/none.
**Festival** - Only nodes target to Festival.
OK to both

**On site** - See cases but take into consideration there are more "if's" like event publish dates / node publish / active events / etc.
**Calendar (mini, full, festival) for anonymous and log-in users:**
**Cinema** - All event nodes that target Cinema
For editor users – all events (active and non-active)
For anonymous and logged-in users – only active events

Festival - All events nodes that target Festival (current festival only)
Festival calendar display events until end of current festival term
For editor users – all events (active and non-active)
For anonymous and logged-in users – only active events

**Film / event page**
Cinema - show events until start of events. Only events that are cinema domain access.
Festival – display events until festival term ends. Only events that are festival domain access

**Search page for anonymous and log-in users:**
Cinema - All nodes that target Cinema and festival

Festival - All nodes that target current Festival as default with ability to un/filter festival edition
In festival search result page the festival filter should be populated with all editions, with current festival term checked

**Archive**
When festival term has passed, add to all nodes linked to term -
Festival term and Lobby term as tags

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Waiting for your approve

**Comment by JerusalemCinematheque** [comment]
**Management tables for editors (Event, movies, terms, etc)** 
Cinema - All nodes are display whether the target Festival/Cinema/none.
Festival - Only nodes target to Festival.
**OK to both**


**On site - See cases but take into cinsiduration there are more "if's" like event publish dates / node publish / active events / etc.**
Calendar (mini, full, festival) for anonymous and log-in users:
Cinema - All event nodes that target Cinema
For editor users – all events (active and non-active)
For anonymous and logged-in users – only active events

Festival - All events nodes that target Festival (current festival only) 
Festival calendar display events until end of current festival term
For editor users – all events (active and non-active)
For anonymous and logged-in users – only active events

**Film / event page**
Cinema - show events until start of events. Only events that are cinema domain access.
Festival – display events until festival term ends. Only events that are festival domain access

**Search page for anonymous and log-in users:**
Cinema - All nodes that target Cinema and festival

Festival - All nodes that target current Festival as default with ability to un/filter festival edition
In festival search result page the festival filter should be populated with all editions, with current festival term checked 

**Archive** 
When festival term has passed, add to all nodes linked to term -
Festival term and Lobby term as tags

**Comment by reasonat** [comment]
Search page >> Festival
If current festival chacked user will see only current festival nodes will be displayed. 

**Archive**
When festival term has passed, add to all nodes linked to term -
Festival term and Lobby term as tags
>> All this paragraph isn't clear

**Comment by navotb** [comment]
To answer the question of how to manifest the fact that a films was part
(in the past) in a festival. Instead of adding this to the credits of the
film, we suggest to add it to the "tags" of the film: one tag as the
festival "edition" (click will lead to the festival archive page) and one
of the lobby(ies) of the film (click will lead to the archive lobby page)
what to do you think?

**Comment by JerusalemCinematheque** [comment]
אמיר, האם אפשר לפחות בינתיים להפעיל את מנגנון החיפוש בצד עברית?
בצד אנגלית ניתן לעשות חיפוש, אומנם בלי הסינון בהתכתבות פה, אבל בצד עברית לא ניתן לחפש סרטים בכלל

**Comment by reasonat** [comment]
אנא מכם, אל תערבבו דיונים בדיונים, דברים נופלים בין הכסאות וגם כך יש לא מעט משימות ותגובות לנהל. 
את הדיון על החיפוש עצמו ובעיות שהעלתם מעביר לפה - https://github.com/Reasonat1/Cinema/issues/191 
את הדיון על כיצד לסמן סרט הקשור במהדורה יש לקיים פה - https://github.com/Reasonat1/Cinema/issues/190 

לעניינו אני חוזר על השאלות: 
1. אם ברירת המחדל בתוצאות החיפוש היא שהפסטיבל הנוכחי מסומן, לא יהיו תוצאות של פסטיבל אחר, לא רעיון טוב כמובן. 
2. לא הבנתי מה כתבתם על ארכיב בהקשר של הדיון הזה

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb ?

**Comment by JerusalemCinematheque** [comment]
נראה לי יש כאן איזה בלבול לגבי הטיקט ולא ברור מה פתוח
האחד זה עניין תוצאות החיפוש בפרונטאנד
יש לנו דיון פתוח על תוצאות החיפוש בפסטיבל כאן #190 
מה שלא נפתר בהקשר של החיפוש הוא תוצאות של נודס שמשוייכים לדומיין אחד בחיפוש של הדומיין השני
כאן ביקשנו שבצד פסטיבל לא יתקבלו תוצאות חיפוש של פריטים ששוייכו לדומיין סינמטק
כרגע גם בצד פסטיבל מקבלים תוצאות של צד סינמטק. לדוגמא "פיטר פן"
בצד סינמטק ביקשנו שכן יתקבלו תוצאות משני הדומיינים
העניין כאן הוא שצריך לוודא שאם התוצאה היא מצד פסטיבל, הקישור יוביל לעמוד בצד פסטיבל ולא יפתח את התוצאה בצד סינמטק, בו העמוד מוצג בצורה "חסרה", כי רוב השדות מסומנים "הסתר" מצד סינמטק ושדות התקציר מלאים רק בשדה תקציר פסטיבל
לדוגמא
http://jer-cin.org.il/he/search/results/1945

http://jer-cin.org.il/he/movie/8149

מן הסתם חלק מעניין זה ייפתר ברגע שנחליט איך סרט פסטיבל והמהדורה שלו מזוהים בתוצאות החיפוש

הנושא השני שהועלה פה הוא סימון סרט/אירוע כשייך למהדורת פסטיבל
זה לא קשור לדיון ב #190 
אפשר לפתוח לזה טיקט חדש אם צריך
אנחנו הצענו שהמהדורה והלובי יסומנו כמו תגיות, תגית מהדורה, לדוגמא "פסטיבל הקולנוע ירושלים 2017" והשני לובי, לדוגמא "תחרות בינלאומית"
כך שאם ניקח למשל את 
http://jff.org.il/he/movie/8149
ברגע שהמהדורה מסתיימת יוספו לו בחלק של התגיות בעמוד "פסטיבל הקולנוע ירושלים 2017" "תחרות בינלאומית"

טבלאות ניהול
 ביקשנו שבצד פסטיבל יופיעו רק אייטמים של דומיין פסטיבל

נראה לי שכל שאר ההערות בטיקט כבר נפתרו

**Comment by reasonat** [comment]
1. For the first part see this https://github.com/Reasonat1/Cinema/issues/292. Notice the freeze since this is an extra request and development. **Please comment there if needed.** 
2. Didnt get it. Please explain better
3. Also freeze - Look here https://github.com/Reasonat1/Cinema/issues/293 **Please comment there if needed.**

**Comment by JerusalemCinematheque** [comment]
מדובר כאן על סימון שיוך מהדורת פסטיבל ולובי של הפסטיבל לסרט כאשר טווח תאריכי הפסטיבל עבר
כלומר זה קשור לענייני ארכיון הפסטיבל
ולכן הצעתי לפתוח לזה טיקט חדש

**Comment by reasonat** [comment]
עדיין לא הבנתי
אולי באמת תפתחו על זה טיקט חדש. 
לאחר שתפתחו אסגור את הטיקט הזה שהוא כללי מדי

**Comment by JerusalemCinematheque** [comment]
see #298
