### ISSUE TITLE
jercin live site homepage edit - add nodes window

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#193]
@bruria1 
כשאנחנו מבקשים לחפש נודס החלונית חיפוש נפתחת במיקום של השדה בו אנחנו רוצים להוסיף את הנוד. כך שאם השדה הוא בתחתית העמוד החלונית נפתתחת בסוף העמוד וצריך לגלול עד למטה כדי להוסיף נודס במקום שהחלונית תפתח בראש העמוד
מקווה שהוידאו מסביר מה הכוונה
https://www.youtube.com/watch?v=RPx1gUG2Ekc

**Comment by bruria1** [comment]
@yakoub תוכל להסתכל? משהו שם לא עובד. העמוד אמור להיגלל למקום שבו הוא נפתח ולא לחזור ללמעלה.

**Comment by yakoub** [comment]
similar issue, maybe combine them ?
anyway the window opened for me in correction position and not at the bottom .
https://github.com/Reasonat1/Cinema/issues/136#issuecomment-308032955

**Comment by JerusalemCinematheque** [comment]
זה קורה בכל פעם שמבקשים להוסיף פריט אחר בשדה כלשהו בעמוד סרט

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque   Can you recheck this? I can't see this.

**Comment by JerusalemCinematheque** [comment]
seems okay now
