### ISSUE TITLE
save as draft button missing from live site

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#195]
@reasonat 
בעמוד עריכת סרט / אירוע נעלם כפתור שמור כדראפט
אנחנו צריכים אותו חזרה בבקשה די דחוף

**Comment by bruria1** [comment]
הוחזר.
עכשיו יש לכם כפתור פרסום/בטל פרסום

**Comment by JerusalemCinematheque** [comment]
אני רואה שיש כפתור 
שמירה ועריכה
שמירה
פרסם

רק לוודא זה אומר שכפתורי שמירה ועריכה ושמירה זה למעשה שמירה כדראפט?

**Comment by bruria1** [comment]
![buttons](https://user-images.githubusercontent.com/5786526/27173763-6954839e-51c2-11e7-93ae-c80637912538.png)
שמירה והמשך עריכה - להמשיך לערוך (מצב מפורסם/לא מפורסם נשאר כפי שהיה)
שמירה - שמירת השינויים (מצב מפורסם/לא מפורסם נשאר כפי שהיה)
בטל פרסום- שמירה ושינוי מצב הפרסום ללא מפורסם
פרסום- שמירה ושינוי מצב הפרסום למפורסם

**Comment by JerusalemCinematheque** [comment]
אבל איך אני שומרת את זה מהתחלה במצב לא מפורסם?

**Comment by bruria1** [comment]
תראי אם עכשיו זה טוב

**Comment by bruria1** [comment]
תראי אם עכשיו זה טוב

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
האם אפשר להוסיף גם לעמוד מסוג מקבץ?

**Comment by bruria1** [comment]
הוספתי
