### ISSUE TITLE
remove temporary domains

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#196]
remote jer-cin.reasonat.com and jff.reasonat.com and add redirect .

**Comment by yakoub** [comment]
i completely removed dns entries for jer-cin.reasonat.com .
if you prefer redirect then i'll need to return them and defined 301 redirect on cinematic server cpanel .
@reasonat

**Comment by yakoub** [comment]
@reasonat do you need redirect or is it enough to remove the addresses ?

**Comment by yakoub** [comment]
@reasonat i didn't add redirect, i don't think it is required .
should we close this ?
