### ISSUE TITLE
festival site name

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#197]
@reasonat @bruria1 
האם אפשר בבקשה לשנות את שם אתר הפסטיבל בעברית ל
פסטיבל הקולנוע ירושלים
ובאנגלית
Jerusalem Film Festival

**Comment by bruria1** [comment]
אתם עושים את זה פה:
http://jer-cin.org.il/he/block/festival-title---hebrew/edit
http://jer-cin.org.il/he/block/festival-title---english/edit

**Comment by JerusalemCinematheque** [comment]
סליחה הכוונה הייתה לא השם בהאדר אלא השם בטאב
כשנכנסים לעמוד הבית רשום סינמטק ירושלים - ארכיון ישראלי לסרטים
אבל כשנכנסים לעמודים פנימיים רשום פסטיבל הקולנוע ירושלים
כנ"ל מתי כשמבקשים לשמור בפייבוריטס

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
מצויין
