### ISSUE TITLE
unpublish "person"

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#198]
@reasonat 
can we ask that all "person" added from 1.6 until today become unpulished?
or to mark them all as "hide the person from the search results"
if you can add that to person managing page we can do it ourselves

**Comment by reasonat** [comment]
@bruria1 Please add publish date to manage page and option to sort this column.

**Comment by bruria1** [comment]
הוספתי לכם אפשרות סינון ואפשרות לפרסם/להוריד מפרסום בעמוד ניהול

**Comment by JerusalemCinematheque** [comment]
עובד מצויין
אבל עכשיו אי אפשר למצוא את האישים שהעברנו למצב לא מפורסם במערכת ניהול אישים
ואי אפשר להוסיף את האישים הלא מפורסמים בקרדיטים בעמוד הסרט

**Comment by bruria1** [comment]
הוספתי לניהול את הלא מפורסמים.
נכון. אי אפשר להוסיף אישים לא מפורסמים כי לא ניתן להציג באתר כאשר הם לא מפורמים..

**Comment by JerusalemCinematheque** [comment]
ואי אפשר לשנות את זה כך שישלפו גם תוצאות של אישים שלא מפורסמים?

**Comment by bruria1** [comment]
אבל אז הם לא יוצגו.. כי לא ניתן להציג באתר מי שלא מפורסם

**Comment by reasonat** [comment]
Can I close this issue?

**Comment by JerusalemCinematheque** [comment]
it would be better if "unpublished" persons could be found when adding credits
it will be the editor's responsibility to make sure they are published later on

**Comment by bruria1** [comment]
בוצע. באתר הלייב. אםשר להוסיף אנשים לא מפורסמים אבל הם לא יוצגו.

**Comment by JerusalemCinematheque** [comment]
כמובן שברגע שהם מפורסמים הם מפורסמים גם בעמוד הסרט כן?

**Comment by bruria1** [comment]
נכון
