### ISSUE TITLE
JFF homepage edit - cant find content for homepage

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#202]
@bruria1 
בצד פסטיבל
אני מנסה לקשר תכנים מסוג
content for homepage
הכנתי עכשיו 9 כאלו אבל כשאני מבקשת למצוא אותם במערכת עריכת עמוד הבית אני לא מצליחה למצוא אותם
לדוגמא
http://jff.org.il/he/node/8738

**Comment by JerusalemCinematheque** [comment]
עשיתי עכשיו עוד בדיקה
נראה שזה קורה בוואן אאיטם סטטיק

**Comment by bruria1** [comment]
תבדקי כעת

**Comment by JerusalemCinematheque** [comment]
מעולה
תודה
