### ISSUE TITLE
Festival logos footer - navigation arrows missing in responsive view

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#203]
@bruria1 
בצד פסטיבל בסטריפ הלוגואים בתצוגה ריספונסיבית חסרים חצי המעבר

**Comment by JerusalemCinematheque** [comment]
האם אפשר להפוך את זה לסליידר אוטומטי כמו הסליידר של הספונסר?

**Comment by bruria1** [comment]
תסתכלי כעת. באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
אני עוד לא רואה שינוי

**Comment by bruria1** [comment]
http://dev.jff.reasonat.com/he

**Comment by JerusalemCinematheque** [comment]
יופי
זה אפשרי שהמעבר בין הלוגואים יהיה גם אוטומטי?
נגיד מעבר כל שתיים-שלוש שניות

**Comment by bruria1** [comment]
ובלי חיצים או להשאיר אותם?

**Comment by JerusalemCinematheque** [comment]
עם

**Comment by JerusalemCinematheque** [comment]
כל המנגנון אבל רק כשזה נכנס לתצוגה ריספונסיבית נכון?
אם התצוגה היא תצוגה רגילה בגודל מסך מלא אין למעשה צורך בחצים ובמעבר בין הלוגואיים
אלא רואים את כל הלוגואים מחולקים לשורות
כמו שזה עכשיו ב
jff.org.il

**Comment by bruria1** [comment]
לבדיקה באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
מעולה

**Comment by JerusalemCinematheque** [comment]
תוכלו בבקשה רק לעדכן אותנו כשזה עובר ללייב? תודה

**Comment by bruria1** [comment]
יעודכן עד סוף היום

**Comment by JerusalemCinematheque** [comment]
הכל פיקס
