### ISSUE TITLE
jff responsive view - add icons

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#204]
@bruria1 
אפשר להוסיף בתצוגה ריספונסיבית את האייקון של השעון שיפתח את הקלנדר למובייל של הפסטיבל?

ואת אייקון סל הקניות?

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
למעשה צריך את האייקון רק כשנכנסים למצב של תצוגה ריספונסיבית
כשהתפריט הראשי "נעלם" מההדר

**Comment by bruria1** [comment]
בדסקטופ אין צורך באייקון שמוביל ללוח הפסטיבל??

**Comment by JerusalemCinematheque** [comment]
לא כי יהיה קישור ישיר מהתפריט הראשי

**Comment by bruria1** [comment]
הורדתי מהדסקטופ

**Comment by JerusalemCinematheque** [comment]
אני עדיין רואה את האייקון בדסקטופ
זה בגלל שזה בסביבת הפיתוח?
בנוסף אייקון עגלת הקניות בתצוגה ריספונסיבית חתוך. רואים רק את החלק של העגלה, בלי הגלגלים

**Comment by bruria1** [comment]
כמובן שכל התיקונים נעשים כעת בסביבת הפיתוח.
לאחר מכן נעביר לליב
בסביבת הפיתוח את לא אמורה לראות את האייקון והעגלה מופיעה עם גלגלים לפי מה שאני רואה. תוכלי להראות לי צילום מסך?

**Comment by JerusalemCinematheque** [comment]
עכשיו לא רואים. כנראה הייתי צריכה לנקות את הקאש

![image](https://user-images.githubusercontent.com/26960693/27260420-9773ad94-5434-11e7-928f-37923950d00c.png)

**Comment by bruria1** [comment]
ויש בעיה אחרת..?

**Comment by JerusalemCinematheque** [comment]
רק האייקון של סל הקניות

אני גם רוצה לחכות קצת עם ההעברה של האייקונים לאתר לייב

**Comment by bruria1** [comment]
האייקונים כבר באתר לייב...
אני לא רואה את הבעייה עם סל הקניות.. איזה דפדפן? איזה מכשיר?

**Comment by JerusalemCinematheque** [comment]
כרום באייפון
וגם בספארי באייפון

**Comment by JerusalemCinematheque** [comment]
ברוריה אני רק רוצה לוודא שאין זליגה בין קלנדר פסטיבל וקלנדר סינמטק בגלל תוספת האייקון שעון
כי בסביבת פיתוח במיני קלנדר סינמטק מופיעים אירועים שסומנו לפרסום בצד פסטיבל

**Comment by bruria1** [comment]
לא הבנתי.
בפסטיבל אין מיני קלנדר. לחיצה על האייקון מובילה ללוח הפסטיבל.

**Comment by JerusalemCinematheque** [comment]
אבל במיני קלנדר בצד סינמטק בסביבת פיתוח מופיעים אירועים שסומנו לפרסום בצד פסטיבל
זה לא היה ככה (לפחות לא נראה לי) עד אתמול כשביקשתי להוסיף את אייקון השעון לצד פסטיבל

**Comment by bruria1** [comment]
תוכלו להראות לי דוגמה למצב כזה?
אין כלל קשר בין הדברים...

**Comment by JerusalemCinematheque** [comment]
![image](https://user-images.githubusercontent.com/26960693/27275101-aa942e1c-54de-11e7-8a85-ff16c9f98b55.png)

כמעט כל האירועים כאן משוייכים לדומיין פסטיבל

**Comment by bruria1** [comment]
טופל

**Comment by JerusalemCinematheque** [comment]
העניין הזה בסדר
ראינו שהעניין עבר ללייב
והאייקון של השעון נמצא בתצוגה הרגילה. אמור להיות רק כשנכנסים לתצוגת מובייל

**Comment by bruria1** [comment]
פה?
http://jff.org.il/he
הוא רק בתצוגת מובייל

**Comment by JerusalemCinematheque** [comment]
כנראה היה בדיוק בזמן עדכון או משהו
הדבר היחיד שנשאר הוא אייקון סל הקניות במובייל שנחתך
![image](https://user-images.githubusercontent.com/26960693/27391348-74e340e4-56ac-11e7-926a-87f2b3c4366e.png)

**Comment by bruria1** [comment]
אני לא מצליח הלראות את הבעיה.
אמיר אתה רואה את זה? @reasonat

**Comment by reasonat** [comment]
לא רואה את הבעיה הזו

**Comment by JerusalemCinematheque** [comment]
זה באייפון

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
רק בפיתוח נכון?

**Comment by JerusalemCinematheque** [comment]
אוקיי בפיתוח

**Comment by JerusalemCinematheque** [comment]
מתארת לעצמי שאין הרבה משתמשים בספארי אבל תראי את האייקון של עגלת הקניות בספארי בדסקטופ
![image](https://user-images.githubusercontent.com/26960693/27560024-5aecd8da-5acb-11e7-8364-d3b3db82d77a.png)

![image](https://user-images.githubusercontent.com/26960693/27560039-60a34ca0-5acb-11e7-9b8c-7618bd276999.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
