### ISSUE TITLE
film page subtitles

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#205]
@reasonat @bruria1 
בעמוד סרט באנגלית בשורה מעל תקציר הסרט בשדה תרגום אין קיבוץ של שפות התרגום וכתוב
Hebrew subtitles, English
במקום
Hebrew, English subtitles

http://jff.org.il/en/movie/8928

**Comment by bruria1** [comment]
@yakoub

**Comment by yakoub** [comment]
@JerusalemCinematheque problem fixed

**Comment by JerusalemCinematheque** [comment]
ok
