### ISSUE TITLE
when pressing on festival term - moves to unrelated page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#208]
@reasonat 
לחצתי על טרם פסטיבל מתוך עמוד ניהול הלובי
והגעתי לעמוד הזה
http://jff.org.il/he/taxonomy/term/12

שהוא איזשהו גרסה מוקדמת של עמוד הבית
ושאין בו שום קשר למה שנמצא בצד העריכה של הטרם

ברור שאי אפשר להגיע לעמוד הטרם כרגע בפרונטאנד אבל אנחנו רוצים לוודא שכנקשר את הטרם לעמוד הארכיון זה לא יוביל לעמוד הזה

**Comment by reasonat** [comment]
Closing this one and work on this one 
https://github.com/Reasonat1/Cinema/issues/168
