### ISSUE TITLE
film collection page - jff - synopsis missing

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#209]
@reasonat @bruria1 
בעמוד מקבץ של סרטים בהם התקציר נמצא בשדה תקציר פסטיבל חסר התקציר ברשימת הסרטים
http://jff.org.il/he/%D7%9E%D7%A7%D7%91%D7%A5-%D7%A1%D7%A8%D7%98%D7%99%D7%9D/8041

**Comment by JerusalemCinematheque** [comment]
האם זה קשור לכך שהסרטים עוד לא לפרסום?

**Comment by bruria1** [comment]
מה שמוגדר שם זה להציג את התוכן של הסרט ואם הוא ריק להציג את התקציר.
לפי מה שאני מבינה זה אם זה אתר פסטיבל להציג את התקציר שלו ואם הוא ריק להציג את התקציר הרגיל ואם זה אתר סינמטק אז להציג את התקציר הרגיל. נכון?

**Comment by JerusalemCinematheque** [comment]
כן

**Comment by bruria1** [comment]
זה מה שעשיתי. לבדיקה באתר פיתוח.

**Comment by JerusalemCinematheque** [comment]
אוקיי
רק שאמור להופיע התקציר המלא לא התקציר המקוצר

**Comment by bruria1** [comment]
בסינמטק השדה Long summary
בפסטיבל השדה Long summary - Festival
???

**Comment by JerusalemCinematheque** [comment]
נכון
________________________________
מאת: Bruria <notifications@github.com>
‏‏נשלח: יום שלישי 27 יוני 2017 08:32:34
‏‏אל: Reasonat1/Cinema
עותק: Tamar Freeman; Author
‏‏נושא: Re: [Reasonat1/Cinema] film collection page - jff - synopsis missing (#209)


בסינמטק השדה Long summary
בפסטיבל השדה Long summary - Festival
???

**Comment by bruria1** [comment]
לבדיקה באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
@bruria1 
פותחת את הנושא מחדש
 בעמוד האירוע של המקבץ חסרים התקצירים של הסרטים שמקושרים למקבץ
http://jff.org.il/he/event/10608
