### ISSUE TITLE
add spacing between sponsor area and logo area

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#210]
@bruria1 
אפשר בבקשה להוסיף קצת ריווח בין החלק של באנר ספונסר לחלק של הלוגואים
והאם אפשר שהריווח מעל הבאנר יהיה מתוך העמודים ולא בחלק של הבאנר מכיוון שצבע העמוד משתנה (לפעמים הוא לבן ולפעמים ורוד)

**Comment by bruria1** [comment]
בוצע. באתר פיתוח בינתיים
