### ISSUE TITLE
ckeditor short event details - does not save text

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#211]
@bruria1 
משום מה בשדה תקציר אירוע מקוצר כשאנחנו מכניסים טקסט במצב סיקייאדיטור ומבקשים לשמור
הטקסט לא נשמר
תראי כאן
http://jer-cin.org.il/he/node/9093/edit

כשעוברים לויזיוויג אין בעיה

**Comment by JerusalemCinematheque** [comment]
בצד אנגלית נכון גם לשדה תקציר אירוע

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
