### ISSUE TITLE
Festival calendar final issues

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#213]
@reasonat @bruria1 
פותחת טיקט חדש לעניינים אחרונים בכל הקשור לקלנדר

1. כפתור "אולמות נוספים" גולש לחלק של הקלנדר נוטס 
1. קבענו שאם יש לסרט המקושר באירוע הקרנה נוספת יופיע בפופ-אפ הקרנות נוספות. זה עבד בעבר וכעת לא. ראו "האירוע" ב-15.6 שיש לו הקרנה נוספת ב17.6
1. תצוגה ריספונסיבית - אנחנו מבינים שבגודל מסויים של מסך הקלנדר עובר למצב מובייל. אבל נראה לנו שיש בעיה בתצוגה של מסכים קטנים יותר כמו טאבלטים. נוצרת גלילה הצידה וכפתור אולמות נוספים עולה על האולמות
1. במובייל בחלק של הקלנדר נוטס חסר צבע הרקע הוורדרד. הוא עכשיו לבן מה שיוצר אי בהירות לגבי החלוקה של האירועים
1. האם זה אפשרי שאם אין עדיין כפתור כרטיסים "שלח לקנדר" יתיישר שמאלה/ימינה (בהתאם לשפה) וככפתור הכרטיסים יהיה פעיל יחזור למקומו כפי שהוא כעת?
1. בפופ-אפ היינו רוצים שהמועד שמופיע למעלה יהיה בבולד מלא. הקרנות נוספות ישארו במשקל רגיל
1. יש באנגלית בעיה בשורת הימים עם יום רביעי. האם אפשר להוסיף עוד פיקסל מכל צד לכל קובייה?
1. ״שלח לקלנדר״ אמור להיעלם כשמועד האירוע עובר. עבד בעבר. עכשיו לא.

**Comment by bruria1** [comment]
1. תוכלי להראות ל צילום מסך? אני לא רואה את הבעיה
2. ההגדרה היא שמוקרנות רק הקרנות נוספות עתידיות
3. מאוד מורכב להציג את זה במסכים קטנים. אולי כדאי לעבור מנקודה גדולה יותר של מסך לתצוגה הרספוניבית?
4. סודר
5. איך עכשיו?
6. בוצע
7. זו בעיה כי זה יגרום לנו לשיבושים בעיצוב. הקטנתי את הפונט בפיקסל וכעת זה נראה טוב
8. בוצע

**Comment by JerusalemCinematheque** [comment]
1. מוזר אתמול זה התנהג ככה. וגם אתמול לא ראו את המעבר של האירועים מאחורי שורת האולמות
![image](https://user-images.githubusercontent.com/26960693/27375105-c96b81b6-5676-11e7-8ba0-a592f814b0e7.png)
אפשר לראות מעל סינמטק 2 את הקצה של קוביית האירוע
2. אוקיי
3. מאיזה גודל מסך את מציעה לעשות זאת?
4. אוקיי
5.מצויין. אפשר ליישם גם בקלנדר נוטס?
6. מעולה
7. אוקיי
8. אוקיי

**Comment by bruria1** [comment]
1. סודר
3. אני רואה שמאוד מהר זה מוצג לא טוב. בטיפול.
5. בשורה של ההקרנה???

**Comment by JerusalemCinematheque** [comment]
בשורה של ההקרנה???
זה בהקשר של כפתור שלח לקלנדר בקלנדר נוטס?
אז כן בשורת ההקרנה בתצוגת ליסטה

**Comment by bruria1** [comment]
זה ממש ישבש את העיצוב אם נשים את הקלנדר צמודלשמאל כאשר אין כרטיס בתצוגת ליסטה.
לגבי הקלנדר במסכים קטנים לפני המובייל. כעת זה נראה טוב - תבדקו

**Comment by JerusalemCinematheque** [comment]
אוקיי
בהחלט יותר טוב. נראה לי שרק נשאר בעיה עם התצוגה בטאבלטים במצב אנכי. אבל אולי אז כבר צריך לעבור לתצוגת מובייל
![image](https://user-images.githubusercontent.com/26960693/27389154-42c5dce4-56a6-11e7-9c9c-ffb88b20c307.png)

**Comment by bruria1** [comment]
תנסזו לראות מאיזה גודל של מסך זה מתחיל להיראות טוב ואז נעדכן. בכל שינוי גודל מסך יש לרענן את העמוד.

**Comment by JerusalemCinematheque** [comment]
זה נראה לרוב בסדר במסכים של טאבלט
יש שתי בעיות שרואים
1. המיקום של האולמות מול מיקום החיצים שבאנגלית חץ שמאל נדבק לאולמות וחץ ימין רחוק מהם
![image](https://user-images.githubusercontent.com/26960693/27421963-3c76db24-5735-11e7-8eb1-cd27ab620a40.png)
2. בצד עברית בוקסות האירועים בורחות שמאלה מחוץ לפריים ומחוץ להגדרות האולם שלהן
![image](https://user-images.githubusercontent.com/26960693/27422001-5c28cdc4-5735-11e7-81fd-c7a0a783cb2f.png)

![image](https://user-images.githubusercontent.com/26960693/27422021-6bf13f84-5735-11e7-854e-6743e95187f3.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
עכשיו בתצוגה אנכית בטאבלט הקוביות נראות באופן בולט מעבר לקו האולמות בגלילה
![image](https://user-images.githubusercontent.com/26960693/27431895-c61bcfe4-5756-11e7-87f2-b2acefae0af5.png)
זה לא קורה בתצוגה אופקית

**Comment by bruria1** [comment]
סודר. למרות שלא אמורים להגיע למסך הזה בגודל כזה אלא למסך המובייל.
אלא אם כן, היית במסך אופקי וסובבת את המכשיר לאנכי.

**Comment by JerusalemCinematheque** [comment]
מעולה
נראה לי שאפשר להעביר לאתר החי

**Comment by JerusalemCinematheque** [comment]
@bruria1 
כפתור שלח לקלנדר קפץ שורה ומופיע מעל שורת הקוד / כפתור כרטיסים
תראו ביום הראשון של הקלנדר

**Comment by bruria1** [comment]
לא הכל עבר לאתר החי. עכשיו זה טוב.

**Comment by bruria1** [comment]
מחכה לאישורכם..

**Comment by reasonat** [comment]
This is already checked. If any more issues please reopen this.
