### ISSUE TITLE
film synopsis on this event page is shown in wrong font

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#214]
@bruria1 
תראי את האירוע הבא
http://jer-cin.org.il/he/event/9093
שדה תקציר הסרט מופיע בפונט הלא נכון

מה שקרה הוא שהעתקתי את הטקסט של התקציר משדה תקציר פסטיבל לשדה תקציר סינמטק
קופי-פייסט הכי פשוט
ובהדבקה נוסף ב
HTML
עוד תגיות
תראי כאן
http://jer-cin.org.il/he/node/7771/edit

בעמוד הסרט הטקסט מוצג נכון, אבל בעמוד האירוע של הסרט לא
מה שגם משפיע על התצוגה שלו בעמוד הבית בתצוגת ליסטה

**Comment by bruria1** [comment]
מה שקרה הוא שהעתקתם תגיות הטמל לתוך העורך.
יש כפתור בעורך שנראה כמו מחק ואם את עומדת עליו רשום 
remove format
תסמני את הטקסט ותלחצי עליו ואז כל התגיות יוסרו

**Comment by JerusalemCinematheque** [comment]
אבל התגיות הועתקו מתוך הסיקיי אדיטור
ועכשיו כשעושים קופי פייסט של טקסט לתוך הסיקיי אדיטור הוא מוסיף תגיות שמופיעות בפרונטאנד
http://jff.org.il/he/movie/9260

**Comment by navotb** [comment]
נראה שצריך להוסיף "הדבק מוורד". אמור להיות כפתור כזה ב-CKeditor

2017-06-21 10:35 GMT+03:00 JerusalemCinematheque <notifications@github.com>:

**Comment by JerusalemCinematheque** [comment]
אולי קשור לתוכנת הוורד פרוססר של המק שהשתמשתי בה
ניסיתי מוורד אונליין ונראה שזה בסדר

**Comment by bruria1** [comment]
הוספתי כפתור של הדבקה מוורד אם זה עוזר.
אפשר לסגור את זה?

**Comment by navotb** [comment]
ברוריה
בטופס עריכת סרט בטאב תוכן יש לינקים "disable rich text". מה זה?

**Comment by bruria1** [comment]
אופצייה לראות את הטקסט ללא האדיטור עם כל תגיות ההטמל. אפשר להוריד את זה

**Comment by JerusalemCinematheque** [comment]
בעמוד הבית התקציר של האירוע הבעייתי מופיע עדיין בפונט שונה

**Comment by bruria1** [comment]
בעמוד הבית זה היה שדה אחר של תקציר שעדיין הכיל את התגית של הפונט.
הורדתי.

**Comment by JerusalemCinematheque** [comment]
אוקיי
