### ISSUE TITLE
home page gallery

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#215]
@bruria1 
האם זה בעייתי להפוך את הסליידר גם לסליידר אוטומטי
ואם לא האם זה משפיע על התצוגה במובייל?

**Comment by bruria1** [comment]
אין בעיה. עדכנתי בדב.

**Comment by JerusalemCinematheque** [comment]
צריך לוודא שכשפותחים את חלונית הרכישה באייטמים של הגלריה הגלריה לא מתחלפת
זה אפשרי?

**Comment by bruria1** [comment]
אפשר להגדיר שהיא לא מתחלפת כשעומדים עליה. הבעיה היא שהיא גדולה אז תמיד יעמדו.
בעייתי.

**Comment by JerusalemCinematheque** [comment]
אז אפשר להחליף את המנגנון למתחלף
תודה רבה

**Comment by bruria1** [comment]
איך שקיים עכשיו בדב כן?

**Comment by JerusalemCinematheque** [comment]
כן

**Comment by bruria1** [comment]
יעודכן בעדכון הבא של הקבצים

**Comment by bruria1** [comment]
עודכן בלייב

**Comment by JerusalemCinematheque** [comment]
יופי 
תודה
