### ISSUE TITLE
Lobby reference title

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#216]
@reasonat 
אחרי שהוספנו לסרט / אירוע לובי רפרנס ועושים שמור
הלובי רפרנס בעמוד עריכה מופיע בשם שלו לפרונטאנד במקום בכותרת האדמיניסטרטיבית
לדוגמא פה
http://jff.org.il/he/node/8521/edit
השם האדמיניסטרטיבי של הלובי המקושרים הם
א - ת פסטיבל 17
תחרות בינלאומית פסטיבל 17
אפשר בבקשה לשנות זאת?

**Comment by reasonat** [comment]
לא ברור מה הבעיה

**Comment by navotb** [comment]
אנסה להסביר

ממשק בחירת לובי לסרט, מציג בעת הבחירה את שדה "כותרת אדמיניסטרטיבית", הכוללת
שם מפורט יותר של הלובי
אחרי השמירה, מופיע באותו ממשק שדה "כותרת" שכולל פחות נתונים
לכן, בעתיד, כאשר נרצה לדעת לאיזה לובי מחובר הסרט - לא נוכל לעשות זאת מצד
הסרט מפני שאנחנו רואים שם חלקי

לדוגמא
בוחרים לובי בשם "פנורמה פסטיבל 2017" - זה השם האדמיניסטרטיבי המכיל גם את שם
הלובי "פנורמה" וגם את שם הפסטיבל "פסטיבל 2017"
אחרי השמירה מופיע בשם הלובי "פנורמה", כך איננו יכולים לדעת בעתיד לאיזה
פנורמה מדובר - 2017? 2018? 2011? וכו'

המבוקש הוא שהשם המופיע בממשק הבחירה יהיה תמיד השם האדמינסטרטיבי של הלובי

**Comment by reasonat** [comment]
אני מקפיא את הבקשה הזו. 
ההתנהגות של הרכיב היא להציג את הכותרת ליבה של הישות. שינוי ועדכון של זה יקח לא מעט שעות עבודה.

**Comment by navotb** [comment]
אבל במהלך הבחירה זה מציג את השדה האדמיניסטרטיבי. רק בזמן התצוגה זה לא מציג
את זה.

2017-06-22 15:26 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
כן, כי שילבנו פה וודג׳ט שונה למהלך הבחירה. התצוגה היא עדיין הרכיב המקורי והתנהגות הליבה שלו

**Comment by navotb** [comment]
אפשר לפתור את זה עם display suite. אם לא מותקן, אז צריך איזה טלאי קטן שיציג
את השם האדמיניסטרטיבי, מפני שהבחירה בכיוון הזה של בחירת לובי ובחירת פסטיבל
התבססה על השימוש בשם אדמיניסטרטיבי. אם הוא לא מוצג, זה קצת בעיה.

2017-06-25 11:25 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
בדיוק, הטלאי הזה לוקח זמן שכבר מזמן אין לנו נבות.. 
הדרך היחידה לעבור את זה היא על ידי שימוש בטבלת הניהול

**Comment by navotb** [comment]
האם בטבלת הניהול של הסרטים אפשר לראות הלובי האדמיניסטרטיבי של כל סרט? זו
אמורה להיות אותה בעיה הדורשת את אותו טלאי.

ואפרופו - אנחנו צריכים טבלת ניהול עבור לוביים (חיפוש וכו')

2017-06-25 11:52 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
1. https://github.com/Reasonat1/Cinema/issues/221 
2. https://github.com/Reasonat1/Cinema/issues/222

**Comment by reasonat** [comment]
@bruria1 can change the reference field so you will choose the administrative title instead of the title, then later when done editing it will display, on the form, the administrative title. 
We need to recheck frontend after this but we assume there will be no issues.

**Comment by reasonat** [comment]
Sorry, The case now is that you can choose administrative title in the reference field, but once choosen it display the title + node ID. 
This is the module core behave which we can change. 
Remain freeze.
