### ISSUE TITLE
event details on film page are removed to soon

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#217]
@reasonat 
קבענו בצד סינמטק ששורת ההקרנה נעלמת מעמודי הסרטים כשמועד ההקרנה עבר
מה שגילנו הוא שהמידע הזה נעלם מוקדם מידי
לדוגמא לסרט הזה
http://jer-cin.org.il/he/movie/5353
יש הקרנה היום ב-21:00
בתמונת המסך שצילמתי עכשיו רואים ששורת ההקרנה לא מופיעה

![image](https://user-images.githubusercontent.com/26960693/27391864-bbba4fa2-56ad-11e7-94b9-6f975101d424.png)

בדקתי את זה גם עם סרט אחר שמוקרן היום וקורה אותו הדבר

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
ok
