### ISSUE TITLE
Homepage - Set same homepage function like on main site.

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#22]
צריך שתהיה אפשרות ליצירת עמוד בית בדיוק כמו שיש באתר סינמטק הראשי
רק תוכן אשר סומן ככזה המופיע בפסטיבל צריך להופיע שם. 
יש ליצור עמוד בית דמה עבור פסטיבל אנגלית ועברית

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Roei Dahan האם באתר הרגיל ניתן להוסיף תכנים גם של הפסטיבל בעמוד הבית?<br />מאוד מבלבל שאתה רושם עם היוזר של רועי...<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer לא, תכנים של פסטיבל מופיעים בפסטיבל בלבד. לא הבנתי את השאלה<br />

**Comment by JerusalemCinematheque** [comment]
נראה שאפשר להוסיף את כל סוגי התכנים השונים
יש בעיית תצוגה באתר הdev בעמוד הבית, אבל אני מתארת לעצמי שזו רק בעיית תצוגה שם ולא בעיה אמיתית

**Comment by bruria1** [comment]
לא ברורה לי הערה האחרונה שלכם פה

**Comment by JerusalemCinematheque** [comment]
סליחה. אנחנו חושבים שזה בסדר, אבל לא יכולים להגיד במאה אחוז כי יש בעיית תצוגה באתר הDEV

**Comment by bruria1** [comment]
מה הבעיה בתצוגה באתר פיתוח?

**Comment by JerusalemCinematheque** [comment]
לא רואים את תמונות הגלריה

**Comment by bruria1** [comment]
http://dev.jer-cin.reasonat.com/he
פה?? בעמוד הבית?
הגלריה מוצגת..

**Comment by JerusalemCinematheque** [comment]
סינמטק כן. פסטיבל לא.
אני רואה עכשיו שיש אייקון קטן בצד למעלה של תמונה שבורה

**Comment by bruria1** [comment]
באתר פיתוח? יתכן מאוד. כי העברנו מסד נתונים אך לא העברנו תמונות. אם כך אפשר לסגור את הטיקט הזה?

**Comment by JerusalemCinematheque** [comment]
אוקיי. כל עוד אין לזה משמעות לגבי אתר הלייב
