### ISSUE TITLE
Management pages - Add Lobby administrative title to movie management page

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#221]
At the movie management page add a new column to display the administrative title of the referenced Lobby term. Also add the option to search this value.

**Comment by bruria1** [comment]
עכשיו זה הכותרת האדמינסטרטיבית במקום הכותרת של הלובי

**Comment by navotb** [comment]
השאלה היא איך אפשר לראות עבור סרט מסוים את הלובי האדמיניסטרטיבי שלו? אם
לסרט משוייכים 20 לוביים, זה קצת מסובך לראות את זה דרך הטבלת הניהול.

**Comment by bruria1** [comment]
איך עכשיו? תסתכלו באתר פיתוח.

**Comment by navotb** [comment]
הקלקה על "רשימת הלובי" מעבירה להומפייג' - זו הכוונה?
מכל מקום, הענין יהיה בעייתי יותר כאשר סרט יהיה מקושר ל-20 לוביז.
והדבר המשונה מכל, אי אפשר לתקוע סטאטית כזו בתוך טופס עדכון הסרט? רק רשימה?

**Comment by reasonat** [comment]
@bruria1 will take care of the first 2. 
As fot the 3rd one, I reopen this https://github.com/Reasonat1/Cinema/issues/216

**Comment by bruria1** [comment]
תסתכלו באתר פיתוח.
מעבר על הרשימה מציגה חלון נפתח עם כל הלובים המקושרים.

**Comment by navotb** [comment]
אם זה לא השתנה, אז זה טוב אבל הבעיה עם זה היא שכאשר לסרט יהיו הרבה יותר
לובים מקושרים, הרשימה הזו תהיה יותר קשר לקריאה או דפדוף. ענין שני הוא
שהקלקה על כפתור הרשימה מוביל להומפייג'. ואם אפשר לזרוק את הבלוק הזה כמו
שהוא לתוך טופס יצירת/עדכון סרט - הכי טוב.

**Comment by reasonat** [comment]
נבות הדיון על טופס יצירה ועדכון הוא במקום אחר אליו הפניתי, לא לפה
אלא אם כן אתה מתכוון למשהו אחר

**Comment by navotb** [comment]
לא ראיתי את הנושא השני.

2017-06-27 12:38 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
יש דיון על הווידג׳ט בטופס ההוספה של נוד
ופה זה דיון על הצגת כותרת לובי בעמודי הניהול.

**Comment by reasonat** [comment]
Closing this issue. Reopen if needed.
