### ISSUE TITLE
Management pages - Add Lobby management page

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#222]
Add Lobby management page with all the related fields and filters.

**Comment by bruria1** [comment]
האם זה:
http://dev.jer-cin.org.il/he/admin/taxonomy-manage?language=All&machine_name=lobby&name=&field_administrative_title_value=&field_festival_tid=All
לא מספיק?

**Comment by navotb** [comment]
האם אפשר שיהיה קיצור מיידי לעמוד הזה כמו "ניהול סרטים" ואחרים?
האם אפשר להוסיף כאן חיפוש לפי סרט (כלומר, תוצאת החיפוש תציג את רשימת כל
הלוביים שסרט מקושר אליהם) - זה יפתור באופן עקום את רשימת הלוביים שמקושרים
לסרט.

**Comment by bruria1** [comment]
הוספתי קישור.
בעצם אתם צריכים טבלה שמציגה לובי ורשימת כל הסרטים שמקושרים אליו?

**Comment by navotb** [comment]
לא, שדרך ממשק ניהול הלובי, אני אוכל לסנן רשימה של כל הלובייז שסרט איקס
משויך אליו, בצורת טבלת הלוביז (כולל אלטרנטיב טייטל) (כמו שבטבלת סרטים אפשר
לסנן סרטים לפי לובי, אז הפוך: בטבלת לובי לסנן לוביז לפי סרט)

**Comment by bruria1** [comment]
הוספתי מסנן שנקרא movie title
תראה אם זה עושה את מה שאתה רוצה.

**Comment by navotb** [comment]
זה לא רע, הבעיה תהיה כשתהיינה תוצאות שרלוונטיות ליותר מסרט אחד במסנן
כלומר, נגיד שנסנן לפי שם סרט חלקי, אז התוצאות תהיינה קשורות לכל אחד מהסרטים
שעונים לפילטר

**Comment by bruria1** [comment]
נכון.
אז איך תרצו את זה? רק מי שעונה לסרט המדוייק שנרשם שם?

**Comment by bruria1** [comment]
מחכה לתגובתכם..

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb This wait for your response.

**Comment by JerusalemCinematheque** [comment]
האם ניתן להכניס פקטור של חיפוש לפי מספר נוד?
חוץ מזה בסדר

**Comment by reasonat** [comment]
Yes. @bruria1 please add NID exposed filter. THanks

**Comment by bruria1** [comment]
NID של מה? זו טבלת ניהול סיווגים לא?

**Comment by JerusalemCinematheque** [comment]
כמו שאפשר לחפש שם סרט שיהיה אפשר לחפש גם לפי מספר נוד

**Comment by bruria1** [comment]
לבדיקה

**Comment by reasonat** [comment]
Closing after qa. Reopen if needed.
