### ISSUE TITLE
Movie manager page - each node appears twice

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#223]
@reasonat 
כל נוד סרט שיש לו יותר מלובי אחד מופיע מספר פעמים בתוך מערכת ניהול הסרטים
כל פעם מתחת ללובי השונים אליו הסרט מקושר
זה מאוד מבלבל

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
