### ISSUE TITLE
Article - Bio order

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#224]
@reasonat @bruria1 
בעמוד מאמר כשאנחנו מוסיפים מספר אישים ב"ביו" הם לא מופיעים בפרונטאנד בסדר ההוספה שלהם לעמוד
ראו
http://jff.org.il/en/%D7%9E%D7%90%D7%9E%D7%A8/10021

אמור להיות
Nadav Lapid
Evgenia Dodina
Sturla Brandth Grøvlen

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
