### ISSUE TITLE
festival calendar mobile view

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#225]
@bruria1 
שורות ההקרנה לא נפרסות על כל רוחב הדף. זה בצד עברית ובצד אנגלית
![image](https://user-images.githubusercontent.com/26960693/27559754-64f290aa-5aca-11e7-89ba-2c3c3ee8c3fe.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
בפיתוח כן?
אני לא חושבת שצריך שוב את היום והתאריך

**Comment by bruria1** [comment]
אז להוריד את הכותרת עם היום והתאריך?

**Comment by JerusalemCinematheque** [comment]
כן

**Comment by bruria1** [comment]
בוצע

**Comment by JerusalemCinematheque** [comment]
ok
