### ISSUE TITLE
Front page - timing issue

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#226]
@bruria1 
הקמתי עמוד מסוג פרונט פייג'
הכנסתי איזור מסוג גריד וננתי לו שעת התחלה היום ב-10:00
לפריטים שהוספתי בגריד נתתי מועדי התחלה שונים, חלקם היום וחלקם בעוד מספר ימים
אבל כל הפריטים הופיעו בעמוד, למרות מועדי ההתחלה שנקבעו להם

אני לא יכולה לשלוח לזה דוגמא כי הייתי צריכה למחוק את הפריטים מהעמוד שעולה היום

**Comment by bruria1** [comment]
בבקשה תצרי כזה עמוד באתר פיתוח שנוכל לראות את הבעיה

**Comment by JerusalemCinematheque** [comment]
http://dev.jff.reasonat.com/he/8809
האייטם אמור להופיע ב-29.6

**Comment by bruria1** [comment]
@sato2004

**Comment by sato2004** [comment]
fixed

**Comment by reasonat** [comment]
ממתין לאישור שלכם

**Comment by reasonat** [comment]
I have checked this and it looks fine. Reopen if needed.
