### ISSUE TITLE
Credits- All credits get same profession

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#227]
After saving a movie node all credits receiving the same profession. 
This is a repeatable bug issue. 
Example - 
http://jff.org.il/en/movie/9397 
http://jff.org.il/en/node/9397/edit

**Comment by sato2004** [comment]
fixed on dev

**Comment by navotb** [comment]
I had this happening again now after editing an existing film node and
saving.

**Comment by JerusalemCinematheque** [comment]
I'm not sure how we can check this on DEV site as it seems random to us
here is another example from today
http://jff.org.il/he/movie/8505

**Comment by JerusalemCinematheque** [comment]
http://jff.org.il/he/movie/9911

**Comment by sato2004** [comment]
This can happen in 2 cases
1 after you click save and translate, and then save the translation
2 when you edit a movie in an inappropriate language
example http://dev.jer-cin.reasonat.com/he/node/8506/edit
English translation, site in Hebrew.
Now I fixed both cases on the dev site

**Comment by navotb** [comment]
It still happens in this scenario
Back office Hebrew side>
Films Management Page>
Search for English Title
Click Edit
Go to Credits Tab
All credits are with same profession
Click Back in order not to Save

**Comment by reasonat** [comment]
אבל למה לעשות הפוך ממה שהמערכת צריכה לעשות? 
למה להיכנס לעמוד אנגלית דרך ממשק העריכה בעברית? 
למה לא להיכנס לעמודי האנגלית דרך ניהול האנגלית?

**Comment by navotb** [comment]
למה הפוך? זה לא ממשק עריכה. זה ממשק חיפוש. אני יכול למצוא את כל הנודים -
בעברית ובאנגלית. ומכאן אני יכול להכנס לכל אחד מהם ולטפל בו. זו צריכה להיות
המטרה של ממשק הניהול - שהוא אוניברסלי ולא תלוי שפה.

2017-07-03 13:22 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
אני יכול למצוא עוד המון מטרות לממשק ניהול, זה לא העניין. 
הליבה של דרופל עובדת באופן כזה שאם אתה עמוד עברית >> ממשקי ניהול >> עריכה  >> אתה נשאר בשפה למרות שזה נוד בשפה אחרת. זה הגיוני כמובן
אלא שבמקרה שלנו יש לזה מחיר.

**Comment by navotb** [comment]
אז תכלס אתה אומר לא להכנס לנוד ממשק בשפה ההפוכה אלא אם עוברים דרך ממשק
התרגום?

2017-07-03 15:32 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
כן.

**Comment by navotb** [comment]
אוקיי, אבל יש בעיות אמיתיות שתלויות ממשק
למשל
מניהול אירועים
יש אפשרות להכנס לעריכת הסרט שבליין אפ
אבל אם אתה נמצא בניהול אירועים בצד אנגלית
נוד הסרט נפתח דווקא בעברית, כלומר יש כאן איזה לינק אוטומטי שפותח את השפה
ההפוכה

**Comment by reasonat** [comment]
טוב, זה לא קשור לדיון הזה כלל
תוכל לעלות בעיות במקרה הזה - https://github.com/Reasonat1/Cinema/issues/261
אני יכול להבין שהדיון הזה סגור?

**Comment by navotb** [comment]
אני לא יודע אם זה לא קשור, זה פשוט עוד נתיב שדרכו נוצר המעבר הלא נכון בין
צד אנגלית לצד עברית, דרך טבלת האינדקס.

**Comment by reasonat** [comment]
למה הכוונה טבלת האינדקס?

**Comment by navotb** [comment]
טבלת ניהול סרטים (אינדקס הסרטים)

**Comment by reasonat** [comment]
הבנתי. אתה מגדיר זאת כמעבר לא נכון למרות שזו התנהגות נכונה. 
בכלל, עמודי הניהול באופן תקני אמורים להציג סרטים בשפה בה אתה נמצא כעת ולא להציג למשל נודים בעברית כאשר אני בטבלת ניהול באנגלית

**Comment by JerusalemCinematheque** [comment]
אבל בעמודי הניהול רואים את כל הנודס משתי השפות

**Comment by reasonat** [comment]
כי זה מה שאתם ביקשתם :)

**Comment by navotb** [comment]
כן, אבל אף פעם לא אמרתם לנו - אתם תוכלו להכנס מעמוד ניהול בשפה איקס רק
לנודים בשפה איקס.
מעבר לכך: כאשר מנסים להכנס מטבלת ניהול אירועים באנגלית ל"סרטים מקושרים"
נפתח הנוד בעברית, כלומר כאן זה כבר בעיה אחרת
