### ISSUE TITLE
Option to display different logos set on each content type

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#228]
Editor can have the option to display different set of logos on each content type pages - Movie nodes, event nodes, lobby terms, etc. 

Not clear if editor want the option to add different set to each node. 
@navotb ? 

Also have the option to add a different logo set on Lobby term pages

Also - does this need to be at the footer (And replace the footer logos gallery) or below the content area?

**Comment by JerusalemCinematheque** [comment]
אמיר עניין הלוגואים די דחוף
כרגע המצב הוא שאי אפשר להכניס שום אימאג' לתוך איזור התכנים

כן, סט שונה של לוגואים לכל נוד
 זה לא במקום הפוטר
חשבנו שיהיה נכון להשתמש במנגנון של הפוטר שעובד מצויין בעמודים אחרים

**Comment by JerusalemCinematheque** [comment]
וכמובן הכוונה היא גם לכל טרם

**Comment by bruria1** [comment]
@JerusalemCinematheque @navotb 
מה שניתן לעשות כרגע זה להוסיף שדה שבו אפשר להוסיף לוגויים כמה שרוצים והוא יוצג בדיוק באופן שמוצגים הלוגויים למטה.
באופן כזה אתם צריכים לומר לנו איפה בדיוק בעמוד הלוגויים צריכים להופיע.
האם זה עונה על בקשתכם?

**Comment by JerusalemCinematheque** [comment]
וזה שדה לוגואיים לכל אייטם כן?
הכי נכון להציג את הלוגואים ככה:
**לובי - אחרי שדה** 
Lobby description & teaser
**מאמר - אחרי שדה**
Body
**סרט - אחרי שדה**
Long summary 
או
Long summary - Festival
**אירוע - אחרי שדה**
Event Details
**מקבץ - אחרי שדה**
Body

**Comment by bruria1** [comment]
האם תצטרכו למחזר את אותו סט של לוגויים בכמה מקומות?
אם כן, ניישם את זה בצורה אחרת:
יהיה סוג תוכן של לוגויים ששם תייצרו את הסט ותוכלו לשייך אותו לכל סוג תוכן שתרצו.

**Comment by JerusalemCinematheque** [comment]
לא זה סט שונה בכל מקום
זה רק צריך לעבור גם לצד תרגום

**Comment by bruria1** [comment]
איך התצוגה אמורה להיראות? כמו הלוגויים למטה? רשימה של כל הלוגויים ובמובייל גלריה?

**Comment by bruria1** [comment]
בינתיים אתם יכולים לראות איך זה עובד בסוג תוכן סרט באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
נוצרה איזו שגיאה אחרי שהוספתי את הלוגואים
![image](https://user-images.githubusercontent.com/26960693/27769365-9ce3b844-5f30-11e7-96ed-c2f86f436049.png)

http://dev.jff.reasonat.com/he/movie/8523

**Comment by JerusalemCinematheque** [comment]
אני מתנצלת, עכשיו שאני רואה את העמוד נראה יותר נכון שהלוגואים ישבו אחרי הקרדיטים

**Comment by bruria1** [comment]
איך עכשיו?
תבדקי בכל סוגי התוכן שרשמת.
כרגע הלוגויים הם לא גלרייה. האם זה צריך להיות?

**Comment by JerusalemCinematheque** [comment]
מה הכוונה בגלריה? שבתצוגה ריספונסיבית הם מופיעים כמו סטריפ הלוגואים למטה??

**Comment by bruria1** [comment]
האם התצוגה רספוניבית הם צריכים להראות כמו הלוגויים למטה? זאת אומרת עם חיצים בושרה אחת בלבד?

**Comment by JerusalemCinematheque** [comment]
נראה נהדר בעמוד סרט
אבל, הלוגואים צריכים לעבור גם לעמוד האירוע של הסרט
לדוגמא: 
http://dev.jff.reasonat.com/he/event/8818

בעמוד אירוע עם מקבץ - הלוגואים צריכים להופיע לפני פרטי המקבץ, לא אחרי
http://dev.jff.reasonat.com/en/event/8820

בעמוד אירוע עם סרט - הם צריכים להופיע לפני פרטי הסרט 
http://dev.jff.reasonat.com/he/event/8806

בעמוד לובי צד עברית - לא רואים את הלוגואים
http://dev.jff.reasonat.com/he/lobby/5-%D7%99%D7%9E%D7%99%D7%9D-%D7%91%D7%99%D7%95%D7%A0%D7%99

בעמוד לובי צד אנגלית - בלוגואים מופיעים אחד מתחת לשני, לא אחד אחרי השני
http://dev.jff.reasonat.com/en/lobby/5-days-june

בעמוד מאמר - צריך להוסיף עוד ריווח בין אזור הטקסט לאזור הלוגואים
http://dev.jff.reasonat.com/he/article/7810

בעמוד מקבץ - להוסיף ריווח בין הלוגואים לרשימת הסרטים
http://dev.jff.reasonat.com/he/movie-group/5999

**Comment by bruria1** [comment]
האם התצוגה רספוניבית הם צריכים להראות כמו הלוגויים למטה? זאת אומרת עם חיצים בושרה אחת בלבד?

**Comment by bruria1** [comment]
אם כך השדה לא אמור להופיע בעמוד אירוע? כי הלוגויים נלקחים מהסרט?

**Comment by JerusalemCinematheque** [comment]
כן לריספונסיבי

**Comment by JerusalemCinematheque** [comment]
השדה כן צריך להיות גם באירוע וגם בסרט
אבל אם לסרט יש לוגואים אז הם צריכים להופיע גם בהופעה שלו בעמוד האירוע בלי קשר ללוגואים שאולי יצורפו לעמוד האירוע

**Comment by bruria1** [comment]
1. לגבי עמודי לובי - אם נעשו שינויים בעמוד מבחינת הפאנלים השינוי לא נתפס לכן יש ללכת לעמוד הזה:
http://dev.jff.reasonat.com/he/admin/panopoly/pages
לחפש את העמוד המבוקש ולאפס אותו. ואז הלוגויים יחזרו. אחר כך יש להחזיר אותו לתצוגה הרצויה.
כמובן שיהיה עליכם לעשות זאת בלייב.
השאר עודכן גם במובייל, תעשו בדיקות ותעדכנו אותי.

**Comment by JerusalemCinematheque** [comment]
לאפס אותו זה אומר ללחוץ על "שחזר"?
ונצטרך לעשות את זה לכל עמוד לובי?

**Comment by JerusalemCinematheque** [comment]
?וזה נכון גם למקרה הזה
http://dev.jff.reasonat.com/he/event/8818

**Comment by JerusalemCinematheque** [comment]
בעמוד אירוע עם מקבץ - צריך לרווח בין איזור הלוגואים לפרטי המקבץ. 
http://dev.jff.reasonat.com/en/event/8820

בעמוד אירוע עם סרט - צריך לרווח בין איזור הלוגואים לפרטי הסרט
http://dev.jff.reasonat.com/he/event/8806

בעמוד לובי צד אנגלית - אפשר להוסיף עוד קצת רווח בין הטקסט ללוגואים
http://dev.jff.reasonat.com/en/lobby/5-days-june

**Comment by JerusalemCinematheque** [comment]
עוד שני דברים
בעמוד האירוע עם סרט שיש לו לוגואיים, הלוגואיים צריכים להופיע כפי שהם מופיעים בעמוד הסרט, אחרי הקרדיטים
עמוד הסרט
http://dev.jff.reasonat.com/en/movie/8524
עמוד האירוע
http://dev.jff.reasonat.com/en/event/8819

דבר שני, שאני לא יודעת אם זה קשור ולא יודעת אם זה קשור לזה שמדובר על סביבת עבודה,
אבל משהו השתבש עם התצוגה של שדה "תרגום" בעמוד הסרט ובעמוד האירוע
בצד אנגלית חזרה המילה
subtitles
ובצד עברית כתוב
תרגום ל|תרגום לעברית
במקום רק תרגום לעברית

**Comment by reasonat** [comment]
As for the second comment - I reopen this one - https://github.com/Reasonat1/Cinema/issues/158

**Comment by bruria1** [comment]
לאפס אותו זה אומר ללחוץ על "שחזר"?
ונצטרך לעשות את זה לכל עמוד לובי?
כן. תצטרכו לעשות את זה לכל עמוד שתרצו שהלוגויים יתווספו ולאחר מכן לעדכן את העמוד לתצוגה שאתם רוצים.

**Comment by bruria1** [comment]
?וזה נכון גם למקרה הזה
http://dev.jff.reasonat.com/he/event/8818
לא. זה אירוע. מה הבעיה פה?

**Comment by bruria1** [comment]
שאר הדברים נעשו. אנא בדקו.

**Comment by JerusalemCinematheque** [comment]
בעמוד אירוע עם מקבץ - צריך לרווח בין איזור הלוגואים לפרטי המקבץ. - אפשר עוד לרווח כמו הריווח בעליון שיש בעמוד לובי
http://dev.jff.reasonat.com/en/event/8820

בעמוד אירוע עם סרט - צריך לרווח בין איזור הלוגואים לפרטי הסרט - אפשר עוד לרווח כמו הריווח בעליון שיש בעמוד לובי
http://dev.jff.reasonat.com/he/event/8806

לאפס אותו זה אומר ללחוץ על "שחזר"?
ונצטרך לעשות את זה לכל עמוד לובי?
כן. תצטרכו לעשות את זה לכל עמוד שתרצו שהלוגויים יתווספו ולאחר מכן לעדכן את העמוד לתצוגה שאתם רוצים.
**אפשר להוסיף שם איזשהו מנגנון חיפוש?**

**Comment by JerusalemCinematheque** [comment]
תצוגה ריספונסיבית
עמודי סרטים אירועים מאמרים - הגלרייה לא פרוסה לכל רוחב המסך מה שיוצר תצוגה משובשת
![image](https://user-images.githubusercontent.com/26960693/27781607-538a1efc-5fd7-11e7-92d8-e31c904a5942.png)

![image](https://user-images.githubusercontent.com/26960693/27781872-b9ec108c-5fd8-11e7-8b3e-612bf1d305cd.png)

עמוד לובי - הלוגואים לא נכנסים נכון לתוך תצוגת גלרייה וחסרים חצי המעבר
![image](https://user-images.githubusercontent.com/26960693/27781747-0f198dd8-5fd8-11e7-9bfe-a937c7c93e7e.png)

**Comment by bruria1** [comment]
בדקו כעת.
לגבי איפוס עמוד הלוגויים. בצעו את החיפוש עם החיפוש של הדפדפן יש שם בסך הכל שני עמודים. וזה משהו חד פעמי

**Comment by navotb** [comment]
עכשיו יש שני עמודים. עוד חצי שנה יהיו 10 עמודים.

2017-07-03 10:53 GMT+03:00 Bruria <notifications@github.com>:

**Comment by JerusalemCinematheque** [comment]
אוקיי לכל ענייני תצוגת הלוגואים
ברוריה תוכלי בבקשה לעדכן אותנו כשזה באתר החי?
תודה

**Comment by bruria1** [comment]
לגבי השחזור של עמודי הלובי זה משהו חד פעמי שאתם צריכים לעשות. כל להלוביים החדשים לא תהיה בעיה

**Comment by bruria1** [comment]
מעודכן בלייב. עדכנו שזה בסדר.

**Comment by JerusalemCinematheque** [comment]
נראה שעבר לכל סוגי התוכן חוץ מעמוד לובי

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
http://jff.org.il/en/lobby/jewish-experience
הלוגואים שהוספתי בצד העברית של עמוד זה לא מוצגים בצד אנגלית

הלכתי לעמוד הזה כדי לעשות שחזור
http://jff.org.il/en/admin/panopoly/pages?page=1
אבל אני לא מוצאת את הלובי הזה שם

**Comment by bruria1** [comment]
שכחתי לגרום לכך שזה יעודכן בשמירה. כעת זה טוב.

**Comment by JerusalemCinematheque** [comment]
אוקיי
בתצוגה הריספונסיבית של הלובי הלוגואים לא שומרים על המרווח ביניהם
![image](https://user-images.githubusercontent.com/26960693/27819635-d020dd3a-60a3-11e7-8fbb-8b2f90ecf62e.png)

**Comment by bruria1** [comment]
צריך לרענן את העמוד. זה לא מתעדכן בהקטנת המסך

**Comment by bruria1** [comment]
מחכה לאישורכם..

**Comment by JerusalemCinematheque** [comment]
ok
