### ISSUE TITLE
movie collection - movie order

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#229]
@bruria1 
סדר ההופעה של הסרטים בעמוד מקבץ הוא לא לפי הסדר שהוספנו אותם למקבץ
לדוגמא
http://jff.org.il/he/%D7%9E%D7%A7%D7%91%D7%A5-%D7%A1%D7%A8%D7%98%D7%99%D7%9D/8063

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
@bruria1 
הבעיה עכשיו חזרה
ראי
https://jer-cin.org.il/he/movie-group/14995
קרן היסוד 13 אמור להיות הסרט האחרון ברשימה והוא מופיע כראשון

**Comment by bruria1** [comment]
לבדיקה
