### ISSUE TITLE
Header - גישה לניהול שם האתר בעברית לצד הלוגו

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#23]
עורכי התוכן יכולים לעדכן את שם האתר בעברית ואנגלית

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar אני חושבת שזה מוגדר בקוד ואין אפשרות לשנות את זה ב-UI. &#64;Inbal Jona ?<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar יש צורך בזה?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer בעיקרון כן, אבל עזבי את זה כעת<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar אני מציעה בצורה הכי פשוטה לעשות שהשם של האתר יהיה תיבה ואז לא תהיה להם בעיה לערוך את זה. ממה שאני זוכרת ענבל התעסקה עם זה ולא הצליחה שזה יעבוד דרך ה-UI.<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer כן, מסכים. זה פתרון טוב ומהיר

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar טוב.. ממה שאני רואה מוגדר בקובץ טמפלט (של תבנית האב!!!) שכותרת הפסיבל נלקחת מהסיווג ומשדה התאריך שלו. צריך לשאול אותם אם זה צריך להיות כך או שהם בעצמם רוצים להחליט כל פעם מה יהיה רשום שם.<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer עשית את זה בסוף עם תיבה לא? <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Reasonat Admin לא עשיתי..  רשמתי לך בהודעה שאולי התיבה הזו אמורה להיות השם של  הפסטיבל ולא שם שבא להם או שלא?<br /><br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar לא ענית לי. מה שמוגדר שם כעת זה שהשם מורכב מהסיווג ומהתאריך שלו. האם זה מה שאמור להיות? או שאנחנו רוצים לתת להם לרשום מה שבא להם כל פעם?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer לתת להם לרשום מה שבא להם כל פעם. <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar הם יכולים כעת לנהל את שם האתר מהתיבות פה:<br />http://jff.reasonat.com/en/admin/content/blocks<br />האם צריך קישור לניהול מהלוגו עצמו? אפשר לתת הרשאה ל contexual filter לא?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer אפשר פשוט להוסיף קישור תחת התפריט דאשבורד<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar הוספתי<br />

**Comment by JerusalemCinematheque** [comment]
השם ליד הלוגו צריך להיקבע לפי מילוי שתי השורות בניהול שם האתר. אבל אין בשורה הראשונה בעברית מספיק מקום והשורה מתפצלת לשניים ומעלימה את השורה השנייה. מה שצריך להיות שזה שכל שורה נכנסת כשורה אחת ודוחפת את חלק התפריט שמאלה
