### ISSUE TITLE
movie collection - responsive issues

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#230]
@bruria1 
בתצוגה ריספונסיבית של מקבץ הופיעו מספר עניינים
http://jff.org.il/he/%D7%9E%D7%A7%D7%91%D7%A5-%D7%A1%D7%A8%D7%98%D7%99%D7%9D/8041

1. כותרת המקבץ אמורה להופיע מתחת לתמונות ולא עליהם. בדומה לכותרת בעמוד סרט ועמוד אירוע (קורה בצד עברית ואנגלית
1. בצד עברית יש בעיה באזור התצוגה של כותרת הסרט ברשימת הסרטים המקושרים 
הכותרת נדחפת שמאלה ורואים מצד ימין קוביה שחורה, נראה שאמור להופיע שם כפתור וידיאו למרות שאין לסרטים האלו כרגע טריילר. בצד אנגלית זה בסדר.
![image](https://user-images.githubusercontent.com/26960693/27606453-0570d9ba-5b89-11e7-814a-2163549191dd.png)

**Comment by bruria1** [comment]
לבדיקה באתר פ יתוח

**Comment by JerusalemCinematheque** [comment]
אוקיי
רק החצים בתמונות גלריה קצת יושבים גבוה

**Comment by bruria1** [comment]
אני לא רואה את הבעיה. הם יושבים כמו בכל שאר העמודים

**Comment by JerusalemCinematheque** [comment]
אוקיי לחצים
נושא חדש
בשורת ההקרנה של המקבץ בריספונסיבי אין את פרטי המועד (יום ותאריך) וכפתור שלח לקלנדר שלי
בנוסף חסרי כפתורי השיתוף

![image](https://user-images.githubusercontent.com/26960693/27796070-577a2fa4-6011-11e7-9fcc-f6b4a0e8d36c.png)

**Comment by JerusalemCinematheque** [comment]
בעמוד האירוע של המקבץ שמות הסרטים זזים ימינה בצד עברית
![image](https://user-images.githubusercontent.com/26960693/27796181-c1179a5a-6011-11e7-92df-8f5012ccfd6e.png)

**Comment by bruria1** [comment]
לבדיקה.
ההערה השניה תוקנה כרגע רק בדב.

**Comment by JerusalemCinematheque** [comment]
ok
