### ISSUE TITLE
importing LEV SMADAR hall when creating events from film page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#231]
@yakoub 
כשאנחנו מייבאים אירועים מתוך עמוד סרט, משום מה אולם "לב סמדר" לא מיובא
אם אנחנו מייבאים את אותו אירוע מתוך עמוד "אירוע" אז אין בעיה

לדוגמא הסרט הזה
http://jff.org.il/he/movie/9068

אחרי שעשיתי ייבוא מתוך העמוד בפרונטאנד ראו את מועד ההקרנה הראשונה אבל לא ראו את האולם
אחרי זה נכנסתי לאירוע עצמו ועשיתי ייבוא פעם נוספת מטופטיקס והפעם האולם כן הופיע

נכנסתי פעם נוספת להגדרות האולם ועשיתי לו עדכון לקישור עם טופטיקס, אבל זה לא השפיע

**Comment by JerusalemCinematheque** [comment]
ראינו עכשיו שהבעיה קוראת רק מצד עברית
כלומר אם אנחנו עושים את הייבוא מצד אנגלית הכל בסדר

**Comment by JerusalemCinematheque** [comment]
קורה גם עם אולם שנקרא "בית הנסן"

**Comment by yakoub** [comment]
when i look at the movies events :
http://jff.org.il/he/node/9068/events
http://jff.org.il/en/node/9069/events

i see these events :
http://jff.org.il/en/node/10081/edit
http://jff.org.il/he/node/10080/edit

which have lev smadar hall as expected .

so i don't see the problem .

please provide another example if you believe the problem persists .
@JerusalemCinematheque

**Comment by yakoub** [comment]
please provide another example if you believe the problem persists .

**Comment by yakoub** [comment]
related video : https://www.youtube.com/watch?v=giDutnkrc68

**Comment by JerusalemCinematheque** [comment]
i added the hall individually

here is an example on DEV site

http://dev.jff.reasonat.com/he/movie/8523

**Comment by yakoub** [comment]
@JerusalemCinematheque maybe you have updated that example manually again ?
i am sorry for late response, but i don't see the problem with the last example either .

i need detail explanation of the steps you take with paths, example :
i visit path : node/add/cm_movie or node/999/edit
i assign toptix hall : צבא הצללים
then i expect to see events X,Y added but the result only X .
or before saving when i open toptix browser i see only X and not Y .

**Comment by reasonat** [comment]
Please recheck this @JerusalemCinematheque @navotb

**Comment by JerusalemCinematheque** [comment]
we are still experiencing problems here
for example we want to update an event in hall Lev Smadar
http://jff.org.il/en/node/10073
we go to toptix button and find the said event
we select it
save event
the hall reference disappears
then we have to put in the hall manually, otherwise the evnt appears without the hall name and does not appear in the festival calendar
we don't have a live example

**Comment by JerusalemCinematheque** [comment]
https://www.youtube.com/watch?v=DLPOz1k5yAc

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

"Summer 1993" doesn't appear in toptix browser any more

**Comment by JerusalemCinematheque** [comment]
try this one
http://jff.org.il/he/event/10100
should be there till friday morning

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

as for the other example 1945, then the term "lev smadar" had empty toptix assignment .
http://jff.org.il/en/taxonomy/term/204/edit

after assigning the toptix field, then at event edit page the hall reference also received the value .

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

please provide more examples .

**Comment by JerusalemCinematheque** [comment]
what does 
empty toptix assignment
mean?

**Comment by yakoub** [comment]
the field toptix hall was empty .

**Comment by JerusalemCinematheque** [comment]
empty from the toptix feed?

**Comment by yakoub** [comment]
no, the hall term page edit form : http://jff.org.il/en/taxonomy/term/204/edit
has field called "toptix hall" . 
and if you want automatic import on event pages to happen then this field need to assigned a value using the toptix browser like other toptix fields .

**Comment by JerusalemCinematheque** [comment]
that's the first thing we checked
it seems to be okay now
