### ISSUE TITLE
movie collection event page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#233]
@bruria1 
כמה עניינים בעמוד אירוע של מקבץ

1. לא כל תמונות ההירו מהמקבץ עוברות לעמוד האירוע
2.  הראסטר לא מופיע כמו שצריך על תמונת ההירו
![image](https://user-images.githubusercontent.com/26960693/27643592-261f6464-5c2a-11e7-9f9d-e67967236936.png)
3.  חסרים התקצירים של הסרטים שמקושרים למקבץ

דוגמא כאן
http://jff.org.il/en/event/10611

**Comment by JerusalemCinematheque** [comment]
נראה שעניין הראסטר קורה כשיש למקבץ יותר מתמונה אחת
לדוגמא במקבץ הזה שיש לו רק תמונה אחת הראסטר בסדר
http://jff.org.il/he/event/10618

**Comment by bruria1** [comment]
לבדיקה. פה:
http://dev.jff.org.il/en/event/8820

**Comment by JerusalemCinematheque** [comment]
הראסטר והתמונות בסדר
רק נשאר עניין התקציר

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
אחלה
תודה
