### ISSUE TITLE
Festival calendar - Days nav bug

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#234]
אחרי שעברנו מספר ימים וביקשנו לעבור לעוד יום בצד אנגלית, הקלדנר חזר ליום הראשון שלו ולא עלה
הוא הציג איזשהו קיבוץ של כל מיני אירועים שמופיעים אחד על השני
ולא היה את שורת הימים
![image](https://user-images.githubusercontent.com/26960693/27648109-291a66a8-5c36-11e7-81d6-7ac583453a97.png)

רק אחרי שניקינו את הקאש של האתר הקלנדר חזר

**Comment by JerusalemCinematheque** [comment]
במסך מקבוק 13 אינץ' יש בעיית תצוגה כשיש 6 אולמות ומעלה
![image](https://user-images.githubusercontent.com/26960693/27673397-1e3c9cd8-5ca9-11e7-825a-fe8ef41f7658.png)

![image](https://user-images.githubusercontent.com/26960693/27673439-751adb64-5ca9-11e7-9866-31edd10b7fec.png)

**Comment by reasonat** [comment]
מה הבעיה עם התצוגה במקבוק? אני גם עם אותו מחשב ולא רואה בעיה. 
ובאשר לההערה הראשונה - https://github.com/Reasonat1/Cinema/issues/244

**Comment by JerusalemCinematheque** [comment]
לדוגמא ב-19.7
אולם יס פלאנט חתוך וגם הקוביות מתחתיו
והכיתוב לאולמות נוספים יושב על האולם

![image](https://user-images.githubusercontent.com/26960693/27770270-18a47dac-5f44-11e7-8a91-65599548b06d.png)

**Comment by reasonat** [comment]
Approve @bruria1

**Comment by bruria1** [comment]
@reasonat כדאי שאלכס יסתכל על זה. הוא יודע מה הולך שם. זה פחות עניין של עיצוב אלא יותר של הקוד שנכתב שם ממה שאני יודעת.

**Comment by reasonat** [comment]
@sato2004 Please have a look

**Comment by sato2004** [comment]
Fixed on dev site

**Comment by JerusalemCinematheque** [comment]
ok
