### ISSUE TITLE
Event Management page - finding events that don't have films attached

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#238]
@reasonat 
אי אפשר למצוא במערכת הניהול של האירועים 
אירועים שלא מקושר אליהם סרט
לדוגמא
http://jff.org.il/en/event/10650
אפשר למצוא אותו במערכת ניהול התוכן הכללי, אבל לא בניהול אירועים

כנ"ל
http://jff.org.il/he/event/8528

**Comment by bruria1** [comment]
לא הבנתי כנראה..
אם אני מחפשת אותו פה:
http://jer-cin.org.il/he/admin/events-manager
הוא מופיע..

**Comment by JerusalemCinematheque** [comment]
אני מחפשת אירוע שנקרא סרט הפתעה
יש ארבעה אירועים כאלו
ולא מקבלת שום תוצאות חיפוש

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
אחלה
