### ISSUE TITLE
Events page in English with no film - event details display issue

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#239]
@bruria1 
באירוע הזה
http://jff.org.il/en/event/8529
שהוא אירוע ללא סרט יש בעיה עם איזור גבולות הגריד של תיאור האירוע

**Comment by bruria1** [comment]
תוקן באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
קווי הגריד בסדר עכשיו
יש עניין עם בריווח בין איזור בתמונה, איזור פרטי ההקרנה ואיזור פרטי האירוע

**Comment by bruria1** [comment]
צריך שיהיה רווח גדול יותר מעל פרטי האירוע?

**Comment by JerusalemCinematheque** [comment]
אני לא רואה באתר פיתוח את פרטי ההקרנה
אבל החלק של פרטי האירוע דבוקים לתמונה

**Comment by bruria1** [comment]
לא היו פרטי אירוע כיוון שמועד האירוע שהיה שם עבר. כעת רואים את הפרטי האירוע כי עדכנתי את תאריך האירוע. והוספתי רווח.

**Comment by JerusalemCinematheque** [comment]
מעולה
