### ISSUE TITLE
Calendar - Main Area - Display / Dont display not active events

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#24]
Site calendar should display un-active events to stuff and editors members when they login to the site

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar לא הבנתי את המשימה ואת הרעיון שלה<br />

**Comment by JerusalemCinematheque** [comment]
אתם רוצים שנבדוק אם אירועים שהם לא אקטיביים מופיעים בעמוד ניהול אירועים?

**Comment by reasonat** [comment]
אין קשר בין המשימה הזו לעמוד ניהול אירועים
מדובר על הצגה/אי הצגה של אירועים לא אקטיביים בלוח השנה של הפסטיבל

**Comment by JerusalemCinematheque** [comment]
אירועים שמסומנים כלא אקטיביים מופיעים כשמשתמש אדיטור מחובר ולא מופיעים כמשתמש לא מחובק
השאלה היא איך מי שהוא אדיטור והצוות אמורים לדעת שהאירוע אקטיבי או לא אקטיבי

**Comment by reasonat** [comment]
Thats a good point. 
@bruria1 Please highlight in a way, non-active events which get display for editors role.

**Comment by bruria1** [comment]
בוצע.
ניתן לראות פה:
http://dev.jff.reasonat.com/en/festival-calendar

**Comment by JerusalemCinematheque** [comment]
okay
רק צריך למצוא פתרון לתצוגה במובייל

**Comment by bruria1** [comment]
מה הבעייה שם?

**Comment by JerusalemCinematheque** [comment]
שאין הבחנה בין אירועים מפורסמים לאירועים לא מפורסמים

**Comment by bruria1** [comment]
אבל במובייל גם אדיטור גולש? לא ברור לי למה צריך

**Comment by JerusalemCinematheque** [comment]
יכול להיות שאדיטור או אנשי צוות יגלשו במובייל או בטאבלט
צריך לביות לו איזשהו סימון שונה כמו שיש בתצוגת דסקטופ

**Comment by bruria1** [comment]
הוספתי

**Comment by JerusalemCinematheque** [comment]
מעולה
