### ISSUE TITLE
Festival calendar days jump

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#240]
@reasonat 
כשמבקשים לעבור מיום ליום בעמוד הקלנדר, שורת הימים קופצת וצריך פעם נוספת ללחוץ על היום המבוקש
הסבר ויזואלי בוידאו
https://youtu.be/wPsrQOY-Q2Y

זה לא קורה כל הזמן, אבל קורה מספיק

**Comment by bruria1** [comment]
@sato2004

**Comment by sato2004** [comment]
fixed on the dev site

**Comment by JerusalemCinematheque** [comment]
i hope it's okay
it's difficult to check as this doesn't happen all the time

**Comment by JerusalemCinematheque** [comment]
we checked again and problem seems to be now that the days jump and then go back to their place
also at times days get stuck - when pressing to select a different day, it shows the "loading", but the day does not appear 
a video of the days getting stuck
https://www.youtube.com/watch?v=pmUrpTP4mcQ

**Comment by reasonat** [comment]
Please review again after massive change in the calendar

**Comment by reasonat** [comment]
I can't see this issue again. Closing the issue, please reopen if needed.
