### ISSUE TITLE
festival calendar - sold out button does not work

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#242]
@reasonat 
האירוע הזה
http://jff.org.il/he/event/10132
סומן כאזלו כרטיסים. ואכן כפתור הכרטיסים הפך לאזל בעמוד האירוע, בלובי של הסרט ובעמוד הסרט
אבל בעמוד הקלנדר - בקוביה של האירוע ובפופ-אפ כפתור הכרטיסים עדיין פעיל

**Comment by sato2004** [comment]
I don't see a problem
![sold_out](https://user-images.githubusercontent.com/15141149/27779673-4a2f5098-5fcd-11e7-89d9-a0bcee0cbd51.PNG)
It seems it is a cache issue.

**Comment by JerusalemCinematheque** [comment]
site cache issue?

**Comment by reasonat** [comment]
Yes, and it's not an issue. It's cache limitations
