### ISSUE TITLE
Article - Option to add attach files

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#243]
On Article node type add the option to attach files which can be download by the end user.

**Comment by bruria1** [comment]
איזה סוגי קבצים? איך זה צריך להיות מוצג? מספר קבצים בלתי מוגבל?

**Comment by navotb** [comment]
pdf, docx, xlsx, txt, jpeg וכאלו (gif  וכו')

לא קבצי קוד או קצבים שמפעילים את עצמם איך שהם יורדים, לא קבצי exe או משהו
שיכול להפעיל משהו מאיפשהו.
אפשר להוסיף יותר מקובץ למאמר

**Comment by bruria1** [comment]
הוספתי באתר פיתוח.
ברגע שתאשרו אעלה ללייב.
עדכנו אותי איפה זה צריך להופיע ואיך להראות.
תוכלו לראות דוגמה פה:
http://dev.jer-cin.org.il/en/article/4248

**Comment by JerusalemCinematheque** [comment]
אחלה
העניין היחיד הוא שזה לא צריך להיות שדה מתורגם
אלא שדה נפרד בעברית ובאנגלית

**Comment by bruria1** [comment]
זה לא מסתנכרן האחד עם השני.

**Comment by JerusalemCinematheque** [comment]
אוקיי
