### ISSUE TITLE
Festival calendar - When switching language remain in the same day

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#244]
When user see a date, lets say 19.7, then switch to another language, he should be remain in the same date.

**Comment by navotb** [comment]
could be great if it will also work for "back" - assume i was on 17/07, i
clicked on a film, go to filmpage, now when i click back (from filmpage to
calendar) i get the first day of the calendar (in mobile anyway)

**Comment by sato2004** [comment]
fixed on the dev site

**Comment by JerusalemCinematheque** [comment]
okay on dev site
