### ISSUE TITLE
"No page" error after node update

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#245]
There is a no page error after updating nodes. 
Example: 
http://dev.jff.org.il/he/node/1006/edit 

**Cant approve on:** 
Movie, event (Even when importing from Toptix), Movie group. 
Please provide step by step examples when happen.

**Comment by JerusalemCinematheque** [comment]
מתוך עמוד ניהול אירועים לחצנו על עדכן אירוע
http://dev.jff.reasonat.com/he/event/8818
ייבאנו את ההקרנה מטופטיקס
לחצנו שמור
וקיבלנו את ההודעה 
![image](https://user-images.githubusercontent.com/26960693/27770567-87aa4cc2-5f49-11e7-8798-21c3077a89b5.png)

**Comment by yakoub** [comment]
i have encountered this error before, but so far i can't reproduce it .

**Comment by navotb** [comment]
It happens when you edit person page and press button "save and edit" and
not just "save"

**Comment by JerusalemCinematheque** [comment]
this happens on a daily basis after editing existing film/events/person nodes
there is no consistency, one time it will work properly, and then the next you get the error message

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
seems to be okay now. will reopen if we encounter issue again
