### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#246]
[https://www.wrike.com/open.htm?id=142672742https://www.wrike.com/open.htm?id=142672742](https://www.wrike.com/open.htm?id=142672742)
https://www.wrike.com/open.htm?id=142672742

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

cache_form has grown again to 1.3G

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

i will empty it manually for now

**Comment by yakoub** [comment]
related issue : https://www.drupal.org/node/1506196

**Comment by navotb** [comment]
there is also this article by acquia which might be useful

https://docs.acquia.com/article/keeping-cacheform-table-reasonable-size

**Comment by yakoub** [comment]
i am following the table size through time to determine best practice .
will check again on Thursday .

**Comment by yakoub** [comment]
there seems to be problem with cron not running every day as required, well check that tomorrow .

**Comment by navotb** [comment]
Over all sites' tables or only this table?

**Comment by yakoub** [comment]
cron doesn't run regardless of which table .

**Comment by navotb** [comment]
From the link that Amir sent:

From the DrupalCache perspective, {cache_form} is treated like everything
else, and pruned by system_cron() along with everything else. The main
difference is that drupal_flush_all_caches() doesn't clear it to prevent
problems if someone is filling out a form at that exact instant.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

cron.php is not found although it exist on filesystem, so that is why cron never runs and doesn't clean form_cache table properly .

**Comment by sato2004** [comment]
@reasonat Did Yakoub fix cron issue? I see cron message in log and I don't see old values in form_cache table.

**Comment by navotb** [comment]
I still receive every morning a cron email

**Comment by reasonat** [comment]
➤ Roei Dahan commented:

@Amir Taiar זה עדיין דורש טיפול או הסתיים?

**Comment by reasonat** [comment]
@Roei Dahan עדיין על הפרק.
