### ISSUE TITLE
article - responsive view hebrew side

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#247]
@bruria1 
בעמוד מאמר בתצוגה ריספונסיבית בצד עברית, קווי בגריד קצת השתבשו והטקסט נצמד לקצה המסך
![image](https://user-images.githubusercontent.com/26960693/27782676-2214bcba-5fdc-11e7-904c-902b1d121d59.png)

**Comment by bruria1** [comment]
סודר באתר פיתוח
עוד מעט מעדכנים את הלייב

**Comment by JerusalemCinematheque** [comment]
ok
