### ISSUE TITLE
add pagination to lobby pages

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#249]
@reasonat 
נשמח אם יהיה אפשר להוסיף פג'ינציה לעמודי הלובי
בעמוד כמו זה שיש בו רשומות רבות זמן הטעינה ארוך מידי
http://jff.org.il/en/lobby/z
אם אנחנו יכולים לשלוט במספר התוצאות בכל עמוד מעולה, אם לא האם  נוכל לקבוע 25 תוצאות בכל עמוד?

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
מצויין
