### ISSUE TITLE
lobby title attached to film / event does not appear on film / event page frontend

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#250]
@reasonat 
הלוביים אליהם מקושרים הסרטים לא מופיעים בפרונטאנד של הסרטים או האירועים של הסרטים
לדוגמא
http://jff.org.il/en/movie/9944
שמקושר ללובי 
international competition

**Comment by JerusalemCinematheque** [comment]
זה נכון גם לגבי אירועים שמקשורים ללובי
כמו זה
http://jer-cin.org.il/he/event/7527
שמקושר ללובי "חגיגת קולנוע לילדים יוני 2017"

**Comment by JerusalemCinematheque** [comment]
@reasonat @bruria1 
נשמח אם יהיה אפשר לתת לזה פוש קדימה
תודה רבה

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
מעולה
תודה
