### ISSUE TITLE
HOME PAGE - event title does not appear when event is attached to gallery view

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#251]
@bruria1 
משום מה נעלמה הכותרת של האירוע הזה
http://jer-cin.org.il/he/event/7549
בתצוגה של האירוע בעמוד הבית בחלק של הגלריה
עד אתמול זה הופיע

**Comment by bruria1** [comment]
עודכן באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok
