### ISSUE TITLE
home page - grid view - home page text cut when there is a video button

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#252]
@bruria1 
בעמוד הבית של הפסטיבל בצד עברית 
בתצוגת הגריד הטקסט אקסטרה של האייטמים מופיע על כפתור הוידאו
האם אפשר לקבוע שהחיתוך לשורה השנייה של הטקסט יתאים למיקום של כפתור הוידאו?

**Comment by bruria1** [comment]
עודכן באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok
