### ISSUE TITLE
front page - grid view - does not show next screening date for movie

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#253]
@bruria1 
הוספנו בפרונט פייג' הזה
http://jff.org.il/he/10703

סרט בתצוגת גריד
http://jff.org.il/he/movie/10694

לסרט יש שתי הקרנות, אבל בתצוגה רואים רק את שם הסרט ללא המועד

**Comment by bruria1** [comment]
הוגדר שם שרק אם מסומן:
 Include Ticket Sale?
אז מופיעה פרטי ההקרנה בעמוד הבית
הורדתי את התנאי הזה באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok
