### ISSUE TITLE
front page - wide list view - event item - film synopsis missing

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#254]
@bruria1 
http://jff.org.il/he/10705
 ביקשתי לקשר בעמוד פרונט פייג׳ אירוע עם סרט (האייטם האחרון בעמוד)
התמונה, כותרת, לידינג קרדיט טקסט ואורך מופיעים
אבל התקציר המקוצר של הסרט לא מופיע
מדובר על סרט שיש לו תקציר בשדות תקציר פסטיבל מקוצר

האירוע עצמו כרגע לא מפורסם. אבל עשיתי בדיקה גם כשהאירוע היה לפרסום וגם אז התקציר לא הופיע

**Comment by bruria1** [comment]
עודכן באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by bruria1** [comment]
הכל עודכן גם באתר לייב
