### ISSUE TITLE
intermediate solution to calendar issue

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#255]
@reasonat @bruria1 
 פותחת טיקט חדש ומעתיקה לכאן את הבקשה שלנו מ #48 

Ok, so until there is a solution for calendar problem, would it be possible to
use the mobile calendar on desktop.

The only needed adjustment at the moment is to change the column width to
650-750 pixels, while keeping the day pager on top as is.

**Comment by reasonat** [comment]
Closing this issue and focus on 48. No need for another one.
