### ISSUE TITLE
festival dedicated menu - calendar link - desktop / mobile

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#256]
@bruria1 
ברוריה את זוכרת שבאחד הדיונים שלנו אמרת שכשנעלה את קלנדר הפסטיבל יהיו למעשה שני קישורים
אחד לדסקטופ ואחד למובייל
וכשגולשים במובייל הלינק של הדסקטופ יהיה מוחבא וההפך?
בתפריט הראשי אין בעיה
אבל במגה תפריט נשמח אם יהיה אפשר לעשות את הפעולה הזו
קראנו לקישור בעברית
לוח הקרנות
ובאנגלית
schedule

**Comment by bruria1** [comment]
1. אין צורך לרשום בקישורים את הקישור המלא. מספיק לרשום את הכתובת שבאה אחרי השפה. למשל בהפנייה ללוח ההקרנות מספיק לרשום בקישור:
festival-calendar
2. כרגע יש קישורים ללוח במובייל וללוח בדסקטופ. כל אחד מוצג היכן שאמור להיות מוצג.
3. ממה שאני רואה אם נותנים קישור המכיל כבר את היום הראשון של הפסטיבל. זא קישור בצורה הזו:
festival-calendar/2017-07-13
ולא רק:
festival-calendar
ההגעה לדף מהירה יותר. אז אולי כדאי לעדכן את הקישורים (את כל ה-4, שניים בכל שפה)

**Comment by JerusalemCinematheque** [comment]
מעולה 
תודה
