### ISSUE TITLE
Fesitival calendar - Hebrew - Add to calendar and Ticket issues

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#257]
Hebrew Festival calendar
Add to calendar is missing from the display.  
Ticket buttons arn't working.

**Comment by sato2004** [comment]
@reasonat It is a problem with js aggregate, and I can't find fast solution for this. I turned off js aggregate, and now it is working. @yakoub Do you have some idea about this?

**Comment by yakoub** [comment]
i suspect the problem happens whenever we clear-cache which will generate a new aggregate js file but it gets interrupted for some reason and the aggregation is not complete .
but i need to investigate more, because this error doesn't persist so i didn't debug it .

**Comment by yakoub** [comment]
i enabled js aggregation again, but i don't see the error .
so again the problem doesn't persist so i can debug it .
lets keep aggregation on, and when you encounter it again i 'll be able to examine it .

**Comment by JerusalemCinematheque** [comment]
this seems to happen if you enter the calendar through jff.org.il/he/festival-calendar and then through changing the days
if you go to another day by changing the url to the date then the buttons work
but then when you choose a different day through the days navigation system then the buttons 
don't work again
also if you go to http://jff.org.il/he/festival-calendar/2017-07-13 the buttons don't work but if then you navigate to a different day through the days navigation bar the buttons do work

**Comment by JerusalemCinematheque** [comment]
I don't know what js aggregate does, but can you turn off js aggregate until a solution is found?
We have to have the calendar working and selling tickets tomorrow, as it is the busiest tickets selling day

**Comment by JerusalemCinematheque** [comment]
we checked every day and it seems that some days are working and some are not
not working
13/7
14/7
15/7
18/7
19/7
22/7

then i cleared browser cache
and now the 23/7 isn't working either

**Comment by JerusalemCinematheque** [comment]
and if i am logged in then everything works just fine

**Comment by yakoub** [comment]
i turned off aggregation .

**Comment by JerusalemCinematheque** [comment]
everything works now
thank you

**Comment by navotb** [comment]
Thank you Yakoub.
Is there any risk in turning it off?

**Comment by yakoub** [comment]
it will increase load over the server, since js will be loaded in separate files instead of one big file .

**Comment by navotb** [comment]
Is there a way to prevent overload?

**Comment by sato2004** [comment]
@reasonat I fixed some problems with jquery and turned on aggregation. Everything looks ok now.

**Comment by reasonat** [comment]
Re-Test and it looks fine. Reopen if needed.
