### ISSUE TITLE
festival calendar notes don't appear on the calendar page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#258]
@reasonat @bruria1 
הכנו את הקלדנר נוט הזה ל-13.7.17
http://www.jff.org.il/he/node/10730/edit

אבל התכנים לא מופיעים בקלנדר עצמו

**Comment by bruria1** [comment]
ממה שאני רואה זה מופיע..
אולי עניין של קאש?

**Comment by reasonat** [comment]
Reopen this issue and close this one - https://github.com/Reasonat1/Cinema/issues/272

**Comment by bruria1** [comment]
לבדיקתכם

**Comment by JerusalemCinematheque** [comment]
יופי תודה

**Comment by JerusalemCinematheque** [comment]
סליחה לא שמתי לב
אבל תראי כאן
http://jff.org.il/en/node/10785/edit?destination=admin/calendar-notes-manager
יש שלושה אייטמים שהוספנו
בפרונטאנד של הקלנדר של ה-16.7 צד אנגלית מופיעים רק שניים מהאירועים
http://jff.org.il/en/festival-calendar/2017-07-16

**Comment by bruria1** [comment]
זאת כיוון שלאייטם השלישי אין תמונה.

**Comment by reasonat** [comment]
Closing the issue. Please reopen if needed.
