### ISSUE TITLE
Festival calender - add to my list jump

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#259]
@reasonat 
לחיצה על הוספה / הסרה של אירוע לרשימה שלי בעמוד קלנדר פסטיבל גורמת לעמוד לעלות מחדש או לקפוץ למעלה
מצורף וידאו
https://www.youtube.com/watch?v=2q2F4svdjOc

**Comment by sato2004** [comment]
fixed

**Comment by reasonat** [comment]
Test again and looks good.  Closing this issue. Reopen if needed.
