### ISSUE TITLE
mobile festival calendar - calendar note appears on every day

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#260]
@reasonat @bruria1 
הקלנדר נוט שהקמנו בשביל ה-13.7 (צד עברית) מופיע בכל ימי הקלנדר במובייל
ואף ״מחק״ קלנדר נוט שהקמנו בשביל ה-16.7

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
יופי
