### ISSUE TITLE
shopping cart behavior when shopping on home page - hebrew side

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#262]
@yakoub @reasonat 
On hebrew side of the site
we established that when anonymous user adds items to shopping cart, pressing on cart icon opens toptix purchase window
this works fine when user is inner pages
but if user adds items on home page or goes back to home page, pressing on cart icon opens the register/log-in toptix window

https://www.youtube.com/watch?v=t7TNjVVq1t0

also when user is logged-in to toptix and has items in shopping cart, but presses on cart icon while on home page what opens is toptix user page and not the basket page

**Comment by yakoub** [comment]
לא הצלחתי לשחזר הבעיה .

נא לספק צעדים מסודרים שמובילים לבעיה .

**Comment by JerusalemCinematheque** [comment]
נכנסתי לעמוד הבית בצד עברית
גללתי למטה ולחצתי על כפתור הכרטיסים מאחד הסרטים שמפורסמים בעמוד והוספתי כרטיס לסל הקניות
סגרתי את חלונית הרכישה והמשכתי לשוטט בעמוד
לחצתי על עוד כפתור כרטיסים והוספתי עוד כרטיס לסל הקניות
סגרתי את חלונית הרכישה
ביקשתי לחזור לסל הקניות ולכן לחצתי על אייקון סל הקניות
במקום שתיפתח חלונית סל הקניות נפתחה חלונית הרשמה לטופטיקס
ואם כבר הייתי לוגאין לטופטיקס, נפתחה חלונית עמוד המשתמש ולא חלונית סל הקניות 

וגם אם שוטטתי באתר ועשיתי את פעולות הוספת כרטייסם לסל הקניות
ואז חזרתי לעמוד הבית ולחצתי על אייקון סל הקניות
נפתחה חלונית הרשמה

כאמור כל זה קורה רק מעמוד הבית בעברית

**Comment by reasonat** [comment]
שחזרתי את הצעדים ואני לא נתקל בבעיה הזו. 
באף אחד מהתרחישים

**Comment by yakoub** [comment]
this is same problem as #139, so it got fixed as well .
