### ISSUE TITLE
getting notifications to users add to calendar action

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#263]
@reasonat 
קיבלתי היום למייל שלי את אישור קבלת "שלח לקלנדר שלי" של משתמש באתר
וזה נראה כאילו אני שלחתי את הזימון ליומן של המשתמש

![image](https://user-images.githubusercontent.com/26960693/27993262-42a12860-64af-11e7-8420-889368e01e73.png)

**Comment by reasonat** [comment]
לא ברור

**Comment by JerusalemCinematheque** [comment]
אני לא יודעת עוד איך להסביר את העניין הזה
נבות אמר שגם רואים את זה באנליטיקס שהמייל שלי מופיע בכל פעם שמישהו משתמש בתוסף

**Comment by navotb** [comment]
http://addtocalendar.com/atc/google?utz=180&uln=en-US&vjs=
1.5&e[0][date_start]=2017-07-18%2020%3A30%3A00&e[0][date_
end]=2017-07-18%2022%3A30%3A00&e[0][timezone]=Asia%
2FJerusalem&e[0][title]=%D7%9E%D7%A0%D7%A9%D7%94&e[0][
description]=&e[0][location]=Cinematheque&e[0][organizer]=
tamarf&e[0][organizer_email]=tamarf%40jer-cin.org.il

אלו אירועים מהאנליטיקס של "add to calendar", אתה יכול לראות שמוטמע בהם משום
מה organizer email.

**Comment by reasonat** [comment]
@sato2004 As far as I see on the widget site, this is how it works no?

**Comment by sato2004** [comment]
@reasonat We can change this address to any other

**Comment by JerusalemCinematheque** [comment]
So it has to be an actual adress? We can't change it to just "Jerusalem Cinematheque"

**Comment by sato2004** [comment]
Done

**Comment by reasonat** [comment]
Please check

**Comment by JerusalemCinematheque** [comment]
nope.
look at this email i got
![image](https://user-images.githubusercontent.com/26960693/28617362-bc3f60e0-7208-11e7-8629-976d6654d32d.png)

**Comment by reasonat** [comment]
אני לא מצליח להבין מה הבעיה. 
תוכלו לנסות להסביר שוב?

**Comment by JerusalemCinematheque** [comment]
משום מה המייל שלי התברג לתוך מערכת שליחת אירועים לקלנדר האישי של המשתמשים
אני לא יודעת מה זה אומר מבחינת המשתמשים, אבל אני פעם ב מקבלת נוטיפיקציה למייל של משתמשים באתר ששלחו אירועים לקלנדר שלהם

**Comment by reasonat** [comment]
See @sato2004 comment days before
https://github.com/Reasonat1/Cinema/issues/263#issuecomment-314748831

**Comment by JerusalemCinematheque** [comment]
i know, but i still got this email-notification

**Comment by reasonat** [comment]
אני פשוט לא מצליח להבין את הבעיה. 
אלכס כתב לכם האם יש רצון להחליף למייל אחר וממה שאני מבין זה אמור לפתור את הבעיה לא?

**Comment by JerusalemCinematheque** [comment]
יכול להיות שזה פתר, אין לי מושג
אם יקרה שוב נעדכן

**Comment by reasonat** [comment]
ok, so I close this issue for now
