### ISSUE TITLE
home page galllery pictuers jump

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#264]
@bruria1 @reasonat 
שימו לב לוידאו המצורף
https://www.youtube.com/watch?v=AKy5A6RIgUI

לחיצה על אחת מתמונות הגלריה גורמת לעמוד לקפוץ למסך ריק
זה לא קורה כל הזמן אבל מספיק כדי שמשתמשים חיצוניים ישימו לב

**Comment by bruria1** [comment]
תוכלו לבדוק האם זה כבר לא קורה באתר פיתוח?

**Comment by JerusalemCinematheque** [comment]
זה נראה לי בסדר

**Comment by JerusalemCinematheque** [comment]
עוד לא עבר לחי נכון?

**Comment by bruria1** [comment]
עודכן בלייב
