### ISSUE TITLE
Calendar note 13.7 - problem with display after update

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#266]
@bruria1 
עידכנתי את 
http://jff.org.il/he/node/10725

ועכשיו בקלנדר ב-13.7 החלק של הנוטס השתבש
![image](https://user-images.githubusercontent.com/26960693/28019924-40a89cb4-658b-11e7-9f9b-cc4b885ad9b5.png)

**Comment by bruria1** [comment]
מה משובש? הכל נראה לי טוב..

**Comment by reasonat** [comment]
גם אצלי הכל בסדר

**Comment by JerusalemCinematheque** [comment]
אני חושבת שזה אותו עניין כמו #267

**Comment by reasonat** [comment]
לא חושב שזה קשור אחד לשני. 
סוגר את הכרטיס הזה.
