### ISSUE TITLE
festival calendar - update time

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#267]
@reasonat 
משום מה לוקח לקלדנר הפסטיבל זמן ממושך להתעדכן
אם זה בסימון של כפתור  כרטיסים שסומן כ"אזל"
או אם זה בהקרנות נוספות שהוספנו
לדוגמא ה-23.07
האירוע 
http://jff.org.il/he/event/10764
לא מופיע בקלנדר בצד עברית, למרות שהוא כן מופיע בצד אנגלית
ושהאולם בו האירוע מתקיים גם כן מופיע
![image](https://user-images.githubusercontent.com/26960693/28026809-d484735e-659f-11e7-8598-d062e4d32528.png)

והאירוע
jff.org.il/en/node/10135
מסומן בפופ-אפ כסולד אאוט אבל בקוביית האירוע כפתור הכרטיסים עדיין פעיל
![image](https://user-images.githubusercontent.com/26960693/28026760-bcb390ca-659f-11e7-93a1-8cbc6a25a509.png)

**Comment by reasonat** [comment]
למה הכוונה לוקח לו זמן להתעדכן? הייתי בטוח שהיינו בדיון הזה ושצריך לנקות קאש. 
את האירוע בעברית אני רואה. 
ובעניין האירוע אני לא מבין מה הבעיה. נראה שבאולם 2 יש כרטיסים ובאולם 3 נגמר המלאי. לא?

**Comment by navotb** [comment]
סליחה על השאלה הסתמית: איזה קאש צריך לנקות? של הדפדפן?

2017-07-11 14:30 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
@sato2004 Can you reply tot his question?

**Comment by JerusalemCinematheque** [comment]
הכוונה היא שלוקח לאתר  מספר שעות לעדכן את עמוד הקלנדר (לדוגמא האירוע שהוספנו ב-23.7 הופיע רק בעשר בלילה)
אם זה בכרטיסים שאזלו
אירועים חדשים שמתווספים
או בדוגמא שכתבתי למעלה שהאירוע מתעדכן בצד אחד של האתר, אבל לא בצד השני

לעומת זאת אזלו כרטיסים מתעדכן מייד בעמודי הסרטים, אירועים, לובי
המקום היחיד שלוקח זמן רב עד שרואים את העדכון זה עמוד הקלנדר

זה נראה לי קצת מוזר שצריך לנקות את הקאש של האתר אחרי כל עדכון, במיוחד שמידע זה מתעדכן במקומות אחרים

**Comment by navotb** [comment]
אמיר
זה נשמע כמו בעיה בתהליך הבניה של עמודי הקלנדר עצמם
נבות

2017-07-11 14:35 GMT+03:00 JerusalemCinematheque <notifications@github.com>:

**Comment by reasonat** [comment]
ניקוי קאש נידון בטיקט אחר פה הקשור בביצועי לוח השנה. 
זה נשמע לי אותו הדיון בדיוק. 
ביצענו שם הליך שמירת קאש בכדי לשפר ביצועים אז זה לא מוזר שצריך לנקות קאש לאחר מספר עדכונים.

**Comment by navotb** [comment]
אני מבין. אבל אנחנו מציעים שאחרי הפסטיבל נסתכל על תהליך יצירת העמודים כדי
לזרז את הטעינה ולפתור את בעיות העדכון האלו

2017-07-11 14:50 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by navotb** [comment]
סגור אבל מה עם עמודי הקלנדר? צריך לטפל בענין זמן התגובה והעדכון שלהם, עכשיו
כשנגמר הפסטיבל.

**Comment by reasonat** [comment]
יש משימה הקשורה בביצועים באתר
לא קשור לפה

**Comment by navotb** [comment]
יש עניינים שקשורים לביצועים באתר בכללי,אבל העמודים האלו דורשים פתרון
ספציפי, תשווה את זמן התגובה של העמוד הזה ביחס לעמודים אחרים, יש כאן בעיה.
