### ISSUE TITLE
facebook code

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#268]
@yakoub 
please upload Facebook code to site (jercin/jff)

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;9b568c0b9fdc4cf393a90acedd7fb398:F40796437.A948692&#x2F;pixel+facebook.txt">pixel facebook.txt</a>

**Comment by yakoub** [comment]
[pixel facebook.txt](https://github.com/Reasonat1/Cinema/files/1140047/pixel.facebook.txt)

**Comment by yakoub** [comment]
done

**Comment by reasonat** [comment]
Closing the issue. Please reopen if needed.

**Comment by JerusalemCinematheque** [comment]
[facebookExtraCode.txt](https://github.com/Reasonat1/Cinema/files/1211833/facebookExtraCode.txt)
@yakoub 
because of facebook new guidlines we need to update the facebook code and add the code attached that was sent to the current code
here are the instructions we got

To authorize multiple pages:
•       Copy the Open Graph markup tag for each Page
•       Place each Open Graph markup tag between the <head> tags in your website's HMTL
<meta property="fb:pages" content="52999780846">

**Comment by yakoub** [comment]
@JerusalemCinematheque 
done
