### ISSUE TITLE
home page - editing operation not working on hebrew side

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#269]
@bruria1 @reasonat 
מנגנון הוספת נודס בעמוד הבית פסטיבל צד עברית הפסיק פתאום לעבוד
הייתי באמצע הוספת נודס בחלק של הגלריה ואחרי מספר הוספות כשביקשתים להוסיף נוד החלונית נפתחת
אפשר לעשות חיפוש
אבל לחיצה על הוספה לא סוגרת את החלונית
ואי אפשר להוסיף את הנוד הנבחר

זה קורה רק בצד עברית. צד אנגלית עובד כרגיל

**Comment by JerusalemCinematheque** [comment]
עכשיו גם בצד אנגלית

**Comment by JerusalemCinematheque** [comment]
מבינים עכשיו שיש הגבלה על מספר האייטמים שאפשר להעלות
תוכלו בבקשה להגיד לנו מה המגבלה
והאם אפשרי שלא תהיה מגבלה כזו

**Comment by bruria1** [comment]
לא אמורה להיות מגבלה.
תוכלו לומר לי איפה ניסיתם לעלות ולא עבד?

**Comment by JerusalemCinematheque** [comment]
תנסי עכשיו להעלות עוד תוכן לא משנה איפה בעמוד
ברגע שהעלינו 24 פריטים בסך הכל בעמוד אנחנו לא יכולים להעלות עוד אייטמים

**Comment by bruria1** [comment]
איפה? בעמוד הבית?

**Comment by JerusalemCinematheque** [comment]
כן
אחרי שמוסיפים 24 פריטים
כשפותחים את חלונית החיפוש להוספת סרט / אירוע
עושים חיפוש
מוצאים את הפריט המבוקש
ולוחצים על הוספה
החלון נתקע ואי אפשר להוסיף את האייטם
אם מוחקים פריט ואז מוסיפים אחר במקומו אז אין בעיה, כי "התפנה" מקום

**Comment by reasonat** [comment]
@yakoub Please review comments and check.

**Comment by sato2004** [comment]
I can't reproduce this bug, I added more then 24 items, and everything looks good

**Comment by JerusalemCinematheque** [comment]
We didn't have an issue on jer-cin side
but on JFF live site we do
As soon as we tried to add more than 24 items the window to select film/event/homepage content/article would get stuck

**Comment by JerusalemCinematheque** [comment]
please try to add film or event content to jer-cin homepage hebrew side now
we have 24 items on the hebrew side of the homepage
can't add any more items

**Comment by sato2004** [comment]
Yes, now I see the problem

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
ok
