### ISSUE TITLE
Event - Event and Movie navigational arrows

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#27]
See design to understated how it should look like. 
There need to be a navigation arrow on each movie/event/group movie/ article when a user arrive to the node from a Lobby. 
The logic should be
- The navigation should be base on the Lobby I came from. So the order should be the Lobby order. 
- If the Lobby order changed by editor (a-z/date/so on) the the nav should be according. 

כאשר אני מגיע מלובי ונכנס לאייטם יהיה דפדפוף בין האייטמים לא משנה מה הם - לובי / אירוע / סרט / מקבץ - כלומר הדפדפוף יעבור בין הנודים השונים כפי שיתקיימו בלובי. 
http://www.wrike.com/open.htm?id=142580585

An updated design of movie, event, movie group  pages now include navigational arrows with special properties.

we are talking about prev\next links that are included into the default panel panes of those content types as a custom pane. they do not always appear on the page though. when user navigates to an event page from 1 of the calendar views or from 1 of the lobby (term) content panes (they are both still being built) - then they should appear.
I think  this module https://www.drupal.org/project/views_navigation should do the trick for this requirement.
What we need is that if a user enter an event page from lobby term page or from a link in calendar  pane, then the prev\next arrows will provide ability to navigate the original order of nodes in the panes user navigated from. 
So if I see a calendar of todays events and I click on an event, the next arrow will lead to the next event in the calendar and the previous to the 1 before it in the calendar.
If I see a lobby term with 6 content items in it, and I click on 1 of them, then the navigation will be for the prev\next items from that lobby term view. 
Lobby can include items from different content types (article, webform, movie group, people CT or even another lobby term). so we want a way to include those navigational arrows pane on all of the different panel of those page types, but only show it if user access the page from the lobby context.

First fulfill this requirement only for calendar panes, then after reviewing that they work we will continue to fulfill this for the lobby term pane as well.

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;aaee819614f8400c8814479c49bfb0ba:F35289829.A948692&#x2F;Event_arrows.png">Event_arrows.png</a>

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Ricky Thomas What is status of this one? If it&#39;s need to be review please update the status. <br />

**Comment by reasonat** [comment]
➤ Ricky Thomas commented:
&#64;Tom Meir  &#64;Amir Taiar It is not finished yet, the views_navigation module is not working , so I am creating a custom module that&#39;s why It take time. Any way It will be complate by today.<br />

**Comment by reasonat** [comment]
➤ Tom Meir commented:
&#64;Ricky Thomas please pause work on this task. move to other tasks. this task is not important enough for the upcoming live date. &#64;Amir Taiar  <br />especially if you plan on using custom code.<br />

**Comment by reasonat** [comment]
➤ Tom Meir commented:
implelentation does not fulfill the task requirements, time here is waisted. moving task to phase 2 of project. <br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko I am trying to QA this while entering this event http://dev.jff.reasonat.com/en/movie/892 fromt his Lobby http://dev.jff.reasonat.com/en/lobby/panorama but cant see any nav arrows. <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar I&#39;ve updated dev.jff.reasonat.com (working with jer-cin.reasonat.com before)<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer You can start front end this according to the design. <br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko Since we want to go live with jer-cin.reasonat.com please remove this from this enviorment and keep only on dev site<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar I&#39;ve deleted custom navigation module from jer-cin.reasonat.com<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Alex Voloshchenko איפה ניתן לראות את זה?<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Bruria Helfer http://dev.jer-cin.reasonat.com/en/lobby/children-cinema-club-1 from here open any movie<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

אני צריכה לדעת איך זה צריך להתנהג כאשר המסך קטן ואין מקום לחץ שעולה על העמודה השמאלי. ובכלל האם במסכים קטנים זה אמור להופיע? מובייל?<br />

**Comment by JerusalemCinematheque** [comment]
אנחנו יכולים לראות איך זה נראה בתצוגה מלאה?
אולי אז נוכל לענות על השאלה של ברוריה

**Comment by bruria1** [comment]
@sato2004 אתה יכול להחזיר שיראו את זה?

**Comment by sato2004** [comment]
Go from here http://dev.jer-cin.reasonat.com/en/lobby/5-days-june to any event, and you will see the arrows next, prev

**Comment by bruria1** [comment]
מחכה לתגובתכם..

**Comment by reasonat** [comment]
@bruria1 The link isnt working and there is no hover effect as needed.

**Comment by reasonat** [comment]
ok sorry. @JerusalemCinematheque @navotb , @bruria1 was waiting for you to say what to do in 13inch screens since arrows are over the body area. We will push this and Roei and Bruria will find a solution.

**Comment by bruria1** [comment]
יש פה אפשרויות כיצד לעצב את זה:
1. ברוחב שבו החיצים כמעט עולים על התוכן הם יעלו מעל קופסת התוכן ומתחת לקופסת ההקדמה עם רווחים מינימאלים מעל ומתחת
2. ברוחב שבו החיצים כמעט עולים על התוכן הקופסת של השיתופים בצד ימין תרד מתחת לקופסת התוכן
עדכנו אותי איך תרצו ואבצע

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb This wait for your response

**Comment by JerusalemCinematheque** [comment]
אלו ההערות שלנו על ממשק הדפדוף
1. מיקום החצים – החצים צריכים לשבת על גבולות גריד האתר, כלומר קווי ההמבורגר / ואייקון החלפת שפה, ובגובה של פרטי הסרט
2. החצים צריכים להיות סטיקי
3. אפשר להוסיף לחצים איזשהו רקע
            מקור ההשראה: https://goo.gl/Gjz7xY 
4. צריכים להופיע שם האירוע + שם הסרט (אלא אם הם אותו הדבר)
5. אנחנו רוצים לוודא שגם מופיעים תאריכי האירוע
6. החצים גם צריכים להיות קליקבילים, לא רק כותרת האירוע
6. משום מה ברגע שמתחילים לדפדף, מופיע מתחת לאזור התמונה מצד שמאל כותרת הסרט בצבע האתר
5. בתצוגה ריספונסיבית אולי הכי נכון שהחצים יישבו מתחת לטבלת הקרדיטים, כלומר שיהיו הדבר האחרון בעמוד או שישבו מתחת לתמונה
7. כששם הסרט/אירוע ארוך לחתוך אותו לשתי שורות או יותר אם צריך
  
![image](https://user-images.githubusercontent.com/26960693/28664004-a50231fe-72c7-11e7-80f2-2f3d6b5f7186.png)

8. שצבע פונט "האירוע" יהיה שחור ולא צבע האתר
9. קרה לנו מספר פעמים שהתחלנו לדפדף ואחרי מספר עמודים הדפדוף הפסיק להופיע
9. הדפדוף אמור לעבוד גם בלובי של סרטים, ולא רק של אירועים
10. הגיון הדפדוף:  אם נכנסים דרך לובי - דפדוף בלובי לפי הסדר של כל לובי (א-ב, תאריך יצירה, תאריך הקרנה)
                        אם נכנסים דרך קלנדר – דפדוף לפי סדר כרונולוגי
11. האם המנגנון קיים גם בצד עברית לבדיקה?

**Comment by bruria1** [comment]
תבדקו כעת בבקשה:
1. בוצע
2. החיצים לא יכולים להיות סטיקים אם הם יושבים במקום מסויים. אם רוצים הם יכולים להיות סטיקים ולהופיע תמיד נניח באמצע המסך
3. בוצע
4. בוצע
5. האם תאריכי האירוע אמורים להופיע גם בחיצים???? עמוס מאוד
6. בוצע
7. בוצע
8. זה בעיה. כי בעצם רואים את הכותרת רק במעבר עכבר. ואם במובייל ייראו תמיד זה מאוד יעמיס על הדף. מציעה להוריד את החיצים במובייל לגמרי.
9. בוצע
8. בוצע

לגבי סעיפים 9-12 @sato2004 יגיב

**Comment by JerusalemCinematheque** [comment]
2. נניח לזה
5. כן, יכול להיות רק תאריך ושעה. לא צריך אולם.
8. אבל באיזה גודל תצוגה מורידים את החצים? כי לדוגמא כשאני מסתכלת בתצוגה של אייפד, רואים את החצים, אבל שום דבר לא קורה בהם - אין מעבר של העכבר והם לא קליקבילים
9. יש כאן עדיין בעיה של תוצגה כששם האירוע ארוך
![image](https://user-images.githubusercontent.com/26960693/28751811-b90c3f38-7519-11e7-86bc-27774b794d24.png)

תוספת לבעיות בתפקוד
יכול להיות שיש בעיה בדפדוף כשנוד מקושר ליותר מלובי אחד פעיל ואז חצי הדפדוף נעלמים. ראו וידאו
https://www.youtube.com/watch?v=9WgbfY9iz80

יכול להיות שיש בעיה כשמגיעים לנוד האחרון בלובי ואז לא ניתן לראות דפדוף אחורה. ראו וידאו
https://www.youtube.com/watch?v=_mOBQgOVF_k

אם עושים לעמוד ריפרש מאבדים את הדפדוף

**Comment by bruria1** [comment]
3. הוספתי תאריך. האם הוא צריך להופיע רק כאשר הוא עתידי?
4. תסתכלי עכשיו. זה קליקבילי, אבל באיזשהו שלב זה לא נראה טוב. אני מציעה להוריד את החיצים בתצוגה של 780 פיקסלים ומטה.
5. סידרתי.

ברגע שהעיצוב יהיה מוכן אנא רכזו את כל בעיות התפקוד בטיקט אחר על מנת שאלכס יטפל בהם.

**Comment by JerusalemCinematheque** [comment]
3. כן. נשמח אם התאריך יופיע מעל כותרת האירוע, בבולד ואם אפשר להוסיף פייפ בין התאריך לשעה
שאלה שלא קשורה לדפדוף, אבל קשורה לתצוגה של תאריכים עברו והעלינו אותה מספר פעמים, אבל לא זוכרת איפה השיחה נעצרה. האם זה בעייתי שהתאריך יישאר בעמודי לובי ובעצם בכל מקום חוץ מעמודי הסרטים עצמם ועמודי לובי של סרטים? כלומר גם בעמודי האירועים לדוגמא? 

4. אפשר להראות לנו אולי איך זה יראה עם חצים למטה, אחרי כל התוכן

הערה חדשה
החצים עולים על ההאדר בגלילה


לגבי צד עברית, אני לא יודעת אם זה קשור לתפקוד או לפרונטאנד
אבל החצים הפוכים, קדימה צריך להיות בצד שמאל ואחורה בצד ימין

**Comment by reasonat** [comment]
המשימה הזו לקחה הרבה הרבה מעבר לתכנון ולהציג כעת את החצים בחלק התחתון בצורה נכונה יקח עוד שעתיים של עבודה בערך. מצטער, אני לא יכול לאפשר את זה.

**Comment by bruria1** [comment]
לגבי התאריך סידרתי את התצוגה שלו.
לגבי הדרישה הנוספת של תצוגת תאריכים בכל מיני מקומות באתר אנא העלו על זה טיקט נפרד.

אני לא רואה שהחיצים עולים עלההדר..
לגבי צד עברית - סידרתי

**Comment by JerusalemCinematheque** [comment]
![image](https://user-images.githubusercontent.com/26960693/28872502-28c9de3c-7792-11e7-8100-22eb8e4b9fd2.png)

אפשר שהרווח בין התאריך לכותרת אירוע ולכותרת סרט יהיה אותו הדבר
זה נראה שכותרת האירוע קצת צמודה מידי לתאריך

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
