### ISSUE TITLE
Ticket button on festival calendar does not disappear at scheduled time

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#270]
@reasonat @yakoub 
the tickets button is supposed to disappear on the festival calendar when scheduled on event page
this does not happen
http://jff.org.il/en/node/10501 (the samourai)
was scheduled to end tickets sales on 14.7 at 15:00
it is now 15:25 and the ticket button is still operative
![image](https://user-images.githubusercontent.com/26960693/28212227-14eec92e-68a9-11e7-8c5a-50e3da410d13.png)

it only disappears when site clears cache

**Comment by reasonat** [comment]
Then it another clear cache issue/non-issue. As said before Festival calendar page need cache clear to display changes. I am closing this issue since this is already discussed several time at other issues.

**Comment by JerusalemCinematheque** [comment]
i clear the cache on a daily basis
sometimes even more than once
it's strange that we have to clear cache every hour all day long

**Comment by reasonat** [comment]
You have to clear cache upon site content update - which is multi time a day, I know. 
I will talk with Yakoub about this tomorrow
