### ISSUE TITLE
Frontpage items doesn't display when they don't have end publish dates

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#271]
@bruria1 @reasonat 
עמודי תוכן מסוג פרונטפייג' הפסיקו להציג את התוכן שלהם
לדוגמא:
http://jff.org.il/he/10017

דחוף מאוד

**Comment by bruria1** [comment]
בעמוד הספציפי הזה לא הזנתם תאריכים לסיום המקטע ולכן שום דבר לא מוצג.
הוספתי תאריך וכעת הוא מוצג.

**Comment by JerusalemCinematheque** [comment]
אוקיי, אבל אני הכנסתי להכל תאריכים הבוקר אחרי שראיתי שזה הפסיק להציג את התכנים
אין לי מושג למה עכשיו התאריכים לא מופיעים
גם עד הבוקר לא היתה בעיה של תצוגה. גם ללא התאריכים

**Comment by JerusalemCinematheque** [comment]
האם אפשר לקבוע שאם לא הוזן תאריך סיום תצוגה האייטם ממשיך להיות מוצג?

**Comment by reasonat** [comment]
הייתה בקשת פיתוח שלא להציג אייטם במידה והתאריך סיום אינו מוזן. כעת לשנות את זה יקח משך פיתוח שאין

**Comment by JerusalemCinematheque** [comment]
זה היה נראה לי עוד לפני שהיו לנו עמודים מסוג זה
האם אפשר אז לעדכן את לוח השנה של בחירת טווחי התאריכים?
זה קצת מלחיץ אותי שהוא רק עד דצמבר 2020

**Comment by bruria1** [comment]
כעת אפשר עד 10 שנים קדימה

**Comment by reasonat** [comment]
Closing this issue. Reopen if needed.

**Comment by JerusalemCinematheque** [comment]
אפשר לעשות את השינוי של הקלנדר בכל המקומות בהם הוא מופיע?
עמודי לובי
עמודי אירועים?
לפתוח על זה טיקט חדש?

**Comment by bruria1** [comment]
אתם מדברים על הגדרת התאריכים 10 שנים קדימה?
בוצכ בכל שדה של תאריך בלובי ובאירוע

**Comment by JerusalemCinematheque** [comment]
מצויין תודה
