### ISSUE TITLE
Sold Out button display

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#273]
@reasonat 
התצוגה של כפתור הסולד אאוט השתבשה 
הכיתוב סולד אאוט מתפצל על שתי שורות מה שגורם לכפתור להיראות שונה מכפתור הכרטיסים הרגיל
![image](https://user-images.githubusercontent.com/26960693/28247826-2572b38e-6a41-11e7-9d9a-e778ed329137.png)

**Comment by reasonat** [comment]
אני לא רואה את הבעיה הזו. 
באיזה רזולוציית מסך? האם התצוגה על 100%?

**Comment by bruria1** [comment]
טופל כבר. לכן אתה לא רואה את זה..

**Comment by JerusalemCinematheque** [comment]
רק נשארה בעיה בפופ-אפ
![image](https://user-images.githubusercontent.com/26960693/28315388-d7ef9dac-6bc6-11e7-8ea2-85fc6f5c46c9.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
יכול להיות שהכפתור בפופ-אפ גדול מידי?\
גם של סולד אאוט וגם הכרטיסים
אפשר לראות בתמונה שיש הבדל בגדלים בין הכפתור בפופאפ והכפתור בקוביית האירוע
![image](https://user-images.githubusercontent.com/26960693/28500455-5c6ca3a0-6fd1-11e7-8d7d-fcf4c2a9ddb9.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
