### ISSUE TITLE
homepage extra text - same font weight display

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#274]
@bruria1 

אפשר בבקשה לסדר כך שהפונט של ההום פייג' טקסט תמיד יהיה במשקל קל, כמו שהוא מופיע כשהוא מגיע מעמוד סרט
בתמונה  המשקל הנכון הוא זה שבגריד מצד שמאל, לעומת המשקל המלא יותר של האייטמים מצד ימין ובאמצע
יכול להיות שהבעיה רק בתצוגת גריד
![image](https://user-images.githubusercontent.com/26960693/28262611-4bbffdde-6aec-11e7-997a-58ea4c829e3d.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
