### ISSUE TITLE
apostroph in language select widget

### ISSUE THREAD

**Issue by navotb** [Reasonat1/Cinema#275]
While trying to find language 
צ'כית
the widget could not find it, directly, After adding only first letter 
צ, 
could select it from list of option. However, upon selection the value at the widget is: 
צ&#039;כית (88)
and not with the apostroph.

**Comment by navotb** [comment]
following up on this issue, see the difference while searching for ג'ייקוב היינה
he is not returned in the results for some reason.

**Comment by reasonat** [comment]
@sato2004 This might be same issue like https://github.com/Reasonat1/Cinema/issues/277 please have a look

**Comment by yakoub** [comment]
fixed .

note for @sato2004  : check plain was used on matches array which escapes the character "`" and it match doesn't latter on .
check_plain is needed only on labels which are displayed in html but data keys don't need check_plain

**Comment by yakoub** [comment]
@reasonat this is not same as #277, this is custom coding and not entityrefence module .

**Comment by reasonat** [comment]
ok. Thanks

**Comment by navotb** [comment]
Thank you !
