### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#276]
@reasonat 
קיבלתי את הודעת השגיאה הזו מספר פעמים הבוקר
אני לא בטוחה מתי זה קורה
![image](https://user-images.githubusercontent.com/26960693/28310397-0e632690-6bb5-11e7-8d29-4e1661ad3fcb.png)

**Comment by JerusalemCinematheque** [comment]
ועוד אחת
![image](https://user-images.githubusercontent.com/26960693/28311939-fd3673ae-6bb9-11e7-9ac7-30d33135da2e.png)

**Comment by yakoub** [comment]
this is normal behavior, it happens when you click several times on widget that calls ajax without waiting for the ajax to complete .
nothing to fix here .
