### ISSUE TITLE
person selection widget

### ISSUE THREAD

**Issue by navotb** [Reasonat1/Cinema#277]
while trying to select ג'ניפר קונלי
after clicking ג'ני  the result is
![image](https://user-images.githubusercontent.com/5830669/28314431-36b370ec-6bc3-11e7-907e-80dca023056e.png)

but after clicking ג'ניפ the results are:
![image](https://user-images.githubusercontent.com/5830669/28314476-5e10e958-6bc3-11e7-924a-996b503e7395.png)

do you have any idea why it cuts our ג'ניפר קונלי??

**Comment by yakoub** [comment]
information for developers :

credits auto complete is a view : admin/structure/field-collections/field-cm-movie-credits/fields/field_cm_movie_credits_person

bio auto complete is generic : admin/structure/field-collections/field-person-bio/fields/field_person_bio_name

auto complete code happens in module entityreference under plugin/selection
and called from entityreference.module line 1108

i created menu entry yakoub_test_ref/% in module cm_extra which simulates the query of autocomplete plugin class .
example : dev.jer-cin.org.il/yakoub_test_ref/ג'ני

**Comment by yakoub** [comment]
@navotb while working on this the problem disappeared and connelly appears also after continuing the name .
but i wrote in above comment information about the mechanism behind the autocomplete, and if problems happen again we can continue examining it .

**Comment by navotb** [comment]
Thank you!
