### ISSUE TITLE
credits in film collection page when the film is both festival and jercin

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#278]
@bruria1 
כשסרט שייך לדומיין סינמטק ופסטיבל ויש לו קרדיטים שמסומנים ל"לא לתצוגה בצד סינמטק" והוא משוייך למקבץ בסינמטק
הקרדיטים שמסומנים לא צריכים להופיע בעמוד המקבץ
לדוגמא
http://jer-cin.org.il/en/movie-group/11404
הסרט "ביקור בית" כל הקרדיטים חוץ צ
dir
סומנו לא להצגה בצד סינמטק
במקבץ פה הם כן מופיעים

**Comment by bruria1** [comment]
@yakoub 
זה הקוד שנכתב בהבט הזה:
http://dev.jer-cin.org.il/en/admin/structure/views/view/movie_group_ct/edit/panel_pane_1
בשדה: php
אמור להראות רק את מה שבעריכה של זה:
http://jer-cin.org.il/en/movie/3221
לא נבחר: hide from cinemateqe
באיזור בקרדיטים.

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
fixed on DEV or live?

**Comment by sato2004** [comment]
fixed on both. dev and live

**Comment by JerusalemCinematheque** [comment]
do i need to clear site cache to see the change?
because look at this link
http://jer-cin.org.il/en/movie-group/11404

the first film "house call" shows all the credits even though most of them are marked as hide from cinematheque site

**Comment by sato2004** [comment]
Check it now please

**Comment by JerusalemCinematheque** [comment]
ok
