### ISSUE TITLE
Content not visible on site

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#279]
@reasonat 
אנחנו לא בטוחים מה בדיוק קרה עכשיו,
אבל לא היה אפשר לראות את התוכן של האתר בפרונטאנד
זה לדוגמא איך שנראה המגה תפריט
![image](https://user-images.githubusercontent.com/26960693/28424557-966ac350-6d76-11e7-8240-df17732239c4.png)

בעמוד הבית ועמודים פנימיים ראו רק את ההדר והפוטר
![image](https://user-images.githubusercontent.com/26960693/28424594-ac6a3e6a-6d76-11e7-9afa-88cd84001ea7.png)

עשיתי ניקוי של הקאש של האתר ועכשיו זה בסדר
אבל נשמח אם תבדקו מה קרה

**Comment by bruria1** [comment]
המסך היה ריק?
לא הבנתי מה בדיוק קרה..

**Comment by JerusalemCinematheque** [comment]
כן בדיוק
לא היה אפשר לראות את התוכן של האתר
חוץ מכותרות של פרונטפייג' ואת לוח ההקרנות

**Comment by reasonat** [comment]
For this isn't happening again, and looks like for you as well. Reopen if needed.
