### ISSUE TITLE
homepage grid view - event title display is missing

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#280]
@bruria1 
בעמוד הבית בתצוגת גריד לא מוצגת כותרת האירוע
לדוגמא כרגע בצד עברית סינמטק
בקוביה של גנוב על העולם
אמורה להיות הכותרת
המצאות עתידניות מהסרטים

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
אוקיי
רק שאם כותרת האירוע וכותרת הסרט אותו הדבר אז רק כותרת הסרט מוצגת

**Comment by bruria1** [comment]
כן. זה היה באמצע.. עכשיו אמור להיות טוב

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
יש עדיין עניין בתצוגת גריד כשמדובר רק באירוע ללא סרט מקושר
כותרת האירוע מופיעה פעמיים
ראי בתמונה עם הכותרת סקאר זכאי
למעשה אם מדובר באירוע ללא סרט מקושר, כותרת האירוע אמורה להופיע כמו כותרת סרט
![image](https://user-images.githubusercontent.com/26960693/28751684-d5860444-7516-11e7-9859-afef663d6201.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
Ok
