### ISSUE TITLE
film details view on event page - responsive

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#281]
@bruria1 
בעמוד אירוע בריספונסיבי פרטי הסרט לא נמצאים בגבולות הגריד של העמוד אלא נכנסים קצת פנימה. פרטי הסרט צריכים להיות באותם קווי הגריד כמו פרטי האירוע והקרדיטים
![image](https://user-images.githubusercontent.com/26960693/28561057-96f00094-7125-11e7-97c2-893e8d4d6194.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
