### ISSUE TITLE
Add option to embed Iframe into text areas

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#282]

**Comment by navotb** [comment]
האם אי אפשר להוסיף לנו את האופציה להכניס תגיות הטמל של איפריים או אמבד בתוך
הטקסט אדיטור ? אם זה שובר את הרספונסיבי, תראו לנו מה הקוד המתאים כדי שזה
יתאים לכל המסכים

**Comment by bruria1** [comment]
הוספתי אופציה כזו בעורך תוכן. תראו אם זה טוב.

**Comment by JerusalemCinematheque** [comment]
איך משתמשים בזה?
מכניסים את קוד האייפריים או את הכתובת של העמוד?

**Comment by bruria1** [comment]
כתובת העמוד בלבד

**Comment by JerusalemCinematheque** [comment]
ניסיתי להכניס את העמוד הבא
http://webversion.net/4FC8DA374E91A60188DBE54307904ACC5CB68526F19727AE3281F40E70A160AF/show.aspx

כאן
http://jer-cin.org.il/he/node/12058/edit

כשאני עוברת למצב תצוגה לא רואים שיש תוכן בעמוד
אולי לא הבנתי איך להשתמש במנגנון

**Comment by bruria1** [comment]
אני לא רואה למה זה לא עובד בעורך תוכן.
האם זה יפתור את הבעייה אם יהיה שדה בסוג תוכן ניוזלטר שבו תוכלו להכניס את הכתובת של האייפרם? או שאתם צריכים את זה במקומות שוננים באתר?

**Comment by JerusalemCinematheque** [comment]
מה זה סוג תוכן ניוזלטר?

**Comment by bruria1** [comment]
אני לא רואה סוג תוכן כזה...

**Comment by JerusalemCinematheque** [comment]
כתבת בהערה הקודמת
האם זה יפתור את הבעייה אם יהיה שדה בסוג תוכן ניוזלטר
אז תהיתי אם זה סוג תוכן שקיים ואז אני אוכל לראות איך זה עובד ואם זה מתאים למה שאנחנו צריכים

**Comment by bruria1** [comment]
התכוונתי לסוג תוכן מאמר..

**Comment by JerusalemCinematheque** [comment]
אנחנו זקוקים לזה בעיקר בסוג תוכן מאמר, אבל לא רק
השאלה היא איך זה משתלב בתוך העמוד?
האם זה אומר שהעמוד מציג רק את האייפריים? או שאפשר לשלב שם תוכן נוסף?

**Comment by bruria1** [comment]
זה יהיה שדה שיופיע כשדה. לא ישפיע על שאר השדות בעמוד.

**Comment by reasonat** [comment]
לא ברור לי למה נעשתה פה עבודה. מדובר במשימה בהקפאה.

**Comment by navotb** [comment]
אמיר, אי אפשר להוסיף תגיות embd או iframe לטקסט אדיטור? אנחנו לא מבקשים
יותר, רק שהתגיות יעבדו

**Comment by reasonat** [comment]
אני לא רואה פה שיח על תגיות. 
תעדכן אותי? המשימה הזו מדברת על אמבד של אייפריים
אם יש בעיה עם התגיות אפשר לפתוח על זה משימה חדשה, זה לא קשור לפה.

**Comment by navotb** [comment]
אמבד של אייפריים בתוך כל עמוד, כדי שנוכל להכניס קליפ יוטיוב, גוגל מפס או
חוברות פידיאף וכו' - בקיצור כל מה שאפשר לאמבד אותו.
הדרך הכי פשוטה שהיינו משתמשים בה באתרים קודמים היא פשוט עם קוד iframe או
קוד אמבד. נדמה לי שברוריה הוסיפה את זה, אבל איכשהו האייפריים לא הופיע כמו
שצריך. אנחנו פשוט צריכים שזה יעבוד כקוד.

2017-08-09 13:51 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
בדיוק, וכמו כל בקשה באתר הזה, בקשה פשוטה יכולה להפוך למורכבת. זה לצערי. 
יש רצון, כמו במקרים אחרים, להוסיף אלמנטים ובקשות נוספות, אך כאשר אני רואה שהן נגררות אני נאלץ לעצור.

**Comment by navotb** [comment]
אבל אמיר, זה משהו שאמור להיות טבעי בתוך טקסט אדיטור, לא משהו שצריך לבנות
מאפס. היה לנו את זה באתרים הקודמים שהיו פי מאה פחות מתוחכמים.

2017-08-13 14:06 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
לא יודע מה ההיה באתרים קודמים, ולומר שזה אמור להיות בילדין בתוך אדיטור לא משהו שידוע לי. 
מה שאני כן יודע שבמקרה שלנו יש לזה השפעה שדורשת עבודה נוספת

**Comment by navotb** [comment]
אמיר, זה תג הטמל סטנדרטי, כך שעורך ההטמל אמור לקבל אותו. כרגע הוא חוסם
אותו, זה כנראה נובע מענין של הדרופל, ואנחנו מבקשים אם אפשר להסיר את החסימה
הזו.

2017-08-13 15:06 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
שוב, כפי שאמרתי, נגררנו פה כבר לשעות של עבודה. אחרת לא הייתי מקפיא את זה.

**Comment by navotb** [comment]
אז מה האופציות שלנו כרגע בהקשר הזה?

**Comment by reasonat** [comment]
נוכל לדבר במייל בנפרד על בקשות נוספות. כעת אנחנו כאמור הרבה מעבר למה שצריך לעשות.
