### ISSUE TITLE
homepage - one item - article - title font size

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#283]
@bruria1 
בעמוד הבית נראה שגודל הפונט של כותרת מאמר בתצוגת וואן אייטם קצת גדול יותר מגודל הפונט של סרט / אירוע / לובי
![image](https://user-images.githubusercontent.com/26960693/28663685-bc42c686-72c6-11e7-8e26-c49c47b12076.png)

**Comment by bruria1** [comment]
עודכן באתר פיתוח.
נעדכן בסוף היום את הסביבה החיה

**Comment by bruria1** [comment]
אנא אשרו

**Comment by JerusalemCinematheque** [comment]
ok
