### ISSUE TITLE
event page - Title Text from film page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#284]
@bruria1 @reasonat 
בעמוד אירוע עם סרט, הטייטל טקסט של התמונה המשוייכת לסרט לא מוצג בעמוד האירוע
ראו כאן את הטייטל טקסט של התמונה בעמוד הסרט
https://www.jer-cin.org.il/en/movie/6857

וכאן בעמוד האירוע של הסרט הוא לא מופיע
https://www.jer-cin.org.il/en/event/6858

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
