### ISSUE TITLE
film info line in event page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#285]
@bruria1 @reasonat 
בעמוד אירוע עם סרט, בשורת המידע שמופיעה מעל התקציר
מופיע פייפ מיותר כשאין מידע מאחד השדות
ראו כאן
https://www.jer-cin.org.il/en/event/6858

בעמוד הסרט לא מילאנו את השדה מדינה ושנה ועכשיו בעמוד האירוע יש פייפ מיותר לפני האורך
מה שלא קיים בעמוד הסרט
https://www.jer-cin.org.il/en/movie/6857

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
אני לא יודעת למה, כי כל השדות מלאים, אבל באירוע הזה יש פייפ מיותר
http://jer-cin.org.il/he/event/12180

**Comment by JerusalemCinematheque** [comment]
וכאן הפייפ בין האורך לשפות נעלם
http://jer-cin.org.il/he/event/11447

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
