### ISSUE TITLE
Event and Movie navigational arrows - technical issues

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#286]
@reasonat @sato2004 
רשימה של העניינים הטכניים שקשורים לדפדוף
1. הדפדוף אמור לעבוד גם בלובי של סרטים וגם דרך הקלנדר, ולא רק דרך לובי אירועים
2. הגיון הדפדוף: אם נכנסים דרך לובי - דפדוף בלובי לפי הסדר של כל לובי (א-ב, תאריך יצירה, תאריך הקרנה)
אם נכנסים דרך קלנדר – דפדוף לפי סדר כרונולוגי
3. קרה לנו מספר פעמים שהתחלנו לדפדף ואחרי מספר עמודים הדפדוף הפסיק להופיע
4. יכול להיות שיש בעיה בדפדוף כשנוד מקושר ליותר מלובי אחד פעיל ואז חצי הדפדוף נעלמים. ראו וידאו
https://www.youtube.com/watch?v=9WgbfY9iz80

5. יכול להיות שיש בעיה כשמגיעים לנוד האחרון בלובי ואז לא ניתן לראות דפדוף אחורה. ראו וידאו
https://www.youtube.com/watch?v=_mOBQgOVF_k

6. אם עושים לעמוד ריפרש מאבדים את הדפדוף

**Comment by sato2004** [comment]
On the dev site I added this block to movies and movie groups. Now it is work if in a lobby there are not only events, but movies and movie groups to. The order of navigation is the same as the order in a lobby.
Also this navigation work if you open an event from calendar or festival calendar.

**Comment by JerusalemCinematheque** [comment]
Lobby navigation

1. when navigating in lobby with films, next screening date of the film is missing
http://dev.jer-cin.reasonat.com/en/lobby/new-films-2

2. also need to make sure that the "next screening" is shown after the previous screening has passed

3. the navigation does not appear on hebrew side of lobby with films
http://dev.jer-cin.reasonat.com/he/lobby/%D7%A1%D7%A8%D7%98%D7%99%D7%9D-%D7%97%D7%93%D7%A9%D7%99%D7%9D-2

4. added screenings to films and now navigation arrows are hiding screening line. this seems to happen because screening line borders are messed up
http://dev.jer-cin.reasonat.com/en/movie/5449
![image](https://user-images.githubusercontent.com/26960693/28913849-27073a76-7842-11e7-99a7-8c681e409f13.png)

still need to make sure navigation arrows don't disrupt view of screenings on film/event page

Calendar navigation
1. navigation needs to continue to next day when navigation gets to last event of the day

2. on 23.6, on the second event of the day, the previous button does not show the title of the film attached - trainspotting - but just the event title
![image](https://user-images.githubusercontent.com/26960693/28913978-a1aae354-7842-11e7-839f-5d6a9c26dbd9.png)
it seems to be okay in other places

3. on 26.6 hebrew side, does not show the date and time of event with just a film title on the nest button
![image](https://user-images.githubusercontent.com/26960693/28914011-c48f1a48-7842-11e7-8811-1e3248bc5d16.png)
seems to be okay in other places

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
Lobby navigation

4. if there are more than two screenings this is still an issue
![image](https://user-images.githubusercontent.com/26960693/29249162-42782e52-8033-11e7-891b-97aef27da9ea.png)
also i don't know if it matters, but the screening line borders are wrong. this happened after the application of the browsing arrows. if this wont affect the live site, when navigation is transferred to live, then doesn't matter


Additional remark
when going to a translated page in a lobby, navigation is lost. for example if i browse through the films in this lobby
http://dev.jer-cin.reasonat.com/he/lobby/%D7%A7%D7%99%D7%A5-%D7%A2%D7%9D-%D7%94-national-theatre
and then in one of them move to English side, then you cant navigate any longer

**Comment by bruria1** [comment]
לגבי סעיף 4. האם כעת בסדר?

**Comment by sato2004** [comment]
About language change, this is true. Because if we changed the language, we moved to a new page (like not from lobby). If we need to have navigation when language is changed, I need to change a module.

**Comment by reasonat** [comment]
As for @sato2004 commetn. I don't approve this request. 
Wait for you to approve @bruria1 solve

**Comment by JerusalemCinematheque** [comment]
ok for 4
but isn't it better if the navigation buttons are always in the same place, under the screening lines?
if you browse through this lobby
http://dev.jer-cin.reasonat.com/en/lobby/new-films-2
you see that the placement of the arrows in the first item and the second item is not the same

**Comment by bruria1** [comment]
זה תמיד באותו מקום.. אלא אם כן אין תמונה  לעמוד.
אני לא רואה את הבעיה אולי?

**Comment by JerusalemCinematheque** [comment]
אוקיי אז  כנראה לכן זה נראה לי לא בסדר

**Comment by reasonat** [comment]
I am closing this issue. 
As for the new request I have opened and closed (Freeze) it here https://github.com/Reasonat1/Cinema/issues/297

**Comment by JerusalemCinematheque** [comment]
@reasonat when will this feature be on live site?

**Comment by reasonat** [comment]
@sato2004 will push this in the following days
