### ISSUE TITLE
festival term - adding front page content type

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#287]
@reasonat

 אנחנו צריכים שתהיה לנו אפשרות להוסיף בעמודי "פסטיבל טרם" גם תוכן מסוג פרונטפייג'
כך שנוכל להציג עמודים כמו זה
http://jff.org.il/he/10017

או זה
http://jff.org.il/he/10703

**Comment by bruria1** [comment]
כעיקרון אתם יכולים. איפה נתקלתם בבעיה שלא יכולתם?

**Comment by JerusalemCinematheque** [comment]
זה צילום מסך של חלונית הוספת נודס לפסטיבל טרם הנוכחי
פרונטפייג' הוא לא אחד מסוגי התוכן שאפשר לעשות עליהם חיפוש
![image](https://user-images.githubusercontent.com/26960693/29360527-09041e3c-828c-11e7-9bd6-3b57d7a770a1.png)

**Comment by bruria1** [comment]
אני לא רואה שיש תצוגה לאלמטים שמוסיפים בסקשיין של הפסטיבל טרם. זה אמור להיות ולא קיים?

**Comment by JerusalemCinematheque** [comment]
אני חושבת שהתצוגה תהיה ברגע שטווח התאריכים של הטרם יסתיים
כרגע כן הוא מפנה לעמוד הבית

**Comment by bruria1** [comment]
הוספתי את האפשרות להוסיף עמודים מסוג עמוד הבית. אפשר לראות את זה בעמוד הזה:
http://dev.jer-cin.org.il/he/festivals/2017

**Comment by JerusalemCinematheque** [comment]
מעולה
