### ISSUE TITLE
event page - toptix - does not transfer to translated page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#288]
@yakoub 
כשאנחנו מייבאים אירוע מטופטיקס מתוך עמוד אירוע
הפרטים של תחילת/סוף מכירת כרטיסים לא עוברת לצד המתורגם של האירוע
לדוגמא
צד אנגלית עם פרטי המכירה מטופטיקס
http://jer-cin.org.il/en/node/12179/edit

צד עברית ללא הפרטים
http://jer-cin.org.il/he/node/12180/edit

**Comment by yakoub** [comment]
@JerusalemCinematheque problem fixed .

note for developers @reasonat  : controlled by configuration checkbox in admin/structure/types/manage/cm_event
under tab "Synchronize translations" checkbox "Sale period"

**Comment by JerusalemCinematheque** [comment]
ok
