### ISSUE TITLE
date line of past events appearence

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#289]
@reasonat @bruria1 
we would like to **keep** the date line of past events in the following occurrences
1.        On the event page
2.        In lobby pages and front page content type (including homepage) when an event is attached to said lobby or front page content type
3.        In film box in lobby pages but...
In order to prevent the showing of newer events of the film, (1) show only events that are in the time frame of the lobby term dates and (2) don't cross between festival events and cinematheque events 
4.        As it is now in all calendar appearances
5.        In search results - show date line if results of an event. Do not show date line of past events if the result is of a film

**Do not keep** date line on film page

**Comment by reasonat** [comment]
יש כאן חזרה אחורה בדרישות לאחר שכבר נעשה שינוי לפי דרישה שלכם. מוקפא ונסגר
