### ISSUE TITLE
Cinematheque site - mini calendar icon does not work when browing through days

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#290]
@reasonat 
בצד סינמטק, כשהולכים קדימה/אחורה במיני קלנדר האייקון של השעון מפסיק לפעול
כלומר אי אפשר לסגור את המיני קלנדר מתוך האייקון
ואם סוגרים את המיני קלנדר על ידי לחיצה על כפתור "סגור"
אי אפשר לפתוח אותו מחדש על ידי לחיצה על האייקון

**Comment by reasonat** [comment]
I can approve strange behaviour like this. @bruria1 will check this out

**Comment by JerusalemCinematheque** [comment]
ואם חוזרים להיום, הכל עובד כמו שצריך

**Comment by reasonat** [comment]
Lets keep an eye on it. I leave this open. @bruria1 will be back from vac in few days

**Comment by bruria1** [comment]
תוקן. באתר פיתוח

**Comment by JerusalemCinematheque** [comment]
ok
