### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#291]
@reasonat 
עברנו עכשיו על תוכן מסוג טופס. אלו ההערות שלנו
זו הדוגמא שבה בשתמשנו
http://jer-cin.org.il/he/webform/12396

1. להתאים גודל כותרת טופס לגודל הכותרות באתר
2. אם אין תמונה, אז לא רואים את הכותרת של הטופס

3. להתאים ריווח שורות בודיטקטס לריווח השורות באתר

4. יש לרווח בין השדות של הטופס
5. המלבנים של השדות צריכים להיות עם קצוות מרובעים ולא עגולים

6. הטקסט בכפתור צריך להיות "שלח" ולא "חיפוש"
7. הכפתור בצד עברית צריך להיות מיושר לצד שמאל

8. בצד עברית אחרי כותרת שדה מופיע 
Your answer
זה צריך לעוף

9. confirmation page
צריך לעצב את העמוד. יכול להיות דומה לעמוד הודעה
בעמוד להוריד את האפשרות לחזור לטופס

10. שדה תאריך – האם אפשר שהשדות שמרכיבים את התאריך יופיע אחד ליד השני במקום אחד אחרי השני או לחילופין שהתאריך יופיע כשדה אחד שנבחר מתוך הקלנדר

11. האם יש אפשרות לסדר שדות אחד ליד השני במקום רק אחד מתחת לשני

12. אם מוסיפים שבירת עמוד הטקסט על כפתור העמוד הבא/הקודם בצד עברית צריך להיות בעברית ולא באנגלית

13. צריך לרווח בין כפתור העמוד הקודם לכפתור שלח

14. פס התקדמות – להעביר לסוף העמוד
בצד עברית שהטקסט יהיה בעברית
לשנות את הצבעוניות שלו לצבעוניות האתר

15. צריכים אופציה להוספת לוגואים

16. האם יש אפשרות להגבלת מילים בשדה

17. האם אפשר להוסיף גם שדה 
Selection dropdown

18. האם אפשר להוסיף שדה כתובת – כמו שיש בעמוד איש

19. להוסיף אפשרות להוספת טקסט באמצע הטופס

20. האם יש אפשרות להוסיף כותרת לחלק בטופס. לדוגמא כותרת
פרטים אישים
ואז השדות שצריך למלא

21. Select option
לא מובן איך מוסיפים בו את השדות לבחירה.
אם אנחנו מכניסים את השדה ב <> השדות לא מופיעים

22. נשמח להסבר מה זה
Fieldset
Grid
Markup

23. נצטרך עמוד ניהול טפסים

24. האם יש אפשרות לכפתור נפרד עבור "תשלום"

25. התוצאות לא מתקבלות במייל שהוגדר לטופס

26. להוסיף בעמוד תוצאות את כל השדות שקיימים בטופס

27. איך יוצרים דו"ח מהתשובות לטופס

**Comment by reasonat** [comment]
1-8 +12 - @bruria1 will take of. 
9 - We can't design this but to make it look just like simple page. 
10 + 11 + 14 - This is a frontend change to what already done. Cancel. 
15 + 16 + 17 + 18 + 19 + 20 + 24 - New request - Cancel. 
21 +22 - @bruria1 please answer this
23 + 26 - There is a submission page build in. We will not change the core behaviour. Cancel
25 - @bruria1 will check this
27 - What do you mean by report? xls output?

**Comment by JerusalemCinematheque** [comment]
we never discussed this content type
we understand that somethings cannot be changed, but ask for some of the issues to be reconsidered. the way some of these field look - like date - does't make any sense
or the progress line - the start and finish are in english. and it's green.
15. as we never discussed this content, we would appreciate adding this component that exist in other pages to this page too
16. needed
19. for example, if we don't have a different button for toptix payment, how would you suggest that we inform user that at this time a payment popup will appear. or if we need to add a description that has nothing to do with the fields
23. we can't have a form management page like we do with other content types (film/event/person)?
26. what can we change on this page? the columns now are date of submission, user (which is only related if submitter is also a registered user of the site), i.p. address (not really sure why we need this), and action buttons
27. yes. xls output of each submission and of all the submissions together.

**Comment by bruria1** [comment]
http://dev.jer-cin.org.il/he/webform/8840
כל שינויי העיצוב בוצעו באתר פיתוח
1-8 12 בוצע 
21. באופן הזה:
1|DCP
2|פרורז
3|אחר
עדכנתי בטופס תוכלו לראות כעת
22. fieldset - ליצור שדות כקבוצה - אפשר לראות דוגמה הטופס בדיקה
grid - זה ליצור  מטריצה - אני לא חושבת שתזדקקו לזה פה...
Markup - אם אתם רוצים לרשום איזשהו טקסט בטופס
25. האם תוכלו לבדוק כעת?

**Comment by reasonat** [comment]
15. זה לא סוג תוכן רגיל, זה טופס, להוסיף שדה כזה יקח זמן רב של פיתוח. 
16. מבין, אבל זה לא בסקופ כלל ודורש זמן פיתוח שאני לא יכול לאשר. 
19. אתם יכולים לכתוב בתוכן שמקדים לטופס שזה טופס שמוביל לקנייה של כרטיס. 
23+26. אפשר, כמובן. אבל זה יקח זמן פיתוח רב שאני לא יכול לאשר. 
27. יש אפשרות לייצא את כל התוצאות מטופס אחד ולא תוצאה בודדת. כמו כן לא ניתן כמו שזה כעת לייצא את כלל התוצאות מכלל הטפסים יחד

**Comment by JerusalemCinematheque** [comment]
6. הכפתור צריך להיות עם קצוות מלבניים כמו השדות
25. האם זה אמור להגיע במיידי? כי אם לא אז זה לא עובד

הערה חדשה
אם יש לטופס מספר עמודים גם הכפתור
previous page
בצד עברית צריך להיות בעברית

**Comment by bruria1** [comment]
6 - סידרתי
7 - סידרתי
הערה חדשה - תורגם

**Comment by JerusalemCinematheque** [comment]
7 האם אני לא מקבלת את הטפסים המלאים למייל שלי כי אני ממלא אותם מאותו אי.פי?
מה לגבי עמוד הנחיתה אחרי מילוי הטופס? האם אפשר לתת לו קצת יותר ניראות של האתר? להכניס אותו לגבולות הגריד. להגדיל את הפונט? שהרפרנס "חזרה לטופס" יהיה בצד עברית בעברית?

**Comment by bruria1** [comment]
האם באופן כללי אתם מקבלים מיילים מהאתר?
לגבי עמוד הנחיתה עדיף שתצרו לבד עמוד נחיתה ותפנו את הטופס אליו.

**Comment by JerusalemCinematheque** [comment]
מהצור קשר כן. אבל זה לא ממש מגיע מהאתר כי זה פותח תיבת מייל

**Comment by bruria1** [comment]
לא הבנתי את הערה האחרונה..

**Comment by JerusalemCinematheque** [comment]
אין לנו מקום באתר שממנו נשלח מייל ישירות מהאתר
אז אין לי תשובה לשאלה
האם באופן כללי אתם מקבלים מיילים מהאתר?

**Comment by bruria1** [comment]
@yakoub

**Comment by reasonat** [comment]
אני מנסה להבין מה לא סגור פה. 
נושא קבלת המיילים מהמערכת כלל לא קשור למשימה הזו ואפשר לפתוח משימה חדשה ולהסביר קצת יותר ברור במה מדובר.

**Comment by JerusalemCinematheque** [comment]
אין בעיה נפתח
