### ISSUE TITLE
Search domain access settings

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#292]
[https://www.wrike.com/open.htm?id=142672742https://www.wrike.com/open.htm?id=142672742](https://www.wrike.com/open.htm?id=142672742)

* Display only results of nodes which set to festival in the domain access field AND DONT display results form jer-cin domain. 

**On jer-cin:**

* Display only results of nodes which set to jer-cin in the domain access field AND DONT display results form jff domain. 

**On Freeze: 
On jer-cin:** 

* Display results from both domain. 
* When user click on a node which set to ONLY festival link to the festival site.

**Comment by sato2004** [comment]
Need review

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Waiting for you to check

**Comment by reasonat** [comment]
CLosing this issue. Open if needed
