### ISSUE TITLE
home page - gallery - tickets button

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#295]
@reasonat @bruria1 
בעמוד הבית בחלק של הגלריה
מתי שהתמונות מתחלפות כפתור הכרטיסים הופך להיות לא פעיל
לדוגמא עכשיו
כשנכנסים לעמוד הבית בתמונה הראשונה יש כפתור כרטיסים ואם מייד לוחצים עליו אין בעיה
אבל אם מגיעים אליו אחרי שהעברנו אייטמים עם החצים או אחרי המעבר האוטומטי שלהם אי אפשר ללחוץ על הכפתור

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
ok
