### ISSUE TITLE
jercin calendar when event has no film attached

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#296]
@reasonat @bruria1 
בקלנדר סינמטק כשיש אירוע שהוא רק אירוע ללא סרט מקושר
האירוע מופיע בקלנדר ללא הבוקסה הלבנה
![image](https://user-images.githubusercontent.com/26960693/29666793-7bedf60a-88e2-11e7-8a22-568148051dde.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
