### ISSUE TITLE
marking festival edition and lobby in film page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#298]
**Update description:** 
On movie pages, at the tags block area, add: 
- The festival term which this movie refer to - Exclude current festival and display only past festival (Base on the date setting in the festival term form). 
- The Loby this movie is related to. 

@reasonat 
היו לנו מספר שיחות בנושא סימון מהדורה ולובי בעמוד סרט
שבתחילה חשבנו שיהיה כתוב בעמוד הסרט הוקרן במסגרת פסטיבל [שנה] ושם הלובי לא שוייך

אנחנו מציעים שהסימון יופיע כתגיות בסרט באיזור של התגיות
תגית אחת טרם הפסטיבל
תגית שנייה הלובי אליו הסרט שוייך

כאשר תגיות אלו יופיעו כשטווח התאריכים של טרם הפסטיבל חלף

**Comment by reasonat** [comment]
תגית שהלובי אליו הסרט מקשר - איך זה קשור לטווח תאריכי הפסטיבל? 
זה אומר שהתגית פסטיבל תופיע רק בפסטיבלים שהסתיימו ולא הנוכחי

**Comment by JerusalemCinematheque** [comment]
זה נראה לי ברור שהסרטים שמוצגים עכשיו בפרונט של האתר הם סרטים של המהדורה הנוכחית
ואם נוסיף להם כבר עכשיו את התגיות האלו, זה מידע כפול מיותר

**Comment by reasonat** [comment]
אחלה. 
עדיין לא קיבלתי מענה לשאלה הראשונה.

**Comment by reasonat** [comment]
@sato2004 Please see update description

**Comment by sato2004** [comment]
Done

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Waiting for you to check

**Comment by JerusalemCinematheque** [comment]
הוספת סימון איזה לובי מוצג כתגית ואיזה לא 

התגית תופיע ללא קשר לטווח התאריכים של הלובי / המהדורה

תגית לובי תוצג לפי הדומיין אליו היא משוייכת – כלומר אם לובי סומן כדומיין פסטיבל הוא לא יוצג בעמוד הסרט כשזה מוצג בצד סינמטק ולהפך
	https://jer-cin.org.il/he/movie/9278
	https://jff.org.il/he/movie/9278
	א – ת וגאלה משוייכים לדומיין פסטיבל
	סרטים חדשים משוייכים לדומיין סינמטק
	כל התגיות מופיעות בשני הדומיינים

תג הלובי צריך להופיע גם בעמוד האירוע של סרט שמשוייך ללובי
	https://jer-cin.org.il/he/event/16026
	הסרט "סוף טוב" משוייך ללובי סרטים חדשים
	בעמוד האירוע של הסרט הלובי לא מופיע כתגית

אם אין תגית לא צריך להופיע הפס השחור 
	https://jer-cin.org.il/he/movie/15879

התגית לא צריכה להשפיע על הריווח בחלק של התקציר והקרדיטים כאשר התקציר קצר 
	https://jer-cin.org.il/en/movie/15940
	
תגית מהדורת פסטיבל – יש להוסיף לעמוד ניהול מהדורה שדה > שם מקוצר למהדורה שיופיע כשם התגית.
	https://jff.org.il/he/movie/9076
	התגית תופיע לדוגמא כפסטיבל 2017 במקום השם המלא

להוסיף ללובי שמשוייך לדומיין פסטיבל תגית מהדורה

**Comment by reasonat** [comment]
Divide into several tasks and closing this one. Notice some of them wait for Bank hours
1. https://github.com/Reasonat1/Cinema/issues/316 
2. https://github.com/Reasonat1/Cinema/issues/317 
3 + 4. https://github.com/Reasonat1/Cinema/issues/315 
5. https://github.com/Reasonat1/Cinema/issues/318 
6. https://github.com/Reasonat1/Cinema/issues/319 - Not clear.
