### ISSUE TITLE
Main calendar - links don't work on Hebrew side

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#299]
@reasonat @bruria1 
לא ניתן להיכנס לאירועים השונים מתוך עמוד הקלנדר הראשי צד עברית
הכותרות והתמונות לא קליקבילים

**Comment by reasonat** [comment]
Tested and this works well. 
What browser? 
Are you login as admin?

**Comment by JerusalemCinematheque** [comment]
seems to be okay now
