### ISSUE TITLE
Arrow navigation doesnt work if user is not logged in

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#300]
@reasonat 
נראה שאם משתמש לא מחובר לאתר, פיצ'ר הניווט בתוך לובי ומתוך הקלנדר לא עובד
כשאני כן מחוברת, אז רואים את הפיצ'ר והוא פועל כמו שצריך

**Comment by reasonat** [comment]
האם אנחנו מדברים פה על כפתורי הניווט החדשים בין אירועים ובין סרטים אליהם מגיעים מלוגבי / קלנדר?

**Comment by JerusalemCinematheque** [comment]
כן

**Comment by sato2004** [comment]
I can't see the problem

**Comment by JerusalemCinematheque** [comment]
it seems the issue in now only for events when entering through the mini calendar

![image](https://user-images.githubusercontent.com/26960693/30595950-61b8b8be-9d5b-11e7-9f02-c4a6d46fbcd7.png)

the print screen is from an event I entered from the mini calendar, as you can see there are no navigation arrows

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
does not work when entering events from mini calendar from the home page
but when entering events from mini calendar when opening from other pages it does work

**Comment by reasonat** [comment]
Strange. This is the same view. @sato2004 please have a look

**Comment by sato2004** [comment]
I've checked in all browsers what I have, and I don't see the problem

**Comment by JerusalemCinematheque** [comment]
sending you videos of the issue
https://www.youtube.com/watch?v=mFAwH6cxBOw

https://www.youtube.com/watch?v=OJNW7czSTz8

**Comment by sato2004** [comment]
Fixed.
If there is still the problem, try clearing the cookies for the site jer-cin.org.il (or open new incognito window)

**Comment by JerusalemCinematheque** [comment]
works great
