### ISSUE TITLE
Navigation Arrows in Small Screens (mobile)

### ISSUE THREAD

**Issue by navotb** [Reasonat1/Cinema#301]
Navigation Arrows are visible on small screens, and disrupt display. If we remember correctly we have agreed not to have the arrows on small screens.

**Comment by JerusalemCinematheque** [comment]
זה נראה שזה קורה רק כשנכנסים לאירועי דרך הקלנדר הגדול

**Comment by reasonat** [comment]
I canr remember this agreement - So, should we remove nav functionality from mobile?

**Comment by JerusalemCinematheque** [comment]
yes

**Comment by sato2004** [comment]
done

**Comment by JerusalemCinematheque** [comment]
ok
