### ISSUE TITLE
Event assignment validation

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#302]
We need to create validation to the event management page. 
http://jer-cin.org.il/he/admin/events-manager and
http://jff.org.il/he/admin/events-manager
Which are the same view.. 

**The main idea is to prevent multiple events on the same:**
Hall 
AND/OR 
the same screening date & time 
AND/OR 
the same Technical comment. 

**We might have a problem with Technical comment which is text field and I guess it should have been taxonomy.** 
**So I suggest:** 
- In case there is a conflict events line should be highlighted in a background color.

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Do we even need this?

**Comment by JerusalemCinematheque** [comment]
yes. it's not just time conlict, we also discussed techical conflicts
We should probably have a conversation about this issue

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Notice that we might have issue with the technical field. 
Did you already populated this field in multiple nodes? 
Does this field will contain repeatable technical comments - This way we could make it taxonomy. 

Anyway, @sato2004 might handle the existing field type.

**Comment by JerusalemCinematheque** [comment]
can you please clarify this remark?

**Comment by sato2004** [comment]
@reasonat  This notification should only be in this view? or should it be anywhere else?

**Comment by reasonat** [comment]
@sato2004 Only in this view - Both jff & her-cin

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Technical comment is text simple field which I am afraid can't be used for the functionality we are looking for.
So, I was wondering wether you have populated this field in the event nodes already ot not?

**Comment by sato2004** [comment]
done

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Please check this

**Comment by JerusalemCinematheque** [comment]
@reasonat 
מצרפים קובץ אקסל עם פירוט הדו"ח הרצוי עבור פריט מסוג סרט
[reportsfromWebsite_film.xlsx](https://github.com/Reasonat1/Cinema/files/1659474/reportsfromWebsite_film.xlsx)

**Comment by reasonat** [comment]
@JerusalemCinematheque ממה שאני מבין זה לא קשור למשימות אלא לנושא הדוחות
האם אני צודק?

**Comment by JerusalemCinematheque** [comment]
אכן
מקווים לשלוח בימים הקרובים גם את הפירוט עבור דו"ח אירועים

**Comment by reasonat** [comment]
I have opened this task - https://github.com/Reasonat1/Cinema/issues/320 
and closing this one. 
For the event report open a new task please
