### ISSUE TITLE
getting notifications from site after form is filled out

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#303]
@reasonat 
מערכת הטפסים מאפשרת לקבוע נמען לקבלת תוצאות טפסים מלאים
עשיתי טסט עם כתובת המייל שלי
מילאתי את הטופס
לחצתי על שלח
אבל לא קיבלתי את הטופס עם התשובות למייל שלי

האם זה קשור לכך שהטופס ותיבת המייל יושבים על אותו איי.פי?

**Comment by reasonat** [comment]
בהחלט יש סיכוי. 
באיזה טופס ניסית?

**Comment by bruria1** [comment]
אני לא יודעת...
מבדיקה שלי המיילים הגיעו לתיבה שלי.
אולי הגיע לספאם?

**Comment by JerusalemCinematheque** [comment]
בניתי את הטופס הזה
http://jer-cin.org.il/he/webform/13792

בכתובת הדוא"ל שמתי את 
DanielaT@jer-cin.org.il

מילאתי טופס לדוגמא והוא לא הגיע לתיבת הדוא"ל הזו

אולי אני עושה משהו לא נכון בהגדרות?

**Comment by JerusalemCinematheque** [comment]
הוספתי עכשיו כתובת של ג'ימייל ושם מקבלים את הטופס
אבל כתובת של הסינמטק לא

**Comment by reasonat** [comment]
@sato2004 This seems like yet another server email issue. CAn you check this?

**Comment by sato2004** [comment]
@reasonat I've changed some server's settings. It needs testing.

**Comment by JerusalemCinematheque** [comment]
seems to be working
will let you know if we encounter any further problems

**Comment by reasonat** [comment]
ok
