### ISSUE TITLE
Navigation Arrows are onstructing tickets button

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#305]
@bruria1 @reasonat 
הי, 
שימו לב שבמסכים של לפטופ, כלומר מסכים קטנים יותר, חצי המעבר מפריעים ללחיצה על כפתור הרכישה
מצרפת סרטון
https://youtu.be/LoxbO5vnXHM

**Comment by bruria1** [comment]
אמור להיות בסדר עכשיו

**Comment by JerusalemCinematheque** [comment]
נראה שזה בסדר
ביקשתי ממי שהביא את העניין לתשומת ליבנו לבדוק גם. אז אם משהו ישתנה נעדכן

**Comment by reasonat** [comment]
אחלה, אפשר לפתוח שוב את הפנייה
