### ISSUE TITLE
New TAG MANAGER 

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#306]
[tag body.txt](https://github.com/Reasonat1/Cinema/files/1410906/tag.body.txt)
[tag_head.txt](https://github.com/Reasonat1/Cinema/files/1410910/tag_head.txt)

@reasonat @yakoub 
מצורפים קודים  של 
TAG MANAGER 
האם אפשר בבקשה להטמיע באתר בכל העמודים?
 
קובץ HEAD יש להדביק לאחר פתיחת תגית <head>
קובץ BODY יש להדביק לאחר פתיחת תגית <body>

**Comment by JerusalemCinematheque** [comment]
@reasonat 
אמיר אנא תעביר לנו בבקשה הצעת מחיר עבור טיפול בנושא זה

**Comment by JerusalemCinematheque** [comment]
יש חדש?

**Comment by sato2004** [comment]
@JerusalemCinematheque 
I see google tag already exists with Id GTM-PWXMSPL. Should I replace it with a new one?

**Comment by JerusalemCinematheque** [comment]
closing threat
no need to replace old one
thank you
