### ISSUE TITLE
button shape

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#307]
![ticket button](https://user-images.githubusercontent.com/26960693/33010539-84823902-cde3-11e7-8d58-489d2b66ccb2.jpeg)
 משהו השתנה בצורה של כפתור הכרטיסים
הוא היה מלבן עם זוויות ועכשיו הוא מופיע כמלבן עם קצוות מעוגלים

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

אני לא רואה את זה.. האם זה עדיין?

**Comment by reasonat** [comment]
@JerusalemCinematheque Please test again

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Bruria Helfer Please change to Need review and not to waiting for client.

**Comment by reasonat** [comment]
I am closing this issue, reopen if needed.
