### ISSUE TITLE
google search results for front page - domain issue

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#308]
07/06/2018
**For Jer-cin domain**
**2. Upload** the file to http://jer-cin.org.il/
**3. Confirm** successful upload by visiting [http://jer-cin.org.il/google3e25f1f7e91b6693.html ](http://jer-cin.org.il/google3e25f1f7e91b6693.html)in your browser.
**4. Click** Verify below.
To stay verified, don't remove the HTML file, even after verification succeeds.

**for jff** 
**2. Upload** the file to http://www.jff.org.il/
**3. Confirm** successful upload by visiting [http://www.jff.org.il/google3e25f1f7e91b6693.html ](http://www.jff.org.il/google3e25f1f7e91b6693.html)in your browser.
**4. Click** Verify below.

@reasonat 
כיוון שלא קבענו שיוך לדומיין לחלק מהעמודים נוצרת בעיה בחיפוש בגוגל
לדוגמא הקמנו עמוד מסוג פרונט פייג' שנקרא פסטיבל הקולנוע היהודי 16-21.12.2017
כל הפריטים שמקושריםלעמודי המשנה בעמוד זה משוייכים לדומיין סינמטק

כשעושים חיפוש בגוגל "פסטיבל הקולנוע היהודי", מקבלים תוצאה שמובילה לעמוד בדומיין הפסטיבל במקום דומיין הסינמטק
ובגלל שכל הפריטים שבתוך עמודי המשנה משוייכים לדומיין סינמטק, לא ניתן לראות אותם
זה העמוד שמקבלים בתוצאות החיפוש
https://www.jff.org.il/he/13791
שמוביל ל
https://www.jff.org.il/he/15014
שמוביל לעמוד השגיאה הזה
https://www.jff.org.il/he/movie/14781

מה אפשר לעשות עם זה?

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;c3f1fe377f134409a25410c7eea63410:F62500856.A948692&#x2F;google3e25f1f7e91b6693.html">google3e25f1f7e91b6693.html</a> | <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;5ad0ccdac28f48c999182e5056d2a154:F62501022.A948692&#x2F;google3e25f1f7e91b6693.html">google3e25f1f7e91b6693.html</a>

**Comment by reasonat** [comment]
אני לא מצליח לשחזר את הבעיה. 
לאחר החיפוש אני מגיע לעמוד 
https://www.jff.org.il/he/13791
ושלושת פריטי המשנה בעמוד מובילים לעמודים הנכונים בפסטיבל

ובלי קשר, אני מניח שאם יש עמוד שצריך להיות גם וגם אז אפשר לשייך אותו גם וגם

**Comment by JerusalemCinematheque** [comment]
אבל אם תנסה להיכנס לפריטים בתוך עמודי המשנה תגיע לעמודים ריקים
https://www.jff.org.il/he/movie/14781

אלו לא עמודים שאמורים להיות גם וגם, אלא סוגי תוכן שלא ניתן לעשות להם כרגע שיוך לדומיין ועל כן נוצרת הבעיה

**Comment by reasonat** [comment]
אני לא מבין על מה מדובר. 
צעד אחר צעד בבקשה

**Comment by JerusalemCinematheque** [comment]
עשיתי חיפוש בגוגל של פסטיבל הקולנוע היהודי
התוצאה הגבוהה יותר שמקבלים מהאתר מפנה לעמוד שמשוייך לדומיין פסטיבל
https://www.jff.org.il/he/13791
נכון בעמוד הזה ובפריטים שמקושרים אליהם רואים את העמודים כמו שצריך ואין איתם שום בעיה
אבל הפריטים שמקושרים לסאב-פריטים של עמוד התוצאה משוייכים לדומיין הסינמטק 
כך שאם לדוגמא אחרי עמוד התוצאה "פסטיבל הקולנוע היהודי" תלחץ על הפריט הסרטים
https://www.jff.org.il/he/15014
ואז תלחץ על פריט שנקרא "סרט הפתיחה"
https://www.jff.org.il/he/movie/14781
תגיע לעמוד ריק כי נוד 14781 משוייך לדומיין סינמטק אבל העמוד שהגעת אליו הוא עם הכתובת של הפסטיבל

**Comment by reasonat** [comment]
הבנתי
מדובר על מקרה קצה מאד וזה יהיה בבנק שעות
אני יכול להעריך את העבודה סביב 3-5 שעות, אולי פחות, אולי יותר. 
אנחנו למעשה צריכים להגדיר מצב בו כל קישור, לא משנה מהו, והיה והוא תחת פסטיבל יקבל את הקישור לפסטיבל גם אם הנוד אינו מוגדר כלל תחת פסטיבל.

**Comment by JerusalemCinematheque** [comment]
לא יהיה יותר פשוט להכניס שיוך דומיין לכל סוגי התוכן?

**Comment by reasonat** [comment]
אבל במקרה שציינת למשל מדובר בסרט בו יש למיטב זכרוני כבר שיוך דומיין
אני טועה? 
בעיקרון, הטענה שלך נכונה אבל זה אומר עבודה ידנית שלכם ואז מקרה קצה כזה יוביל לעמוד שגיאה

**Comment by JerusalemCinematheque** [comment]
זה נראה לי שהבעיה כאן נובעת מזה שעמוד המקור "פסטיבל הקולנוע היהודי" לא משוייך לדומיין ולכן התוצאה הראשונה שולחת לדומיין הפסטיבל
אם העמוד היה משוייך לדומיין זה לא היה נותן תיעדוף בתוצאות לדומיין הסינמטק?

**Comment by reasonat** [comment]
אני לא יכול לומר. יכול להיות. 
יכול להיות שמה שצריך להיות פה זה בכלל עבודה של מקדם אתרים מול גוגל שידע ללמוד להציג נודים בצורה יותר רלוונטית. 
למה בעצם עמוד המקור לא משוייך לשום דומיין?

**Comment by JerusalemCinematheque** [comment]
כי אין בעמוד מסוג פרונט פייג' שדה שיוך לדומיין

**Comment by reasonat** [comment]
אוקיי
זה עדיין לא יפתור את הבעיה

**Comment by reasonat** [comment]
צריך להחליט באיזה גישה מתקדמים פה
1. הוספת שדה שיוך לדומיין לכל סוגי התוכן כך שאולי גוגל יוכל לחבר אותם ישר לדומיין הנכון. זה יצריך גם עבודה של מקדם אתרים כמובן בכדי שיעבוד נכון. 
2. המערכת תדע לשייך סרט לדומיין סינמטק במידה והוא מופיע תחת לובי / אירוע / עמוד הבית / כל רשימה אחרת, באתר פסטיבל. זה סעיף פיתוח ארוך בהרבה מן הסתם.

**Comment by JerusalemCinematheque** [comment]
אז הגישה הראשונה כן יכולה לתת מענה לבעיה הזו?
אני לא ממש מבינה את הגישה השניה, תוכל להסביר שוב?

**Comment by reasonat** [comment]
הגישה הראשונה יכולה אולי לתת מענה. אני לא איש קידום ולכן לא יודע. 
הגישה השנייה מדברת על ממשק בו אם למשל יצרת קישור מתוך פסטיבל, בעמוד רשימה כלשהו, לעמוד סינמטק, הקישור יהיה באמת לעמוד סינמטק ולא לעמוד פסטיבל כדי למנוע תקלות מסוג זה.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar This task not clear for me, what exactly should I fix here?

**Comment by JerusalemCinematheque** [comment]
דוגמא נוספת שאני לא ממש מבינה למה זה קורה
הסרט הפיל והפרפר
הסרט משוייך לדומיין סינמטק
הלובי אליו הסרט קשור משוייך לדומיין סינמטק
מדוע בחיפוש בגוגל התוצאה הראשונה שמופיעה מובילה לדומיין פסטיבל

**Comment by reasonat** [comment]
אני בכלל לא רואה את התוצאת חיפוש למילות חיפוש הללו
בקיצר, יש לנו פה עניין שצריך לשוחח עליו בשביל להבין יותר. 
אשלח מייל לתיאום שיחה

**Comment by JerusalemCinematheque** [comment]
התייעצנו עם מספר גורמים בנושא והם מבקשים אם אפשר להתקין באתר (על שני הדומיינים שלו)
google search console
ולתת להם ולנו גישה שנוכל לעקוב אחרי התוצאות
תוך כמה ימים הם אולי יוכלו להבין היכן הבעיה ומה ניתן לעשות כדי לפתור סוגיה זו

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko Please add the attached files to the site. instructions at the description area.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

This one is for the jff domain

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I see 2 identical files. I've uploaded this file.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko they only look identical I think. Anyway if I will get error we will do this together tomorrow

**Comment by reasonat** [comment]
@JerusalemCinematheque Both site are verified now.

**Comment by JerusalemCinematheque** [comment]
okay
how do we get access to the results? and can give lior@kiss-m.co.il access to them as well?

**Comment by reasonat** [comment]
Just did with full permissions

**Comment by JerusalemCinematheque** [comment]
האם יש קוד גישה וסיסמא?

**Comment by reasonat** [comment]
לא. זה פשוט פותח עבורו כניסה גם
