### ISSUE TITLE
Video window not opening properly from home page or lobby page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#309]
@reasonat 
Video window does not open properly from home page and lobby page
when opening, video does not appear
works fine on film page

lobby
https://jer-cin.org.il/en/lobby/new-films-7

home page
https://jff.org.il/he

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

@Amir Taiar אלכס טיפל בזה. ישנה בעיה שמשום מה כאשר יש נוד מקושר עם סרט הסרט לא מוצג. נראה לי כדאי להעברי לאלכס את הטיקט כי הוא זה טיפל בקולובוקס שם ולא זוכרת מה הוא עשה.

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

לבדיקה

**Comment by JerusalemCinematheque** [comment]
okay

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Bruria Helfer Please don't close tasks not here and not on the Giyhub. Thanks
