### ISSUE TITLE
navigation in lobby pages is not working properly

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#310]
@reasonat 
navigation in lobby pages does not work properly
in lobby of films when clicking on a film in the lobby the navigation does not appear at all
for example
https://jer-cin.org.il/he/taxonomy/term/936
when going into the first node there are supposed to be navigation arrows to th next node in the lobby, but navigation arrows do not appear

in lobby of events the navigation is for the next event in the calendar instead of next event in the lobby
for example
https://jer-cin.org.il/en/lobby/10-monday
when clicking on first node Scaffolding - node 16105
navigation should point to next event in lobby Marie-Francine - node 16127
instead navigation arrows point to previous and next events in the schedule

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review this

**Comment by JerusalemCinematheque** [comment]
okay

**Comment by JerusalemCinematheque** [comment]
okay
