### ISSUE TITLE
More screenings button and navigation button on event page in smaller screens

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#311]
עדכון
יש להסתכל על רגישות הכפתור - מעבר העכבר פועל לפני המעבר על הכפתור עצמו
_________
@reasonat 
בעמוד הקרנה 
במסכים קטנים יותר כפתור הניווט מסתיר את כפתור ההקרנות הנוספות
ולא מאפשר לפתוח אותו
![image](https://user-images.githubusercontent.com/26960693/34523209-19723340-f09f-11e7-9ddb-e2c9be1d79fe.png)

**Comment by reasonat** [comment]
מה אתם מציעים לעשות? 
באיזה מסך מדובר?

**Comment by JerusalemCinematheque** [comment]
אני חושבת שזה עניין של רגישות כפתור הניווט
כלומר הוא נפתח מהרגע שאתה עובר לידו ולא מהרגע שאתה עובר עליו וזה מה שגורם לבעיה
https://www.youtube.com/watch?v=JSGaqTYNwcI&feature=youtu.be

**Comment by reasonat** [comment]
אני מבין, אעביר את זה לברוריה להסתכלות

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

לבדיקה

**Comment by JerusalemCinematheque** [comment]
great thanks
