### ISSUE TITLE
Homepage - film title and event title appear even if they are the same in grid view

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#312]
@reasonat 
נקבע כי כששם האירוע ושם הסרט אותו הדבר לא יופיע שם האירוע בתצוגת גריד בעמוד הבית
נראה שכאשר בשם הסרט מופיע סימן כלשהו כמו
&
אז שם האירוע כן מופיע וכך נוצרת כפילות מיותרת
ראה
![image](https://user-images.githubusercontent.com/26960693/34914690-4e8b83e0-f920-11e7-892e-486475301c95.png)

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review this

**Comment by JerusalemCinematheque** [comment]
okay
