### ISSUE TITLE
display of multipal langauges on collection page

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#313]
@reasonat 
בתצוגה של הסרטים בעמוד מקבץ שדה השפות איננו מקובץ וההפרדה בין השפות מופיע כפייפ במקום כפסיק
לדוגמא
https://jer-cin.org.il/he/movie-group/16679
השפות של הסרטים ברשימה הן אנגלית, ויאטמנית
בעמוד זה מופיע אנגלית | ויאטמנית

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

לבדיקה

**Comment by JerusalemCinematheque** [comment]
okay

**Comment by JerusalemCinematheque** [comment]
פותחת מחדש את הנושא
בעמוד המקבץ כיש לסרט מספר שפות יש רווח בין השפה לפסיק
https://jer-cin.org.il/he/movie-group/16855

בעמוד האירוע של המקבץ לא מופיעות כל השפות של הסרט
https://jer-cin.org.il/he/event/16857
במקרה זה אנגלית, ויאטנמית

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

לבדיקה

**Comment by reasonat** [comment]
I am closing this issue, reopen if needed.
