### ISSUE TITLE
Event page with no film - image and title do not appear

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#314]
@reasonat @bruria1 
בעמוד מסוג אירוע כשאין סרט בלייןאפ לא מופיע שם האירוע והתמונה המצורפת לעמוד
ראו
https://jer-cin.org.il/he/event/16830

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

@Amir Taiar@Roei Dahan האם אני אמורה לטפל בזה?

**Comment by JerusalemCinematheque** [comment]
הבריינסטרום זה כדי שנענה על שאלת בנק השעות?

**Comment by reasonat** [comment]
כן, זה נכון לכל המשימות שבבנק שעות ולשני מיילים ללא מענה בנושא

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
@reasonat 
אני לא בטוחה מה הבעיה כאן, אבל נראה לי שזה קשור לטיקט הזה שסגרנו
http://jer-cin.org.il/he/event/19334
יש סרט שמקושר לאירוע
לסרט אין תמונה, אבל לאירוע יש.
בעמוד האירוע, התמונה לא מופיעה, הלובי אליו שייכנו את האירוע לא מופיע, ולא מופיעה כותרת האירוע ופרטי הסרט (כותרת, אורך, לידינג קרדיט טקסט)

**Comment by reasonat** [comment]
מה שאת מתארת כעת הוא מקרה קצה שונה מהטיקט הזה. אפתח חדש
https://github.com/Reasonat1/Cinema/issues/336
סוגר את זה שוב
