### ISSUE TITLE
סרט - תגית לובי תוצג לפי הדומיין אליו היא משוייכת

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#316]
תגית לובי תוצג לפי הדומיין אליו היא משוייכת – כלומר אם לובי סומן כדומיין פסטיבל הוא לא יוצג בעמוד הסרט כשזה מוצג בצד סינמטק ולהפך
https://jer-cin.org.il/he/movie/9278
https://jff.org.il/he/movie/9278
א – ת וגאלה משוייכים לדומיין פסטיבל
סרטים חדשים משוייכים לדומיין סינמטק
כל התגיות מופיעות בשני הדומיינים

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review this

**Comment by JerusalemCinematheque** [comment]
nice
