### ISSUE TITLE
תג הלובי צריך להופיע גם בעמוד האירוע של סרט שמשוייך ללובי

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#317]
תג הלובי צריך להופיע גם בעמוד האירוע של סרט שמשוייך ללובי
https://jer-cin.org.il/he/event/16026
הסרט "סוף טוב" משוייך ללובי סרטים חדשים
בעמוד האירוע של הסרט הלובי לא מופיע כתגית

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko Please pay attention to what I have described. This task and 2 more wasnt in the main task fo TO-DO as I described. 
Only tasks in this main task we should work on - https://www.wrike.com/open.htm?id=208184734

**Comment by reasonat** [comment]
@JerusalemCinematheque please review this

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

Meanwhile, since you already worked on those I will move them to the TO-DO main task. For next time :)

**Comment by JerusalemCinematheque** [comment]
okay

**Comment by JerusalemCinematheque** [comment]
פותחת את הנושא מחדש משום שכעת אני רואה שהתגית מופיעה בצורה שונה מאיך שהיא מופיע בעמוד סרט
בעמוד האירוע התגית מופיע בפונט קצת יותר גדול ובצבע האתר
לדוגמא כאן
https://jer-cin.org.il/he/event/16513
לעומת עמוד הסרט
https://jer-cin.org.il/he/movie/15030

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

לבדיקה

**Comment by JerusalemCinematheque** [comment]
אוקיי
רק בעברית התגית צריכה להיות מיושרת ימינה. כרגע היישור הוא שמאלי
https://jer-cin.org.il/he/event/11732

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

לבדיקה

**Comment by JerusalemCinematheque** [comment]
מצויין תודה
