### ISSUE TITLE
ניהול תגיות מהדורה

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#318]
תגית מהדורת פסטיבל – יש להוסיף לעמוד ניהול מהדורה שדה > שם מקוצר למהדורה שיופיע כשם התגית.
https://jff.org.il/he/movie/9076
התגית תופיע לדוגמא כפסטיבל 2017 במקום השם המלא

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

I added field Tag name. Now if you edit a festival and add the name of the tag, this name will be displayed in the tag area

**Comment by JerusalemCinematheque** [comment]
ok
