### ISSUE TITLE
להוסיף ללובי שמשוייך לדומיין פסטיבל תגית מהדורה

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#319]
כאשר לובי משויך למהדורה יש להציג בעמוד הלובי את המהדורה אליה הוא שייך
- הצגת המהדורה בקישור מעל הכותרת, בהטמעת עיצוב זהה לסיווג המוצג בעמוד סרט ואירוע
- להציג מספר מהדורות במידה ויש מספר מהדורות מקושרות. הפרדה בפסיק
- להציג כל מהדורה, כזו שתקפה כעת או כזו שמועדה תם
להוסיף ללובי שמשוייך לדומיין פסטיבל תגית מהדורה

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque this is not clear.

**Comment by JerusalemCinematheque** [comment]
הכוונה הייתי שיהיה ניתן לדעת בעמוד לובי שמשוייך למהדורת פסטיבל באיזה מהדורה מדובר
לדוגמא
https://jff.org.il/he/lobby/%D7%92%D7%90%D7%9C%D7%94
שתהיה בו את התגית פסטיבל הקולנוע ירושלים 2017

**Comment by reasonat** [comment]
אני מניח שאנחנו רוצים את התגית מעל הכותרת כמו בעמודי אירועי וסרט?

**Comment by JerusalemCinematheque** [comment]
כן נראה לי מיקום נכון
האם אפשרי שיופיע אחרי שטווח מועד המהדורה עבר?

**Comment by reasonat** [comment]
כלומר גם אם טווח המהדורה עבר שבכל זאת יופיע? 
ומה יקרה אם יהיו מספר מהדורות? באותה שורה?

**Comment by JerusalemCinematheque** [comment]
רק כשטווח התאריכים עבר הוא יופיע. כי אם הוא בתוך מהדורה פעילה אז השיוך שלו ברור
כן

**Comment by reasonat** [comment]
אוקיי
מעדכן את המשימה

**Comment by JerusalemCinematheque** [comment]
אפשר שיופיע גם אם טווח תאריכי המהדורה תקף

**Comment by reasonat** [comment]
עודכן

**Comment by JerusalemCinematheque** [comment]
בטוח שמופיע גם שמדובר על מהדורה עכשווית?
עשיתי ניסוי באתר ה
dev
ושם זה לא עובד

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko

**Comment by reasonat** [comment]
סליחה, בלבול בניהול המשימה. 
זו משימה בבנק שעות, אני מעריך סביב 5 שעות עבודה. 
האם יש אישור?

**Comment by JerusalemCinematheque** [comment]
בינתיים לא
רק רוצה לוודא שברגע שהמהדורה הנוכחית מסתיימת תגית המהדורה אכן תופיע למרות שיש עוד מהדורות קודמות

**Comment by reasonat** [comment]
זה לא קשור למשימה הזו. אם יש בעיה עם זה אפשר לפתוח מחדש את המשימה שכבר נסגרה שקשורה בזה

**Comment by dabur75** [comment]
@JerusalemCinematheque @navotb I am closing this, if there is a need please re-open
