### ISSUE TITLE
Calendar -  general notes

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#32]
This is an area below the calendar with genral notes. 
The notes will be apart from the columns and each note will be a row. 
The note should be like the free paragraph they can add to the Homepage, so maybe we should use the same paragraph? 
Each note will be below the other and there should be a management page for all of this. 
So maybe the paragraph should be managed in the calendar node itself? 
That depend whether this a node / not - https://www.wrike.com/open.htm?id=142532573
The look of it should be like the look on the homepage as a single static list item.

**Comment by bruria1** [comment]
האם יש הערות/תכנים שונים בתאריכים שונים?
או שהתכנים/הערות שמוסיפים מופיעים בכל עמודי לוח האירועים?

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

ניתן לערוך את התכנים דרך התיבות שבתפריט הניהול<br />

**Comment by JerusalemCinematheque** [comment]
@reasonat @bruria1 @navotb 
כמה דברים
1. התוכן בחלק הזה קשור ליום, הוא לא אמור להופיע באופן תמידי מתחת לקלנדר, אלא באופן יומי. כל יום, יש לו את התוכן שלו
2. אפשרות להוסיף תוכן מסוג content for homepage / front page
3. אם התצוגה היא תצוגת רשימה, חסר צבע רקע לחלק הזה
4. לוודא שאפשר להוסיף אירועים שמסומנים "hide from festival calendar"?
5. אנחנו רואים איפה מעלים תוכן בצד אנגלית, מה עם צד עברית?
6. האם יש אפשרות שנוכל לבחור אם להציג את התוכן בתצוגות שונות, בדומה לעמוד לובי?
7. לצמצם את הריווח בין חלק הקוביות לחלק זה

**Comment by bruria1** [comment]
1. כעת יש סוג תוכן רשיות ללוח שנה שבו לכל תוכן שאתם מוסיפים אתם מקשרים לתאריך והוא יופיע באותו תאריך. יש גם דף ניהול לתכנים אלו
2. ניתן כרגע להוסיף תוכן לעמוד הבית אבל לא עמודים מסוג עמוד בית. לפי מה שהבנתי נחכה עם זה כרגע @reasonat ?
3. האם כל החלק אמור להיות עם רקע ורוד? ואם יש טקסט הוא אמור להיות עם רקע לבן?
4. האם נתקלתם בבעייה כזו?
5. כעת זהו סוג תוכן שאתם מגדירים אותו אם הוא אנגלית או עברית
6. ואאאו.... זה מאוד מסבך את העניין הזה.. איזה תצוגות? תצוגה רחבה/גריד/ליסט? @reasonat 
7. צומצם

**Comment by JerusalemCinematheque** [comment]
אחרי שלוחצים submit החלונית לא נסגרת
2. לא רואים את התוכן לעמוד בית לפי התאריך אליו קישרנו. הוספנו JFF17 poster ל-27.5 והוא לא מופיע. יכול להיות שזה קשור לבעיות עדכון שישי עם העמוד הזה באתר DEV
3. שהכל יהיה ורוד
4. עוד לא ניסינו, רק רצינו לוודא שזה ככה תוכנן
6. ליסט / רחבה / גריד / וון אייטם

**Comment by bruria1** [comment]
1. הכוונה לחלונית לבחירת תוכן? האם זה קורה גם בעמוד הבית? האם בלייב זה גם קורה?
2. היו שני תכנים באותו יום, אין צורך כזה.. התוכן שהעלת בעייתי. חסרה לו שם תמונה ואין תוכן
3. בוצע
4. אמור לעבוד
6. בביצוע..

**Comment by bruria1** [comment]
6. בוצע. בכל תוכן ניתן בחור את סוג התצוגה

**Comment by JerusalemCinematheque** [comment]
1. כן
2. הוספנו עכשיו אייטמים ל-31.5. אייטם מסוג וואן אייטם מוצג. אייטם מסוג גריד לא מוצג
7. כותרת - יש כאן שני נושאים:
7.1 צריך כותרת שהיא לתצוגה וכותרת שהיא אדמיניסטרטיבית.
7.2 הכותרת לא מופיעה

**Comment by JerusalemCinematheque** [comment]
בתצוגת וון אייטם הכותרת גדולה מידי והריווח בין הכותרת לשורה הבאה צר מידי
צריך להתאים להגדרות בעמוד הבית סינמטק

**Comment by JerusalemCinematheque** [comment]
גם אייטמים מסוג ליסטה לא רואים

**Comment by bruria1** [comment]
לגבי התצוגות שלא רואים, לא רואה את הבעייה. בתאריך שציינת אני רואה את כל מה שהוספת.
לגבי הכותרת של וואן אייטם - סידרתי.
לגבי הבעייה שהחלונית של הוספת תוכן לא נסגרת - אפתח על זה טיקט חדש

**Comment by JerusalemCinematheque** [comment]
כן זה הופיע כמה שעות אחרי
סידרת - זה אומר שהכותרת עכשיו לא מופיע?
עכשיו שראיתי את סוגי התצוגה השוני כמה הערות
1. בתצוגת ליסטה, חסר הרקע הלבן בחלק של הטקסט
2. בתצוגת גריד עם אייטם איורע - גודל פונט אירוע צריך להיות יותר קטן, אלא עם כותרת אירוע וכותרת סרט אותו הדבר או שאין סרט מקושר
3. אייטם לובי צריך להיות קליקבילי
4. תצוגת וון אייטם - הכל צריך להיות קליקבילי גם התמונה וגם הטקסט
5. תצוגת ליסטה - התמונה צריכה להיות קליקבילית
6. תצוגת וואן אייטם אירוע - כותרת האירוע צריכה להיות באותו צבע כמו כל שאר הטקסט ולא בצבע האתר

**Comment by bruria1** [comment]
1. בוצע
2. בוצע
3. בוצע
4. בוצע
5. לפי מה שאני רואה התמונה קליקבילית לא?
6. בוצע

**Comment by JerusalemCinematheque** [comment]
במערכת הניהול, היינו רוצים שתהיה אפשרות לסדר את סדר הפריטים
לגבי הכותרת של האייטמים - האם זה אמור להיות מוצג או לא? הכי נכון יהיה שניתן לבחור אם הכותרת מוצגת או לא

**Comment by reasonat** [comment]
בוקר טוב, 
הלכנו הרבה יותר מדי רחוק עם המשימה הזו, החל מזה שאפשר לשנות תצוגות וכעת עם הבקשות הללו. 
אני מקפיא את שתי הבקשות של סדר הפרטים והכותרות. אפתח על זה משימה נוספת אותה אשים בהקפאה. 

האם למעט שתי הבקשות הנוספות הללו המשימה בוצעה?

**Comment by JerusalemCinematheque** [comment]
רק תסבירו לנו בבקשה את הגיון סדר ההופעה של האייטמים בכל יום
האייטם הראשון שיצרנו ליום יופיע ראשון? או שהוא מופיע אחרון?

**Comment by bruria1** [comment]
האחרון שהוספתם יופיע ראשון

**Comment by JerusalemCinematheque** [comment]
הערות לקלנדר צריכות להופיע גם בגרסת המובייל של הקלנדר

**Comment by navotb** [comment]
אמיר מוכרח להיות כאן מנגנון כלשהו של סידור, זה בלתי אפשרי שהסידור הוא לפי
תאריך היצירה. זה לא מאפשר שום שינוי.

**Comment by reasonat** [comment]
המשימה הזו מזמן מזמן יצאה מגבולות הגזרה שלה ונעשו פה המון שעות מעבר למה שהיה צריך להיות. 
כן אפשר לסדר את הסדר אייטמים במידה וכולם מועלים באותו העמוד ויש להם תצוגה אחידה
מעבר לכך לא ניתן יהיה לממש כעת.

**Comment by navotb** [comment]
מובן, אבל אנחנו צריכים מיון בסיסי ביותר לפי שדה מספרי. אחריות שלנו למספר את
האייטמים עבור כל יום. אם יש בעיה מבחינת התצוגות השונות, זה בעיה שלנו,
ונפתור אותה ע"י שינוי הסדר או שינוי התצוגה.
 אבל להסתמך סדר יצירת הפריטים זה מטורף.

2017-06-14 12:29 GMT+03:00 Amir Taiar <notifications@github.com>:

**Comment by reasonat** [comment]
שוב נבות, יש פה כבר חריגה של כמעט 400% בפיתוח המשימה הזו. 
אתה כעת מבקש להוסיך עוד. 
מצטער, בשלב זה זה בלתי אפשרי. 
למה שלא תציגו הכל בתצוגה אחת זהה ותסדרו? זו הייתה המטרה בהתחלה

**Comment by JerusalemCinematheque** [comment]
הסדר למעשה נקבע לפי סדר ההוספה
אבל בכל נוט אפשר לשנות את 
Authoring information
למועד אחר
האם זה יכול לעזור לנו?

**Comment by bruria1** [comment]
כן. אם תשנו את זה הסדר ישתנה

**Comment by JerusalemCinematheque** [comment]
האייטמים מופיעים פעמיים
תראי 15.6 בסביבת הפיתוח

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok
