### ISSUE TITLE
Movies manager export report

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#320]
Editor need to have the option to export (xls) report from the movies manager page. 
If needed we will create a new view just for this report (There will be also Event report). 
See xls example with all the columns needed. 
Also pay attention to the column comments
[reportsfromWebsite_film.xlsx](https://github.com/Reasonat1/Cinema/files/1685002/reportsfromWebsite_film.xlsx)

**Comment by reasonat** [comment]
**Pay no attention to this notes**
**Doc notes and questions:** 
cinematheque credits & festival credits columns  - Grouped by proffesion and ordering in a single row will be in Bank hours. This is not a simple & obvious request. 
Distributor column - There will be an extra dev time for changing the reference widget also display the data on the pages and other views. 
screening format column - Should we delete "technical screening format" and all his data from the site?

**Comment by navotb** [comment]
Credits: but this is already done and existing in the current film page.
Why extra hours? It is the same query
Distributors column - No. This is the only view (other than the film form
itself) when this widget should be visible. You should not change it in
other views. There are two list of distributors, one that we pushed to the
"persons" list in order to make it easier in the frontend, and which we
will keep as is, and one just for this purpose, since it will be easier to
query it and add custom fields in the future.  I don't see a reason for dev
hours here.

**Comment by reasonat** [comment]
Credits - Fact that it's done in other place doesn't mean there will be no dev time to make it in a view which is totally different. 
Dist - So still we will need to create a new field and display it on this management view.

**Comment by navotb** [comment]
I am sorry Amir, but the reports are part of the project, it was introduced discussed and agreed long ago. We are not asking for anything that is new development or coding. This is something that was left to the final phase and we expect it to be done as best as everything else was done. Thank you!

**Comment by reasonat** [comment]
Yes, reports. But not how the reports will be. This requests are far from a typical report. Also in the development which already have been done, this parts, on the site itself wasn't part of the original requests.

**Comment by navotb** [comment]
These reports are based on existing pages (reports/views) that already exist in the website. Nothing new. These parts of the site are core parts which were defined, drafted and included in early stages. Film page is essential part, and Event page - the next report - is also essential part. Thank you!

**Comment by reasonat** [comment]
The management tables exist but without this new requests which are not obvious and do need extra dev time.

**Comment by navotb** [comment]
Maybe it does request, but this is part of the project to have these reports, and it is not something new.

**Comment by reasonat** [comment]
Let me start to move this task and we will see the progress. OK?

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I added the link for export here https://jer-cin.org.il/en/admin/movies-manager But there is a problem with export, if we try make export for all movies, it takes too long and export can not be completed. So for now I added filter by language (current user language). Now we can make export for each language separately.

**Comment by navotb** [comment]
does it ffdssa

**Comment by navotb** [comment]
We need the export function on specific film(s) and not only on the whole list, by selecting the films (after search for instance) and exporting only selected ones (like "operations")

**Comment by navotb** [comment]
I mean we need the option to specific movie(s) export on the movie-manager page.

**Comment by JerusalemCinematheque** [comment]
1. there is no need for the word minutes
דקות
in the export results, we can just leave the number.
meaning 99
and not 99 Minutes

2. in the credits results
   - missing "space" between profession and person
   - missing "space" between each person in grouped profession
   - missing @ following last profession in the credit list
for examle here is the result we got 
Dir.:Bent Hamer @ W.:Tomas Norström,Joachim Calmeyer
and this is how it should be
Dir.: Bent Hamer @ W.: Tomas Norström, Joachim Calmeyer @

these remarks are for both hebrew and english sides

**Comment by reasonat** [comment]
What do you mean by "and exporting only selected ones (like "operations")" ?

**Comment by JerusalemCinematheque** [comment]
marking the items and exporting only the selection and not the whole database

**Comment by reasonat** [comment]
marking the items? 
Here is what I understand: 
- I go into the management table. 
- I filter results, lets say by title (Or any of the other filters - NOT operations) 
- I export

**Comment by JerusalemCinematheque** [comment]
or i go to management page
mark the items i want
export

**Comment by reasonat** [comment]
No, this is completely something else and not a stable option in Drupal + VBO
I can't approve this option now

**Comment by navotb** [comment]
So we can not filter the results and export only the filtered results?

**Comment by reasonat** [comment]
Yes you can by using the filters. VBO is not a filter but bulk operation module.

**Comment by navotb** [comment]
I have tried it last week after filter, but got the whole db

**Comment by navotb** [comment]
Export option is not available now to test again

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

Export option is available now by press button XLSX below the results table

**Comment by JerusalemCinematheque** [comment]
we are doing some test and now the reports are coming out empty

**Comment by JerusalemCinematheque** [comment]
seems to be okay now

**Comment by reasonat** [comment]
@JerusalemCinematheque  In order to QA this do you have a search parameter which has all the columns?

**Comment by JerusalemCinematheque** [comment]
okay
if there is no option of VBO, we will need to add these filters to the movie management page
תאריך יצירה - מ
and movie nid  

also in technical information column results come out with html signs 
<p> text </p>

When a film is assigned to both cinematheque and festival domain it comes out twice in the report. See for example The cakemaker

Lastly, can we add original title field to the export? Should appear after title for indexing

**Comment by reasonat** [comment]
@sato2004 Please take care of this requests. Thanks

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

Done

**Comment by JerusalemCinematheque** [comment]
created from - created to fields do not work. Calendar window to choose from does not open and manually putting in dates does not work

When on jer-cin domain, can't get results for films that are linked to festival domain. For example if i am on jer-cin domain > movie manager > selection of the following filters - festival domain and the panorama lobby > report > I get a blank report
![image](https://user-images.githubusercontent.com/26960693/37287010-50fa492c-260c-11e8-85fd-8a5555fd54ba.png)

If i move this search to jff domain i get a full report
![image](https://user-images.githubusercontent.com/26960693/37287159-c78c9f22-260c-11e8-9cab-23f15da80e0e.png)

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

Fixed

**Comment by reasonat** [comment]
I am closing this issue. Reopen if needed
