### ISSUE TITLE
dedictaed menu for festival

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#321]
@reasonat 
לא ממש בעיה, רק שאלה/הבהרה
פתחתי אתמול "טרם" לפסטיבל 2018
והיום אני רואה שנוצר תפריט ייעודי לפסטיבל 2018
אני לא הקמתי אותו, זה אומר שהתפריט נוצר אוטומטית?
מה זה למעשה אומר בפועל?

**Comment by reasonat** [comment]
על איזה אייטם מדובר? 
באתר סינמטק?

**Comment by JerusalemCinematheque** [comment]
באתר פסטיבל
https://jff.org.il/he/admin/structure/menu/manage/cinematic-festival-973

**Comment by reasonat** [comment]
זה חלק מפיתוח שלא עשינו בו שימוש בסוף. 
אין מה להתייחס לזה. 
לאחר שתעלו את הפסטיבל הזה לאוויר כדאי לשנות רק את השם של האייטם שבתפריט מגה הראשי

**Comment by JerusalemCinematheque** [comment]
סליחה לא הבנתי מה זה אומר לשנות את שם האייטם שבתפריט מגה הראשי

**Comment by reasonat** [comment]
בתפריט הראשי יש קישור לאתר הפסטיבל
אפשר לשנות את שם הקישור לשם שתרצו
