### ISSUE TITLE
Search page - Cancel - Show different results style for each content type

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#326]
As you can see in the design [SS] there should be different style look for each content type + The results divide to the content types.

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;899e39df8e08407c89577d540154610b:F28642680.A948692&#x2F;search+results+page.png">search results page.png</a>

**Comment by reasonat** [comment]
we need to have seperates views for each content type that are embeded in the same page one under the other .
the problem will be in synchronizing one exposed filters form for all these seperate views .
it is simple to make the synchorniztion in javascript for the form fields, but the problem may rise in the url query .

if url query problem can not be overcome, then we can't use views .
and what we do instead is call search api from custom code, which i have done before when working in gizra .
@Amir Taiar

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@yakoub abaya How about display results by groups? BTW, Tom was working on this page and I think its all in code

**Comment by yakoub** [comment]
@reasonat using same view creates a problem with the pager,
how will you move to next page if some of the groups ran out of results ?

i think using several views is best approach, but you need to configure exposed filters to use same name in the url query .

**Comment by yakoub** [comment]
https://www.drupal.org/docs/7/modules/search-api/developer-documentation/executing-a-search-in-code
