### ISSUE TITLE
event purchase does not work on content for homepage

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#330]
@reasonat 
אני מנסה להוסיף בתוכן לעמוד בית כפתור רכישה דרך מנגנון הקישור לטופטיקס
החלונית נפתחת וניתן לעשות חיפוש לאירוע
אבל לחיצה על האירוע הנבחר לא עובדת

**Comment by sato2004** [comment]
I can't understand the problem. If I edit an event I can add toptix link. Can you explain where I can see the problem?

**Comment by JerusalemCinematheque** [comment]
the problem is in the "content for home page" page
here's a video showing the issue
https://www.youtube.com/watch?v=gjOyf58XpSI&feature=youtu.be

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
great thanx
