### ISSUE TITLE
Festival term publish dates issue

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#331]
@reasonat 
ישנה בעיה בהגדרות של טווח תאריכי פרסום של "פסטיבל"
festival term
אם אנחנו קובעים תאריך שעבר, לדוגמא 1.2.18, אז 
1. לא ניתן להיכנס ללובי שמקושר למהודרת הפסטיבל
לדוגמא http://jff.org.il/he/node/4293
2. בעמודי האירועים שמקושרים למהדורה לא מופיע המידע שאמור להופיע על התמונה, קרי - שם לובי, כותרת אירוע, , כותרת סרט, אורך, לידיג טקסט
מספר דוגמאות
עמוד אירוע עם סרט
http://jff.org.il/he/event/10500
עמוד אירוע
http://jff.org.il/he/event/8528
3. בעמוד מאמר לא מופיעה התמונה או הכותרת
http://jff.org.il/he/node/10687
4. בעמוד סרט לא מופיע תגית מהדורת הפסטיבל ותגיות הלובי
http://jff.org.il/he/movie/8149
5. בעמוד האירוע של הסרט לא מופיע תגית הפסטיבל
http://jff.org.il/he/event/10072

אם אנחנו קובעים תאריך עתידי אז לא ניתן להיכנס למהדורה ונשלחים בחזרה לעמוד הבית

מן הסתם ברגע שאנחנו עוברים למהדורה חדשה, לחיצה על התגית של המהדורה הקודמת צריכה להוביל לעמוד המהדורה

**Comment by reasonat** [comment]
אני לא מצליח כלל להבין את הבעיה שנוצרה פה. 
כל הבעיות שצוינו בהמשך הם בגלל הקישור לתגית פסטיבל עם תאריך שעבר?

**Comment by JerusalemCinematheque** [comment]
הבעיה היא בהגדרת טווח תאריכי המהדורה
אם אנו מגדירים את טווח  מהדורה 2017 עד ה-1.2.2018
אז לא ניתן להיכנס לכל הפריטים שמקושרים למהדורה
זה עמוד מהדורת 2017
http://jff.org.il/he/taxonomy/term/213
נכנסים לקטגוריית סרטים
ואז מנסים להיכנס לאחד הלוביים
מקבלים הודעת שגיאה

גם אם אני מנסה להיכנס ללובי בצורה אחרת
אני מקבלת הודאת שגיאה

אם אני אשנה את טווח תאריכי המהדורה שיהיה עדיין "רלוונטי" אז הבעיה הזו לא מופיעה
אבל אז לא ניתן להגיע לעמוד המהדורה ונזרקים חזרה לעמוד הבית

וכנ"ל לכל הבעיות האחרות שנכתבו בטיקט

**Comment by reasonat** [comment]
@sato2004 Please also read the comment. it made the issue more clear

**Comment by JerusalemCinematheque** [comment]
בעמוד האירוע של הסרט תגית הפסטיבל עדיין לא מופיעה
http://jff.org.il/he/event/10072

בנוסף, תגית המהדורה העכשווית גם כן לא מופיעה
http://jff.org.il/he/movie/7769

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review

**Comment by reasonat** [comment]
@JerusalemCinematheque Need review

**Comment by JerusalemCinematheque** [comment]
בעמוד האירוע של הסרט תגית הפסטיבל עדיין לא מופיעה
ok

ובהקשר של המהדורה הנוכחית יש על זה איזה טיקט ששמנו אותו בהולד לא?

**Comment by reasonat** [comment]
@sato2004 Please check number 5 again
http://jff.org.il/he/event/10072 

לא ידוע לי על טיקט שתיארת בהולד

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar The problem not clear for me I see 
פסטיבל 2017
on the event page

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Any more issues with this task?

**Comment by dabur75** [comment]
@JerusalemCinematheque I am closing this task.
