### ISSUE TITLE
lobby page - error message when trying to reorder content

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#333]
@reasonat 
כשאני מנסה לסדר מחדש את הפריטים בעמוד לובי אני מקבלת את הודעת השגיאה הבאה
נכנסתי ללובי
לחצתי על
reorder content
לחצתי לסדר לפי
 time of event
ואז קיבלתי את הודעת השגיאה
![image](https://user-images.githubusercontent.com/26960693/39465129-574ad400-4d2a-11e8-9181-bc39f6756f22.png)

**Comment by reasonat** [comment]
@JerusalemCinematheque Need review

**Comment by JerusalemCinematheque** [comment]
seems okay
will reopen if problem retuens
