### ISSUE TITLE
Front Page - 3 Item Grid View

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#334]
@reasonat 
בעמוד פרונט פייג' שהקמתי הוספתי תצוגת גריד 3 אייטמים
משום מה האייטמים לא מוצגים כמו שצריך
במקום שיופיעו שלושה בשורה, שלושת האייטמים האחרונים התפצלו לשתי שורות
http://jer-cin.org.il/he/19987

**Comment by reasonat** [comment]
מכניס את זה לשעות יוני

**Comment by reasonat** [comment]
@JerusalemCinematheque Need review

**Comment by JerusalemCinematheque** [comment]
@reasonat 
זה בסדר בדוגמא ששלחתי 
אבל עכשיו יש בדיוק את אותה בעיה בעמוד הבית בצד עברית

**Comment by JerusalemCinematheque** [comment]
ערכתי מחדש את העמוד ולכאורה הבעיה נפתרה
אבל כדאי לעשות בכל אופן בדיקה כדי לוודא שזה לא יחזור על עצמו

**Comment by JerusalemCinematheque** [comment]
עכשיו בעמוד הבית צד אנגלית, בחלק שעד הבוקר היה מוצג כמו שצריך ולא נעשתה בו עריכה
![image](https://user-images.githubusercontent.com/26960693/41643060-e5ee231e-7472-11e8-8b33-e9fae4596ee8.png)

**Comment by reasonat** [comment]
@JerusalemCinematheque I can't see this issue. Which screen resolution and browser?

**Comment by JerusalemCinematheque** [comment]
once i edited the page again the problem resolved
but the issue keeps coming back
it was chrome 1920*1080

**Comment by reasonat** [comment]
So now there is no issue? 
Didn't get it. Looking in this resolution I see no issue.

**Comment by JerusalemCinematheque** [comment]
right now no, but this keeps coming back
i will update next time it happens

**Comment by reasonat** [comment]
ok. I will leave this open for now

**Comment by JerusalemCinematheque** [comment]
http://jff.org.il/he/22535
זה בעמוד מסוג פרונט פייג'
לא רק ששורות התפצלו חלק מהריבועים נצמדו לריבועים שלפניהם

**Comment by JerusalemCinematheque** [comment]
בדוגמא הזו הקמתי את העמוד
הוספתי אייטמים שהם לובי
התצוגה היתה בסדר
אחרי זה נכנסתי לכל לובי וערכתי אותו (הוספתי תמונה ללובי)
חזרתי לעמוד הפרונט פייג'
רעננתי אותו
ואז התצוגה השתבשה

**Comment by JerusalemCinematheque** [comment]
אמיר יכול להיות שהבעיה נובעת מכך שיש שם אייטמים שיש בהם את תמונת הדיפולט של האתר שמשום מה לא בגודל הנכון?
כשבודקים את גדלי התמונה, גובה כל התמונות הוא 242.94
גודל תמונת דיפולט אתר הוא 242.95
הבדל מזערי אבל נראה שהוא משפיע על האייטמים שמגיעים בשורות אחריו
תראה את תמונת המסך הזו כאשר "קלאסיקות" עם תמונת דיפולט אתר נמצא מעל אייטם אחר
![image](https://user-images.githubusercontent.com/26960693/42136197-cce39840-7d5f-11e8-8b7d-2f5de4c6553b.png)
לעומת תמונת מסך כשאין עוד פריטים מתחתיו
![image](https://user-images.githubusercontent.com/26960693/42136230-19d92a2a-7d60-11e8-8ade-6a692bd4b160.png)

**Comment by reasonat** [comment]
תוכל לשלוח לינק לעמוד עם הבעיה?

**Comment by JerusalemCinematheque** [comment]
http://jff.org.il/he/22535
תנסה לשנות את הסדר של הפריטים
העמוד עולה ביום חמישי אז אולי כדאי שנפתח עמוד ניסיון חדש עבור זה

**Comment by reasonat** [comment]
נראה לי כדאי שתסדרו את זה באופן בו ראיתם את הבאג

**Comment by JerusalemCinematheque** [comment]
תראה עכשיו

**Comment by reasonat** [comment]
רואה. הועבר לבדיקה

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review

**Comment by JerusalemCinematheque** [comment]
זה נראה בסדר
למרות שגודל של תמונת הדיפולט עדיין קטן בפיקסל מהתמונות האחרות
http://jff.org.il/he/23219

**Comment by reasonat** [comment]
למה הכוונה תמונת הדיפולט?

**Comment by JerusalemCinematheque** [comment]
התמונה המוצגת בליסטה כשאין לאייטם תמונת מקור
זו התמונה עם האנשים באולם שצופים בסרט
אין לי מושג איפה התמונה נמצאת בתוך המערכת או איפה משנים אותה

**Comment by reasonat** [comment]
הבנתי

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko Notice the comment. This is the default image which I guess dont have the good porportions before resizing.

**Comment by reasonat** [comment]
@JerusalemCinematheque Please reeview again

**Comment by JerusalemCinematheque** [comment]
אני עדיין רואה שגובה התמונה קטן בפיקסל מהתמונות האחרות
הגובה של תמונת הדיפולט בגריד הוא 241.95
של כל שאר התמונות 242.94

**Comment by reasonat** [comment]
השינוי של הגודל נעשה ב-css ו
ולכן אני לא ידוע איך את רואה את הגודל כי כעת הם אותו הדבר

**Comment by JerusalemCinematheque** [comment]
![image](https://user-images.githubusercontent.com/26960693/42734188-84ba0646-8848-11e8-9315-6ef0337d8277.png)

![image](https://user-images.githubusercontent.com/26960693/42734190-8a901970-8848-11e8-94dc-8f087ebf6673.png)

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko I can approve the default image is still 1px less then the others

**Comment by JerusalemCinematheque** [comment]
![defaultpic19201080](https://user-images.githubusercontent.com/26960693/42734305-47870268-884a-11e8-8dca-f6f294d7bf58.jpg)
זו תמונת הדיפולט בגדלים הנכונים

**Comment by reasonat** [comment]
@sato2004 Please replace the default with this one and then make sure sizes are equal

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

@Amir Taiar אני לא רואה את הבעיה הזו. אולי הם הורידו את החלק הבעייתי?

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Bruria Helfer החלק הבעייתי זה תמונת ברירת מחדל שככל הנראה , כן, לא מוצגת כעת

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Please review

**Comment by JerusalemCinematheque** [comment]
http://jff.org.il/en/festivals/2018-jerusalem-film-festival
כפי שניתן לראות הבעיה עדיין קיימת
גודל תמונת המחדל שונה בפיקסל מהתמונות האחרות

**Comment by reasonat** [comment]
@Alex Voloshchenko

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Please review again

**Comment by JerusalemCinematheque** [comment]
looks okay
