### ISSUE TITLE
sponsor banner height

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#335]
@reasonat 
האם ניתן לשנות את גובה באנר ספונסר?
שיהיה זהה  לגובה של באנר המידע ובאנר רשתות חברתיות?

**Comment by reasonat** [comment]
It will be around 1 hour.

**Comment by JerusalemCinematheque** [comment]
לא לביצוע בשלב זה

**Comment by dabur75** [comment]
@JerusalemCinematheque I am closing this issue, if there is a need in the future please let me know.
