### ISSUE TITLE
Festival performance issues

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#337]
@reasonat 
הוספתי כמה וכמה אירועים, אבל אני משום מה לא מצליחה לראות אותם בעמוד הקלנדר
אולי אני מסתכלת על העמוד הלא נכון או שמשהו בהגדרות של הסרטים / הקרנות / טרם פסטיבל לא נכון
http://dev.jff.org.il/he/festival-calendar

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@sato2004  from what I have seen events do have dates, hall set, they are publish, yest the calendar isn't display.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar It was cache issue, now calendar looks ok https://dev.jff.org.il/he/festival-calendar

**Comment by JerusalemCinematheque** [comment]
So this is part of the on-going issues with this page/model

**Comment by JerusalemCinematheque** [comment]
@reasonat 
should i create more events or is this enough to explore the issues at hand?

**Comment by JerusalemCinematheque** [comment]
יש חדש?

**Comment by reasonat** [comment]
@JerusalemCinematheque "So this is part of the on-going issues with this page/model" - What do you mean by that?

**Comment by JerusalemCinematheque** [comment]
that any time we update the festival calendar we have to clear the cache so the updates are also updated on the frontend

**Comment by reasonat** [comment]
כן. זה כל הרעיון של קאש... 
כבר דיברנו על זה עשרות פעמים

**Comment by JerusalemCinematheque** [comment]
אבל זה חלק מהבעיה, שאפילו העדכון הראשוני של העלאת האירועים לא קורה אוטומטית אלא רק בניקוי הקאש

**Comment by reasonat** [comment]
את הקאש לא מעניין מתי אתה מעלה אירועים. הוא תופס קאש לכל החיים
ולכן יש לרענן בכל שלב של עדכון, בהתחלה, באמצע וכן הלאה. 
עשינו כעת עדכון ששיפר משמעותית את הביצועים
אנחנו רוצים לדחוף אותו ללייב השאלה אם יש שם כבר אירועים

**Comment by JerusalemCinematheque** [comment]
יש רק אירוע אחד
כל האירועים אמורים לעלות בחמישי הבא

**Comment by reasonat** [comment]
אוקיי, אז אנחנו דוחפים את העדכון ללייב
מה שחסר לי בפיתוח זה הבאנרים למטה ומסה יותר גדולה של אירועי דמה כדי לדעת שאני בסדר שם

**Comment by JerusalemCinematheque** [comment]
אני אנסה להוסיף היום את מה שצריך

**Comment by JerusalemCinematheque** [comment]
שימו לב שמהלך העדכון שעשיתם משהו השתבש בתצוגה של שם האולם בפופ אפ. במקום שם האולם מופיע מספר
![image](https://user-images.githubusercontent.com/26960693/41841539-4189c316-7871-11e8-9d43-6d643e36e4c1.png)

**Comment by JerusalemCinematheque** [comment]
בעניין הקאש
לדוגמא העליתי לדב אירועים ל-14.7 ואירועים ל15.7
כל האירועים שהעליתי ל-15.7 מעודכנים
כל האירועים שהעליתי ל-14.7 לא מופיעים
ובנוסף אם אני נכנסת ל14.7 לא רואים בלוח שהיום 15.7 קיים אבל אם אני עוברת ל16.7 אז פתאום ה-15.7 כן מופיע

**Comment by JerusalemCinematheque** [comment]
הוספתי ימים מלאים - 14.7 / 15.7
כולל קלנדר נוטס
מקווה שזה מספיק

**Comment by reasonat** [comment]
@sato2004 Please check performances now. Also notice last 3 comments.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I fixed issue with hall name. 
About different days with the list of events, every date that is separate html page in the cache (not only events section, but full page with header, footer list of dates etc) so all we need is to clear the cache when all events are added, after that the pages in the cache are updated and everything should be displayed correctly

**Comment by JerusalemCinematheque** [comment]
okay for hall names
regarding the cache - i'm not sure i understand. what will need to be done is after we finish creating all the events > clear cache and then what?
what happens if we update events after that? will the update appear right away or will we have to clear cache every time? which is what we have been doing.
still takes a long time for the page to upload. also, moving between days still seems to be taking a long time when first entering the calendar - up to 11 seconds. very fast after going back to day already visited

**Comment by JerusalemCinematheque** [comment]
any updates?

**Comment by reasonat** [comment]
כל פעם שמוסיפים אירוע ו/או מעדכנים אירוע יש לנקות קאש בכדי לראות שינויים. 
אני ממש לא 11 שניות, מבדיקת מהירות שעשיתי אני רואה ממוצע מעבר של 4.5 שניות שזה לא רע כלל
בנוסף, מהבדיקה הקודמת שעשיתי נראה כי לבאנרים שמתחת יש השפעה שלילית.

**Comment by JerusalemCinematheque** [comment]
ביום חמישי הלוח העדכני יעלה לאתר ואז נוכל לבחון מה קורה בלייב
אז מה אפשר לעשות לגבי הבאנרים האלו שמכבידים? האם יש דרך אחרת לקשר אותם לעמוד יום ספציפי בלי שזה יוסיף משקל לעמוד?

**Comment by reasonat** [comment]
לא אמרתי שהם אלו שמכבידים אלא רק שהם מוסיפים. מה גם שהם בסוף העמוד בכלל ואני בספק לגבי היחס המרה שלהם. 
אפשר להוריד אותם... ? זה לשיקול דעתכם

**Comment by JerusalemCinematheque** [comment]
@reasonat 
העליתי עכשיו את הקלנדר של פסטיבל 2018
הוא איטי מאוד מאוד
דקה שלמה רק להעלות את הקלנדר
וכך גם המעבר בין הימים

**Comment by JerusalemCinematheque** [comment]
@reasonat 
אמיר קיבלנו גם תלונות מאנשים שלא מצליחים לראות את כל הימים
אני מתארת לעצמי שזה עניין של קוקיס של הדפדפן של כל אחד
אבל האם יש משהו שניתן לעשות בנושא הזה?

**Comment by JerusalemCinematheque** [comment]
האם ההאטה שחווינו הבוקר קשורה לניקוי הקאש של האתר?
כי עכשיו הייתי צריכה לעדכן את הקלנדר ועשיתי ניקוי קאש וזה שוב איטי מאוד
ואם זה המצב מה עושים עם זה?
עכשיו כל פעם שנצטרך לעדכן את הקלנדר (נגיד פעם או פעמיים ביום בקרוב) נפגוש שוב את בעיית מהירות העמוד ?

**Comment by reasonat** [comment]
לא מצליחים לראות את הימים לא קשור לנושא הזה. 
אנחנו לא ראינו האטה כלל, להיפך, ממספר מחשבים הלוח שנה עלה מהר. 

אבל כמו שאמרתי, יש חלופות אבל אתם לא ממש משתפים פעולה. 
לצורך העניין, בואו נרים עמוד פשוט, הטמל סטטי, של כל הימים, ללא הצלבות, ללא אלוגריטם, ללא אינטגרציה לשום מקום, ללא באנרים. אתם תזינו אותו ידנית בהתאם לשינויים. 
האם זה מתאים?

**Comment by JerusalemCinematheque** [comment]
הי אמיר,
תודה. אכן עכשיו וגם כשהיה לחץ על האתר בסוף השבוע הקלנדר עבד במהירות.
כפי שכתבתי אני חושבת שההאטה שחווינו קשורה לניקוי הקאש של האתר שעשיתי לאחר שהעליתי את כל האירועים של קלנדר פסטיבל 2018
אני עשיתי ניקוי קאש של כל האתר אבל אני רואה שיש שם אפשרויות לבחור מה לנקות. האם באמת צריך לנקות את כל הקאש כדי לעדכן, מה שנראה שגורם לאתר להאט מאוד, או שאפשר לנקות רק חלק מהקאש שרלוונטי לקלנדר.

**Comment by JerusalemCinematheque** [comment]
בעניין אחר. קיבלנו מספר תלונות וגם זה קרה לי כשגלשתי בעמוד אנונימי שנכנסים ל1.8 נשארים רק שני ימים בטיקר הימים
תראו כאן
https://www.youtube.com/watch?v=F2ogxFH7Gi0&feature=youtu.be
היתה בעיה דומה בשנה שעברה וזה טופל
אני לא ראיתי שזה קורה מאז יום חמישי ויכול להיות שזה הסתדר, אבל נודה לכם אם תוכלו להעיף מבט

**Comment by reasonat** [comment]
באשר לבעיית התאריך 
https://github.com/Reasonat1/Cinema/issues/347

**Comment by reasonat** [comment]
באשר לקאש רק על אזור נתון. למיטב ידיעתי אין את האפשרות הזו אבל אנחנו נבדוק את הנושא

**Comment by JerusalemCinematheque** [comment]
הייתי שמחה אם היה פתרון לעניין הקלנדר נוטס (בהאנרים שמשויכים לכל יום)
אני נמנעת משימוש בהם כרגע כי זה יוצר עומס על העמוד
אבל זה אלמנט שמאוד חסר

**Comment by reasonat** [comment]
לא בטוח שכעת לאחר ששיפרנו את הביצועים זה יעשה בעיות
אנא תעלי שוב ונראה

**Comment by JerusalemCinematheque** [comment]
הסתכלתי בדב וזה לא מהיר כמו שזה באתר החי בלי הבאנרים

**Comment by reasonat** [comment]
כן, הבאנרים מייצרים עומס. 
@sato2004 Can youo please cache the baners on dev site so we can test this?

**Comment by JerusalemCinematheque** [comment]
האם עניין זה נבדק?
