### ISSUE TITLE
install new DNS facebook code

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#338]
@reasonat 
שינוי נוסף בפייסבוק מביא לכך שלא ניתן יותר להתאים לינקים בעמוד. 
קיבלנו מפייסבוק הוראות כיצד נוכל כנראה לשנות לינקים שעולים באתר.
ההוראות בקובץ תמונה והקוד נמצא במסמך.
![cinematheque](https://user-images.githubusercontent.com/26960693/41506585-4429e3ec-7229-11e8-9be6-0419b7c06611.jpg)
[dns code.txt](https://github.com/Reasonat1/Cinema/files/2108831/dns.code.txt)

**Comment by reasonat** [comment]
זה בנק שעות. 
האם יש אישור לעבוד על זה?

**Comment by JerusalemCinematheque** [comment]
מה הערכת הזמן לדבר כזה?

**Comment by navotb** [comment]
למה זה לא יכול להיות חלק מהשעות של יולי

**Comment by reasonat** [comment]
ראשית כל השעות של יולי כבר הסתיימו אחורה :) 
שנית, שוב, כפי שסוכם - במהלך חודש יכנסו משימות שהן על גבול הבאג / דרישה שלא מומשה עד הסוף  וכדומה

סביב 2 שעות אם לא יהיו תקלות
מדובר במשימה שמתערבת בדומיין

**Comment by JerusalemCinematheque** [comment]
מעבירה אליך במייל הסבר מחברת המרקטינג לגבי עניין זה
משהו שאמור לפתור את הסיבוך של ה
DNS
זה במייל כי אני לא מצליחה להעביר את הקבצים שמצורפים בו דרך הגיטהאב

**Comment by reasonat** [comment]
האם יש אישור לעבוד על זה?

**Comment by JerusalemCinematheque** [comment]
מה הערכת השעות?

**Comment by reasonat** [comment]
סביב 2 שעות אם לא יהיו תקלות
מדובר במשימה שמתערבת בדומיין

**Comment by JerusalemCinematheque** [comment]
יש אישור

**Comment by JerusalemCinematheque** [comment]
יש הערכת זמן מתי זה יטופל?
אנשי המדיה שלנו לא מצליחים בינתיים להעלות תכנים לפייסבוק  כמו שצריך

**Comment by sato2004** [comment]
@JerusalemCinematheque  I uploaded these html files to the server
http://jer-cin.org.il/5v6661kl84akmgq7b5wdykze79xpyu.html
http://jff.org.il/j88zwbt578dj34r976e7qo0vvm8ihl.html

**Comment by JerusalemCinematheque** [comment]
יופי תודה רבה
