### ISSUE TITLE
Calendar - Main Area - pop-up box content

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#34]
pop up box should display: 
✓    Event title
✓    Short description of the event
✓    Link to the event node
✓    Screening table - Like in Lobby pages on the main site.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko I add short event details to this event http://jff.jer-cin.reasonat.com/en/node/5838/edit and I cant see it in the calendar pop up box<br />http://jff.jer-cin.reasonat.com/en/festival-calendar/2017-04-26<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar I&#39;ve fill Short event details (it was empty) and I see text in the calendar<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko Yap, My mistake! <br />

**Comment by JerusalemCinematheque** [comment]
@reasonat האם זה משהו שאתה רוצה שנבדוק?

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque We need to decide where does the pop-up will be open. me and @bruria1 think the best option will be always in the middle of the screen

**Comment by JerusalemCinematheque** [comment]
@reasonat @bruria1 @navotb 
כן במרכז
חסר תיאור קצר של הסרט

**Comment by reasonat** [comment]
לא אמור להיות תיאור קצר של הסרט אלא של האירוע כפי שסיכמנו.

**Comment by JerusalemCinematheque** [comment]
חייב להיות תקציר של הסרט אחרת אין טעם לפופ אפ

**Comment by JerusalemCinematheque** [comment]
אמור להופיע גם short event details וגם תקציר הסרט המקוצר. בדיוק כמו בעמודי לובי ועמוד הקלנדר שבצד סינמטק

**Comment by reasonat** [comment]
Can you write in english what fields need to be here? All of them.

**Comment by JerusalemCinematheque** [comment]
event date line - day / date / time / hall / tickets
event title
short event details
film title
leading credit text / length
short summary festival
More screenings
list of other screenings, not including the chosen screening

if event title and film title the same
event date line - day / date / time / hall / tickets
short event details
film title
leading credit text / length
short summary festival
More screenings
list of other screenings, not including the chosen screening

if there are event title and film title, event title is linked to event date. film title isn't a link
if event title and film title the same, film title links to event page

**Comment by JerusalemCinematheque** [comment]
![image](https://cloud.githubusercontent.com/assets/26960693/25695911/aa095480-30bd-11e7-9de1-fefb6a731a27.png)
something like this (of course don't pay attention to font. font size, etc.)

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Alex Voloshchenko <br />http://jff.reasonat.com/he/festival-calendar<br />יש פה שתי בעיות:<br />1. הכותרת של עוד הקרנות צריכה להופיע רק כאשר יש עוד הקרנות<br />2. באם כותרת הסרט וכותרת הסרט זהים, כותרת הסרט אינה צריכה להופיע.<br />

**Comment by JerusalemCinematheque** [comment]
הפופ-אפ צריך להיפתח במרכז העמוד ביחס לרוחב ולגובה העמוד
כלומר הוא תמיד נפתח באותו מקום

**Comment by JerusalemCinematheque** [comment]
עוד מספר בעיות
1. ההקרנה שנבחרה לא צריכה להופיע בהקרנות הנוספות
2. חסר תקציר הסרט המקוצר
3. אפשר לוותר על  הקישור  to event page מכיוון שכותרת האירוע מובילה לעמוד האירוע
4. לשנות באנגלית מ
more screenings 
ל
Additional screenings
5. בשורת לידינג קרדיט טקסט ואורך באנגלית צריך להוסיף לדקות
s
כלומר
minute**s**
ולא minute
6. אם לוחצים על עוד אירוע בזמן שפופ-אפ פתוח, הפופ-אפ הפתוח צריך להיסגר
7. בצד עברית הדקות מופיעות באנגלית
8. בצד עברית "הקרנות נוספות" במקום more screenings

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Alex Voloshchenko <br />http://jff.reasonat.com/he/festival-calendar<br />יש פה שתי בעיות:<br />1. הכותרת של עוד הקרנות צריכה להופיע רק כאשר יש עוד הקרנות<br />2. באם כותרת הסרט וכותרת הסרט זהים, כותרת הסרט אינה צריכה להופיע.<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Alex Voloshchenko בנוסף באיזור ההקרנות הנוספות ההקרנה הנוכחית לא צריכה להופיע<br />

**Comment by bruria1** [comment]
2. האם הכוונה לתקציר הפסטיבל? הוספתי אותו.
3. הורדתי
4. בוצע
5. האם הבעיה עדיין קיימת? אני לא רואה אותה
6. בטיפול
7. אמור להיות בסדר עכשיו
8. אמור להיות בסדר עכשיו

**Comment by JerusalemCinematheque** [comment]
6. נראה לי כבר עובד
דברים נוספים
גודל הפונט של תיאור אירוע ותקציר הסרט צריך להיות אותו הדבר. 16 נראה לי בסדר
להקטין את שורת לידינג קרדיט טקסט. שיהיה כמו באתר הסינמטק בקלנדר
נראה לי שאם כותרת האירוע וכותרת הסרט לא אותו הדבר, כלומר יש בפופאפ גם כותרת אירוע וגם כותרת סרט, גם כותרת הסרט צריכה להיות בצבע האתר. אחרת זה נראה קצת מוזר שרוב הזמן כותרת הסרט בצבע הפסטיבל ובפעמים אחדות זה לא
אפשר להקטין את כותרת ההקרנות הנוספות

**Comment by bruria1** [comment]
1. לגבי גודל הטקסט - שניהם בגודל 16, לא רואה מה לסדר..
2. שורת לידינג קרדיט - שיניתי צבע וגודל שייה זהה לסינמטק
3. לגבי צבע כותרת סרט - סודר.
4. הקטנתי את הפונט

**Comment by JerusalemCinematheque** [comment]
אולי זה הריווח?
![image](https://cloud.githubusercontent.com/assets/26960693/26053587/11f350ca-3972-11e7-9b21-579a266456e1.png)

![image](https://cloud.githubusercontent.com/assets/26960693/26053630/310fb8c2-3972-11e7-835e-8a63cbad4db5.png)

**Comment by JerusalemCinematheque** [comment]
ככה זה נראה בפיירפוקס

![image](https://cloud.githubusercontent.com/assets/26960693/26053703/78a06f74-3972-11e7-8247-8456b59706d2.png)

**Comment by JerusalemCinematheque** [comment]
אפשר לקרב את כותרת הסרט ושורת הלידינג טקסט?

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
אפשר שהריווח הזה יהיה גם כשיש סרט, בלי פרטי אירוע?
![image](https://cloud.githubusercontent.com/assets/26960693/26099060/4b049246-3a32-11e7-961c-940783c3e364.png)

**Comment by JerusalemCinematheque** [comment]
אפשר להוריד את הבולד מהכותרות?

**Comment by JerusalemCinematheque** [comment]
בצד עברית בשורת הלידינג טקסט יש בעיית ריווח בין הלידינג טקסט והקו המפריד

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
גודל פונט תיאור אירוע מקוצר בפופ אפ עדיין 18
אמור להיות 16 כמו פונט תקציר סרט

**Comment by JerusalemCinematheque** [comment]
בעיה שכבר עברנו עליה אבל עכשיו שוב חזרה
אם יש פרטי אירוע אבל כותרת האירוע וכותרת הסרט אותו הדבר 
פרטי האירוע יופיעו לפני כותרת הסרט
למעשה כותרת האירוע מתמזגת עם כותרת הסרט (אם אותו הדבר)
![image](https://user-images.githubusercontent.com/26960693/27010432-dccc971c-4eac-11e7-8c28-628fbdde6dba.png)

**Comment by bruria1** [comment]
לגבי גודל הפונט סידרתי.
לגבי כותרת האירוע - לא הבנתי איך אמור להיות

**Comment by JerusalemCinematheque** [comment]
תקציר אירוע מקוצר
כותרת סרט
פרטי הסרט

אלא אם כותרת באירוע וכותרת הסרט שונים ואז זה
כותרת אירוע
תקציר אירוע מקוצר
כותרת סרט
פרטי הסרט

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by JerusalemCinematheque** [comment]
עוד הערה. שוב דבר שכבר טופל ועכשיו צץ פעם נוספת
בצד עברית בשורת הלידינג טקסט יש בעיית ריווח בין הלידינג טקסט והקו המפריד

**Comment by reasonat** [comment]
@bruria1

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
עוד הערה
![image](https://user-images.githubusercontent.com/26960693/27079126-23e73ec0-503f-11e7-84af-6061690ea00f.png)
יש כאן מקרה של אירוע ללא סרט. כותרת האירוע מופיעה פעמיים.
לא בטוחה איזה שדות הפופ אפ לוקח במקרה כזה אבל בעל אופן רק הכותרת העליונה אמורה להופיע

**Comment by bruria1** [comment]
זה קורה כאשר לאירוע לא מקושר שום סרט.
מצב שלא אמור להיות
בכל מקרה סידרתי.

**Comment by JerusalemCinematheque** [comment]
זה כן מצב שיכול להיות
עכשיו אבל בקובייה של האירוע אין את שם האירוע

![image](https://user-images.githubusercontent.com/26960693/27080338-109dec60-5044-11e7-937c-95a03ae58964.png)

**Comment by bruria1** [comment]
האם כעת בסדר?

**Comment by JerusalemCinematheque** [comment]
כן
