### ISSUE TITLE
Dev festival calendar - events not presented in the correct hall

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#340]
@reasonat 
אני ממש מקווה שזו רק בעיה בסביבת הפיתוח ולא בקלנדר באתר החי
אבל יש מספר אירועים שהקמתי בסביבת הפיתוח שלא מופיעים בטור אולם נכון
לדוגמא ב-20.7 האירוע האי היפה ביותר שוייך לאולם סינמטק 3, אבל מופיע בטור של סינמטק 1
http://dev.jff.org.il/he/festival-calendar/2018-07-20
או ב-14.7 הפרס שוייך לסינמטק 2 ומוצג בסינמטק 1
http://dev.jff.org.il/he/festival-calendar/2018-07-14
בשני המקרים הטור של האולם הנכון מופיע, אבל אין בו אירועים

**Comment by reasonat** [comment]
@JerusalemCinematheque need review

**Comment by JerusalemCinematheque** [comment]
seems to be okay
will reopen if problem returns
