### ISSUE TITLE
sponsor banner slider

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#341]
The sponser baner should be a slider replacing each image within 5 seconds. 
So the gallery should: 
1. Arrows right-left
2. Auto replace each 5 seconds with a basic slide effect. 
3. On mobile using finger swipe 

See image to understand the section
![slider_jff](https://user-images.githubusercontent.com/741209/41893681-43d3a678-7925-11e8-9e1c-4da1487b4970.jpg)

**Comment by reasonat** [comment]
@JerusalemCinematheque זו הייתה בקשת שינוי שלכם לפני מספר חודשים למיטב זכרוני ולכן החלפנו מבאנר מתחלף לסטטי.

**Comment by JerusalemCinematheque** [comment]
לא שזכור לי
לפני שנה החלפנו את התמונה הראשית מסטטית למתחלפת אולי מכאן הבלבול
בכל אופן כרגע זה גם לא סטטי, הבאנרים מופיעים אחד מתחת לשני

**Comment by reasonat** [comment]
זו בדיוק הייתה הבקשה. לא זוכר משהו אחר. 
גם בעיצוב זה ככה.

**Comment by JerusalemCinematheque** [comment]
ומה שרצוי הוא שזה יהיה סליידר אוטומטי שמתחלף כל 5 שניות

**Comment by reasonat** [comment]
אז רק בכדי לחדד
שורה אחת, של לוגואים, חצים לשני הצדדים להחלפה
החלפה אוטומטית כל 5 שניות
הזזה עם האצבע במובייל
במובייל 2 לוגוים בשורה אחת ?

מצרף צילום מסך רק בכדי לוודא שאנחנו על אותו מקום
![banners_and_alerts_and_ _ _](https://user-images.githubusercontent.com/741209/41834362-b85a8152-785c-11e8-9297-951dd6634fde.jpg)

**Comment by JerusalemCinematheque** [comment]
זה לא החלק הזה
אני מדברת על החלק שמעליו. איפה שכרגע יש שני באנרים ברוחב מסך שלם שמופיעים אחד מתחת לשני - פדקס ופררלה

**Comment by reasonat** [comment]
עדכנתי את התיאור של המשימה והעברתי אותה לשעתיים של יולי

**Comment by JerusalemCinematheque** [comment]
יש אפשרות לטפל בזה ממש בימים הקרובים? אנחנו מצפים למסה של אנשים שיכנסו לאתר החל מיום חמישי

**Comment by reasonat** [comment]
לפני מחר זה ממש לא יקרה בהתחשב בכך שיש לנו משימה דחופה בהרבה מזה.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko also cache this view when done.

**Comment by reasonat** [comment]
@JerusalemCinematheque please review

**Comment by JerusalemCinematheque** [comment]
okay great
