### ISSUE TITLE
Festival site > event page > film lobby does not appear on picture

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#342]
@reasonat 
בצד פסטיבל בעמוד אירוע אליו מקושר סרט שמקושר ללובי, הלובי לא מופיע על התמונה
עמוד הסרט עם הלובי
http://jff.org.il/he/movie/22311

עמוד האירוע של הסרט ללא הלובי
http://jff.org.il/he/event/22318

בצד סינמטק נראה שזה בסדר
http://jer-cin.org.il/he/event/19376

**Comment by reasonat** [comment]
עמוד הסרט אינו קיים. 
וגם, מהו הלובי שאמור להופיע?

**Comment by JerusalemCinematheque** [comment]
looks t be okay now
thanx
