### ISSUE TITLE
Hall Toptix issue

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#344]
@reasonat 
עניין מאוד דחוף
משום מה החיבור בין הגדרות אולם באתר והגדרות אולם מטופטיקס הפסיק לעבוד
כלומר מנגנון המשיכה מטופטיקס בעמוד אולם לא שומר את האולם
נכנסתי לדוגמא לאולם סינמטק 1
לחצתי על
toptix hall
לחצתי על סינמטק 1
כתוב בשדה סינמטק 1
עשיתי שמור
נכנסתי חזרה לעמוד והשדה ריק
כאני מושכת אירוע מטופטיקס בעמוד אירוע כל המידע (שעת תחילה, סיום וכו) נמשך אבל שדה האולם נשאר ריק

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review

**Comment by JerusalemCinematheque** [comment]
greta. working now
