### ISSUE TITLE
festival calendar - day choice mark

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#345]
Active day in the calendar nav day should be the "Site color"  - http://jff.org.il/he/admin/appearance/flexicolor 

The front should be like here only with the festival color
https://user-images.githubusercontent.com/26960693/42418041-68d4e386-82a0-11e8-8538-f8da1265b50a.png

**Comment by reasonat** [comment]
מה תרצו שיהיה?

**Comment by JerusalemCinematheque** [comment]
היום הנבחר אמור להיות מסומן בצבע האתר כמו שהיה בעבר
כמו שקיים בקלנדר סינמטק
![image](https://user-images.githubusercontent.com/26960693/42418041-68d4e386-82a0-11e8-8538-f8da1265b50a.png)

**Comment by reasonat** [comment]
אבל בזהב נכון?

**Comment by JerusalemCinematheque** [comment]
כן בצבע הדומיין
כלומר שכמו כל אלמנט אחר, אם אנחנו בוחרים לשנות את צבע הדומיין אז גם שם זה ישתנה בהתאם

**Comment by reasonat** [comment]
update description and move to dev

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review

**Comment by JerusalemCinematheque** [comment]
okay
