### ISSUE TITLE
festival calendar mobile - day ticker

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#346]
On Mobile - Calendar page - http://jff.org.il/he/festival-calendar 
What needed: 
- In case the first day yet to arrive the calendar should start with it. 
- Then calendar should start with current date. 

Now there is also an issue  -When I click a date, the date nav bar, always return to 2/8 which I guess it's actually and LTR issue and it's return to the 5/08
![mobilecalendarss](https://user-images.githubusercontent.com/26960693/42308172-7ac4afbe-803d-11e8-9e21-b6c76895b611.jpg)

**Comment by reasonat** [comment]
לא ברור. נתחיל מכך שתאמרו לי למה הכוונה ״טיקר״ ?

**Comment by JerusalemCinematheque** [comment]
שורת ניווט הימים
בכניסה ראשונית לעמוד הקלנדר היום הראשון שאמור להופיע זה היום הראשון בקלנדר
כשהיום הראשון בקלנדר חולף כרונולוגית היום הראשון שאמור להופיע בכניסה לקלנדר הוא היום "הנוכחי"
כשהקלנדר מסתיים כרונולוגית אמור לחזור ליום הראשון בקלנדר
כשבוחרים יום בקלנדר היום שנבחר אמור "להופיע" ראשון
ככה זה היה כשהעלינו את האתר בשנה שעברה
עכשיו המצב הוא שלא משנה מה שורת ניווט הימים "מתחילה" ב-2.8 וצריך לדפדף אחורה כדי להגיע לימים הראשונים
כשנכנסים לקלנדר השורה "מתחילה" ב-2.8
כשעוברים ליום אחר נגיד ה-27.7 שורת הניווט "מתחילה" ב-2.8 וכן הלאה
וכמו בשורת ניווט הימים בדסקטופ גם כאן היום שנבחר לא "מסומן"
אני מקווה שזה יותר ברור

**Comment by reasonat** [comment]
Move to dev

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review

**Comment by JerusalemCinematheque** [comment]
okay
