### ISSUE TITLE
1.8 picking issue

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#347]
When a anonimous user choose the date 1/8 in the calendar 
http://jff.org.il/he/festival-calendar/2018-08-01 
The other dates (most of them) disappear .

**Comment by reasonat** [comment]
אני לא מצליח לשחזר את זה. בלחיצה על התאריך מופיעים לי כל שאר הימים

**Comment by JerusalemCinematheque** [comment]
גם אני לא. זה קרה לי פעם אחת
והיו עוד כמה אנשים שהתלוננו על זה
אם נשמע על זה שוב נכתוב

**Comment by reasonat** [comment]
אוקיי
אז אני סוגר את זה
