### ISSUE TITLE
additional tag manager

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#348]
@reasonat 
?תוכלו בבקשה להוסיף את הטאג מנג'ר הזה לזה הקיים באתר

Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KK3PWKL');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KK3PWKL"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I added second tag, so now we have:


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PWXMSPL');</script>


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KK3PWKL');</script>


but I think this is wrong, tag should be only one

**Comment by reasonat** [comment]
@JerusalemCinematheque

**Comment by JerusalemCinematheque** [comment]
אני בודקת את העניין

**Comment by JerusalemCinematheque** [comment]
מסתבר שזה עניין חדש של גוגל לשים את שני הקודים
אני מצרפת גם את ההוראות והקודים בקובץ נפרד למקרה שלא רואים את הקודים כמו שצריך כאן

צריך להטמיע את החלקים  –
**חלק עליון ב
[head] 
חלק תחתון ב
[body]** 

**Paste this code as high in the [head] of the page as possible:**


<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KK3PWKL');</script>


**Additionally, paste this code immediately after the opening [body]
[tagManager.txt](https://github.com/Reasonat1/Cinema/files/2184081/tagManager.txt)
 tag:**


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KK3PWKL"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by sato2004** [comment]
This is not clear for me, should I live only new tag? And looks like new tag has wrong id

**Comment by JerusalemCinematheque** [comment]
Hi, can i connect you to the company asking for the Tag Manager?
If so what is your email address or phone number?

**Comment by sato2004** [comment]
alex@reasonat.com 0538211993

**Comment by JerusalemCinematheque** [comment]
תודה אלכס
אני סוגרת את הטיקט

**Comment by JerusalemCinematheque** [comment]
אפשר בבקשה להסיר את זה?

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Alex delete this tag, but now site doesn't have a Google tag, which might be not good. Closing this issue, reopen if needed
