### ISSUE TITLE
homepage - editing content issue

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#349]
@reasonat 
לא ניתן לערוך או להעלות מספר פריטים במקביל בעמוד הבית
אחרי כל הוספה/עריכה של פריט (לא לובי) צריך לשמור את העמוד אחרת מקבלים הודעת שגיאה
![image](https://user-images.githubusercontent.com/26960693/43043696-aed4dcd6-8da1-11e8-8ccb-94c2a7102d46.png)
או שלא ניתן לבחור את הפריט הבא

**Comment by reasonat** [comment]
@JerusalemCinematheque Please review this

**Comment by JerusalemCinematheque** [comment]
great thanx
