### ISSUE TITLE
events created twice

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#350]
@reasonat 
ביקשתי לשייך הקרנות מתוך טופטיקס לנוד 19438 (אתה מת רק פעמיים)
פתחתי את חלונית טופטיקס
חיפשתי את אתה מת רק פעמיים
ראיתי שיש לו 6 אירועים
אישרתי שיוך
והמערכת יצרה כל אירוע פעמיים גם בעברית וגם באנגלית
http://jer-cin.org.il/he/movie/19438

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I made few tests with diifferent events and I can't see the problem

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Is this still an issue?

**Comment by JerusalemCinematheque** [comment]
we haven't encountered this issue since then

**Comment by dvirco** [comment]
@JerusalemCinematheque @navotb I am closing this issue
