### ISSUE TITLE
problem with ticketing website

### ISSUE THREAD

**Issue by navotb** [Reasonat1/Cinema#351]
Hi,
We have encountered a problem with ticketing today and would like to check the possible connection between jff site and ticketing site. In order to solve the ticketing issue, we have shut the ticketing website,. When we have done this, suddenly we did not have any credits in the jff sites. As you can see in the photo bothe shopping cart icon is missing and credits are missing. That leads us to think that the two are connected, and maybe there are other issues which create unnecessary linkage between the two sites and slow them both down. Could you please check this issue, as we it really effect the shopping functionality of the website. Thank you!
![image](https://user-images.githubusercontent.com/5830669/43260263-985e6de4-90e1-11e8-8509-08c1c5f7d1d9.png)

**Comment by reasonat** [comment]
לא ברור כלל
הפסקתם את הפעילות רכישה באתר פסטיבל? בסינמטק? 
בגלל בעיה שהייתה במערכת כרטוס עצמה בלי קשר לאתר?

**Comment by navotb** [comment]
היתה בעיה בתפקוד של הטופטיקס. אנשי התמיכה של טופטיקס חשבו שיש קשר בין אתר התוכן לאתר של טופטיקס - אולי אתר התוכן מייצר הרבה הפניות לאתר של טופטיקס ומשבית אותו. אז הם הורידו את האתר מכירת הכרטיסים של טופטיקס כדי לבדוק אם זה משנה משהו. לבסוף התברר שהבעיה היתה במקום אחר ולא קשורה לענין הזה. 
בכל מקרה, כאשר הם הורידו את אתר מכירת הכרטיסים של טופטיקס, התברר שיש לזה השפעה על אתר התוכן - כפי שכתבנו: לא עלו הקרדיטים בעמודי הסרטים (והאירועים).

**Comment by reasonat** [comment]
אז כעת החזירו חזרה את הטופטיקס לפעילות? ז״א שכעת לא נראה כלל את הבעיה?

**Comment by navotb** [comment]
עכשיו לא תוכלו לראות את הבעיה. שלחנו צילום מסך של הבעיה: רואים את "המקצועות" אבל לא את "האנשים"

אולי כדאי לבדוק אם זה קשור ל(1) סדר טעינת האלמנטים בעמוד או (2) אם יש קשר (שלא צריך להיות לפי איך שאני מבין) בין שאילתת הקרדיטים לטופטיקס.

**Comment by reasonat** [comment]
בסדר גמור. אני רק רציתי להבין את רמת הדחיפות של זה מול משימות אחרות.

**Comment by navotb** [comment]
כרגע זה לא דחוף.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I do not see how it can be connected. All credits these are just view and not related to Toptix

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque See Alex comment. I am closing this issue, re-open if needed.
