### ISSUE TITLE
home page adding content error message

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#355]
@reasonat 
אני לא מצליחה להוסיף נודים נוספים בעמוד הבית
אני מבקשת להוסיף פריט בעמוד הבית בגריד 3
לוחצת על 
add item
עושה חיפוש לאייטם ומקבלת
![image](https://user-images.githubusercontent.com/26960693/43397082-4e10e298-940c-11e8-8f13-bf1f2dc86443.png)
![image](https://user-images.githubusercontent.com/26960693/43397119-67f89f70-940c-11e8-9d46-5e0be7274f7e.png)
![image](https://user-images.githubusercontent.com/26960693/43397122-6bfc0076-940c-11e8-9765-e8f892be21aa.png)

┆Attachments: <a href="https:&#x2F;&#x2F;storage.www.wrike.com&#x2F;attachments&#x2F;74131878?accountId&#x3D;948692">2018-10-22.png</a>

**Comment by JerusalemCinematheque** [comment]
היה עניין דומה לזה בשנה שעברה כשכמות האייטמים שיכולנו להוסיף לעמוד הבית היתה מוגבל

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I don't see the error, I made all steps and I see nodes without error

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque ?

**Comment by JerusalemCinematheque** [comment]
works okay now
will reopen if needed
