### ISSUE TITLE
home page hebrew - top gallery - adding film collection error

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#358]
@reasonat 
ערכתי את עמוד הבית בעברית
הוספתי פריטים לטופ גלרי ולגריד שלישיה
כשלחצתי על שמירה קיבלתי את הודעת השגיאה הבאה
Parse error: syntax error, unexpected 'else' (T_ELSE) in /home/jercin/public_html/sites/all/themes/cinemateque/templates/node/node--cm-movie-group--top_gallery_front.tpl.php on line 8

ועכשיו לא ניתן לגשת לעמוד הבית בצד עברית
עזרתכם הדחופה
תודה

**Comment by JerusalemCinematheque** [comment]
הסתכלתי שוב על מה שכתוב בשגיאה וכנראה שיש בעיה עם הוספת פריט מסוג מקבץ בטופ גלרי
בקיצור הצלחתי איכשהו להיכנס לעריכה של העמוד ולתקן את זה
אני משנה את נושא הטיקט בהתאם

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Please review this

**Comment by JerusalemCinematheque** [comment]
okay
