### ISSUE TITLE
DEV jff site seems to be under bot attack

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#359]
@reasonat 
התחלנו היום לקבל מיילים מאתר הדב של טפסים שמילאו מתוך האתר דב
http://dev.jff.reasonat.com/
מצורפת דוגמא
בבחינה של אתר הדב רואים שיש יותר מאלף טפסים שמולאו ביומיים האחרונים
אני מחקתי את הטופס ממנו הם הגיעו
אבל אולי כדאי שתבדקו מה קורה שם
[file1.docx](https://github.com/Reasonat1/Cinema/files/2325363/file1.docx)

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@Alex Voloshchenko I guesss we ca close this one now right?

**Comment by reasonat** [comment]
Closing this one since we assume there will be no bot overload, on dev site, after changing the access code. 
If this is happening again please open the issue again.
