### ISSUE TITLE
Calendar - Main Area - pop-up should appear when pressing the title of the event

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#36]

**Comment by reasonat** [comment]
Popup appear well and fast

**Comment by JerusalemCinematheque** [comment]
מה שדיברנו עליו זה שפופ אפ עובד בהובר. לחיצה על האירוע מובילה לעמוד האירוע

**Comment by reasonat** [comment]
לא, זה לא מה שאמרנו ולא מה שכתוב... 
אמרנו שלחיצה על האירוע פותחת את הפופ-אפ אחרת זה משגע את העין. ואז, לחיצה בפופ-אפ על האירוע מכניסה לאירוע.
