### ISSUE TITLE
new pixel code

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#360]
@reasonat 
האם ניתן להטמיע קוד פיקסל רק בעמודים מסויימים?
יש לנו קוד פיקסל עבור תכנית מסויימת שהרצון הוא שזה יעבוד רק בעמודים שקשורים לתכנית
האם דבר כזה אפשרי או שהקוד הוא לכל האתר

**Comment by reasonat** [comment]
אפשר כמובן. 
הבעיה שיכולה לצוץ, אני לא בטוח, היא שהקוד הגלובלי ״יעלה״ על הקוד הספציפי
יש לבדוק את זה קודם. 
כעת הקוד הגלובלי הוא על התבנית אב שהיא המעטפת להטמעת העיצוב של כלל העמודים

**Comment by dabur75** [comment]
@JerusalemCinematheque @navotb Is there a demand like this? to embed the code just for certain pages?

**Comment by JerusalemCinematheque** [comment]
this issue can be closed
