### ISSUE TITLE
cinematheque main calendar appearance

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#362]
@reasonat 
יש מספר ימים בקלנדר הראשי של הפסטיבל שהתצוגה בו השתבשה ואין הפרדה בין הבוקסות
לדוגמא ב-24.10 וב-26.10
![image](https://user-images.githubusercontent.com/26960693/45596847-398f6a80-b9cb-11e8-95b7-bcc2125ba62c.png)

┆Attachments: <a href="https:&#x2F;&#x2F;storage.www.wrike.com&#x2F;attachments&#x2F;75096970?accountId&#x3D;948692">2018-10-30.png</a>

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I don't know how reproduce the problem, I checked these days in all browsers and I don't see the problem

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Is this still an issue?

**Comment by JerusalemCinematheque** [comment]
yes
please see 6.11 hebrew side
first box is an event without a film
the next three are events with films

**Comment by reasonat** [comment]
@Alex Voloshchenko

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Please review

**Comment by JerusalemCinematheque** [comment]
okay
