### ISSUE TITLE
dev sites security issues

### ISSUE THREAD

**Issue by navotb** [Reasonat1/Cinema#364]
we receive alerts regarding SSL certificates and other issues for 
**www.dev.jer-cin.reasonat.com  
jer-cin.reasonat.com 
jff.reasonat.com 
mail.jer-cin.reasonat.com 
mail.jff.reasonat.com 
www.jer-cin.reasonat.com
www.jff.reasonat.com** 

Please make sure all development sites are well secured, and access is restricted to approved users.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Amir Taiar I've removed these aliases, now dev sites http://dev.jer-cin.org.il http://dev.jff.org.il

**Comment by reasonat** [comment]
I am closing this issue. In case something comes up please re-open.
