### ISSUE TITLE
Sound of video continues after media window has closed

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#365]
אני נכנסת לעמוד סרט שיש לו מדיה מסוג וידאו 
הוידאו הוא קישור לוימאו
אני לוחצת על הטריילר ועושה פליי
הוידאו רץ
בזמן שהוא רץ אני סוגרת את חלונית הוידאו
החלונית נסגרת אבל עדיין אפשר לשמוע את הסאונד של הוידאו

לדוגמא כאן
https://www.jer-cin.org.il/he/movie/27538

**Comment by dabur75** [comment]
@JerusalemCinematheque העניין טופל, האם תוכלו בבקשה לבדוק?

**Comment by JerusalemCinematheque** [comment]
ok

**Comment by dvirco** [comment]
@JerusalemCinematheque is this fixed now? can I close?

**Comment by dabur75** [comment]
@JerusalemCinematheque are you still experiencing this issue?
