### ISSUE TITLE
Update db version

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#366]

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

Dvir Cohen Eraki I don't see compatibility issues. But it is necessary to create a full backup of the database before updating.

**Comment by navotb** [comment]
Are you (Reasonat) back it up?

**Comment by reasonat** [comment]
➤ Dvir Cohen Eraki commented:

Alex Voloshchenko did you create a backup?

**Comment by navotb** [comment]
What about this issue? Can you backup before update for the mysql version?

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

I created database backup path to the backup - /home/jercin/JerusalemCinemathequeIsraelFilmArchive.mysql.gz

**Comment by dabur75** [comment]
@navotb did you get it?

**Comment by navotb** [comment]
I don't navigate in the server. It is beyond me
Anyway, we are planning to upgrade after the weekend, and the db will have more data. Is it automatic update ? If not, will ask you to backup again before the upgrade.

**Comment by dabur75** [comment]
done
