### ISSUE TITLE
Change server host name

### ISSUE THREAD

**Issue by navotb** [Reasonat1/Cinema#367]
There is a problem with SSL certificate at the server. 
EuroVPS has replied:

> You are getting this error since your server hostname srv.hb5487.com does not have proper records pointing to our server. This might be temporary name that we provide during the server set up.
> 
> I suggest you to change the hostname to a new one with your main domain in the server.
> 
> eg: srv.jer-cin.org.il

Reasonat, please approve there is no problem making this change in terms of the website functionality etc.

Thank you!

**Comment by sato2004** [comment]
Yes, there is no problem with this. You can change this record

**Comment by navotb** [comment]
Thank you!

**Comment by dabur75** [comment]
done
