### ISSUE TITLE
front page > special grid dynamic > event with movie group display

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#368]
כשאנחנו נסים להציג אירועים בתצוגה דינמית שבליין אפ שלהם יש אירוע עם מקבץ סרטים לא רואים את תקציר המקבץ
אמור להופיע בתצוגה של אירוע חוץ משם האירוע, שם הסרט/מקבץ בליין אפ/מועד/כרטיסים גם את פרטי האירוע המקוצרים ופרטי הליין אפ המקוצרים
במקרה של מקבץ, למרות שבכל אחד מהמקבצים יש תקציר (שמופיע במקומות אחרים ובתצוגות מסוג שונה, כמו  תצוגת ליסט), הוא לא מופיע בתצוגה מסוג ספיישל גריד דינמיק
בנוסף, כפתור הכרטיסים בפריט השני בגריד הדינמי לא נמצא במיקום הנכון. הוא אמור להיות צמוד למועד ולא כפי שהוא עכשיו.
מצורף צילום מסך
![image](https://user-images.githubusercontent.com/26960693/54880032-f960e700-4e48-11e9-8541-14423337d170.png)

**Comment by dabur75** [comment]
@JerusalemCinematheque please review

**Comment by JerusalemCinematheque** [comment]
great thank you

**Comment by dabur75** [comment]
done
