### ISSUE TITLE
Calendar - Main Area -Event pop-up box display

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#37]

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko This is done via other tasks no? Need review? <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar Yes<br />

**Comment by JerusalemCinematheque** [comment]
אני קצת חוששת שהקשר בין הפופ-אפ והאירוע שנבחר עוד לא מספיק נהיר
מה את חושבת שאפשר לעשות? 
להדגיש את קווי הגבול עוד יותר?
להוסיף גם גבול זהב לפופ-אפ?
לשנות את הצבע של קוביית האירוע?
או להשחיר קצת את הרקע כשהפופ-אפ פתוח?

**Comment by bruria1** [comment]
איך עכשיו?
בעיני זה ברור מאוד ונראה טוב..

**Comment by reasonat** [comment]
אני חושב שזה נראה מצוין. מה גם שהדגשה יתרה תוציא את תשומת הלב מהחלון הנפתח

**Comment by JerusalemCinematheque** [comment]
מצטערת חשבתי שסגרנו את הנושא. מבחינתנו נושא זה סגור
