### ISSUE TITLE
Calendar - Main Area -Add option on event form to remove event from festival calendar

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#38]
Add option on event form to remove event from festival calendar

Then prevent this events from display in the calendar.

**Comment by JerusalemCinematheque** [comment]
זה אופציה שכבר קיימת ועובדת
מקווים שזה עובד עברית / אנגלית. כרגע אי אפשר לבדוק

**Comment by reasonat** [comment]
למה אי אפשר לבדוק?

**Comment by JerusalemCinematheque** [comment]
זה היה שהעברתם את האתר לשרת אחר והאתר לא היה זמין
יודע להסתיר. לא יודע להחזיר אם מבקשים כבר לא להסתיר מהקלנדר

**Comment by JerusalemCinematheque** [comment]
when marked as remove from calendar - works
when we go back to unmark the mark and add to calendar - doesn't work, and event does not appear on calendar

**Comment by reasonat** [comment]
@sato2004 Please check this.

**Comment by sato2004** [comment]
It seems that is cache issue. After cleaning the cache, everything is ok

**Comment by JerusalemCinematheque** [comment]
ok
