### ISSUE TITLE
Calendar - Main Area -Event box display

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#39]
Event box should display: 
✓    Event time | Event length | Favorite icon  - 20:30 | 112m | favorite icon
✓    Movie title - The movie the event is related to
✓    Screening remarks table - If exist. 
✓    Screening ID + Ticket button

**Ticket logic:** 
Like on main site
✓    In case the event date is before NOW dont displat ticket button. 
✓    In case it's out of stock display "Sold out". 
✓    Ticket button appear only if beginning hour exist on Toptix.

**Comment by reasonat** [comment]
I have add this dummy event http://jff.jer-cin.reasonat.com/en/event/5838  to the calendar as can be seen on this date
http://jff.jer-cin.reasonat.com/en/festival-calendar/2017-04-26 on Cine 3 Hall
All requested field get display

**Comment by JerusalemCinematheque** [comment]
השאלה היא האם כל השדות שאנחנו רוצים שיהיו מוצגים מוצגים?

**Comment by reasonat** [comment]
זה ניתן לבדיקה אז סביר להניח שכן. מבדיקה שלי, כן.

**Comment by JerusalemCinematheque** [comment]
להתייחס לפרונט פייג' או רק לשדות שמופיעים?

**Comment by reasonat** [comment]
לא הבנתי את השאלה. 
מדובר על לוח השנה בפסטיבל ועל התיבה הקטנה, לפני שהיא נפתחת לתיבה הגדולה שזו משימה אחרת

**Comment by JerusalemCinematheque** [comment]
הקישור לקלנדר לא פועל. איך אנחנו מגיעים לעמוד?

**Comment by reasonat** [comment]
אני לא מצליח להבין אתכם כלל. סליחה

**Comment by JerusalemCinematheque** [comment]
אנחנו לא מצליחים להיכנס לעמוד של הקלנדר כדי לבדוק אותו ולשלוח הערות לכל הנושאים הפתוחים
זו ההודעה שאנחנו מקבלים בלחיצה על הקישור לקלנדר בהאדר
We're sorry....

The page you are looking for cannot be found.

**Comment by reasonat** [comment]
@bruria1 Can you please check this permission issue?

**Comment by JerusalemCinematheque** [comment]
ticket button should be in same place and not relative to title of event (see 27.5) in cin'1 first event and other events

**Comment by JerusalemCinematheque** [comment]
minutes should not be capitalized
**m**inutes not **M**inutes

**Comment by JerusalemCinematheque** [comment]
i think we should add "add to calendar" button next to ticket button

**Comment by JerusalemCinematheque** [comment]
please note that the spacing between each line appeares different on different browsers
on firefox
![image](https://cloud.githubusercontent.com/assets/26960693/26033300/2cc4ab3a-38b2-11e7-918e-48855a24aca2.png)

on chrome
![image](https://cloud.githubusercontent.com/assets/26960693/26033305/454fd8d2-38b2-11e7-98db-45f41cff9119.png)

**Comment by JerusalemCinematheque** [comment]
Screening table remarks - need to add a little more spaceing between title and the remark
also need to change font color > parhpas stronger gray

**Comment by JerusalemCinematheque** [comment]
add a few more pixles to spacing between columns

**Comment by bruria1** [comment]
לסיכום הבקשות פה:
1. לגבי מיקום הכפתור - כרגע הוא אחיד יחסית לתחתית התיבה אך כאשר כותרת האירוע ארוכה תיבת האירוע תהיה גבוהה יותר, יש לכם בקשה אחרת?
2. לגבי כתיבת ה"דקות" סודר
3. הוספה ללוח השנ - איפה לוסיף? בקוביה של האירוע או בקובייה הנפתחת? ואם זו הנפתחת אז איפה?
4. ריווחים שונים בפיירפוקס ובכרום - אצלי הם זהים האם זה קריטי מבחינתכם?
5. Screening table remarks - איפה מופיע? לא הבנתי על מה מדובר..
6. לגבי טבלת ההקרות - אם רוצים שיהיה רווח גדול יותר יש צורך להרחיב את כל התיבה הנפתחת.

**Comment by JerusalemCinematheque** [comment]
1. נראה לי שצריך לקבוע גובה קבוע לבוקסה על פי ההגיון של כותרת שמתפצלת לשתי שורות 
2. בסדר
3 בקוביה של האירוע
4. הסתכלתי שוב שאני לא מחוברת למערכת הניהול וזה אותו הדבר, אבל הרווח קצת גדול מידי. 
5. הערת ההקרנה שמופיע אחרי הכותרת בקוביה של האירוע
6. הכוונה היתה לריווח בין טורי האולמות. זה קצת צפוף כשיש קוביית אירוע ליד קוביית אירוע

**Comment by bruria1** [comment]
1. בוצע
3. כעיקרון יש שם מספר זיהוי של האירוע. לא נראה לי שיש מקום גם לקלנדר, אלא אם כן זה במקום?
4. בוצע
5. בעייתי כיוון שאז לא יכנסו שישה אולמות במסך. אלא אם כן מספיק לך שיכנסו חמישה אולמות במסך

**Comment by JerusalemCinematheque** [comment]
2. אפשר להוריד את שם השדה ID ולהשאיר רק את הקוד ואז נראה לי שיהיה מקום גם לקלנדר
3. הריווח קצת גדול מידי עכשיו. האם זה בגלל שנקבע שהערת ההקרנה במיקום קבוע בבוקסה ללא קשר לאורך הכותרת?
4. אי אפשר להוריד פיקסל מכל צד של קובייה?

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

2. בוצע<br />3. כן. זה מה שהבנתי שרציתם לא?<br />4. &#64;Alex Voloshchenko האם אפשרי שיהיה יותר רווח בין העמודות בלוח שנה?<br />

**Comment by JerusalemCinematheque** [comment]
3. כן יותר ריווח, אבל שיהיה יחסי לכותרת. כך שאם הכותרת תופסת רק שורה יהיה אותו ריווח כמו אם הכותרת תופסת שתי שורות
4. לפי איך שנראה כרגע יש בכלל בעיה עם התצוגה של העמודות כשיש 6 טורים. הקובייה האחרונה נחתכת

**Comment by JerusalemCinematheque** [comment]
האם אפשר לצמצם את גובה כל בוקסת אירוע?
יש מקום למטה ולמעלה

**Comment by bruria1** [comment]
3. האם כעת זה טוב?
4. יש עמוד לדוגמה עם 6 עמודות?
5. אני לא רואה מקום לצמצם. יש שוליים של 10 פיקסל ולא נראה לי שיהיה יפה פחות

**Comment by JerusalemCinematheque** [comment]
3. כן
4. 27.5
5. האם יש דרך להראות לנו עם ריווח של 5 פיקסל, בלי לעשות את השינוי?

**Comment by bruria1** [comment]
4. איך עכשיו
5. בוצע

**Comment by JerusalemCinematheque** [comment]
4. במסך 1280 עדיין רואים בעיה
5. אפשר להוריד גם מלמעלה ומלמטה?

**Comment by JerusalemCinematheque** [comment]
עוד דבר, צריך לוודא שכפתור שלח לקלנדר יירד כשמועד האירוע מסתיים

**Comment by JerusalemCinematheque** [comment]
צריך לוודא שהאירועים ממשיכים להיות מוצגים גם אחרי שהמועד שלהם עבר. בדומה לקלנדר הסינמטק.
@reasonat באיזשהו שלב אנחנו צריכים לדבר על נושא האירכוב של הקלנדר לפי מהדורה

**Comment by JerusalemCinematheque** [comment]
האם אפשר לצמצם את הרווח בין שורת האולמות לאזור הקוביות?

**Comment by bruria1** [comment]
4. את מדברת על זה ששם האולם נקטע על ידי "אולמות נוספים"?
5. הורדתי. עכשיו ישבכל קוביה שולים של 5 פיקסלל מכל הכיוניים
6. הורדתי את הכפתור אם אין כרטיס
7. לגבי הצגת אירועים שהתאריך שלהם עבר - זה כבר נושא לטיקט חדש.. תפתחו.
8. צמצמתי את הרווח

**Comment by reasonat** [comment]
No need to open new task for 7 since it's part of archive logic which yet to start.

**Comment by JerusalemCinematheque** [comment]
4. כן
6. שלח לקלנדר כן יכול להופיע לפני שכפתור הכרטיסים מופיע. יכול להיות מצב שבו מופיעים האירועים לפני שמתחילה מכירת הכרטיסים. רק צריך לוודא שאחרי שהאירוע הסתיים האייקון כבר לא מופיע
7. ובכל זאת, כי מי יודע אם נסיים את נושא הארכיון בזמן, רצוי שכבר בשלב זה הגיון תאריכון הקלנדר והאירועים לא נמחקים אחרי מועד האירוע יתקיים
8. אפשר לצמצם אפילו יותר? אפילו בחצי ממה שכרגע

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

4. בטיקט אחר רשמת שאת רוצה שיהיו החיצים של אולמות נוספים ללא הטקסט, זה יכול לפתור את הבעייה הזו.<br />6. &#64;Alex Voloshchenko תוכל לסדר שהקלנדר יופיע רק לפני שהאירוע מתקיים ולא לאחריו? לדוגמה בעמוד פה שהאירוע כבר עבר ועדיין מופיע הקלנדר<br />http://dev.jff.reasonat.com/en/festival-calendar/2017-05-16<br />7. לפי מה שאני רואה אירועי עבר גם מופיעים. ראו 16.5<br />8. צמצמתי עוד<br /><br />

**Comment by JerusalemCinematheque** [comment]
4. אוקיי. רק תראי #40 שם אמיר כותב שיש בעיה של פאדינג
7. אנחנו רואים בקלנדר רק 24-31.5. כנראה קשור לבעיה באתר הdev שיעקוב בודק אותה. אז יכול שזה עובד בסדר
8. יופי. רק עכשיו רואים שהבוקסה מיושרת לשמאל (אם בצד אנגלית של האתר) של העמודה במקום להיות ממורכזת בעמודה

**Comment by bruria1** [comment]
6. האם כעת בסדר?

**Comment by JerusalemCinematheque** [comment]
6. כן. תודה

**Comment by JerusalemCinematheque** [comment]
כשעוברים ליום חדש העמוד צריך להתחיל בטופ שלו ולא באותו מיקום מיום אחר

**Comment by reasonat** [comment]
There is a new issue for this. 
Closing this one
