### ISSUE TITLE
Calendar - Main Area -Each event should be display under the related Hall tab column and in the related day of the event

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#40]
MIght be a duplication of this
https://www.wrike.com/open.htm?id=142580585

**Comment by reasonat** [comment]
➤ Roei Dahan commented:

&#64;Alex Voloshchenko Seems like this is done via other tasks. Need review? <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Roei Dahan Yes<br />

**Comment by reasonat** [comment]
➤ Roei Dahan commented:

&#64;Amir Taiar alex answered yes, i mistakly read the inbox of it. so i&#39;m notifying you.<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Roei Dahan Yes, sorry. Use your account. <br />

**Comment by JerusalemCinematheque** [comment]
relative to hour as well - aka if event begings at :15 / :30 / :45 should appeare in middle of line and not aligned to top

**Comment by JerusalemCinematheque** [comment]
problems with display on Hebrew side
boxes not aligned with hall column

**Comment by JerusalemCinematheque** [comment]
when there are 6 cloumns problem with display of boxes in last column

**Comment by reasonat** [comment]
@bruria1 Here is a summary of issue for this task: 

- [ ] Event box arn't relative to there time/ 
- [ ] Hebrew side there is an alignment problem. See SS (This is also related to what @JerusalemCinematheque Write - This is not a 6 halls issue but a right padding/margin issue): 

<img width="1273" alt="columns_1" src="https://cloud.githubusercontent.com/assets/741209/26102755/26e9faec-3a3f-11e7-992e-968ed79fcd47.png">
<img width="1252" alt="columns_2" src="https://cloud.githubusercontent.com/assets/741209/26102756/26ec88d4-3a3f-11e7-8094-4a2b947d53be.png">

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko the last comment - Event box arn&#39;t relative to there time. Each event should be &#34;close&#34; to his time. It&#39;s not the case now. <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar Now event appeare in middle of line, if event&#39;s time in second half of hour<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar I changed the markup according to the comment, if more than 15 minutes - an event in the middle of the line<br />

**Comment by JerusalemCinematheque** [comment]
@reasonat @navotb  אמיר איך שאנחנו מבינים את ההיגיון של גובה כל שורה היא שכל שעה קיבלה גובה של הקובייה (משהו כמו 235 פיקסל) מה שיוצר סקרול ארוך מאוד ורווחים שעלולים לגרום לבלבול בקרב הקהל. מה שאנחנו מציעים כדי לחסוך בסקרול וכדי למנוע בלבול של הרווחים הגדולים שנוצרים בין קובייה לקובייה הוא לקבוע שגובה שורה של שעה הוא 40 או 50 פיקסל ולסדר את הקוביות לפי זה
אני מקווה שהצלחתי להסביר מה הבעיה והכוונה שלנו.

**Comment by navotb** [comment]
אתקן:
גובה של שעה הוא 160 פיקסל. כל רבע שעה הם 40 פיקסל. בוא נראה איך זה נראה ואז
נדייק את זה.

2017-05-17 12:29 GMT+03:00 JerusalemCinematheque <notifications@github.com>:

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

איך אתם מציעים שגובה של שורה יהי רק 50 פיקסלים? זה מאד נמוך. <br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

גובה של 160 פיקסלים מצריך לא מעט שינויים בתוכן ובמבנה התיבה. &#64;Bruria Helfer תוכלי לבצע שינוי רק לגובה, בלי להתעסק כעת יותר מדי עם המידע שנמצא בפנים, רק בכדי שנוכל לראות? <br />

**Comment by navotb** [comment]
אנחנו מציעים לא לגעת בתיבה בכלל.
זה רק בענין המיקום של התיבות על ציר ה-y.
כרגע, מוגדר שאורך כל "שעה" בטור הקלנדרי היא כאורך תיבה, כלומר 235 פיקסל.
אבל אנחנו חושבים שעדיף לצמצם את ההגדרה של זה ל-160 פיקסל.
כלומר: אם תיבה צריכה להיות בשעה 09:00 היא בגובה 0, בגובה 09:15, היא בגובה
40 וכו' וכו'.

**Comment by JerusalemCinematheque** [comment]
יש התקדמות?

**Comment by reasonat** [comment]
@bruria1 Please schedule a call with @JerusalemCinematheque to go through this online. 
And maybe other small frontend issues.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

@Bruria Helfer Is it ok now? I deleted extra space

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

@sato2004  No.. the first columns, the space between "Johnny Guitar" and "Translation by H. Rackham" is 90 minutes so they have to be one after the other without any space.

**Comment by JerusalemCinematheque** [comment]
בענין מיקום משבצות האירועים בטורי האולמות

כל טור מייצג את שעות היום  

כך שכל 2 פיקסל = 1 דקה

כל בוקסה של אירוע מייצגת 80 דקות 

יש למקם את הפאה העליונה של כל בוקסה באופן יחסי לשעת האירוע על ציר ה-y.

נקודת מוצא לחישוב של כל הטורים תקבע ע"פ שעת ההקרנה הראשונה של אותו היום, אותה "נצמיד" לראש הטור המתאים. ממנה נמדוד את מיקום שאר הבוקסות בכל הטורים.

אם שעת ההקרנה הראשונה היא 09:00 נמקם אותה בנקודת ה-y בטור המתאים. (נניח לצורך הענין ש-y שווה ל-120)

נחשב את נקודת ה-y של כל שאר הבוקסות ביחס אליה.

כלומר, 
אם שעת האירוע היא 10:30
יש לחשב את ההפרש 10:30-09:00 = 90 דקות 
כפול 2 פיקסל לדקה 
שווה ל-180 פיקסל
אם נקודת ההתחלה היא 120 פיקסל
אז יש למקם את הבוקסה ב-300 פיקסל

מקווה שההסבר הזה ברור

**Comment by sato2004** [comment]
I've change position of events related to time

**Comment by JerusalemCinematheque** [comment]
great
i dn't know if the this is the right place to make the comment
when going to a new date, page should start at the beginning and not where the user was on the previous selected date

**Comment by reasonat** [comment]
Here is the issue for this comment. Closing this task
https://github.com/Reasonat1/Cinema/issues/172
