### ISSUE TITLE
Calendar - Hall table -Editor can be able to order tabs for the festival site

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#41]
Add ordering functionality to Festival site only in the Halls taxonomy so editor can order the halls. 
Then the halls should be display according to this order.

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:
&#64;Amir Taiar Order for different domains should be different?<br />

**Comment by navotb** [comment]
NO

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko Where can I set the order? <br />

**Comment by JerusalemCinematheque** [comment]
אי אפשר פשוט לגרור את האולמות ולסדר אותם ידנית בעמוד ניהול האולמות?

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar http://jer-cin.reasonat.com/en/admin/structure/taxonomy/hall<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko Test this and it works great<br />

**Comment by JerusalemCinematheque** [comment]
נראה שזה עובד
