### ISSUE TITLE
Calendar - Hall table -Create a new field "short hall name fo calendar" for the display

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#43]
Add a new field for the term fields Hall "short hall name fo calendar" 
Then display this name in the tabs

For testing add you own short names till the client will edit this.

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque As can be seen here
http://jff.jer-cin.reasonat.com/en/festival-calendar/2017-04-26 
I have add a short name for http://jff.jer-cin.reasonat.com/en/taxonomy/term/202/edit?destination=admin/structure/taxonomy/hall name it to "Cine 3" and the short name get display. 

So I suggest updating all Hall short names - 
http://jff.jer-cin.reasonat.com/en/admin/structure/taxonomy/hall

**Comment by JerusalemCinematheque** [comment]
short names are only for festival calendar view?

**Comment by reasonat** [comment]
Yes

**Comment by JerusalemCinematheque** [comment]
קיצרנו את מה שהיה אפשר לקצר. אם השם לא מקוצר יש להציג שם מלא

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko In case short name is empty display the title of the term . <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar It was allready done<br />

**Comment by JerusalemCinematheque** [comment]
look at 2.5 Sultan's pool hall - name is displayed as Sultan's instead of Sultan's Pool

**Comment by reasonat** [comment]
It should display the short name and not the long. So I cant see the problem.

**Comment by JerusalemCinematheque** [comment]
Sultan's pool does not have a short name
which means the system is shortening the title instead of displaying the full name

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko &#64;Bruria Helfer ? Can you take a look? <br />As said, the Hall name should be<br />- The short Hall name<br />- If there is no short name then display term name<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar http://dev.jff.reasonat.com/festival-calendar/2017-05-02 I don&#39;t see the problem, if we have short name (it was Sultan&#39;s) we see srot name, now I&#39;ve deleted short name and I see Sultan&#39;s Pool<br />

**Comment by JerusalemCinematheque** [comment]
okay
what happens if it's a very long name? Does i split into two rows?

**Comment by bruria1** [comment]
אם ככה תוצג רק השורה השניה, כל מה שיהיה מעבר לשורה השניה לא יראה.
האם תרצו שיוצגו עד שתי שורות?

**Comment by JerusalemCinematheque** [comment]
כן
אבל רק אם יש באותו יום אולם עם שם ארוך
אחרת שישאר על שורה אחת

**Comment by bruria1** [comment]
בוצע

**Comment by JerusalemCinematheque** [comment]
ok
