### ISSUE TITLE
Calendar - Hall table -Display up to 6 Halls at a time

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#44]
Display only 6 halls at current display. 
I case there are more then 6 display right and left arrows. 
pressing arrow should move full tab right or left, not half tab. 

Here is a node to display 7 Halls http://jff.jer-cin.reasonat.com/en/festival-calendar/2017-04-26

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Alex Voloshchenko I have add 7 events with different Halls at the 26/4<br />

**Comment by JerusalemCinematheque** [comment]
מה השאלה?
