### ISSUE TITLE
Calendar - Hall table

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#46]
In the attach design I have marked the halls table for better understanding. 

Halls are taxonomy terms and events are being referenced to them. 

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;445b4c45e8974f729bea3c7db631a881:F35305831.A948692&#x2F;calenday_halls.png">calenday_halls.png</a>

**Comment by JerusalemCinematheque** [comment]
מה השאלה?

**Comment by reasonat** [comment]
1. להחליף את החיווי לאולמות נוספים לשני חצים בבולד ושיהיו באותה שורה כמו האולמות
2. אולי כדאי להוסיף קו מתחת לשם כל אולם. השורה קצת מרחפת לה
3. כשעושים סקרול החלק של הקוביות מציץ מעל שורת האולמות

![hall table](https://cloud.githubusercontent.com/assets/741209/26102066/1ecb4242-3a3c-11e7-8444-5d53a13495be.png)

**Comment by bruria1** [comment]
אמיר, תסתכל כאשר אינך מחובר כאדמין...

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque זו תגובה מועתקת של הלקוח

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer <br />

**Comment by bruria1** [comment]
לגבי סעיף 1. הכוונה להוריד את הטקט ולהשאיר רק את החיצים הקיימים כבר?
לגבי הקו מתחת, ככה הכוונה?

**Comment by JerusalemCinematheque** [comment]
כן זו הכוונה
ושאלה לגבי תצוגה ריספונסיבית. אנחנו יודעים שיש תצוגה למובייל עם URך נפרד
באיזה גודל משך הוא עובר לתצוגה כזו?
כי הסתכלנו על מסכים קטנים יותר והתצוגה משתבשת

**Comment by bruria1** [comment]
יש עמוד אחר למובייל. במובייל ההפנייה לעמוד הזה תהיה הפניה לעמוד המתאים. מאיזה תפריט אמורים להגיע לעמוד הזה?

**Comment by JerusalemCinematheque** [comment]
ההפניה לקלנדר תהיה מתוך תפריט המגה
גם במובייל וגם בדסקטופ
אבל זה אותו תפריט, אז איך זה יעבוד?

**Comment by bruria1** [comment]
יש להכניס את שני הלינקים כאשר במובייל נסתיר את זה של הדסקטופ ובדסקטופ נ סתיר את זה של המובייל

**Comment by JerusalemCinematheque** [comment]
הבנתי. אוקיי.
אז שנגיע לשם אני מקווה לזכור להגיד לעדכן

תודה

**Comment by JerusalemCinematheque** [comment]
האם הקישורים יהיו
jff.org.il/en/festival-calendar

jff.org.il/en/festival-calendar-mobile

**Comment by bruria1** [comment]
כן

**Comment by reasonat** [comment]
I add Slack reminder to @bruria1 tomorrow at 2PM
