### ISSUE TITLE
Calendar - days table - Each day should have his own url end

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#47]
So if I on Monday, 12/4 it should have some unique url
jff.jer-cin.reasonat.com/en/calendar/{monday124} for example. Doesn't really matter what it will be. 

If this task https://www.wrike.com/open.htm?id=142570218 cause issues with this one the this one is more important.

**Comment by JerusalemCinematheque** [comment]
מה הבעיה בדיוק? כי אנחנו לא יכולים לראות את הקישור ששלחת

**Comment by reasonat** [comment]
אין פה בעיה אלא תיאור משימה. לכל יום יהיה נתיב משלו.

**Comment by JerusalemCinematheque** [comment]
אוקיי. בינתיים אנחנו לא רואים את זה בפועל

**Comment by JerusalemCinematheque** [comment]
Ctrl+Click does not work. Pnly works with right click.
when clicking on a different day loses different url

**Comment by alex** [comment]
אני לא ה”Alex” שאתה רוצה. בבקשה אל תזכיר אותי.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko The user need to see the different URL when he click on each day in the days table. <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar It is possible only without ajax. Don&#39;t use ajax?<br />

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque As I was worry, you need to decide between: 
- Ajax navigation. 
- URL for each day.

**Comment by JerusalemCinematheque** [comment]
Ajax navigation

**Comment by reasonat** [comment]
Then this is how it works now.
