### ISSUE TITLE
Calendar - days table - Ajax load between days

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#48]
Changing days should be fast then better using Ajax calls.

**Comment by JerusalemCinematheque** [comment]
מתייחס לקלנדר סינמטק? פסטיבל? שניהם?

**Comment by reasonat** [comment]
לוח שנה פסטיבל

**Comment by JerusalemCinematheque** [comment]
ajax takes longer than cin' site
some times gets stuck
don't know if this is a new issue or not

**Comment by reasonat** [comment]
We had some issues with performances on dev site. 
I will wait with this. 
Anyway for now I cant even see more then one day on http://dev.jff.reasonat.com/en/festival-calendar 
Can you add dummy / real future events?

**Comment by JerusalemCinematheque** [comment]
there is a full day on 27.5 and there are events up for more than 10 days, but DEV site does not display any of them. Probably has to do with #118 which you asked yakoub to check

**Comment by reasonat** [comment]
I am closing this issue. Anyway we are waiting for your answer whether to choose AJAX or URL - https://github.com/Reasonat1/Cinema/issues/47

**Comment by JerusalemCinematheque** [comment]
@reasonat 
הלינו עכשיו את כל ההקרנות לקלנדר פסטיבל
לוקח לעמוד הרבה זמן להיטען
והמעבר בין הימים לוקח משהו כמו 30 שניות

**Comment by navotb** [comment]
Hi

I am sorry to push but we have to publish the festival calendar tomorrow
and at the moment the loading time of each page is very long (30-40
seconds)

and after 4-5 page loading, the calendar collapses and the pages are
distorted totally

On firefox the browser details this function as a possible source for the
problem

http://jff.org.il/sites/default/files/js/js_MpKfe1sTh5JIVGCZ17DsAuT1rqAC38MLLlkjqjQ1X_k.js

*We really need to solve this issue urgently as this is a major sales
interface for our public.*

**Comment by JerusalemCinematheque** [comment]
@reasonat 
כמובן שמכל הנושאים שהעלינו בקשר לפסטיבל זה הנושא הדחוף ביותר
תודה על הכל

**Comment by yakoub** [comment]
i am making progress on this issue, will update again at end of the day .

**Comment by navotb** [comment]
Thank you Yakoub. Much appreciated.

**Comment by navotb** [comment]
Hi Yakoub,
Sorry to nudge, we have to report to our superiors, can you please update
about the calendar upload speed?
Thank you
Navot

**Comment by yakoub** [comment]
i finished optimizing and fixing problems in javascript,
i still need to work on sql query since the server response sometimes takes 15 seconds .
so i believe i can finish this sunday morning before 12:00 .
@navotb

**Comment by navotb** [comment]
Great. Is there a way to cache this queries, instead of running it every
click?

**Comment by yakoub** [comment]
hi @navotb 
we already enabled cache for calendar and it improved response time from 15 seconds to 6 seconds .

in addition i fixed several javascript problems which caused the page ui to break and stop responding after clicking through the days of the calendar .

i can try to improve the sql query and page build logic for additional 5 hours if you approve .

**Comment by navotb** [comment]
Hi Yakoub, Thank you for your great work.
We measure 16 sec for each page load, which is much better but still very
long.

I don't know what is the cache mechanism, but what i meant by cached qurey
is not have at all sql qurey with each click and just send to the user's
browser the "right" results from last "approved" query in the right format.
Is there a way of doing it?

**Comment by yakoub** [comment]
it looks like there is general performance problem with the server, because when i checked the calendar pages this morning it was responding in 6 seconds .
also alex just cleared the cache in the past hour so maybe that corresponded with the time of your check .

**Comment by navotb** [comment]
Now there is now server at all and it looks like the site is down.

**Comment by navotb** [comment]
Ok, where are the bottlenecks of this issue and how can we solve it? We
have 16-22 seconds for page upload.
What is the most efficient way to cut it down? We must have this calendar
up and functioning with good user experience.

**Comment by yakoub** [comment]
i am not sure this is the bottleneck .

but i believe i can improve the sql query significantly .

**Comment by navotb** [comment]
But the question is this:
if we cache the query, than once we have it results done - we don't need it
to be very efficient, because we send to the browser with the known
results.

the question is what taking it so long to process? is it the query or is it
the javascript of the page? can we eliminate the query and send cached
results (for each day its own results)?

**Comment by navotb** [comment]
btw, now the calendar does not upload correctly on my firefox: it is
distorted again.

**Comment by yakoub** [comment]
javascript problem seems to be related to browser cache, meaning it is loading outdated js file .
can you please try refreshing the page ?

**Comment by JerusalemCinematheque** [comment]
we cleared browser cache and reloaded page
it's still not uploading correctly
![image](https://user-images.githubusercontent.com/26960693/27768742-76d94432-5f23-11e7-91ed-9fb52ebaebc1.png)

**Comment by yakoub** [comment]
this is strange .
try visiting this url directly in browser : view-source:http://jff.org.il/sites/default/files/js/js_MpKfe1sTh5JIVGCZ17DsAuT1rqAC38MLLlkjqjQ1X_k.js

**Comment by yakoub** [comment]
then reload the page again .

**Comment by navotb** [comment]
nothing changed. clicked the js file, viewed it in browser, than refreshed
calendar page - no change

**Comment by navotb** [comment]
if works on chrome, not on firefox

**Comment by navotb** [comment]
NO!! the problem is that it works for signed-in user.

But anonymous user get the distorted page on both browsers.

**Comment by yakoub** [comment]
i checked it using anonymous and in both browser and it is fine .
@reasonat can you check as well please ?

**Comment by navotb** [comment]
It works now.
15-17 sec per pageload.
On dev site it takes 7-8 seconds.
Do you know what makes the difference?

**Comment by JerusalemCinematheque** [comment]
still not working for me
Hebrew side uploads properly 
but English side is still distorted

**Comment by navotb** [comment]
Yakoub, Amir - how are we proceeding with this? IT is now about 15-17 sec
per click. We would be happy if it could be 10 seconds less. WE must
publish this pages already.

**Comment by yakoub** [comment]
לדעתי יש בעית ביצועים כללית ברמת השרת וזה לא תלוי בדפי לוח האירועים .
בכל מקרה בדיקה שלי אני מוצא זמנים 6-7 שניות לכל מעבר בלוח האירועים ואני מצרף צילום מסך שמראה הזמנים ב מילישניות
![screenshot from 2017-07-02 15-54-58](https://user-images.githubusercontent.com/478740/27769987-9704e678-5f3f-11e7-92ab-00d0aaffb6bd.png)

**Comment by yakoub** [comment]
אבל יכול להיות כשאנחנו ניגשים לדפים ביחד זמן  התוגבה עולה, כלומר הצילום שאני צירפתי זה עבור מקרה שאני ביקשתי הדפים לבד .

**Comment by JerusalemCinematheque** [comment]
אז מה יקרה כשיהיו 100 איש או אפילו יותר שמתסכלים בעמוד בו זמנית?

**Comment by navotb** [comment]
יעקב בפיירפוקס אתה יכול להקליט מה קורה בדפדפן כשהוא מעבד את התגובה
אני לא יודע איך לשלוח לך את זה
אבל אתה יכול לראות מה אוכל משאבים וזמן ולפי זה אפשר לטייב את התגובה

**Comment by yakoub** [comment]
לא צריך לקליט אפשר להבחין בקלות שברגע שהבקשה מהשרת מסתימת אז הדף מתעדכן
אין משהו משמעותי  לשפר בצד של הדפדפן .

**Comment by navotb** [comment]
אבל אתה יכול להסתכל על התהליכים ולראות שיש תהליכים שלוקחים הרבה זמן
למשל, יש תהליך שנקרא Paint שיש לפחות 1000 כמוהו, והוא די ארוך בין 5-10 Ms
כל אחד. אם נטייב אותו, או נבין איפה אפשר לקצר אותו, נצליח להוריד את זמן
העבודה של השרת.


2017-07-02 16:26 GMT+03:00 yakoub <notifications@github.com>:

**Comment by navotb** [comment]
הי
מה זה התהליך הזה paint שמתרחש המון זמן המון המון פעמים והתיעוד שלו הוא כזה

"end": 6525.103441949934,
      "endStack": null,
      "isOffMainThread": false,
      "name": "Paint",
      "processType": 0,
          "width": 39,
      "rectangles": [
        {
          "height": 39,
          "y": 304
          "x": 759,


2017-07-02 16:19 GMT+03:00 Navot <navotb@gmail.com>:

> יעקב בפיירפוקס אתה יכול להקליט מה קורה בדפדפן כשהוא מעבד את התגובה
> אני לא יודע איך לשלוח לך את זה
> אבל אתה יכול לראות מה אוכל משאבים וזמן ולפי זה אפשר לטייב את התגובה
>
>
>
> On Sun, Jul 2, 2017 at 4:06 PM, JerusalemCinematheque <

**Comment by navotb** [comment]
Yakoub, Amir

Please record the upload of the page through Chrome console.

It seems there is a lot of time that is being wasted on the preparation
side of the graphic processes and idle activity. Can you please have a look
and suggest how can we eliminate it? is not there a way to cache this data
and just send it as a file to the browser, instead of rearrange it with
each click?

Thank you,
Navot

2017-07-02 17:03 GMT+03:00 Navot <navotb@gmail.com>:

> הי
> מה זה התהליך הזה paint שמתרחש המון זמן המון המון פעמים והתיעוד שלו הוא כזה
>
> "end": 6525.103441949934,
>       "endStack": null,
>       "isOffMainThread": false,
>       "name": "Paint",
>       "processType": 0,
>           "width": 39,
>       "rectangles": [
>         {
>           "height": 39,
>           "y": 304
>           "x": 759,
>
>
> 2017-07-02 16:19 GMT+03:00 Navot <navotb@gmail.com>:
>
>> יעקב בפיירפוקס אתה יכול להקליט מה קורה בדפדפן כשהוא מעבד את התגובה
>> אני לא יודע איך לשלוח לך את זה
>> אבל אתה יכול לראות מה אוכל משאבים וזמן ולפי זה אפשר לטייב את התגובה
>>
>>
>>
>> On Sun, Jul 2, 2017 at 4:06 PM, JerusalemCinematheque <

**Comment by navotb** [comment]
איפה אנחנו עומדים עם הנושא של לוח השנה? זה הדבר הכי דחוף כרגע מהבחינה שלנו.

**Comment by yakoub** [comment]
i am currently working on #158 and not this .

i'll switch to this around 11:00 .

**Comment by navotb** [comment]
Yakoub, any news regarding this issue?
Thank you

**Comment by yakoub** [comment]
i was preoccupied with other issue regarding synchronizing configuration between live site and dev site because the operation was too heavy and causing server failures .

what i plan about this issue is to optimize the sql query, but it won't be done until the end of the day .
i will update you once i make progress .

**Comment by yakoub** [comment]
i don't know how to explain, in the morning admin configuration operation kept crashing database .
but now the operations got completed smoothly, so i'm free to return to this issue .

**Comment by navotb** [comment]
Great Yakoub. We really have to publish the calendar already. If it is
possible to have it done today, it will be great.

Thank you!

**Comment by navotb** [comment]
Yakoub, any progress?
We have to update our bosses everyday what is the status of this. We are in
the middle of tickets sale and this is quite important feature for us.

Thank you for your understanding
Navot

**Comment by yakoub** [comment]
i am deeply sorry i couldn't continue work on this yesterday, something urgent came up in my personal life .

i noticed dev environment have much better response time, so now i am creating staging environment to copy live site and work on it without loosing current state on dev .

i still encounter server issues and i contacted eurovps support again .

**Comment by navotb** [comment]
Yakoub please remember that dev site has much fewer events in calendar.

**Comment by yakoub** [comment]
yes that is why i wanted to create staging environment .
but also i discovered that live website database had problem with table cache_form reaching size 14G which is huge and probably responsible server and performance problems .

now i cleared that table and will continue to investigate

**Comment by navotb** [comment]
Yakoub,
Thank you very much.
Our top priority is the Calendar, we just can not wait with it any longer
as it effects the festival's performance.
We really need it to be corrected and published soon.

Please let us know if it is possible to both finish the calendar and
monitor the server on the same time.

Thank you,
Navot

**Comment by yakoub** [comment]
currently the cleared cache_form content and it is not urgent to solve its problem, i'll return to it latter to prevent it getting large once again .
now i create staging environment and will try to solve the calendar problem .
i don't think i will have solution before 14:00 .

**Comment by navotb** [comment]
Ok, So please update us on 14:00 about the situation with the Calendar.
Thank you very much
Navot

**Comment by navotb** [comment]
Yakoub,
Is there a light at the end of this tunnel already?

**Comment by yakoub** [comment]
i tried eliminating some components of the page and query but didn't observe performance improvement .
i suspect i can't observe it because there is general performance load on the server .
so i want to try and copy the website to our server and test it there in isolated environment .

**Comment by navotb** [comment]
@reasonat @bruria

Ok, so until there is a solution for this problem, would it be possible to
use the mobile calendar on desktop.

The only needed adjustment at the moment is to change the column width to
650-750 pixels, while keeping the day pager on top as is.

**Comment by navotb** [comment]
Yakoub, if it is the Cache Form problem, could it be because we have
sign-in form in the footer of the website?
So every time a page is loaded a form is created?

**Comment by yakoub** [comment]
no, it shouldn't be a problem to present forms on homepage .

i discovered that the new server you moved to didn't have cron configuration, while the cron job is what is supposed to clean that table periodically .
so now i configured cron to run twice a day .

anyway now the table is much smaller around 200M, but it is still the biggest table .
i will investigate it more latter on .

**Comment by navotb** [comment]
Ok. So let's try to see whats make the problem with the calendar. IF there
is anything we can do to help with the solution - let us know.

**Comment by navotb** [comment]
Yakoub, any progress with this? Thank you!

**Comment by yakoub** [comment]
i copied the website to our server and tried to strip the view of its components one by one but there is no improvement .
next i can try to build a new minimalist page from scratch similar to the calendar and see how it performs and its ajax response time (edited)

it should take 2 hours max i think .
if that page performs considerably better, then we can make the calendar work .
but if it doesn't , this mean there must be more general problem across the website not related to the calendar .

**Comment by navotb** [comment]
OK, so let's try it.
On the copied site- do you have logs of performance that can hint where is
the problem?

**Comment by yakoub** [comment]
currently i disabled the logs on live site because it may cause greater performance penalty .
i'll enable it on my local computer and see what i can find .

**Comment by yakoub** [comment]
but last log file from live site showed slow queries for captcha and cache_form tables and some other queries related to site content .

**Comment by navotb** [comment]
But when you copies the website - you can check the logs over copied site.

**Comment by yakoub** [comment]
i copied it to our production server which hosts many other site, and i can't enable the logs only for specific website .

**Comment by navotb** [comment]
Ok. So what can we do to make progress here? We really need to correct this
problem and have a functioning calendar. Do you have any clue if it is
query? Graphics? javascripts?

**Comment by yakoub** [comment]
i think it is most probably query, but :
i can try to build a new minimalist page from scratch similar to the calendar and see how it performs and its ajax response time, with minimalist page i can identify problems easier .

**Comment by navotb** [comment]
Ok. I really want to this solved, if this is the best way- than go on. Is
not there a tool that can tell you which process is taking most of the time
and resources?

**Comment by navotb** [comment]
Anyway, lets be in touch later the evening to see where we are standing
with it. Thank you. Navot

**Comment by navotb** [comment]
Yakoub, does the mobile calendar is using the same query? Because I have a
feeling it is performing a little faster in the query process.

**Comment by yakoub** [comment]
i created this new page : http://jff.org.il/he/slim-calendar
it has response time around 2 seconds .
i couldn't figure out the problem with current calendar page .
how about we get a functional calendar that works instead of all the fancy UI in current calendar ?

i'm not saying the fancy UI is causing the drop in performance at all, just that if we want to use the new calendar we won't have time to invest in applying all the fancy UI .
unless you have the patience ...

**Comment by navotb** [comment]
Hi Yakoub,

Thank you for the efforts. It does runs the query and load this page much
faster.

Still we need some kind of a UI

(1) to have different page for Hebrew and English
(2) to navigate between the different days of the calendar, and show only
available days
(3) to represent each hall as a column, to keep the order of the halls
according to the hall hierarchy in the halls taxonomy table
(4) to add more data for each event (length, screening code, start hour,
(add to my events, add to my calendar))
(5) to have the pop up with more details for each event

We might be able to start without some of these features but not all of it.

We can send another IFYUN for the calendar if necessary - which events are
not needed to be published, what fields are required to be represented.

The question is whether you can re-use the existing code you already have
for the existing UI with your new query?

Thank you,
Navot

**Comment by yakoub** [comment]
first three items are easy .
for (4) i can add data but i don't know what is "screening code"
as for "add to my .." if it was implemented using standard flags then no problem .
(5) not problem either .

i can't use existing UI code myself because it was done by alex and bruria,
but after i finish the basic html and design, they might be able to adapt their code .

i estimate 6-8 hours to finish the basic requirements .
then we'll see what else you need .

but this require approval from @reasonat

**Comment by reasonat** [comment]
I am closing this issue since we have a performances issue open.
