### ISSUE TITLE
Calendar - days table - navigation between days when there is more then 12 days

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#49]
On desktop - Each arrow click jump a full day and not half day. 
On Mobile - With the finger

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Alex Voloshchenko We will need dome dummy content I see in order to see the arrows. Do we? <br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:
&#64;Amir Taiar Yes we need it<br /><br />

**Comment by amir** [comment]
Sorry, I don't want to be rude, but I'm receiving lots of notifications today because @amir is getting mentioned. Would it be possible for you to mention the recipients username completely if it exists?

**Comment by JerusalemCinematheque** [comment]
On mobile > both with finger and arrows, as it is on Cin' side

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko See client comment<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar For days panel I used very same code like in jer-cin side, so it should work. But I think it make sence fix it after &#64;Bruria Helfer will finish front end<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer Have done with the frontend of this part. But we need more dummy content to see more days. &#64;Alex Voloshchenko <br />

**Comment by JerusalemCinematheque** [comment]
ok
