### ISSUE TITLE
Calendar - days table - Table should display 12 days only with arrows for more days if any

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#51]
Table should display up to 12 days in a current display. 
In case there is more then 12 days it should display forward and backward arrows.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Alex Voloshchenko From what I can see it display 10 days. Is it because I am on 13 inch screen? <br />

**Comment by JerusalemCinematheque** [comment]
אין לנו הרשאה לעריכה של הקלנדר ולכן אנחנו לא יכולים להוסיף ימים ולבדוק אם אכן מוצגים 12 ימים ואת עניין החצים

**Comment by reasonat** [comment]
מה ז״א? אין דבר כזה הרשאה לעריכת לוח שנה, הוא מציג אירועים בהתאם לתאריך שלהם.

**Comment by JerusalemCinematheque** [comment]
אז הימים בלוח נקבעים לפי אם יש אירועים ביום או לא?

**Comment by reasonat** [comment]
כן

**Comment by JerusalemCinematheque** [comment]
אולי קשור לזה שזה באתר הdev שלוקח לו זמן להתעדכן
אבל הוספנו אירועים לקלנדר  אחרי ה-31.5 והם לא מופיעים
וגם כשנכנסים אל הקלנדר מופיעים 24.5 25.5 27.5 28.5 29.5 30.5 31.5
אחרי שעוברים יום מופיע גם 26.5
ובקיצור יש שם בעיה ואי אפשר לבדוק את עניין הימים

**Comment by JerusalemCinematheque** [comment]
עוד דבר שקשור לפרונטאנד
שימו לב שיש הבדל במיקום של שורת הימים בין כניסה ראשונית לקלנדר ומעבר בין הימים
כניסה לעמוד הקלנדר
![image](https://cloud.githubusercontent.com/assets/26960693/26033982/1f194980-38be-11e7-9694-3c601e3f4ad5.png)

במעבר ליום אחר
![image](https://cloud.githubusercontent.com/assets/26960693/26033986/2cdbc520-38be-11e7-9c48-b7f5e13a5208.png)

צריך להיות כמו בתמונה השנייה

**Comment by JerusalemCinematheque** [comment]
גם במעבר בין הימים התאריכון קופץ שמאלה

**Comment by JerusalemCinematheque** [comment]
@reasonat במעבר בין ימים, היום הנבחר לא מודגש בצבע. הדגש נשאר על היום הראשון בקלנדר
כלומר התוכן של היום מוצג, אבל זה נראה כאילו הגולש בחר ביום הראשון שמופיע בקלנדר

**Comment by JerusalemCinematheque** [comment]
סוגרת את הטיקט הזה. יש דיון כמעט סגור בכל ענייני הקלנדר בטיקט אחר
