### ISSUE TITLE
Toptix - webform toptix purchase button

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#55]
יכולת להוסיף כפתור סליקה כחלק מתהליך הגשת הטופס - בעריכת הטופס ניתן לקבוע האם יש להוסיף את הכפתור והאם הוא חובה. הכפתור מוביל לעמוד רכישה של טופטיס עבור מוצר מסויים (אפשר כפופ-אפ, הגדרות הרכיב שומרות את הנתיב הספציפי לרכישת המוצר). במידה והכפתור הוגדר כחובה לא יהיה ניתן להגיש את הטופס לפני שטופטיקס דיווחו (דרך הJS) שהמשתמש סיים את הרכישה. במידת האפשר הטופס ישמור נתוני רכישה שחזרו מטופטיקס בשדה מוסתר בטופס.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
we are talking about intigration to webfrom module here, right ?<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
&#64;Amir Taiar why do we need this ?<br />are we really talking about webform here or somthing else ?<br />is the client even aware of this feature ?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;yakoub abaya The client well aware and this is important one. I thinkk it will be best to contact client to get better explenation. <br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
sent mail to client at Wed, Mar 29, 2017 at 2:18 PM .<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
client provided toptix account that i can use in my development work, but the iframe doesn&#39;t provide a widget to login to that account .<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
the basket object has property isCommited which seems to indicate that customer commpleted the checkout process, i need to confirm that with toptix support .<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

&#64;Amir Taiar is the client still interested in this ?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;yakoub abaya Sure! <br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

@Amir Taiar
i added field toptix purchase to webform content type .
and then to enable toptix you simply assign value to that field on node edit form .
example : http://dev.jff.org.il/en/webform/8817

**Comment by reasonat** [comment]
@JerusalemCinematheque @navotb Please check this

**Comment by JerusalemCinematheque** [comment]
please send us a tutorial about creating forms
we don't understand how this works and how we incorporated the toptix button

**Comment by reasonat** [comment]
@yakoub is on a vacation for the next 4 days. 
When he will come back he will call you.

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque 
The flow should be: 
1. Create the form you need with the webform fields and text as any other form on the site. 
2. Set the form settings - Like email notifications and so on. 
3. On the form edit page reference to the event needed. 

Once the user will submitted the form he will be redirected to the event payment page. 

This is already passed QA so I am closing this issue, re-open if needed. 
Will be merge to Live at the end of the day

**Comment by JerusalemCinematheque** [comment]
We have only seen the forms over a year ago when Tom first showed us the site.
we would appreciate it if you could give us a tutorial on how to use the forms, so we can see if this and the toptix button work correctly

**Comment by reasonat** [comment]
https://www.youtube.com/watch?v=hwlJgrvT1Kk this can help you. 
This is from our client docs, so some items might not relevent: 
**Create the node form itself** 
Add a title & description to the form. 
When you create the form you will be redirect to the form setting page. 
**Form settings:** 
Elements - Add fields to the form. 
Source (YAML) - Should not be touched, 
Settings - General settings. 
Access - Set permissions to the form and different state of the form. 
Emails / Handlers - Notifications and more. 
Third party - Should not be touched. 
**Add elements to the form**
Use the “Add elements” button.
Choose the element and press the “Add element” 
Set up the fields settings 
Salesforce project - Set the field mapping - Can be done only after Mapping the form in the form settings tab. 
**Set emails notifications:**
You can set up as many emails as you want to. For example, email to the user, to the editor and to the CEO. 
Go to Emails / Handlers tab
Add handler - For developers use only. 
Add email - Here you can set up many configurations. 
Add the name Token so the email received will include the name at the beginning. 
Got to the email handlers settings of the form - /admin/structure/webform/manage/{form-name}/handlers
Go to the edit form of the email setting [You will need to do this for each email handler]

**Comment by JerusalemCinematheque** [comment]
this hasn't been implemented to live site

**Comment by yakoub** [comment]
example : http://jer-cin.org.il/en/webform/4154

**Comment by yakoub** [comment]
@JerusalemCinematheque added the field to live site as well : http://jer-cin.org.il/en/webform/4154

**Comment by JerusalemCinematheque** [comment]
ok
