### ISSUE TITLE
Toptix - toptix iframe google analytics

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#56]
setup analytics for multiple domains .
https://support.google.com/analytics/answer/1034342

toptix iframe reports using js: event url changes & cart updates. the site google analytics registers these events.

https://support.google.com/analytics#topic=3544906

https://developers.google.com/analytics/devguides/collection/analyticsjs/

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;8b28042a7c8a4d2a88b0a9c4936cc3d5:F38548560.A948692&#x2F;Screenshot+from+2017-05-28+12-54-30.png">Screenshot from 2017-05-28 12-54-30.png</a>

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
&#64;Amir Taiar i don&#39;t know if client even aware of this issue .<br />this is about when user opens the toptix window then we need to track their navigation and report it back to drupal site analytics .<br /><br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
https://developers.google.com/analytics/devguides/collection/analyticsjs/<br /><br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
&#64;Amir Taiar &#64;Roei Dahan google analytics is not even currently installed on jer-cin, are you sure we need to go through with this ?<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
i will also need at least 2 hours to learn how google analytics api work .<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;yakoub abaya Anyway you can install GA for the site. This is part of the scope and it&#39;s an important task. So we need to do this. <br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
reseatch multiple domains setup in google analytics<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
maybe use ecommerce ? https://support.google.com/analytics/answer/1009612?hl&#61;en<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
researching tag manager : https://support.google.com/tagmanager/answer/6103657<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
&#64;Amir Taiar i reported toptix as analytics events : https://support.google.com/analytics/answer/1033068?hl&#61;en&amp;ref_topic&#61;1033067<br /><br />event category &#61; toptix<br />event action &#61; {navigation path reporting by toptix}<br />event label &#61; {drupal event title}<br />event value &#61; {toptix event id}<br /><br />problem in analytics is i can&#39;t see the event value ...<br /><br />i can add you and navot to the anaylitucs property i created .<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;yakoub abaya Please add me for now<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
&#64;Amir Taiar i sent an invite<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
&#64;Amir Taiar https://youtu.be/LYa27lsv1r8<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
&#64;Amir Taiar how should i continue with this, maybe it is ready for client to give us feedback ?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;yakoub abaya Yes, this can be reviewed by the client<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

here is update about the statistics and how it works <br /><a rel="nofollow noreferrer noopener" href="https://youtu.be/dNyEgokaX-o">https://youtu.be/dNyEgokaX-o<br />

**Comment by reasonat** [comment]
@JerusalemCinematheque 
From what I can see on the video and on GA this task is ready for review. 
Sure, we can do many more with GA and events on the site, but as for the requirements and even more, it's done.

**Comment by navotb** [comment]
1. we do not have yakoub account on our analytics page
2. can you please show us how we add facebook and google Pixels to the site?

**Comment by reasonat** [comment]
1. @yakoub please share GA account with the Navot and Tamar accounts. 
2. Not related to this task. I will open a new task for this - 2 tasks.

**Comment by reasonat** [comment]
2. Here is the task - https://github.com/Reasonat1/Cinema/issues/125

**Comment by navotb** [comment]
Is it possible to merge our previous account with the new one, so we could
use historic data in comparison with new one?

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

i don't know why it doesn't appear, i already shared the account with navot .
see screenshot .

**Comment by yakoub** [comment]
http://imgur.com/a/RAWa6

**Comment by navotb** [comment]
I think it is not our account.
What account is it?

**Comment by navotb** [comment]
My user in analytics is my gmail: navotb@gmail.com

**Comment by navotb** [comment]
What is the difference between the new account and the old one? We only
need to implement a new view in the old account for jff,no? It will be a
pity to lose the old data for comparison.

**Comment by yakoub** [comment]
you don't have to use a new account, only add new views to your current account .

**Comment by navotb** [comment]
But why can not we use the current accounts that we have for our different
websites? is there any problem? I don't want to lose the historic data

**Comment by yakoub** [comment]
you can continue using your current account, this is what i mean when i wrote you don't have to use a new account .

**Comment by navotb** [comment]
We have one account with two properties: one for jer-cin and one for jff,
could we keep them? That will be the best for us. Can you embed the
tracking code of the old website in the new one according to domain?

**Comment by yakoub** [comment]
yes .
but we will only use the property for jer-cin for both domains .
property jff won't be needed anymore .

**Comment by navotb** [comment]
Yakoub, did you embed the old google tracking in the new cinematheque
website? because the old view is showing 0 sessions.

**Comment by yakoub** [comment]
the site is now working with your account which has property UA-7605141-1 .

**Comment by navotb** [comment]
Great thank you!
