### ISSUE TITLE
Person - Person management view

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#57]
Create a management view for persons.
Add a link to this view under the Dashboard tab. 

**Columns:** 
✓   VBO - Can set person type + Profession
✓   Photo
✓   Language - 
✓   First name + Last Name
✓   Person type
✓   Job title
✓   Profession 
✓   Email address
✓   Search additions

**Filters:** 
✓   Number of items
✓   Language
✓   First name and full name search
✓   Person type 
✓   Job title
✓   Profession

**Comment by bruria1** [comment]
Done
