### ISSUE TITLE
Person - Add option field to hide person from search results

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#58]
Add a field checkbox which allow the editor to hide the person from the search results. 
Then at the search results hide this nodes. 

For both festival and cinema main site

**Comment by JerusalemCinematheque** [comment]
האם זה אמור לתת פתרון לעניין שיש אישים שעושים בהם שימוש פנימי בלבד?

**Comment by reasonat** [comment]
זה מונע הצגה של אישים דרך מנוע החיפוש. 
זהו, רק מסתיר מעמוד תוצאות החיפוש.

**Comment by JerusalemCinematheque** [comment]
עובד
