### ISSUE TITLE
פאנל לוגואים נפרד לאתר פסטיבל

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#6]
זה כבר כמעט גמור יש רק הערה שהם העירו 
״יש כאן בעיה של תצוגה > לוגו מופיע מתחת ללוגו במקום אחרי״

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar אני לא רואה את הבעייה. האם זה כבר סודר?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer אני חושב שהבעיה ברזולוציות מסוימות. ניסית לראות במצבי מסך שונים? <br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer תשלחי לנבות ותמר מייל בנושא.נראה מה הם יאמרו. <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar הייתה איזשהי בעיה. סידרתי אותה. אני מקווה שלזה הם יתכוונו.<br />

**Comment by JerusalemCinematheque** [comment]
כן. תודה
