### ISSUE TITLE
Breaking messages - Display messages on the screen

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#61]
**Theming should include this functions:** 
 □    Message box should be above site
 □    Can be closed by the user by using the "x" sign.

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar על מה מדובר?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer I guess &#64;Tom Meir meant messages like &#34;Please fill this field&#34; on webform. And so... &#64;Tom Meir ?<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar &#64;Tom Meir which?<br />

**Comment by reasonat** [comment]
➤ Tom Meir commented:
&#64;Bruria Helfer  this is a sub task for theming a new content type view that is not created yet.<br />

**Comment by reasonat** [comment]
➤ Tom Meir commented:
&#64;Amir Taiar why is this task cancelled? Navot or Tamar said they dont need breaking messages functionality anymore?<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar אני צריכה לדבר איתך לפני העיצוב וההטמעה של זה.<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar איפה זה עומד? איך להטמיע? איך זה אמור להיראות? האם לחיצה על איקס סוגרת את זה לתמיד לאותו משתמש? איך הוא יכול לפתוח את זה אחרי זה? לא ברור לי כל הנושא הזה.<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer מה שכן ברור: <br />1. יכולות להופיע מספר הודעות אחת אחר השניה. <br />2. יש כפתור איקס לסגירה של כל הודעה. <br />3. במידה והודעה נסגרה היא אינה מופיעה יותר בשאר העמודים. <br />מה שטרם ידוע: <br />1. האם הודעה מכילה גם קישור לעמוד המציג את כלל ההודעות . <br />2. האם יש עמוד כלל ההודעות<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar הוספתי.<br />זה מעוצב זוועה - אני יודעת. אני צריכה שתגידו איך לעצב.<br />לאחר שסוגרים ההודעה לא תופיע יותר (זה נשמר בקוקי) - מה יקרה אם רוצים לראות שוב?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer אז בשביל זה יהיה את העמוד המרכז את כל ההודעות. את יכולה כבר להכין אותו במצב ראשוני - רשימה פשוטה של כל ההודעות עם התאריך שלהם וקישור המשך קריאת ההודעה המלאה - עמוד פשוט המציג את ההודעה. <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar עשיתי משהו ממש בסיסי. בלי עיצוב:<br />http://jer-cin.reasonat.com/en/article/5825<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer זה בסדר גמור. לבינתיים. בשתי שפות? איפה אני יכול לראות הודעות קופצות? <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar http://jff.reasonat.com/en<br />אבל אם תבקש לסגור לא תראה את זה יותר כל החיים. שזה לא נראה לי התנהגות נכונה.<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer מממ.. כן, זה לא טוב כל כך. האם אין אפשרות למשל להציג שוב לאחר זמן מסוים? <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar ברור שאפשר. כמה זמן?<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer בואי נאמר 24 שעות<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar אמור לעבוד. אבדוק מחר שאכן זה חוזר..<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar עובד..<br />

**Comment by JerusalemCinematheque** [comment]
בוקסת ההודעות אמורה להופיע מעל האתר, לרוחב כל העמוד
תאריך ההודעה
תוכן הודעה מקוצר
כפתור "לידיעה המלאה"
כפתור סגירה
כל הודעה יושבת או בבוקסה נפרדת או עם איזשהו קו מפריד בין הודעות

**Comment by JerusalemCinematheque** [comment]
איפה אנחנו מוספים הודעות?

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

אתם מוסיפים הודעות כמו תכנים אחרים וכן בטבלה של ההודעות יש לינק להוספת הודעה<br />

**Comment by JerusalemCinematheque** [comment]
אין בהוספת תכנים סוג תוכן כזה ומתוך עמוד ניהול ההודעות כשאנחנו מבקשים להוסיף הודעה חדשה אנחנו מקבלים הודעה שאין לנו הרשאה להוספת תוכן זה

**Comment by bruria1** [comment]
בבקשה בדקו כעת שוב.

**Comment by JerusalemCinematheque** [comment]
תודה.
האם להעביר לפה הערות פרונטאנד לבוקסה?
מה עם עיצוב עמוד ההודעה עצמה?

**Comment by reasonat** [comment]
אם אני מבין נכון פונקציונאלית הדברים עובדים וכעת אנחנו רק עם משימת העיצוב. 
הנה היא - 
https://github.com/Reasonat1/Cinema/issues/83 
אם כן, אפשר לסגור את זה?

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque Please recheck this. 
I think in order to make height lower we shoul remove the border around the date. 
Also move the dots and "For al message" to the other side.

**Comment by JerusalemCinematheque** [comment]
אפשר אולי לצמצם את הריווח של מלבן התאריך
אתם רוצים להראות לנו איך זה נראה אם מזיזים את הנקודות והקישור לצד השני באחד מצדדי האתר ואז נחליט?

**Comment by bruria1** [comment]
http://dev.jff.reasonat.com/he
איך זה?

**Comment by JerusalemCinematheque** [comment]
אולי רק נמרכז את האיקס יחסית למלבן התאריך ואז אפשר לסגור את הנושא הזה

**Comment by bruria1** [comment]
האם בסדר?

**Comment by JerusalemCinematheque** [comment]
מעולה. סוגרת את הנושא
