### ISSUE TITLE
Breaking messages - Admin table to manage messages

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#62]
Create admin table so the editors can manage messages. 
Add view link to dashboard main link as a child. 

View include this columns: 
✓   Title
✓   Body
✓   Time range
✓   Domain 
✓   Manage - Edit / Delete links

**Filters:** 
✓   Title search and body
✓   Domain
✓   Time range

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer Looks like date range filter is not working well<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Reasonat Admin זה אופן באופן כזה שצריך למלא את שני שדות התאריך על מנת לראות את המודעות שפעילו בטווח הזה. אם ממלאים רק אחד אפשר לראות מודעות גם שכבר הסתיימו ולא אמורות להיות מוצגות. אולי אפשר לעשות שהשדות האלה יהיו חובה ואז לא תתאפשר לראות משהו שגוי<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer kלא הבנתי כלום<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Reasonat Admin אז דבר איתי..<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer What is the status of this one? <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar  יש פה באג שאם תנסה לראות את כל המודועות שמוצגות מתאריך מסויים והלאה אתה תראה גם מודעות שכבר הסתיימו. אבל לא נראה לי קריטי. זה רק בטבלת אדמין.<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer <br />1. Move language column after title<br />2. Add VBO option for delete and if it&#39;s possible change dates range. <br />

**Comment by bruria1** [comment]
לבדיקה
