### ISSUE TITLE
Movie Group - Add a trailar to a group movie node

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#63]

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar יש בעיה להציג פה טריילר כיוון שהתמונות למעלה הם סטטיות ומועלות בשדה אחר. אפשר לעלות את הטריילר בסרטים למטה או שהמצגת העליונה תהיה מורכבת המסרטים למטה.<br />

**Comment by reasonat** [comment]
@navotb We have an issue here. 
Now, the top area display static images which uploaded in the movie group node form. Also, there is the group movie node title on all images which is good. 

What me and @bruria1 think will be best is: 
**Option 1:** 
Display the movie trailer under each movie (If there is any) - On top of the image. 
**Option 2 - At the top area:** 
1. Display Images from the movies instead of uploading them. 
2. Display movie name (small font) above the movie group title. 
3. Display the movie trailer on top of the movie image (like in event)  

What do you think?

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque ?

**Comment by JerusalemCinematheque** [comment]
@reasonat אמיר תוכל בבקשה להסביר את האופציה השנייה קצת יותר?
1. זה אומר שהתמונות מגיעות ישירות מהסרטים המקושרים כמו שתמונה של הסרט מגיעה לעמוד האירוע? 
2. לא הבנתי מה זה אומר ואיך זה קשור לטריילר?
3. הכוונה שהטיילר מגיע ישירות מעמוד הסרט? מה ההבדל בין זה לבין אופציה 1?

**Comment by reasonat** [comment]
ביחס לאופציה השניה: 
1. כן
2. כי יש לנו בעיה, מוצגת כותרת קבועה של המקבץ בכלל התמונות שבבאנר הראשי. ולכן רצוי להציג גם את שם הסרט. זה קשור לטריילר כי במידה ויהיה טריילר הוא יהיה על התמונה (סעיף3) ולכן זה מייצר הקשר לוגי
3. לא, באופציה 1 הטריילר מוצג בליסטה, בטיזרים ולא בבאנר הראשי כפי שמוצע פה.

**Comment by JerusalemCinematheque** [comment]
1. ואפשר לעשות לזה אוברייד אם מוסיפים תמונה מתוך עמוד האירוע?
2. נראה לי מבלבל במיוחד אם יש גם כיתוב של אירוע ו/או לובי
3. עדיף שהטריילר יופיע בכל סרט ולא בתמונות הגלריה

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Alex Voloshchenko האם תוכל להסתכל? הוספתי לינק לוידאו בקובץ:<br />views-view-fields--movie-group-ct--panel-pane-1.tpl.php<br />שורות 46-48 אבל משום מה זה לא מדפיס את הוידאו. אפשר לראות בעמוד הזה:<br />http://dev.jer-cin.reasonat.com/en/movie-group/4741<br />שם לסרטים יש וידאו ואמור להיות להם מודפס הפליי של הוידאו.<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Bruria Helfer I&#39;ve fixed tpl<br />

**Comment by bruria1** [comment]
@navotb @JerusalemCinematheque 
כעת ניתן לראות בעמוד ה למשל:
http://dev.jer-cin.reasonat.com/en/movie-group/4741
את הטריילרים של הסרטים.

האם יש צורך בעוד משהו במשימה זו?

**Comment by JerusalemCinematheque** [comment]
אז יש וידאו למקבץ ויש לכל סרט וידאו שמגיע מעמוד הסרט כן?

**Comment by JerusalemCinematheque** [comment]
הוידאו של המקבץ לא נפתח כמו שצריך
![image](https://cloud.githubusercontent.com/assets/26960693/26345266/118e14be-3fab-11e7-9116-a06fce38292f.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
טריילר על תמונות הגלריה בסדר
החלונית שנפתחת בכל סרט צרה וארוכה במקום להיפתח לגודל הטריילר כמו שזה בעמודים אחרים

**Comment by bruria1** [comment]
לבדיקה באתר פיתוח.

**Comment by JerusalemCinematheque** [comment]
עדיין נראה שונה
זה מה שנפתח מתוך ליסטת הסרטים
![image](https://cloud.githubusercontent.com/assets/26960693/26541857/2eadb9d2-4460-11e7-8d3f-179f23940ebf.png)

וזה מה שנפתח בעמוד הסרט
![image](https://cloud.githubusercontent.com/assets/26960693/26541868/3ece6438-4460-11e7-8be1-1ca8414dec1d.png)

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
מצויין. תודה.
