### ISSUE TITLE
Movie Group - Add favorite option to group movie node

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#64]
This should also add the movies associate with the group movie to the "My movies" on the user page

**Comment by JerusalemCinematheque** [comment]
לא. כי יש אפשרות להוסיף כל סרט בנפרד. אנחנו רוצים שתהיה אפשרות להוסיף את המקבץ עצמו

**Comment by reasonat** [comment]
איי איי איי... חבל

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko Please prevent this from happening. Meaning when user add group movie as favorite only this grou movie node will be flaged. For now there is no place the user will see this. This will be another discussion .<br />

**Comment by JerusalemCinematheque** [comment]
עובד יפה

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko Issue from the client:<br />משהו השתבש בשורה שנמצאת מעל רשימת הסרטים<br />במקום שיהיה כתוב<br />saved films<br />כתוב<br />saved movie groups<br /><br />ובעברית<br />במקום שיהיה כתוב<br />סרטים שמורים<br />כתוב<br />מקבץ סרטיםים שמורים<br />

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar Sould it be always &#34;saved movie groups&#34;? Now we take content type from first row<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Alex Voloshchenko It should be &#34;My movies&#34; and &#34;My events&#34;. There might be in the future &#34;My grouped movies&#34; but not now<br />

**Comment by JerusalemCinematheque** [comment]
It's just the title, not the content

**Comment by reasonat** [comment]
➤ Alex Voloshchenko commented:

&#64;Amir Taiar Now in this liist there are movie groups to, is it ok?<br />

**Comment by JerusalemCinematheque** [comment]
yes. it's only the title of the list, not the content displayed

**Comment by JerusalemCinematheque** [comment]
ok
