### ISSUE TITLE
Movie Group - Add share pane to group movie node

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#65]

**Comment by JerusalemCinematheque** [comment]
מה השאלה כאן?

**Comment by reasonat** [comment]
אין כאן שאלה אלא תיאור משימה. הוספת תיבת שיתוף לעמוד מקבץ..

**Comment by JerusalemCinematheque** [comment]
זה מתייחס גם לשלח לסרטים שלי?
השלח עובד רק על הצד בו המשתמש נמצא ולא עובר לצד המתורגם כפי שזה עובד עם סרטים ואירועים

**Comment by reasonat** [comment]
לא הבנתי את ההערה שלכם

**Comment by JerusalemCinematheque** [comment]
כבר לא רלוונטי. העניין נפתר.
