### ISSUE TITLE
Movie Group - Add tags pane to group movie node

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#66]

**Comment by JerusalemCinematheque** [comment]
מה השאלה כאן?

**Comment by reasonat** [comment]
שוב... זה תיאור משימה. נא לבדוק אם נעשה / לא

**Comment by JerusalemCinematheque** [comment]
התגיות מופיעות בעמוד המקבץ. הן צריכות להופיע גם בעמוד האירוע אליו המקבץ משוייך
לדוגמא זה עמוד המקבץ
http://jer-cin.reasonat.com/he/movie-group/6780
יש לו שתי תגיות

זה עמוד האירוע עם המקבץ
http://jer-cin.reasonat.com/he/event/6782

התגיות לא מופיעות

**Comment by reasonat** [comment]
זו הייתה דרישה בעמוד סרט, שתגיות מסרט יופיעו בעמוד אירוע. 
כאן הדרישה היא להציג את תיבת התגיות. 
הדרישה להציג את התגיות של מקבץ גם באירוע המקושר היא דרישה נוספת שכרוכה בשעות עבודה רבות. מייצר משימה חדשה עבור זה ומקפיא אותה בשלב זה. 
יש לציין כי גם דרישה זו הייתה בהקפאה ועברה בסוף לביצוע. 
את המשימה הזו מעביר לבוצע.
