### ISSUE TITLE
User page - Show Similar movies and events

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#67]
Display on "my movies" & "My Events" tab a movie/events gallery based on similar terms of his movies. 

לא ממש ברור איך זה אמור להיראות. אין עיצוב לזה. 
בשלב זה נציג רשימה פשוטה של 3 אייטמים. לאחר מכן נראה איך אנחנו מציגים את זה. 

┆Attachments: <a href="https:&#x2F;&#x2F;www.wrike.com&#x2F;extlink&#x2F;4b7fb1d12a014f58a877ee431bf5a967:F37645702.A948692&#x2F;Screenshot+from+2017-05-10+13-15-51.png">Screenshot from 2017-05-10 13-15-51.png</a>

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar אני לא יודעת איך להציג רק את התכנים שקשורים עם תגיות לתכנים המוצגים. כי זה בעצם לקשר את התכנים להיבט אחר באותו עמוד.. אין לי מושג איך לעשות את זה. כרגע עשיתי את ההיבט בלי הסינון הזה פה:<br />http://jer-cin.reasonat.com/en/admin/structure/views/view/similar_user_flagged_content/edit<br /><br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:
&#64;Bruria Helfer &#64;yakoub abaya Can you also have a look? <br />

**Comment by navotb** [comment]
What is this view?

**Comment by reasonat** [comment]
➤ yakoub abaya commented:
wrote custom hook : cm_extra_views_post_execute .<br />which embeds the similar terms view in attachment_after of main view .<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer Please front end this to be like the list above. Make a minor gap between the wishlist and the similar. Also: <br />1. Make it width the same like the wishlist. <br />2. Change title to Similar movies / Events. <br />3. Make a small gap between the title and the list. <br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer I see no changes but the title... <br />

**Comment by JerusalemCinematheque** [comment]
על פי אלו קריטריונים נקבעים התכנים הדומים?

**Comment by JerusalemCinematheque** [comment]
מבחינת תצוגה יש לזה עיצוב בסקיצות, וזה אמור להיות תצוגת גריד ולא תצוגת רשימה.

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Unito Bot for Two-Way Sync מה שיש בתצוגת גריד בעיצוב זה היום בפסטיבל. האם הםתכנים הדומים אמורים להיות מוצגים כמו היום בפסטיבל? התכנים המוצגים שם הם התכנים הדומים בתגיות לתכנים שהמתמש בחר.<br />

**Comment by JerusalemCinematheque** [comment]
זה העיצוב שמוכר לנו

![recommendations design](https://cloud.githubusercontent.com/assets/26960693/25314152/15c54c76-2847-11e7-9f28-86745d8fc9a8.png)

לגבי זיהוי תכנים דומים - לפחות ממה שאני רואה בעמוד האישי שלי אין בתכנים האישים תגיות ובחלק מההמלצות גם אין תגיות ולכן לא ברור איך נקבע הקשר בין הפריטים בהמלצות לפריטים שנבחרו.

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;yakoub abaya התכנים המוצגים לא נכונים. הם צריכים להיות על פי התגיות של התכנים שהמתמש בחר וזה לא כך.<br />

**Comment by reasonat** [comment]
@bruria1 Also change to this grid view.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;yakoub abaya I see no updates since the 26/4. What is the real status of this? <br />

**Comment by bruria1** [comment]
אמיר,
לא הבנתי את הערה שלך אלי.

**Comment by reasonat** [comment]
@bruria1 לעדכן את העיצוב בהתאם למה שנבות ותמר העלו פה.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

&#64;Amir Taiar i still need to debug the problem .<br />it works on clean drupal but on cinematic somehow not working .<br />i will work on this from 12:00 to 13:00<br />

**Comment by bruria1** [comment]
אבל זה מה שעשיתי כבר. עדכנתי את זה לגריד במקום ליסט.
זה לא טוב?

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

&#64;Amir Taiar i am currently working on this, so hold on the style review<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

the problem was i showed the view &#34;content pane&#34; display of that view while on my local dev environment i was working with &#34;block&#34; display .<br />and it turns out passing arguments in code to &#34;content pane&#34; doesn&#39;t work like a &#34;block&#34;<br />so now i added block display and it is working .<br /><br />currently i kept the field display for that view, so that testers (bruria, amir, maybe client ?) can see for each item all its terms to verify the view is showing what is supposed to .<br />(changing the view display can be easily reverted to grid later on by bruria)<br /><br />but there is a new problem : the view is supposed to show tyes &#34;cm event&#34; and &#34;cm movie&#34; while in filter area there is condition that checks &#34;field_cm_event_time&#34; which exist only for &#34;cm event&#34; and not &#34;cm movie&#34;<br />and that means this view will never show &#34;cm movie&#34; nodes but only &#34;cm event&#34; .<br />so question do we really need to show type &#34;cm movie&#34; ? <br /><br />&#64;Amir Taiar &#64;Bruria Helfer <br />

**Comment by reasonat** [comment]
@yakoub We need to display related movies under >> My movies tab. 
And display related events under >> My events tab. 
So yes.

**Comment by navotb** [comment]
afterwards,  it would be great use this as a general template to be embedded (manually) in other pages with a manual selection of content (or according to lobby/tag)?

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

&#64;Amir Taiar no, i didn&#39;t ask about other pages .<br />for different pages we can have different views so there is no problem .<br /><br />but if we want to have both events and movies on same page and still filter the list according to events date, then this is a compolicated condition which will require to write custom views query alter code .<br /><br />so again, do we need this ?<br />

**Comment by reasonat** [comment]
@yakoub Please pay attention to the requeirments in the task: 
"Display on "my movies" & "My Events" tab a movie/events gallery based on similar terms of his movies." 
That it. There is nothing here about event dates. 
And if we really want to order also by event date then we can always display 2 blocks, one for events and one for movie. True?

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

&#64;Amir Taiar i continued working on view that already existed before and someone else added condition about event time, so that is why i took that as requirement .<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

if filtering by event time is not a requirement then there then i&#39;ll simply remove these conditions and finish the task .<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;yakoub abaya For now please do so. Only for Similar movies and events views. Thanks<br /><br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;yakoub abaya Is this one of this 2 options? I think the second one is better. &#64;Bruria Helfer ? <br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

&#64;Amir Taiar i removed all reference to event time field in this view : http://jer-cin.reasonat.com/en/admin/structure/views/view/similar_user_flagged_content/edit<br />

**Comment by bruria1** [comment]
אני כרגע לא רואה את התיבה הזו כלל. איפה אני אמורה לראות אותה?

**Comment by yakoub** [comment]
currently this block display fields for debugging purposes, when done you can change view back to rendered entity .

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

it appears under /user<br />

**Comment by bruria1** [comment]
כרגע זה נראה טוב. לא מוצג למשתמשים מלבד אדמין כיוון שזו ההרשאה שניתנה להיבט.

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer Can the client see this then? <br />

**Comment by bruria1** [comment]
לא. רק אדמין רואה את זה.
@yakoub תוכל לבדוק למה?

**Comment by yakoub** [comment]
@bruria1 כתבת בעצמך :
" לא מוצג למשתמשים מלבד אדמין כיוון שזו ההרשאה שניתנה להיבט"
אני לא מודע להרשאה כזאת, למה התכוונת בזה ?

**Comment by bruria1** [comment]
כעת רק העורכים יכולים לראות את התיבה. היא מופיעה באתר הלייב מתחת לתכנים המסומנים בעמוד משתמש.
משתמש רגיל לא רואה את התיבה.

**Comment by JerusalemCinematheque** [comment]
1. חסרה כותרת שמסבירה מה מהות האזור הזה
You might also like...
מומלצים בשבילך...
2. הקישור בין הנודס מתנהל לפי התגיות, אבל יש כאן קרוסרפרנס בין סרטים ואירועים, קרי אם סרט יש לו תגית קלאסיקה ויש אירוע שיש לו תגית קלאסיקה, האירוע מופיע מתחת לחלק של הסרטים, במקום מתחת לחלק של אירועים
3. אירועים שעברו לא אמורים להיות מוצגים
4. בתצוגה של סרטים חסר כותרת הסרט
5. האם אפשרי שכל התמונה תהיה קליקבילית ולא רק הכותרת?
6. מוצגים למעשה שלושה אייטמים שקשורים, אבל מן הסתם יש הרבה יותר אייטמים שקשורים אחד לשני, האם אפשר לקבוע תצוגה רנדומלית שונה בכל פעם שמשתמש נכנס לעמוד שלו? כלומר שכל פעם מוצגים לו אייטמים אחרים? או שיש חצים שמאפשרים מעבר לשלושת האייטמים הבאים הקשורים? ועוד יותר, האם אפשר לקבוע עדיפות לתצוגה של אייטמים שיש להם הקרנות?

**Comment by bruria1** [comment]
1.  עודכן
2. @yakoub 
3. עודכן
4. כותרת הסרט כתובה על התמונה לא?
5. עודכן
6. @yakoub

**Comment by JerusalemCinematheque** [comment]
1. אפשר להקטין קצת
3. עדיין רואה אצלי אירועים שעברו
4. עכשיו יש. מאוד גדול
![image](https://cloud.githubusercontent.com/assets/26960693/26206894/b13a593e-3bee-11e7-9440-545ee7a4f1db.png)

**Comment by bruria1** [comment]
1. בוצע
2. ביקשתי מ @yakoub לטפל בזה..
3. סודר

**Comment by JerusalemCinematheque** [comment]
אתם עובדים על החלק הזה? כי אני כבר לא רואה אותו בעמוד

**Comment by bruria1** [comment]
אמור להופיע לעורכים בלבד בעמוד משתמש

**Comment by JerusalemCinematheque** [comment]
מחכים לתשובות מיעקוב

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

@yakoub abaya Please look at 2. + 6.

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

adding random order breakes distinct function and produces duplicate results .

**Comment by JerusalemCinematheque** [comment]
אז אפשר שיהיו חצים שמעבירים לאייטמים הבאים?

**Comment by reasonat** [comment]
@bruria1 Notice in Hebrew the heart icon is on the right side instead of the left side.

**Comment by bruria1** [comment]
בקשר ללב - סידרתי. בקשר לאייטמים נוספים - כמה אייטמים סה"כ יופיעו?

**Comment by yakoub** [comment]
@bruria1 i believe i can solve the problem with random items, so wait on pager solution .

**Comment by yakoub** [comment]
created different block displays for movies and events which allows filtering events by date

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

add random sort using custom hook in module feature cinematheque_feature_views_3 , because drupal default behavior will add random expression to fields list and that will hamper sql distinct caluse and show duplicate resutls .

**Comment by bruria1** [comment]
@navotb @JerusalemCinematheque 
כרגע מופיעים שלושה תכנים באופן רנדומלי. האם זה מספק אתכם?
האם בכל זאת תרצו שיופיעו יותר משלושה ואז יהיו חיצים שמאלה וימינה לדפדפוף?
אם כן, כמה תכנים סך הכל?

**Comment by reasonat** [comment]
Lets close this, if there are 3 random items so this what was needed to be done. 
More requests will be another task.

**Comment by navotb** [comment]
אני מתנצל פשוט תמר חולה ואני לא לגמרי בתמונה של כל הנושאים האלו

**Comment by JerusalemCinematheque** [comment]
נושא התצוגה הרנדומלית נפתר
יש עוד כמה ענייני פרונטאנד
1. לחיצה על הלב מעבירה לעמוד האייטם במקום להוסיפו לרשימה האישית
2. חסר לב למקבץ
3. במקבץ צבע הכותרת מופיע כצבע האתר, במקום פונט לבן
4. בצד עברית הכותרת שמופיע מעל  היא באנגלית במקום בעברית. אמרנו שהכותרת תהיה "מומלצים בשבילך..."

**Comment by reasonat** [comment]
1+2+3 נראים לי לא קשורים לפה אלא לדיונים אחרים וגם לא ברור לי מה אתם מציינים

**Comment by JerusalemCinematheque** [comment]
הדיון כאן כלל גם הערות פרונטאנד
אפשר לפתוח דיון חדש אם צריך
לאייטמים שמוצגים כמומלצים יש את אייקון הלב להוספה לרשימה שלי. אבל לחיצה על האייקון לא עושה את הפעולה שהוא אמור לעשות אלא מוביל לעמוד של האייטם המומלץ
יכול להיות אייטם מומלץ מסוג מקבץ. כשהוא מופיע אין לו את האייקון של הלב והכותרת של המקבץ מופיע בצבע ורוד במקום בצבע לבן. ראו האייטם הימיני ביותר
![image](https://cloud.githubusercontent.com/assets/26960693/26819133/4def0944-4aa6-11e7-9b5d-7a1128cf005b.png)

**Comment by bruria1** [comment]
סידרתי את 1,3,4
בעצם בכל מקום בעמוד הבית שיש מקבת אמור להופיע הלב שמוסיף את כל הסרטים שבתוך המקבץ לסרטים שמורים? כרגע בשום מקום אין את הלב על המקבץ.

**Comment by JerusalemCinematheque** [comment]
ברמת העיקון כן
בעמוד המקבץ זה מופיע כמו שהוא מופיע בעמוד סרט בצד של השיתוף

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
לא רואים שינוי. זה רק בסביבת הפיתוח?

**Comment by bruria1** [comment]
רק בסיבת הפיתוח. כן. ברגע שתאשרו את השינוי של האייקונים נוכל לעלות את כל השינויים ללייב

**Comment by JerusalemCinematheque** [comment]
ok
