### ISSUE TITLE
Term page - Front end term page

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#68]

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:
&#64;Amir Taiar אני צריכה לדעת איך העמוד הזה אמור להיראות.<br />

**Comment by reasonat** [comment]
@navotb We have the simple tagging page, example - http://jff.jer-cin.reasonat.com/en/tags/india 
Which need a better look. 
I was thinking theming this in a list display. 
Any comment?

**Comment by JerusalemCinematheque** [comment]
תצוגת רשימה כמו שבתוצאות חיפוש

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Amir Taiar כרגע זה מוצג כרשימה. לא ניתן לשנות את צורת התצוגה כפי שאפשר בלובי אבל אני מבינה שאין דרישה כזו בינתיים.<br />

**Comment by JerusalemCinematheque** [comment]
לא אין דרישה כזו
