### ISSUE TITLE
responsive shopping cart

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#75]

**Comment by navotb** [comment]
האם זה הפתיל שעוסק בהצגת עמודי טופטיקס בצורה רספונסיבית? אם כך, לטופטיקס יש כבר רספונסיביות מובנית, הבעיה היא שכאשר אנחנו קוראים לטופטיקס דרך המודל (החלונית) הרספוניסיביות לא מתרחשת, לכן צריך להיות הגדרה אחרת למודל במכשירים סלולריים

**Comment by JerusalemCinematheque** [comment]
חושבת שאפשר לסגור את העניין הזה. העגלה ריספונסיבית.
