### ISSUE TITLE
טבלת קרדיטים צ'ק בוקס

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#76]
הבחירה צריכה להיות האם להציג בצד סינמטק ולא האם להציג בצד פסטיבל

**Comment by JerusalemCinematheque** [comment]
עובד מצויין

**Comment by JerusalemCinematheque** [comment]
@reasonat סליחה, מסתבר שזה לא קשור לצ'ק בוקס, אלא לעדכון של פרטי סרט בעמוד אירוע. פתחתי נושא חדש

**Comment by JerusalemCinematheque** [comment]
seems okay
