### ISSUE TITLE
שינויים בהאדר ומגה תפריט

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#78]
【 highlighted #2985e0 】✓   בצד עברית, שונה הכיתוב שליד הלוגו. איפה אנחנו עורכים את זה?【 end highlighted 】
【 highlighted #2985e0 】✓   כל הקישורים הפכו לורודים, היו לבנים【 end highlighted 】
【 highlighted #2985e0 】✓   למה הקישור ללוח שנה פסטיבל נמצא בצד דומיין סינמטק? והאם זה בסדר שנוריד אותו משם או שזקוקים לזה לגישה קלה לבדיקה של העמוד?【 end highlighted 】

**Comment by JerusalemCinematheque** [comment]
הכיתוב צריך להיות 
סינמטק ירושלים
ארכיון ישראלי לסרטים

האם תוכלו להסביר לנו איפה אנחנו יכולים לערוך את הכיתוב?

**Comment by JerusalemCinematheque** [comment]
@bruria1 האם להתייחס גם לשתי ההערות האחרות?

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer Client is still waiting for answers... <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

בתפריט הניהול בתוך block managment יש לכם קישור לעריכה של הכיתוב בפסטיבל ובסינמטק בעברית ובאנגלית <br />

**Comment by JerusalemCinematheque** [comment]
תודה
