### ISSUE TITLE
When finish editing and save a person page redirect to persons management page

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#80]
┆Task is synchronized with this GitHub [issue](https://github.com/Reasonat1/Cinema/issues/80)

**Comment by JerusalemCinematheque** [comment]
כשלוחצים על שמירה ועריכה צריך להישאר בעמוד עריכה.
בלחיצה על שמירה לעבור לעמוד ניהול אישים

**Comment by JerusalemCinematheque** [comment]
ואם אפשר להוסיף לעמוד הניהול תרגום לכל פריט זה גם מאוד יעזור

**Comment by reasonat** [comment]
שמירה ועריכה - עובד. 
ואם אפשר להוסיף לעמוד הניהול תרגום לכל פריט זה גם מאוד יעזור - נעשה
שמירה ומעבר לעמוד ניהול - מדובר בעבודה מרובה דרך הקוד. מקפיא כעת את זה. נא להתייחס רק למה שציינתי שעובד

**Comment by JerusalemCinematheque** [comment]
שמירה ומעבר לעמוד ניהול - מדובר בעבודה מרובה דרך הקוד. מקפיא כעת את זה. נא להתייחס רק למה שציינתי שעובד > זה עבד. פשוט עבד גם בכפתור "שמירה ועריכה"

**Comment by reasonat** [comment]
כן, המערכת מזהה את שניהם ככפתור אחד ובכדי להפריד ביניהם נדרש להתלכלך פה בקוד כמה שעות.
