### ISSUE TITLE
דיפולט ל"איש" > person

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#81]

**Comment by JerusalemCinematheque** [comment]
@reasonat האם מחכים לבדיקה שלנו?

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;Bruria Helfer Are we talking cbout the person type field with the 3 option to choose from? <br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Amir Taiar Yes<br />

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Amir Taiar &#64;yakoub abaya ללקוח אין אפשרות לעלות לשרת שלנו הקלטות. רק להכניס כתובת url.<br />

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque We have an issue here that this field isnt translatable. We can implement translation for this field but all data will be lost. We can add bulk operation to the person management view so you can bulk edit this info to multiple persons once we have done with the translation change. Is it fine?

**Comment by JerusalemCinematheque** [comment]
@reasonat @navotb 
 כרגע בחירה בצד אחד מעבירה את הבחירה גם לצד התרגום אז איך זה שזה לא שדה מתורגם?

**Comment by bruria1** [comment]
ממה שאני רואה רק חברה ופסטיבל מתורגמים. איש ופרסון לא קשורים אחד לשני והתרגום לא מתבצע
אבל כפי שאמיר הציכ אפשר בבת אחת לעדכן הרבה תכנים והעדכון יעשה מהר.

**Comment by reasonat** [comment]
במשימה הזו אתם מציינים שזה לא קורה. 
https://github.com/Reasonat1/Cinema/issues/86

**Comment by JerusalemCinematheque** [comment]
אבל זה עבד בעבר. ואחרי שכתבנו את המשימה זה עבד שוב. עכשיו שוב פעם לא עובד.
איזו סיבה יש שחברה ופסטיבל כן מתורגמים אבל איש לא מתורגם?

**Comment by bruria1** [comment]
נכון. אבל זה מיוצר אחרת.
חברה ופסטיבל הם מתורגמים ואילו באיש הם ישויות נפרדות.
לכן אני רוצה שזה יהיה ישות אחת מתורגמת אבל אז הערכים בעברית שיש בהם איש ימחקו
רק נשאר להסתכל בטבלה למי אין ערך ולהוסיף לו את הערך איש.

**Comment by JerusalemCinematheque** [comment]
יש מאות פריטים שהם פרסון

**Comment by bruria1** [comment]
אבל אם אני מוחקת את כל הפרטים בעברית שהם איש, כל מה שיהיה ריק יהיה איש נכון? אין מצב שהשדה ריק נכון?
אז אסנן את הטבלה לכל הריקים ואעדכן אותם לאיש החדש.

**Comment by JerusalemCinematheque** [comment]
הערכים > הכוונה היא לperson type? כן?
לא לכל הפריטים?

**Comment by bruria1** [comment]
הכוונה היא לערך "איש" בשדה:
person type
הוא היחיד שיימחק.

**Comment by JerusalemCinematheque** [comment]
אז רק לסכם את הכל כדי להיות בטוחה שהבנתי. 
מוחקים מכל ה"אישים" שקיימים במערכת את הערך ב-person type
הופכים את השדה לשדה מתורגם
מוסיפים לכל ה"אישים" בבת אחת בחזרה את הערך "איש" בperson type
ואחרי זה הדיפולט בשדה זה הוא "איש" בצד עברית ובצד אנגלית
ואנחנו צריכים לעבור על הרשימה כדי לברור אילו מהפריטים הם לא "איש"

**Comment by bruria1** [comment]
הערך שיימחק הוא רק אם הזנתם בו איש. כל ערך אחר שהוזן בשדה הזה לא ימחק.

**Comment by navotb** [comment]
אז מה שיקרה:
נעבור על כל רשימת האישים
נמחוק מכל אלו שיש להם ערך person את הערך הזה
נהפוך אותו למתורגם
ואז נוסיף אותו
ערכים שהם פסטיבל או חברה - יישארו כמו שהם. 
האם זה התהליך?

**Comment by bruria1** [comment]
בעצם זה יהיה פשוט יותר.
אם מעדכנים ערך באנגלית אז העך המתאים מתעדכן בעברית נכון?
אם כך אם נמחוק את הערך איש שכרגע לא מתורגם, ניצור ערך מתורגם ונשמור בפעם אחת את כל האישים, הערך התעדכן באופן אוטומטי.

**Comment by JerusalemCinematheque** [comment]
אני עדיין לא בטוחה שאני מבינה את התהליך
אבל כל עוד זה לא מוחק שום פריט והכל נעשה בצורה אוטומטית אז נראה לי שאפשר להתקדם
ברוריה רק תוכלי להסביר לנו מה נצטרך לעשות אחרי שהתהליך מסתיים?

**Comment by bruria1** [comment]
אין צורך שתעשו שום דבר. אמור להיות בסדר כעת.
רק אשמח לדעת איפה השדה הזה משפיע על התצוגה על מנת שאוכל לבדוק שהכל בסדר.

**Comment by JerusalemCinematheque** [comment]
השדה לא אמור להשפיע על התצוגה, אלא רק לעזור למבנה הדאטה בייס

**Comment by bruria1** [comment]
אם כך מבחינתי הטיקט הזה סגור

**Comment by JerusalemCinematheque** [comment]
@bruria1 
הדיפולט נעלם מעמוד הוספת איש

**Comment by bruria1** [comment]
חזר.

**Comment by JerusalemCinematheque** [comment]
יופי תודה

**Comment by JerusalemCinematheque** [comment]
@bruria1 
הדיפולט נעלם מעמוד הוספת איש
האם אפשר בבקשה להוסיף לכל האישים שנוספו היום את הדיפולט הזה?

**Comment by bruria1** [comment]
עודכן.
מקווה שלא יקרה שוב.

**Comment by JerusalemCinematheque** [comment]
ok
