### ISSUE TITLE
Theme global message

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#83]

**Comment by reasonat** [comment]
@navotb @JerusalemCinematheque 
We need to decide what to do here, right now it looks bad and disturbing. 
From system we use it always one message at a time and a slideshow which replace messages (Ticker is out of fashion). 
Please make up your mind.

**Comment by JerusalemCinematheque** [comment]
@reasonat @navotb 
מסכימה שזה לא נראה כל כך טוב.
הבעיה היא שאם זה סליידר ולא שמים לב שיש מספר הודעות אז האיקס סוגר את כל ההודעות והמשתמש לא יבחין בהודעות הנוספות
האם יש אפשרות למספר את ההודעות?

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Unito Bot for Two-Way Sync אין בעיה למספר את ההודעות אבל למה זה יפתור את הבעיה?<br />את מתכוונת למספור מהצורה:<br />1/4<br />2/4<br />3/4<br />4/4<br />??<br />

**Comment by reasonat** [comment]
אז מה אנחנו מחליטים בנושא? 
מעדיף כעת לא להוסיף משימות כמו מספור אלא לסגור משימות קיימות.

**Comment by JerusalemCinematheque** [comment]
אז אם אין מספור, איזה סימון יש לכך שיש מספר הודעות?

**Comment by reasonat** [comment]
שוב, אני לא חושב שנכון להציג מספר הודעות ואם כן אז בסלייד. 
לא חייב להיות מחווה אבל זה חשוב אפשר להציג מתחת נקודות ממש כמו בגלריה.

**Comment by bruria1** [comment]
אשמח לקבל סיכום על מה לעשות פה.

**Comment by JerusalemCinematheque** [comment]
סליידר אוטומטי
נקודות למטה למעבר של המשתמש בין ההודעות
מופיע עד לסגירה של המשתמש – מופיע כל 24 שעות. כמובן אם יש הודעה חדשה מופיע ללא קשר לטיים אאוט
לחיצה על הודעה מובילה לעמוד ההודעה (צריך לעבור על העיצוב של זה)
בכל עמוד הודעה קישור לעמוד ההודעות הכללי (צריך לעבור על העיצוב של זה)
בעמוד ההודעות הכללי מופיעות רק הודעות פעילות

**Comment by JerusalemCinematheque** [comment]
הודעות יתחילו יותר פנימה באותו קו כמו ה-X, אבל אחריו
להגדיל פונט
 משקל פונט רגיל
בוקסת ההודעות דוחפת את כל האתר למטה. לא רק את ההדר

**Comment by reasonat** [comment]
העיצוב של עמוד הודעה יהיה כמו עמוד בסיסי רגיל, לא רואה כעת זמן פיתוח להתחיל לעצב את זה מה גם שזה באמת עמוד פשוט. 
בסופו אפשר לשים לינק קבוע לעמוד העדכונים הראשי

**Comment by reasonat** [comment]
כמו כן, פרסום מחדש כאשר יש הודעה חדשה - זה יהיה משימה חדשה שתיכנס להקפאה

**Comment by JerusalemCinematheque** [comment]
למה להקפאה? מה אם ההודעה מתייחסת לאירוע של אותו יום? ההודעה לא תגיע למשתמש שנכנס שוב פעם לאתר כי יש למנגנון טיימאאוט?

**Comment by JerusalemCinematheque** [comment]
עיצוב בסיסי - כלומר כמו עמוד מאמר ללא תמונה?
וכן נשמח לשים לינק קבוע לעמוד עדכונים ראשי

**Comment by bruria1** [comment]
לינק קבוע בעמוד הודעה?
איפה הלינק יופיע? מה יהיה רשום עליו?

**Comment by JerusalemCinematheque** [comment]
בתחתית העמוד
לכלל ההודעות
For all messages

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
האם אפשר לשים את השורה שמפנה לכל ההודעות לצד הנקודות?
לשנות בעברית ל לכל ההודעות
הבוקסה של ההודעות צריכה לדחוף את כל העמוד למטה ולא רק את ההדר
שהפונט לא יהיה בבולד

**Comment by bruria1** [comment]
עודכן

**Comment by JerusalemCinematheque** [comment]
הבוקסה עדיין יושבת על התמונה

**Comment by bruria1** [comment]
התמונה נדחפת ללמטה ורואים שהיא אכן לא מפתפרשת על כל העמוד. אלא יורדת ללמטה.

**Comment by JerusalemCinematheque** [comment]
אולי זה קשור לקאש אבל ככה אנחנו רואים את זה
זו התמונה המלאה ללא ההודעה
![image](https://cloud.githubusercontent.com/assets/26960693/25892916/97f2480e-357e-11e7-8c64-3ce8c35bdf4d.png)
וזו התמונה עם ההודעה
![image](https://cloud.githubusercontent.com/assets/26960693/25892945/b2a63ea8-357e-11e7-80c6-c4f02b8845e1.png)

**Comment by bruria1** [comment]
אכן קאש. אנא בדקו כעת

**Comment by JerusalemCinematheque** [comment]
אוקיי. נראה טוב

**Comment by JerusalemCinematheque** [comment]
הקישור לכל ההודעות לא פועל

**Comment by bruria1** [comment]
עובד כעת

**Comment by JerusalemCinematheque** [comment]
סוגרת את הנושא

**Comment by JerusalemCinematheque** [comment]
בצד עברית הקישור למעבר לכל ההודעות מופיע בעברית
![image](https://cloud.githubusercontent.com/assets/26960693/26817821/d48c778a-4aa0-11e7-9357-2dbba0688f78.png)

**Comment by bruria1** [comment]
Done
