### ISSUE TITLE
תפריט ההאדר של הפסטיבל צריך להיות שונה מתפריט ההאדר של הסינמטק. כרגע זה מנוהל באותו מקום

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#84]

**Comment by reasonat** [comment]
➤ Bruria Helfer commented:

&#64;Amir Taiar כעת יש תפריט שונה לתפריט הראשי באתר בפסטיבל ובסינמטק וכן לתפריט הנפתח במובייל ובדסקטופ<br />

**Comment by JerusalemCinematheque** [comment]
יופי תודה
