### ISSUE TITLE
toptix basket checks user login

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#85]
when opening basket and it is empty, redirect to user page .
user page : **crmdetails.aspx (will open login widget automatically)**
user login : **crmlogin.aspx**

**Comment by JerusalemCinematheque** [comment]
האם אפשר שברגע שיש פעילות בסל הקניות - אם זה משתמש רשום, או שיש אייטמים בסל -  האייקון יהיה "דלוק"?

**Comment by reasonat** [comment]
I have created a new task for this https://github.com/Reasonat1/Cinema/issues/139
This task as far as I know is done.
