### ISSUE TITLE
Event - Error message

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#87]
@reasonat 
Warning: Invalid argument supplied for foreach() ב-__lambda_func() (שורה 4 מ-/home2/jercin/public_html/sites/all/modules/views_php/plugins/views/views_php_handler_field.inc(202) : runtime-created function).
Warning: Invalid argument supplied for foreach() ב-__lambda_func() (שורה 9 מ-/home2/jercin/public_html/sites/all/modules/views_php/plugins/views/views_php_handler_field.inc(202) : runtime-created function).

**Comment by JerusalemCinematheque** [comment]
יש חדש?

**Comment by reasonat** [comment]
I duplicate this issue since it wasnt sync well with Wrike
https://github.com/Reasonat1/Cinema/issues/99
