### ISSUE TITLE
Lobby wide list screenings view

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#88]
@bruria1 @reasonat 
בתצוגה של סרט בעמוד לובי נקבע כי יופיעו עד שלוש הקרנות ואם יש יותר הקרנות יופיע כפתור הקרנות נוספות
בתצוגת לובי תמונה רחבה מופיעות כל ההקרנות וכפתור ההקרנות הנוספות למרות שהוא לא פעיל
http://jer-cin.reasonat.com/en/lobby/all-about-me

**Comment by bruria1** [comment]
אני לא רואה את הבעיה.
לפי מה שאני רואה זה עובד בעמוד הספציפי הזה.

**Comment by JerusalemCinematheque** [comment]
כן צריך לרפרש את העמוד

**Comment by bruria1** [comment]
אז אין בעיה?

**Comment by JerusalemCinematheque** [comment]
לא. הכל בסדר
