### ISSUE TITLE
When film page is updated, the film details in event page doesn't get updated as well

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#89]
@reasonat 
כשפרטים של סרט מתעדכנים, הם צריכים להתעדכן גם בעמוד האירוע
עמוד הסרט
http://jer-cin.reasonat.com/en/movie/1175

עמוד האירוע
http://jer-cin.reasonat.com/en/event/5842

**Comment by sato2004** [comment]
fixed

**Comment by JerusalemCinematheque** [comment]
looks okay
will let you know if we experience this bug again
