### ISSUE TITLE
iframe default redirect

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#90]
toptix has mechanism which redirects browser after closing the iframe .
(for example after pressing "continue purchase" button)
the problem is the address they redirect to is not dynamic to current site but statically configured (or hard coded).
so if the domain cinematic is eventually installed on is not the same as what is configured in toptix it will redirect to the wrong site .

they describe a procedure on client side which catches the event of the toptix redirect and allows controlling the page to redirect too .
but previous attempt to implement this procedure resulted in infinite redirect loop .

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

&#64;Amir Taiar new task<br />

**Comment by reasonat** [comment]
➤ Amir Taiar commented:

&#64;yakoub abaya I understand the issues. What might be a solution if any? <br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

i will update the example on : http://jer-cin.reasonat.com/esro/event.php<br />and send new support request for toptix .<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

updated example page and now waiting for toptix support reply .<br />

**Comment by reasonat** [comment]
➤ yakoub abaya commented:

saif from toptix support requested code update <br />

**Comment by reasonat** [comment]
@yakoub What is the status of this one?

**Comment by yakoub** [comment]
@reasonat in wrike i marked it complete .
the redirection stopped happening on esro framework, but because of *flagrant* lack of cooperation from toptix people i can't confirm the reason this redirection has stopped .

given the redirection is gone then problem is solved .
if client still have complains about this issue they are welcome to explain .
