### ISSUE TITLE
If event is marked as domain access > publish to festival do not display on cinematheque side

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#91]
@reasonat @navotb 
ערכנו עכשיו כל מיני אירועים שהופיעו בקלנדר הסינמטק ונועדו לקלנדר פסטיבל. סימנו אותם כשייכים לדומיין פסטיבל. אבל הם עדיין מופיעים בצד סינמטק
לדוגמא
http://jer-cin.reasonat.com/he/event/6463

**Comment by reasonat** [comment]
This task also didnt sync with Wrike. from some reason all your new issues doesnt get synced with Wrike... 
See issue on work here https://github.com/Reasonat1/Cinema/issues/100 
Closing this one
