### ISSUE TITLE
Movie group summary does not appear in calander

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#92]
@reasonat @navotb 
תיאור המקבץ http://jer-cin.reasonat.com/he/movie-group/6777
לא מופיע באירוע של המקבץ בקלנדר. ראו תאריך 7.5

**Comment by JerusalemCinematheque** [comment]
כי אחרת מופיע רק שם המקבץ או שם האירוע ולא מבינים על מה מדובר
קצת נראה כמו טעות

**Comment by reasonat** [comment]
שואל שוב - מה הבקשה?

**Comment by JerusalemCinematheque** [comment]
שבעמוד הקלנדר הגדול יופיע התקציר המקוצר של המקבץ

**Comment by bruria1** [comment]
בדקו כעת

**Comment by JerusalemCinematheque** [comment]
יופי. תודה
