### ISSUE TITLE
event details display in movie group

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#93]
@reasonat @bruria1 @navotb 
שימו לב ששורת ההקרנה בעמוד המקבץ לא מוצגת כמו שצריך. זה היה בסדר בעבר
http://jer-cin.reasonat.com/he/movie-group/6777

**Comment by bruria1** [comment]
מה הבעיה? איך זה אמור להיראות?

**Comment by JerusalemCinematheque** [comment]
כמו בעמוד סרט

**Comment by bruria1** [comment]
הכוונה שזה אמור להופיע מתחת לתמונה ולא עליה?

**Comment by JerusalemCinematheque** [comment]
השורה עצמה נראית שונה מאיך ששורת ההקרנה נראית בעמוד סרט
יש קו שמפריד בין היום והתאריך
חסר פרטי אולם
חסר שלח לקלנדר שלי
חסר כפתור כרטיסים

**Comment by bruria1** [comment]
והכל צריך להופיע מתחת לתמונה או עליה?

**Comment by JerusalemCinematheque** [comment]
מתחת. איפה שזה עכשיו. רק שיראה כמו שזה נראה בעמוד סרט
![image](https://cloud.githubusercontent.com/assets/26960693/25578124/5aa7688c-2e74-11e7-861f-23cb7b9b4d77.png)

**Comment by bruria1** [comment]
האם כעת זה בסדר? האם יכולות להופיע כמה שורות של הקרנות? האם יש צורך בכותרות?

**Comment by JerusalemCinematheque** [comment]
הלב ושלח לקלנדר רחוקים מידי מכפתור הכרטיסין
כן יכולות להופיע מספר שורות
כן

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
רק שעה אולם אמור להתיישר עם קו הגריד של הטקסט

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
אוקיי
