### ISSUE TITLE
Genrael Frontend issues 1.5.17

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#94]

**Comment by bruria1** [comment]
**מובייל:**
עמוד קלנדר:
1. הורדתי את הקו
4. מנגנון הגלילה- מה הבעיה באייפון? מה לא נגלל היטב?

עמוד הבית:
2. לא הבנתי את הבעיה

מגה תרפיט:
1. הרקע הורוד עדיין מופיע, לא רואה בעיה

**דסקטופ**
עמוד לובי
2. אני לא רואה בעייה בתצוגת רשימה:
http://jer-cin.reasonat.com/en/lobby/all-about-me
3. מדובר על אירועים? כרגע אירועים שהתאריך שלהם עבר כלל לא מופיעים? ואתם רוצים שכל האירועים האלה יופיעו?

פוטר:
1. בוודאי. אתם עורכים את זה פה:
http://jer-cin.reasonat.com/en/block/footer-social-block/edit
ותצטרכו לערוך שוב כשהדומיין יעלה.
(יש גם קישור בתפריט ניהול - social block)

כל השאר בוצע.

**Comment by JerusalemCinematheque** [comment]
מובייל:
עמוד קלנדר:

מנגנון הגלילה- מה הבעיה באייפון? מה לא נגלל היטב? 
השורה של הקלנדר עם המעבר בין הימים

עמוד הבית:
2. לא הבנתי את הבעיה
בקו המפריד נצמד לשעה במקום להיות קו הפרדה

השורה הבעייתית
![image](https://cloud.githubusercontent.com/assets/26960693/25656177/6f183386-3000-11e7-9d1c-ba16cde013c5.png)

התצוגה הנכונה
![image](https://cloud.githubusercontent.com/assets/26960693/25656201/88cfb6fa-3000-11e7-9a0f-321efd26e766.png)

מגה תרפיט:

הרקע הורוד עדיין מופיע, לא רואה בעיה
הפך לשחור. עכשיו הוא בסדר

דסקטופ
עמוד לובי
2. אני לא רואה בעייה בתצוגת רשימה:
http://jer-cin.reasonat.com/en/lobby/all-about-me
לא תצוגת הרשימה, תצוגת הגריד

3. מדובר על אירועים? כרגע אירועים שהתאריך שלהם עבר כלל לא מופיעים? ואתם רוצים שכל האירועים האלה יופיעו?
כן. אם אפשר רק בעמודי הלובי, לא בעמודי האירועים עצמם או בטיזר בעמוד הבית.

כל השאר בוצע.
יופי. תודה!

**Comment by JerusalemCinematheque** [comment]
3. כמובן מדובר על שורת התאריך. כלומר שהאירוע ישאר (כמו שזה עכשיו) וששורת התאריך באירוע לא תמחק לאחר שמועד האירוע עבר

**Comment by JerusalemCinematheque** [comment]
@bruria1 בעמוד הבית > תמונות גלריה > משקל הפונט השתנה. הוא היה כמו בכותרת עמוד סרט

**Comment by bruria1** [comment]
מובייל:
עמוד קלנדר:
מנגנון הגלילה - טרם טופל

עמוד הבית:
2. תוקן

דסקטופ
עמוד לובי
2. עדיין לא רואה מה הבעיה...
3. לא הבנתי.. מה שאני רואה אירוע שהתאריך שלו עבר (כמו האירוע האחרון לדוגמה שמופיע בעמוד:
http://jer-cin.reasonat.com/en/lobby/all-about-me)
התאריך שלו עבר והוא מופיע עם התאריך שלו. מה הרצוי מבחינתכם?

לגבי שמקל הפונט - תוקן

**Comment by navotb** [comment]
הי ברוריה בענין סעיף 3
הדוגמא שאת מביאה היא של לובי שאליו מקושרים *סרטים*, המציג את ההקרנה הראשונה של כל סרט. הבעיה עם מה שאת מציגה היא מה יקרה כאשר נפתח לובי חדש עם הסרטים האלו בעתיד, כאשר תהיינה להם הקרנות נוספות בעתיד. האם תופיע ההקרנה הנכונה (העתידית) או התאריך ההקרנה הראשון (היסטורית) של כל סרט. יכול להיות שמה שאת מראה לנו זה בעצם באג. 

אנחנו מתכוונים ללובי שאליו מקושרים אירועים כמו זה:
http://jer-cin.reasonat.com/en/lobby/cinematic-variations-live-classical-music-2016-17
כאן עבור *אירועים* שמועדם כבר חלף, נעלמת שורת המועד
ואילו עבור *אירועים* שמועדם בעתיד - היא עדיין מופיעה
הנכון מבחינתנו במקרה זה הוא להציג בכל מקרה את שורת המועד, לא משנה אם האירוע כבר חלף.

**Comment by JerusalemCinematheque** [comment]
http://jer-cin.reasonat.com/he/lobby/%D7%AA%D7%A8%D7%90%D7%95-%D7%90%D7%95%D7%AA%D7%99
כנראה שהבעיה של תצוגת הגריד בלובי זה רק בצד עברית

**Comment by bruria1** [comment]
לגבי הגריד בעברית - סודר

**Comment by reasonat** [comment]
אנחנו לא מצליחים לשחזר את הבעיה באייפון, אנא שלחו צילום וידאו של המסך בעת ההתנהגות

**Comment by JerusalemCinematheque** [comment]
כרגע נראה שזה עובד

**Comment by JerusalemCinematheque** [comment]
בתצוגת גריד בעמוד הבית באייטם אירוע > כותרת האירוע אמורה להיות יותר קטנה מכותרת הסרט אלא אם הכותרות אותו הדבר או אם מדובר רק על אירוע ללא סרט

**Comment by bruria1** [comment]
לגבי הכותרות של האירועים - סודר.
לגבי הבקשה להצגת מועד אירועים שעברו בתצוגת לובי - זו בקשה מורכבת ולא פשוטה אמיר?

**Comment by reasonat** [comment]
@bruria1 תפתחי על זה בבקשה משימה בנפרד אני לא מצליח להבין מפה במה בדיוק מדובר. 
אני יעבור על זה
