### ISSUE TITLE
Add body field and Short Summary field to Front Page content type

### ISSUE THREAD

**Issue by JerusalemCinematheque** [Reasonat1/Cinema#95]
בהמשך להתכתבות שלנו בקובץ האקסל
כשאנחנו משתמשים בעמוד מסוג פרונט פייג' כעמוד בפני עצמו ולא כעמוד הבית, היינו רוצים שבין כותרת העמוד לפריטים שאנחנו מוסיפים אליו יהיה שדה טקסט, כמו שיש בעמוד מסוג "לובי"
לדוגמא בעמוד הזה
http://jer-cin.reasonat.com/he/5672
ככה אנחנו יכולים לייצר עמודי לובי בלי לייצר אותם כעמוד לובי של ממש

**Comment by reasonat** [comment]
אתם מדברים פה על פסקה מקדימה. 
ממיבט הבנתי ברוריה הוסיפה פרגרפ של טקסט פשוט, למה זה לא פותר את הבקשה? 
@bruria1

**Comment by JerusalemCinematheque** [comment]
לא רואים שנוסף שדה כזה
יש את שדה טקסט שאפשר להוסיף לפני כל חלק, אבל לא על זה מדובר

**Comment by bruria1** [comment]
כעת יש אפשרות להוסיף תוכן

**Comment by JerusalemCinematheque** [comment]
היינו רוצים שהוא יופיע כמו הטקסטים בעמוד לובי, מאמר, סרט. כלומר יהיו לפסקה הזו קווי גריד ורקע

**Comment by bruria1** [comment]
קווי הגירד הם כמו בלובי. איזה רקע צריך להיות?

**Comment by bruria1** [comment]
מחכה לתגובתכם..

**Comment by reasonat** [comment]
Test and it looks good. Closing this issue. Reopen if needed.
