### ISSUE TITLE
Display group movie node tags in the referenced event node

### ISSUE THREAD

**Issue by reasonat** [Reasonat1/Cinema#96]
Disply the group movie node tags
for example this node has 2 tags
http://jer-cin.reasonat.com/he/movie-group/6780

in the event tags pane which display this group movie node
http://jer-cin.reasonat.com/he/event/6782

**Comment by bruria1** [comment]
לבדיקה

**Comment by JerusalemCinematheque** [comment]
רק צריך לדאוג ליישר את התגיות בעמוד האירוע כשיש תגית שמגיעה מהאירוע ותגית שמגיעה מהסרט
http://jer-cin.org.il/he/event/6782

**Comment by bruria1** [comment]
בוצע. באתר פיתוח.

**Comment by JerusalemCinematheque** [comment]
אחלה
